### ISSUE TITLE
Slow height indexing after upgrade to v1.7.5

### ISSUE THREAD

**Issue by barryz** [ava-labs/avalanchego#1014]
**Describe the bug**
We have a problem with a C-chain node. After we upgrade the node version from v1.7.1 to v1.7.5, the node starts up and consistently shows `height indexing ...`

**To Reproduce**
Former version: v1.7.1
Version: v1.7.5

**Screenshots**
<img width="1805" alt="image" src="https://user-images.githubusercontent.com/16658738/153865938-d987d9f0-f40b-4900-9603-9e848003c412.png">

**Operating System**
Linux amd64

**Comment by ssakiz** [comment]
Hi,

We have the same slowness  problem  after upgrading from 1.7.4 to 1.7.5  during C chain index, during first startup.

To Reproduce
Former version: v1.7.4
Version: v1.7.5

Operating System
Linux amd64


![1 7 5_index_slow_issue](https://user-images.githubusercontent.com/5831161/154100557-1acde658-1e63-46ba-9cea-481e562c6ecb.jpg)

**Comment by barryz** [comment]
> Hi,
> 
> We have the same slowness problem after upgrading from 1.7.4 to 1.7.5 during C chain index, during first startup.
> 
> To Reproduce Former version: v1.7.4 Version: v1.7.5
> 
> Operating System Linux amd64
> 
> ![1 7 5_index_slow_issue](https://user-images.githubusercontent.com/5831161/154100557-1acde658-1e63-46ba-9cea-481e562c6ecb.jpg)

Finally, after about 8 hours of height indexing, the c-chain was successfully launched.

**Comment by StephenButtolph** [comment]
To clarify - height indexing doesn't prevent the chain from turning on.
