### ISSUE TITLE
Running a New Node Port 9651 Forwarding Error

### ISSUE THREAD

**Issue by manwe88** [ava-labs/avalanchego#1017]
I have just begun to run a node on avalanche and it is currently bootstrapping. However, when I started it it gives the following error:

ERROR[02-25|17:57:56.839] nat/nat.go#90: Renewing port mapping try #1 from external port 9651 to internal port 9651 failed with SOAP fault: 
ERROR[02-25|17:57:57.844] nat/nat.go#90: Renewing port mapping try #2 from external port 9651 to internal port 9651 failed with SOAP fault: 
ERROR[02-25|17:57:58.848] nat/nat.go#90: Renewing port mapping try #3 from external port 9651 to internal port 9651 failed with SOAP fault: 
ERROR[02-25|17:57:59.848] nat/nat.go#72: NAT Traversal failed from external port 9651 to internal port 9651 with SOAP fault: 

I had also port forwarded to 9651 from my router and also checked the IP address of the computer where node is running.
What am I missing?

**Comment by VishalWaman** [comment]
+1

**Comment by manwe88** [comment]
My problem is solved. I bought static IP from my ISP for port forwarding to run smoothly

**Comment by VishalWaman** [comment]
I have also linked static up address, but when I run test net it fails

Fails On test net, woks fine on mainet 

Also curl localhost works

Same experience on aws and azure VM

**Comment by manwe88** [comment]
I am not capable of giving an answer to that one, it might be better someone competent answers that

**Comment by danlaine** [comment]
@manwe88 @VishalWaman 

In general, this NAT traversal failure isn't a critical error. I've made a ticket for us to change the log level here from ERROR to WARN.

I would suggest using a static IP for your node and specifying it with the `--public-ip` flag.

If you can't use a static IP, I suggest using flag `--public-ip-resolution-service=ifconfigco` to dynamically resolve your node's IP from time to time.

See [documentation](https://docs.avax.network/nodes/maintain/avalanchego-config-flags#public-ip) for more information.
