### ISSUE TITLE
How to use local build of coreth in avalanchego?

### ISSUE THREAD

**Issue by paymog** [ava-labs/avalanchego#1018]
I've downloaded and built avalanchego and coreth. I'm having trouble figuring out how to get avalanchego to use my local build of coreth - I've searched the avalanche docs and the docs for the two repos but haven't found instructions.

How do I get a local build of avalanchego to use a local build of coreth? Do I have to place the coreth binary under `avalanchego/build/plugins`? If so, does the binary need to have a specific name?

**Comment by paymog** [comment]
Ah, do I need to update this path to point to my local checkout of coreth? 

https://github.com/ava-labs/avalanchego/blob/a9c21a9c692cb6528c276ea1198009ab19db2011/scripts/constants.sh#L12

**Comment by paymog** [comment]
Ah, looks like the following command should work `/bin/sh /Users/paymahn/code/partyhat/avalanchego/scripts/build.sh /Users/paymahn/code/partyhat/coreth /Users/paymahn/code/partyhat/coreth/build/evm` but I find that this does not set `coreth_path` in this script: 

https://github.com/ava-labs/avalanchego/blob/a13d640810532576d31c1f952d061870e129546b/scripts/build_coreth.sh#L18-L19

**Comment by paymog** [comment]
Ah, turns out `build.sh` doesn't propagate parameters to `build_coreth.sh`:

https://github.com/ava-labs/avalanchego/blob/a13d640810532576d31c1f952d061870e129546b/scripts/build.sh#L22

**Comment by paymog** [comment]
It's still not clear how to use the plugin correctly, should the binary for the plugin built locally be placed at `avalanchego/build/plugins/evm`?

**Comment by huahuayu** [comment]
Put `avalanchego` and `coreth` src in the same dir, so it's looks like `src/avalanchego`, `src/coreth`

Suppose you changed something in `coreth`, you can compile it independently.

But when comes to `avalanchego` you need to amend`go.mod`, add this line to it.

```
replace github.com/ava-labs/coreth => /path/to/coreth
```

After that, you compile `avalanchego` binary.
