### ISSUE TITLE
How to run single node local network?

### ISSUE THREAD

**Issue by paymog** [ava-labs/avalanchego#1022]
I'm learning how to use the avalanche infrastructure and I've figured out how to use the [avalanche network runner](https://github.com/ava-labs/avalanche-network-runner). The network runner is a great tool but makes the dev cycle a bit slower because it needs to wait for 5 separate nodes to come online and also requires me to have yet another repo involved in my dev cycle.

Ideally I'd like to be able to run a single avalanchego node from the terminal. Is that possible? I tried starting one up with the following command taken from [here](https://docs.avax.network/build/tutorials/platform/create-a-local-test-network#manually):

```
./build/avalanchego --public-ip=127.0.0.1 --http-port=9650 --staking-port=9651 --db-dir=db/node1 --network-id=local --bootstrap-ips=
```

but that ends up with the node stuck in the bootstrapping phase. I get the following logs over and over:

```
INFO [03-02|09:08:52] <P Chain> snow/engine/common/bootstrapper.go#294: Bootstrapping skipped due to no provided bootstraps
INFO [03-02|09:09:02] <P Chain> snow/engine/common/bootstrapper.go#294: Bootstrapping skipped due to no provided bootstraps
INFO [03-02|09:09:12] <P Chain> snow/engine/common/bootstrapper.go#294: Bootstrapping skipped due to no provided bootstraps
INFO [03-02|09:09:22] <P Chain> snow/engine/common/bootstrapper.go#294: Bootstrapping skipped due to no provided bootstraps
INFO [03-02|09:09:32] <P Chain> snow/engine/common/bootstrapper.go#294: Bootstrapping skipped due to no provided bootstraps
INFO [03-02|09:09:42] <P Chain> snow/engine/common/bootstrapper.go#294: Bootstrapping skipped due to no provided bootstraps
INFO [03-02|09:09:52] <P Chain> snow/engine/common/bootstrapper.go#294: Bootstrapping skipped due to no provided bootstraps
```

Those docs for manually starting avalanche suggest that I can manually start a 5 node network. I want to start a one node network. 

Is there a way to run a single node network locally? If so, how?

**Comment by gatesyp** [comment]
This should get you to where you want to be: 
https://docs.avax.network/build/tutorials/platform/create-a-local-test-network#manually

@paymog

**Comment by huahuayu** [comment]
@gatesyp the first node command is not right, `--bootstrap-ips=` is left blank and `--bootstrap-ids` is omitted, but others are fine.
```
./build/avalanchego --public-ip=127.0.0.1 --http-port=9650 --staking-port=9651 --db-dir=db/node1 --network-id=local --bootstrap-ips= --staking-tls-cert-file=$(pwd)/staking/local/staker1.crt --staking-tls-key-file=$(pwd)/staking/local/staker1.key
```

**Comment by huahuayu** [comment]
@paymog I think this may help you https://github.com/blockchain-private-network/avalanche-local-private-network

**Comment by StephenButtolph** [comment]
If you want to run a quick single node test network to hit the APIs and send transactions - then you can run:
```
avalanchego --network-id=local --staking-enabled=false --db-type=memdb
```
Note that this setup should never be used in a production environment - only for quick testing.
