### ISSUE TITLE
Coreth version not updated(avax v1.7.6 coreth v0.8.5-rc.2)

### ISSUE THREAD

**Issue by kenyh0926** [ava-labs/avalanchego#1024]
In the last release of avax, the coreth version is not updated.
https://github.com/ava-labs/avalanchego/blob/v1.7.6/scripts/versions.sh
coreth_version=${CORETH_VERSION:-'v0.8.5-rc.2'}
In the release note of avax v1.7.6, coreth updates in v0.8.6 is included

**Comment by StephenButtolph** [comment]
Thanks for point this out! This has been resolved in `v1.7.7`.
