### ISSUE TITLE
Interesting flash attack address (Is Avax really decentralized?)

### ISSUE THREAD

**Issue by darlin99** [ava-labs/avalanchego#1025]
https://snowtrace.io/address/0x000000004edf117e7d051d0de2712a5c527678b3

If you check this address, you will see that it is behind all the transactions that create opportunities. 
If the Avax main node randomly chooses and sends the validator addresses it will gossip to, and we know that this unknown person does not have all the validators, how can it manage to be behind every transaction?

**Comment by StephenButtolph** [comment]
Sorry, I don't seem to understand the question here. Feel free to re-open this with a more clear question.

For reference - this is where peer selection is done for transaction gossiping: https://github.com/ava-labs/avalanchego/blob/master/network/network.go#L622

**Comment by darlin99** [comment]
I see...

**Comment by darlin99** [comment]
Let's verify sth before going further on discussion.
Assuming transactions are being collected on a *randomly* chosen validator, and when it's time to order them two variables taken into account:
* Gwei used,
* Transaction arrival time.
Consequently assuming tx #55 arrived, in order to become tx #56 someone needs to use exact same amount of gwei + first arriving tx after #55 (timestamp).
What if this never happens? If someone else wins the race all the time?
* Faster than us? 
* Any other variable must be taken into account?
* Competing with validator itself, if so what about next block? All validators are in a such race?
Any suggestion is highly appreciated.

**Comment by darlin99** [comment]
Let's verify sth before going further on discussion.
Assuming transactions are being collected on a 'randomly' chosen validator, and when it's time to order them two variables taken into account:
* Gwei used,
* Transaction arrival time.
Consequently assuming tx 55 arrived, in order to become tx 56 someone needs to use exact same amount of gwei + first arriving tx after 55 (timestamp).
What if this never happens? If someone else wins the race all the time?
* Faster than us? 
* Any other variable must be taken into account?
* Competing with validator itself, if so what about next block? All validators are in a such race?
Any suggestion is highly appreciated.
