### ISSUE TITLE
Consider quoting command expansion to prevent word splitting SH-2046

### ISSUE THREAD

**Issue by philipjonsen** [ava-labs/avalanchego#1034]
DESCRIPTION
When command expansions are unquoted, word splitting and globbing will occur. This can result unintended behaviour filenames contain spaces.

Trying to fix it by adding quotes or escapes to the data will not work. Instead, quote the command substitution itself.

If the command substitution outputs multiple pieces of data, it is recommended use a loop instead.

Problematic code:
ls -l $(getfilename)
Preferred code:
# getfilename outputs 1 file
ls -l "$(getfilename)"

# getfilename outputs multiple files, linefeed separated
getfilename | while IFS='' read -r line
do
  ls -l "$line"
done
Exceptions:
In cases where you actually want word splitting, such as:

gcc $(pkg-config --libs openssl) client.c
This is because pkg-config outputs -lssl -lcrypto, which you want to break up by spaces into -lssl and -lcrypto.

A bash alternative in these cases is to use read -a for words or mapfile for lines. ksh can also use read -a, or a while read loop for lines. In this case, since pkg-config outputs words, you could use:

# Read words into an array in bash and ksh
read -ra args < <(pkg-config --libs openssl)

# expand args
gcc "${args[@]}" client.c

![bug4](https://user-images.githubusercontent.com/87861683/159888757-05186095-5bec-4583-8c55-78b89b8d4ed6.jpg)

**Additional context**

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by Administratordes** [comment]
Hello GoodDay if you need any help or assistance regarding to any issue at all please don’t hesitate to contact the LiveChat Support https://direct.lc.chat/14065185/
