### ISSUE TITLE
The document for manually start a local network is not followable

### ISSUE THREAD

**Issue by huahuayu** [ava-labs/avalanchego#1040]
Hi, I want manually start a local network based on the document https://docs.avax.network/build/tutorials/platform/create-a-local-test-network/#manually.

Let me copy the steps here

`step1`
```bash
cd $GOPATH/src/github.com/ava-labs/avalanchego
```
`step2`
```bash
./scripts/build.sh
```

`step3`
```bash
./build/avalanchego --public-ip=127.0.0.1 --http-port=9650 --staking-port=9651 --db-dir=db/node1 --network-id=local --bootstrap-ips= --staking-tls-cert-file=$(pwd)/staking/local/staker1.crt --staking-tls-key-file=$(pwd)/staking/local/staker1.key
```

`step4`
```bash
./build/avalanchego --public-ip=127.0.0.1 --http-port=9652 --staking-port=9653 --db-dir=db/node2 --network-id=local --bootstrap-ips=127.0.0.1:9651 --bootstrap-ids=NodeID-7Xhw2mDxuDS44j42TCB6U5579esbSt3Lg --staking-tls-cert-file=$(pwd)/staking/local/staker2.crt --staking-tls-key-file=$(pwd)/staking/local/staker2.key
```

Omit the other 3 nodes...

## Two problems here

1. when executing `step3`, get an error
```
couldn't load node config: set "bootstrap-ips" but didn't set "bootstrap-ids"
```
2. there's no steps to starting a bootstrap node ( 127.0.0.1:9651 ), so the nodes can't find each other

**Comment by ceyonur** [comment]
1- Thank you for reporting. it seems this one was not updated.
2- The bootstrap node is started in the step3. but since you wasn't able to start it (due to 1) it fails to connect it.

**Comment by huahuayu** [comment]
if you delete `--bootstrap-ips=` in the `step3`, thus the cmd changes to

```bash
./build/avalanchego --public-ip=127.0.0.1 --http-port=9650 --staking-port=9651 --db-dir=db/node1 --network-id=local  --staking-tls-cert-file=$(pwd)/staking/local/staker1.crt --staking-tls-key-file=$(pwd)/staking/local/staker1.key
```

then it works.

**Comment by ceyonur** [comment]
Fixed in docs repo.
