### ISSUE TITLE
how to send avax in C chain in local network

### ISSUE THREAD

**Issue by huahuayu** [ava-labs/avalanchego#1041]
Hi, I started the local network by follow the [doc](https://docs.avax.network/build/tutorials/platform/create-a-local-test-network/#manually)

then I import key to C chain

```bash
echo "create user: "
curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"keystore.createUser",
    "params" :{
        "username":"user",
        "password":"PfC77^%^2F"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9652/ext/keystore

echo "import key: "
curl -X POST --data '{  
    "jsonrpc":"2.0",    
    "id"     :1,    
    "method" :"avax.importKey", 
    "params" :{ 
        "username" :"user",   
        "password":"PfC77^%^2F",    
        "privateKey":"PrivateKey-ewoqjP7PxY4yr3iLTpLisriqt94hdyDFNgchSxGGztUrTXtNN"    
    }   
}' -H 'content-type:application/json;' 127.0.0.1:9652/ext/bc/C/avax

echo "get balance: "
curl --location --request POST 'http://127.0.0.1:9652/ext/bc/C/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_getBalance",
    "params": [
        "0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC",
        "latest"
    ],
    "id": 1
}'
```

all successed

```
create user: 
{"jsonrpc":"2.0","result":{"success":true},"id":1}
import key: 
{"jsonrpc":"2.0","result":{"address":"0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC"},"id":1}
get balance: 
{"jsonrpc":"2.0","id":1,"result":"0x295be96e64066972000000"}
```

## Problem

Now I have a c chain address `0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC` which has balance, but I don't know how to transfer the fund to another address so I can do test.

**Comment by ceyonur** [comment]
You can integrate your address to metamask and send funds, or you can export from C-chain to other chains. Please see this documents:
https://docs.avax.network/build/tutorials/platform/fund-a-local-test-network#integrate-with-metamask
https://docs.avax.network/build/tutorials/platform/transfer-avax-between-p-chain-and-c-chain/
https://docs.avax.network/build/tutorials/platform/transfer-avax-between-x-chain-and-c-chain/

This repository is for AvalancheGo related issues/bugs. You can use chat.avax.network for questions.

**Comment by huahuayu** [comment]
Thanks, I see!
