### ISSUE TITLE
blockNumber keeps 0 in local network

### ISSUE THREAD

**Issue by huahuayu** [ava-labs/avalanchego#1042]
Hi, I started a local network by follow the [doc](https://docs.avax.network/build/tutorials/platform/create-a-local-test-network/#manually)

The nodes bootstraps are successful and the health check is good, but the blockNumber keeps zero.

I wonder if I don't send transactions then the block keeps zero?

Now I am not sure if the network is truly health.

**Comment by ceyonur** [comment]
Yes. if you don't send any transactions, network won't create a new block. 

For quicker responses, you can ask your questions in chat.avax.network.

**Comment by huahuayu** [comment]
I think this can be added to https://docs.avax.network/build/tutorials/platform/create-a-local-test-network page.

> For quicker responses, you can ask your questions in chat.avax.network.
I don't expect a quick response from github issue, I like communicating with developers by issue, in discord msg get fragmented.
