### ISSUE TITLE
x chain private to c chain private key 

### ISSUE THREAD

**Issue by huahuayu** [ava-labs/avalanchego#1043]
Hi, if I know the x chain private key how can I get the corresponding c chain private key? I believe there's some internal relation between them.

Let's say the x chain private key is `PrivateKey-ewoqjP7PxY4yr3iLTpLisriqt94hdyDFNgchSxGGztUrTXtNN`

In the official documentation https://docs.avax.network/build/tutorials/platform/create-a-local-test-network/#getting-avax mentioned how to get avax in x chain, but I need the c chain private key so I can use it in metamask.

**Comment by ceyonur** [comment]
It is `0x56289e99c94b6912bfc12adc093c9b51124f0dc54ac7a766b2bc5ccf558d8027` as mentioned in https://docs.avax.network/build/tutorials/platform/fund-a-local-test-network#integrate-with-metamask
