### ISSUE TITLE
Feature request: Better IPv6 support.

### ISSUE THREAD

**Issue by haight6716** [ava-labs/avalanchego#1045]
**Describe the bug**
Using `dynamic-public-ip` on a host with an IPv6 interface, only the v6 IP is advertised and this leads to the node being marked not accessible.

**To Reproduce**
- Start a node using `dynamic-public-ip: opendns` on a host with a v6 IP address and v4 IP address.
- `getNodeIP`

**Expected behavior**
v4 IP address is reported, or better, multiple IPs are reported.

**Screenshots**
```
# curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"info.getNodeIP"
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/info
{"jsonrpc":"2.0","result":{"ip":"[2601:602:8e00:2e7d:92a5:3172:1eba:daf]:9651"},"id":1}
```

**Operating System**
PoPOS (Ubuntu) 21.10

**Additional context**
Workaround: if `dynamic-public-ip: ifconfigme` is used, a v4 IP is returned & advertised.

IMO Ideally we could publish multiple IPs, either v4 or v6 and the client could decide which to use, preferring v6, but falling back to v4.  v4 and v6 IPs would be detected by dyndns and advertised automatically when in `dynamic-public-ip` mode.

Alternately, we could stop penalizing hosts only advertising v6 IPs.

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by kuramo1** [comment]
Kindly open this live chat to talk to the customer service directly on your issue https://direct.lc.chat/13898481/

**Comment by Administratordes** [comment]
Hello GoodDay if you need any help or assistance regarding to any issue at all please don’t hesitate to contact the LiveChat Support https://direct.lc.chat/14065185/
