### ISSUE TITLE
nodeId vs shortId

### ISSUE THREAD

**Issue by huahuayu** [ava-labs/avalanchego#1046]
Hi, I found that in avalanchego and plugin (coreth) the node is actually identified by shortId which is converted by https://github.com/ava-labs/avalanchego/blob/8f0f175868618d5222f4d32af62d4cf954010f56/ids/short.go#L39-L45

May I know why there is a NodeId and then a ShortId, what's the design consideration?

nodeId

```
NodeID-7Xhw2mDxuDS44j42TCB6U5579esbSt3Lg
```

shortId

```
7Xhw2mDxuDS44j42TCB6U5579esbSt3Lg
```

From nodeId you can get shortId by hashing, and the hashed string is shortId but the result is same as trim `NodeID-` prefix, so why not just use trim rather than hashing?

**Comment by StephenButtolph** [comment]
Sorry - I guess I don't really understand your question. `NodeID-` is just a prefix that is added to a hash to clarify that it is referring to a node's ID. Converting from a NodeID to a ShortID does not involve any hashing - all it does is trim the prefix - as you linked on line 44.

**Comment by huahuayu** [comment]
hi @StephenButtolph if you trace the `ShortFromString` function
https://github.com/ava-labs/avalanchego/blob/8f0f175868618d5222f4d32af62d4cf954010f56/ids/short.go#L39-L45

to it's the implementation, isn't it a hash function here

https://github.com/ava-labs/avalanchego/blob/8f0f175868618d5222f4d32af62d4cf954010f56/ids/short.go#L24-L26

**Comment by StephenButtolph** [comment]
`ToHash160` does not compute a hash: https://github.com/ava-labs/avalanchego/blob/27b30767a6b8818e293c54146f0c5305437c02c4/utils/hashing/hashing.go#L92-L99
