### ISSUE TITLE
node monitoring for multi avalanchego node

### ISSUE THREAD

**Issue by huahuayu** [ava-labs/avalanchego#1048]
Hi, [this official tutorial](https://docs.avax.network/build/tutorials/nodes-and-staking/setting-up-node-monitoring/) introduced a method for monitoring one node metrics, but what if I have multi nodes?

The dashboard needs a drop-down menu to select host. Something like

![image](https://user-images.githubusercontent.com/1725060/162679743-c8619bbf-a875-4d88-a912-07877ba504de.png)

Otherwise, say I have 4 nodes, so I need 4x of those same dashboard:

![image](https://user-images.githubusercontent.com/1725060/162678992-d34b771a-7687-4137-81b3-c3472100fbac.png)

**Comment by huahuayu** [comment]
Hi @danlaine how do you think of it?

**Comment by StephenButtolph** [comment]
I'm closing this because this doesn't seem to relate to the `avalanchego` repo. Feel free to open this as an issue on https://github.com/ava-labs/avalanche-docs.
