### ISSUE TITLE
bootstraping never ends

### ISSUE THREAD

**Issue by hiletmis** [ava-labs/avalanchego#1049]
I have set an avalanche node a while ago. It started fetching X and P chains and fetched them successfully. So far it was so good. But when it comes to bootstrapping C chain, the node started acting strange. It has been over a week and still not completed. 

I thought if there is a problem and restarted the node but that didn't help the ETA increased on every restart though. 

Bootstrapped 8M block in 2 days but I'm waiting for the last 5M blocks for days!

I am getting this log and progress to slow.
Apr 12 05:43:03 magna avalanchego[33284]: INFO [04-12|05:43:03.253] <C Chain> snow/engine/common/queue/jobs.go#173: executed 260000 of 4731899 operations. ETA = 393h41m9s
 
**Operating System**
Ubuntu 20

**Additional context**
The node is running on cloud. The machine has a decent configuration.

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by Administratordes** [comment]
Hello GoodDay if you need any help or assistance regarding to any issue at all please don’t hesitate to contact the LiveChat Support https://direct.lc.chat/14065185/

**Comment by singhsahilzeeve** [comment]
I have started a mainnet node about a week ago and it also have not been bootstrapped till now. My system specifications are also good(EC2 instance :- t3.2xlarge with 32 GB ram). Can someone help on how can i reduce this time ?

**Comment by hiletmis** [comment]
No one can reduce the sync time ATM. 512 SSD is also not enough fyi

**Comment by alecalve** [comment]
Running into a similar issue with an already partially synced node:

```
INFO [05-24|15:24:37.456] <C Chain> github.com/ava-labs/coreth/eth/backend.go:185: Initialising Ethereum protocol network=43114 dbversion=8
INFO [05-24|15:24:37.460] <C Chain> github.com/ava-labs/coreth/core/blockchain.go:311: Loaded most recent local header number=14,779,565 hash=cbcf8e..4a7e72 age=1w22h58s
INFO [05-24|15:24:37.460] <C Chain> github.com/ava-labs/coreth/core/blockchain.go:312: Loaded most recent local full block number=14,779,565 hash=cbcf8e..4a7e72 age=1w22h58s
INFO [05-24|15:24:37.463] <C Chain> github.com/ava-labs/coreth/core/blockchain.go:266: Initializing snapshots async=true
INFO [05-24|15:24:37.473] <C Chain> github.com/ava-labs/coreth/plugin/evm/atomic_trie.go:224: initializing atomic trie c=atomicTrie lastAcceptedBlockNumber=14,779,565
INFO [05-24|15:24:37.475] <C Chain> github.com/ava-labs/coreth/plugin/evm/atomic_trie.go:395: committed atomic trie c=atomicTrie hash=0x0cfaf11bc6122023d4f63847e384668e16c1e060f62da3b2898b587210d51ffc height=14,778,368
INFO [05-24|15:24:37.477] <C Chain> github.com/ava-labs/coreth/plugin/evm/atomic_trie.go:338: finished initializing atomic trie c=atomicTrie lastAcceptedBlockNumber=14,779,565 preCommitEntriesIndexed=0 postCommitEntriesIndexed=9 time=3.3959ms
...
INFO [05-25|05:23:26.538] <C Chain> snow/engine/common/queue/jobs.go#173: executed 5000 of 340598 operations. ETA = 783h50m21s
```

783hrs to catchup 340k blocks?!

**Comment by xinxurockx** [comment]
Meet the same problem. Any one can help or just give us a snapshot.

**Comment by DaMandal0rian** [comment]
This is usually an IO and/or CPU issue with not enough cores. Fast disk hardware and high IOPS is essential. Could be poor bandwidth too.

**Comment by DaMandal0rian** [comment]
@xinxurockx let me know if you need a snapshot.

> Meet the same problem. Any one can help or just give us a snapshot.

**Comment by singhsahilzeeve** [comment]
Does passing --state-sync-enabled=true allows C chain to bootstrap faster ? If after bootstrapping will it download previous blocks (historical data ) 
also ?

**Comment by fatminer** [comment]
i have the same problem.

After 10 days, the C-Chain synchronization has not finished.

Isn't there an option like fast-sync like go-ethereum?

**Comment by SquidFinder** [comment]
Same issue, I make zero progress when starting the node. Everything updates to Chain which gets stuck.  If I stop and restart the node my block number (block remaining?) gets smaller, example below

Start number 1: 
![image](https://user-images.githubusercontent.com/83293271/205201228-1e7d6a49-d2d0-433b-935c-033ea14a5b1e.png)

Start number 2:
![image](https://user-images.githubusercontent.com/83293271/205201248-533c84a6-9485-4fac-971e-0b7629c50043.png)

**Comment by SquidFinder** [comment]
> @xinxurockx let me know if you need a snapshot.
> 
> > Meet the same problem. Any one can help or just give us a snapshot.

Can you provide me a snapshot?

**Comment by hiletmis** [comment]
It has been almost one year and is this still a problem!

ava-labs should provide a snapshot option for fast sync. 

> Fast disk hardware (SSD,nvme) and high IOPS is essential. 

hw should not be an excuse. Running a node is not always about mining avax, there can be education purposes, developing purposes etc.

hope ava-labs solve this issue.

**Comment by StephenButtolph** [comment]
> Isn't there an option like fast-sync like go-ethereum?

Yes, there is: https://docs.avax.network/nodes/maintain/chain-config-flags#state-sync

**Comment by StephenButtolph** [comment]
> Does passing --state-sync-enabled=true allows C chain to bootstrap faster ?

Yes, significantly.

> If after bootstrapping will it download previous blocks (historical data ) also ?

State sync will currently not download previous blocks.
