### ISSUE TITLE
validator list api

### ISSUE THREAD

**Issue by huahuayu** [ava-labs/avalanchego#1053]
Hi, I can see there's a validator list in https://explorer-xp.avax.network/validators and https://avascan.info/staking/validators

But neither of them provide api like etherscan, Before I raise issue, I searched issue list , docs and postman api collection, didn't found.

Could you please tell me where is the validator list api? Prefer native api from the node.

**Comment by ceyonur** [comment]
Have you checked API docs? 
https://docs.avax.network/build/avalanchego-apis/p-chain/#platformgetcurrentvalidators

This repository/issue board is for AvalancheGo related bugs/issues. These type of questions can be anwered in: chat.avax.network

**Comment by huahuayu** [comment]
sorry @ceyonur, I do searched the api collection in my postman, it shows like
![image](https://user-images.githubusercontent.com/1725060/163788121-458e23d9-00d9-4722-a087-01d113f0235f.png)

For the doc, the validator keyword is not exclusion ability. Anyway, next time I will communicate in discord.
