### ISSUE TITLE
avm.getAllBalances does not return results in Postman

### ISSUE THREAD

**Issue by SerdarDemirbas** [ava-labs/avalanchego#1054]
I test public api on fuji testnet or mainnet.

But I get following problem.

avm.getAllBalances does not return results in Postman

![image](https://user-images.githubusercontent.com/1551801/163971279-704d8553-b7b4-4892-9c78-5f3cf1f6bc4a.png)

![image](https://user-images.githubusercontent.com/1551801/163971538-db8803ac-4f5c-4945-bbdd-d7aaff476581.png)

`
POST https://api.avax-test.network:443/ext/bc/X
200
620 ms
Network
Request Headers
Content-Type: application/json
User-Agent: PostmanRuntime/7.29.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 5da9ce39-2c36-4910-ba92-f14ecf610ba1
Host: api.avax-test.network:443
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 166
Cookie: AWSALB=3mRo0Tb6rYvl/VWur2zt0F/oXmuQZw4ubSCQ8jcGjmucfNqet1CReFgomo3gvrALnqmtFPZaWhQwovS8fn32FADgCobcAw0FXv7qmZmNVxQ1V2211Fj0TyoRB4L1; AWSALBCORS=3mRo0Tb6rYvl/VWur2zt0F/oXmuQZw4ubSCQ8jcGjmucfNqet1CReFgomo3gvrALnqmtFPZaWhQwovS8fn32FADgCobcAw0FXv7qmZmNVxQ1V2211Fj0TyoRB4L1; __cflb=04dToSvdRcbyfpHwfXTzWXXdEyutfnSv2EnqNWSR6k

Request Body
{
    "jsonrpc":"2.0",
    "id"     : 1,
    "method" :"avm.getAllBalances",
    "params" :{
        "address":"X-fuji1j7zv5g848d67mhsgqkkg5mfvls2se6ckfathsf"
    }
}`

**Comment by Administratordes** [comment]
Hello GoodDay if you need any help or assistance regarding to any issue at all please don’t hesitate to contact the LiveChat Support https://direct.lc.chat/14065185/

**Comment by SerdarDemirbas** [comment]
[Administratordes](https://github.com/Administratordes)    This user is trying to scam with live chat. Be careful.

**Comment by ceyonur** [comment]
`getAllBalances` returns an array of assets with their balances, and seems there is no balance in that address.
https://testnet.avascan.info/blockchain/x/address/X-fuji1j7zv5g848d67mhsgqkkg5mfvls2se6ckfathsf

**Comment by SerdarDemirbas** [comment]
Thanks for your reply ceyonur. 
But when I enter the online wallet with Mnemonic words, the balance appears.

![image](https://user-images.githubusercontent.com/1551801/165511741-55a9c1d5-b38b-4322-b969-6adf2ec30d39.png)

**Comment by ceyonur** [comment]
This wallet is a HD wallet so it can control many addresses. That particular address (starting with `X-fuji1jzv...`) is a fresh one. However that 2 AVAX seems went to another address starting with `X-fuji1x...` (just notice Transactions section in the right pane)

**Comment by ceyonur** [comment]
Yes sender is the faucet address but the address you received those funds probably was different. Try to expand that transaction and see which address actually received the funds. 

Now in this time funds are sent to the address `X-fuji1j7zv5g848d67mhsgqkkg5mfvls2se6ckfathsf`.  You can try `avm.getAllBalances` again and see it yourself.

**Comment by hexfusion** [comment]
> [Administratordes](https://github.com/Administratordes) This user is trying to scam with live chat. Be careful. The comment he wrote here is sent as an e-mail and you think it really came from github.

user was reported

**Comment by ceyonur** [comment]
Take a look at how HD-wallets work. 
https://support.avax.network/en/articles/4784893-what-is-an-hd-wallet

You can use chat.avax.network for general questions

Closing this issue since this repo is only related to AvalancheGo code-related bugs/issues.
