### ISSUE TITLE
avalanchego coreth communcation

### ISSUE THREAD

**Issue by huahuayu** [ava-labs/avalanchego#1057]
Hi, I can see that coreth is avalanchego's plugin, and is implemented by `go-plugin`, also in the doc there is a [sinppets](https://docs.avax.network/build/tutorials/platform/subnets/create-a-virtual-machine-vm/#plugin) shows how to make a plugin to communicate with avalanchgo by grpc.

But in discord developer-chat, @jpop32 said `coreth is in-process to avalanchego so it probably doesn't use grpc. Subnet VMs do` which makes me very confused.

coreth do started a grpc server([link](https://github.com/ava-labs/coreth/blob/f59716999fd10446a91a9aa2e019203f555dbac0/plugin/main.go#L33)) , it's useless?

```go
    plugin.Serve(&plugin.ServeConfig{
        HandshakeConfig: rpcchainvm.Handshake,
        Plugins: map[string]plugin.Plugin{
            "vm": rpcchainvm.New(&evm.VM{}),
        },

        // A non-nil value here enables gRPC serving for this plugin...
        GRPCServer: plugin.DefaultGRPCServer,
    })
```

Could someone clarify this?

**Comment by StephenButtolph** [comment]
Coreth has been inlined directly into Avalanchego in official releases since `v1.7.4`. Coreth is still compatible to be run as a plugin, which has been very useful in testing of further plugin improvements.

**Comment by huahuayu** [comment]
hi, @StephenButtolph thanks for clarifying. I just checked the release v1.7.4, and found your commit https://github.com/ava-labs/avalanchego/commit/7dd7bea0e2660b21ecbdac80504104e93d622047 the title is "inlined the evm", but the change is simple, basically, one line effectively makes it inlined?

```go
 		n.Config.VMManager.RegisterFactory(evm.ID, &coreth.Factory{}),
```

If it's inlined, suppose coreth no need to compile and put the binary at a specific dir which is later invoked by avalanchego. But now we still need compile coreth at first, how's that?
