### ISSUE TITLE
`eth_syncing` does not seem to be implemented

### ISSUE THREAD

**Issue by AaronKutch** [ava-labs/avalanchego#1058]
When remote procedure calling `avalanchego`, I found an unimplemented call needed for the Onomy<->Avalanche [ava-bridge](https://github.com/AaronKutch/cosmos-gravity-bridge/tree/ava-bridge)
```
Err(JsonRpcError { code: -32601, message: "the method eth_syncing does not exist/is not available", data: "None" })
```

A quick way to test for some calls I need is to clone https://github.com/AaronKutch/rust_container_runner/tree/ava-bridge and run `bash ./run.sh` (there are going to be some errors from incomplete calls, but when the call doesn't exist at all it will say). You can also run the in-development ava-bridge branch with `USE_LOCAL_ARTIFACTS=1 bash tests/all-up-test.sh HAPPY_PATH_V2` (but note if eth_syncing is fixed it may run into some unrelated issues before getting to other calls).

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

Note: both terms and conditions links are broken, can someone fix the bug report template?

**Comment by AaronKutch** [comment]
wait I just realized I did something stupid in the automation

**Comment by ceyonur** [comment]
`eth_syncing` is not implemented currently. for bootstrapping status you should check: https://docs.avax.network/build/avalanchego-apis/info#infoisbootstrapped

**Comment by AaronKutch** [comment]
bootstrapped is just a boolean, `eth_syncing` supplies realtime information about block heights
```
pub enum SyncingStatus {
    NotSyncing(bool),
    #[serde(rename_all = "camelCase")]
    Syncing {
        starting_block: Uint256,
        current_block: Uint256,
        highest_block: Uint256,
    },
}
```
So `info.isbootstrapped` both is not standard and does not have the information needed. From a brief look it seems `eth_syncing` has some information we can't get from other `eth_` calls. `eth_syncing` is used quite numerously and 3 deep in our dependencies, we would have to make a lot of ava specific changes we don't have to make to other bridges, and we want our bridges to have as much in common as possible.

**Comment by AaronKutch** [comment]
I'm also getting `the method info.isBootstrapped does not exist/is not available`
```
[/home/aaron/web30/src/jsonrpc/client.rs:81] &req = Request {
    method: POST,
    uri: http://localhost:9650/ext/bc/C/rpc,
    version: HTTP/1.1,
    headers: {
        "content-type": "application/json",
    },
    body: Body(
        Full(
            "{"id":1,"jsonrpc":"2.0","method":"info.isBootstrapped","params":[]}",
        ),
    ),
}
````

**Comment by AaronKutch** [comment]
I now realize that Avalanche may have done some radical changes to the EVM compared to previous networks I have bridged to. I made a workaround for the lack of `eth_syncing` and immediately encountered an issue where the bridge would halt because blocks were not being produced after transactions were made (determined by `eth_blockNumber`). It appears that a block is made for every contract creation made, and nothing happens with regular transactions (`avalanchego` logs indicate it just seems to idle indefinitely without contracts). Is this expected behavior?

**Comment by AaronKutch** [comment]
> It looks like that you used the wrong end point when calling this api

All of our `Web3` structs, container scripts, and environment variables are built around one entry point for all RPC stuff per bridge, the hacks and special cases would be tremendous, I would rather `eth_syncing` were implemented and then this conundrum doesn't need to exist. Maybe it's not so bad if I made a specialized branch of our `web3` crate that used a different address for the syncing, but then I have to remember to rebase that branch when updating `web3` for all the bridges, ... no matter how you look at it, it is completely unnecessary forced technical debt.

> Avalanche is quiescent - if there are no transactions posted, there are no blocks created

Normal quiescence our bridges can handle, they send out transactions first before blocking on block numbers incrementing. However, for some reason blocks only seem to be produced on contracts being submitted and not with transactions. For example: this is the last line in the logs from `avalanchego`:
```
INFO [05-16|18:14:56.353] <C Chain> github.com/ava-labs/coreth/internal/ethapi/api.go:1745: Submitted transaction hash=0xc0ea83c5c1b2ba2b2d1ae9d3748b87625044acd4f562ae79bf02f49f77e0a763 from=0xBf660843528035a5A4921534E156a27e64B231fE nonce=0 recipient=0xb3d82b1367D362DE99aB59A658165AFf520CBd4d value=10,000,000,000,000,000,000,000,000 type=0 gasFeeCap=30,000,000,000 gasTipCap=30,000,000,000 gasPrice=30,000,000,000
```
The bridge is waiting for the transaction id to be included in a block that never comes

**Comment by AaronKutch** [comment]
When working on another bridge I ran into another quiescence problem where the chain would not produce blocks if there were no transactions, softlocking some tests. I decided that it wasn't the chain's fault, it does make sense that no blocks should be produced if there are no transactions pending. I implemented a workaround where a worker would periodically submit dummy transactions and poll things forward. However, `avalanchego` still only seems to build blocks for contracts and not transactions, I would need a much more complex workaround for it until this issue is fixed. I just need quiescence to work with respect to transactions and then the workaround will work

**Comment by AaronKutch** [comment]
There's actually two issues, should I make a separate issue for the block production problem?

**Comment by aaronbuchwald** [comment]
Hey @AaronKutch , `eth_syncing` was removed when we made a push to remove any APIs that didn't make sense in the context of Avalanche and this was probably a mistake in the case of `eth_syncing`.

We will add this endpoint back in the next release. As for the other issue regarding txs vs contract txs, I would not expect that to be an issue so I suspect there may be an issue with regards to building the transactions with different gas prices/gas limits or something of that kind. If you're still seeing that issue, would you mind porting all of the details to a bug report in coreth here: https://github.com/ava-labs/coreth/issues/new/choose.

**Comment by StephenButtolph** [comment]
`eth_syncing` was added back in `v1.7.15`.

**Comment by Mrvarg** [comment]
How can i unsubscribe this thing it’s irritating me

**Comment by AaronKutch** [comment]
there is an option in the github UI to unsubscribe from a thread, or maybe you have the Watch setting on this repo set to all activity
