### ISSUE TITLE
Avalanche integration into Santiment

### ISSUE THREAD

**Issue by antisaa** [ava-labs/avalanchego#1059]
I am working on Avalanche integration to Santiment - data analytics platform. I have issues with exporting internal transactions and I would need support of `trace_filter` API method or some similar, could you please help?

**Comment by danlaine** [comment]
@antisaa We generally use Github issues to track bugs and feature requests. For help writing code, please see the `#developers-chat` on our [Discord Server](https://chat.avax.network). Thanks.
