### ISSUE TITLE
avm.getAddressTxs does not exist on api.avax-test.network/ext/bc/X

### ISSUE THREAD

**Issue by kriptontr** [ava-labs/avalanchego#1065]
As described [here](https://docs.avax.network/apis/avalanchego/apis/x-chain#avmgetaddresstxs) I'm trying to hit ```avm.getAddressTxs``` method with address ``X-fuji10rcn2g92669dyadv3h32sqdsyk7h5ghmvgcd70``  at ``` https://api.avax-test.network/ext/bc/X ```  but I get the error message 
````
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32601,
        "message": "the method avm.getAddressTxs does not exist"
    }
}
````
then if I change ```"avm.getAddressTxs"``` with   ```"avm.getBalance"``` I'm able to get succesfull message like below 
```
{
    "jsonrpc": "2.0",
    "result": {
        "balance": "2000000000",
        "utxoIDs": [
            {
                "txID": "VrnMtekJ691UoddiqUkiy3j9VoKgk71SP8TvmH43PJcNy6GVr",
                "outputIndex": 0
            }
        ]
    },
    "id": 1
}
```

**To Reproduce**
 you can run 
```
curl --location --request POST 'https://api.avax-test.network/ext/bc/X' \
--header 'content-type: application/json;' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "avm.getAddressTxs",
    "params": {
        "address": "X-fuji10rcn2g92669dyadv3h32sqdsyk7h5ghmvgcd70",
        "assetID": "AVAX",
        "pageSize": 20
    }
}'
```
and for getBalance
```
curl --location --request POST 'https://api.avax-test.network/ext/bc/X' \
--header 'content-type: application/json;' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "avm.getBalance",
    "params": {
        "address": "X-fuji10rcn2g92669dyadv3h32sqdsyk7h5ghmvgcd70",
        "assetID": "AVAX",
        "pageSize": 20
    }
}'
```
**Expected behavior**
I guess it should behave like expected at docs. Is it something restricted on public APIs or sth?

**Comment by danlaine** [comment]
The Public API doesn't support this method. I've made a [PR](https://github.com/ava-labs/avalanche-docs/pull/957) to specify this. Thanks for pointing this out.
