### ISSUE TITLE
Cross-chain transaction doesn't work: the method avax.issueTx does not exist

### ISSUE THREAD

**Issue by ramilexe** [ava-labs/avalanchego#1066]
Cross-chain transaction doesn't work: the method avax.issueTx does not exist

**Describe the bug**
Using wallet I am trying to cross-transfer my funds from C-Chain to P-Chain and getting error `the method avax.issueTx does not exist`

**To Reproduce**

Using curl

```
> curl 'https://api.avax.network/ext/bc/X'   -H 'content-type: application/json;charset=UTF-8'   --data-raw '{"id":4,"method":"avax.issueTx","params":{"tx":"...."},"jsonrpc":"2.0"}' 

{"jsonrpc":"2.0","id":4,"error":{"code":-32601,"message":"the method avax.issueTx does not exist"}}
```

Using Wallet: perform cross-chain transaction from C-Chain to P-Chain

**Expected behavior**
Tranasction should be accepted by the network

**Screenshots**

**Operating System**
Ubuntu

**Additional context**

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by ceyonur** [comment]
the method name is `avm.issueTx` not `avax.issueTx`:
https://docs.avax.network/apis/avalanchego/apis/x-chain/#avmissuetx

**Comment by ramilexe** [comment]
@ceyonur the issue appear on web wallet

**Comment by ramilexe** [comment]
From my bug report:
> Using Wallet: perform cross-chain transaction from C-Chain to P-Chain

**Comment by ramilexe** [comment]
@ceyonur here is the code in Wallet: https://github.com/ava-labs/avalanche-wallet/blob/41028787d947aa660338a41a5c22700ccc48ac50/src/js/wallets/WalletCore.ts#L147

**Comment by Activatorq1** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14156445/

**Comment by Activatorq1** [comment]
You can Notify me when you have any issues

**Comment by StephenButtolph** [comment]
Seems like at worst this is an AvalancheJS issue. Please open the issue there.
