### ISSUE TITLE
Question: what is the purpose of `ethAddr` in allocations section of Genesis config?

### ISSUE THREAD

**Issue by kirillt** [ava-labs/avalanchego#1072]
Hello, I am working on stress testing of Avalanche network for educational reasons. In order to achieve this, I am creating private network with custom Genesis config. I noticed that each validator listed in `initialStakers` section must have it's own field in `allocations` section of the same JSON.

Now, I see that each allocation, apart from `initialAmount` field, contains fields `avaxAddr` and `ethAddr`. It seems to be clear what are the former 2, but what is `ethAddr`?

Brief code examination revealed, that corresponding field `ETHAddr` of Go structure `Allocation` is used only for filling these 2 fields:
* `Memo` of `AssetDefinition` structure
* `Message` of `APIUTXO` structure

Am I right that `ethAddr` is attached for solely informational and debugging reasons?

**Comment by StephenButtolph** [comment]
You are correct, `ethAddr` is attached solely for informational purposes. It has no impact on the state in the network (other than the genesis hash).
