### ISSUE TITLE
How to perform data pruning

### ISSUE THREAD

**Issue by liuhongfei0517** [ava-labs/avalanchego#1089]
Hello, I only found about c-chain pruning in the document, how to do all data pruning.
Can someone give me some advice? Thank you very much!

**Comment by patrick-ogrady** [comment]
Hi @liuhongfei0517,

Offline Pruning is only supported on the C-Chain right now. We'll be sure to let you know when you can run pruning on the rest of the node.

**Comment by liuhongfei0517** [comment]
Hi @patrick-ogrady,

My disk is about to fill up. Is there another solution.

![image](https://user-images.githubusercontent.com/105718312/175798222-dce7d54f-6b71-4457-bedf-045d7a42a5a7.png)

**Comment by aaronbuchwald** [comment]
You can run offline pruning on the C-Chain again, but if your disk is nearing full after running offline pruning then you will need to add more disk space.

**Comment by danlaine** [comment]
We plan to release more functionality to reduce disk usage in the future. Closing this as there isn't anything more you can do at the moment.
