### ISSUE TITLE
Questions about seed C- accounts

### ISSUE THREAD

**Issue by DDiscua** [ava-labs/avalanchego#1091]
Hi, 

I have created a custom blockchain (custom genesis) in a local network. My questions is : 

is there any way to add more funds to the seed account after creation?

**Comment by aaronbuchwald** [comment]
For your local network, there is not a way to mint more of these funds directly on the C-Chain. The way to mint more funds on a new network in general is through staking on the P-Chain, which generates funds that can be exported to the C-Chain.

If you are launching a subnet, you may be interested in taking a look at the native minter stateful precompile: https://docs.avax.network/subnets/customize-a-subnet#minting-native-coins.

**Comment by DDiscua504** [comment]
Thank you...!
