### ISSUE TITLE
Is there a way to get the ETAs for each chain?

### ISSUE THREAD

**Issue by vldolot** [ava-labs/avalanchego#1093]
I've tried to search for the keywords `estimate`, `ETA`, `duration`, or even `time` from the available Avalanche docs, from /ext/metrics endpoint and from the issues list here but couldn't find anything about how to get the ETAs for each chain.

Is there a way to get the ETAs for each chain?

Thanks

**Comment by danlaine** [comment]
@vldolot Are you referring to the ETA until the node is done bootstrapping each chain?

**Comment by vldolot** [comment]
Yes. For each chain. Thanks

**Comment by danlaine** [comment]
There's no Prometheus metric for this, only the info that's printed, but I've made a ticket to add this functionality because I think it's a good idea. Thanks.

**Comment by vldolot** [comment]
That's good to hear. Looking forward to it. Thank you

**Comment by tubededentifrice** [comment]
Check the following metrics:
```
avalanche_C_block_eta_execution_complete
avalanche_X_tx_eta_execution_complete
avalanche_X_vtx_eta_execution_complete
avalanche_P_block_eta_execution_complete
```

However due to https://github.com/ava-labs/avalanchego/issues/1143 the metrics are currently stuck at 0

**Comment by abi87** [comment]
Hello @vldolot,
We have just added some documentation explaining the bootstrap process [here](https://docs.avax.network/nodes/maintain/node-bootstrap).
I am going ahead and closing down this issue. You are welcome to open another one, here or in [our docs repo](https://github.com/ava-labs/avalanche-docs/issues) should there be more questions.
