### ISSUE TITLE
Some problem about grafana

### ISSUE THREAD

**Issue by asdfec** [ava-labs/avalanchego#1095]
There is a question about grafana.I want to know why there are so many [nodata]s on the page although my node have been bootstrapped.However the machine metrics can be showed.
I reinstall the Monitor parts,and restart them.Nothing changed.
How should I troubleshoot this problem。
![Boot](https://user-images.githubusercontent.com/15544607/179462100-3c80722a-456e-4756-9bc8-ef5851412bd0.png)
![gra](https://user-images.githubusercontent.com/15544607/179462107-26d18561-71a7-44f2-a3dc-00a7aaf17567.png)
![prom](https://user-images.githubusercontent.com/15544607/179462109-7262bc89-7e3f-4ceb-9079-1b39b489e3d0.png)
![Machine](https://user-images.githubusercontent.com/15544607/179462608-37fe9dbe-3bad-4b0d-8b21-ae111b458b0b.png)

**Comment by danlaine** [comment]
@asdfec Is Grafana configured to scrape data from AvalancheGo's metrics API?

I suggest using the installation script [here](https://docs.avax.network/nodes/maintain/setting-up-node-monitoring).
