### ISSUE TITLE
how to use /ext/index/X/vtx?

### ISSUE THREAD

**Issue by sukicyh** [ava-labs/avalanchego#1105]
may i know how to use X-Chain Vertices?
i want to get height number.

**Comment by sukicyh** [comment]
@danlaine i dont think so. i have read this doc before, but it seem no API allow me to get height number. however, i have search that vertex should be able to do that. but i cannot find how to do it. could you give me an advice ?
https://docs.avax.network/specs/avm-transaction-serialization#vertex-example

**Comment by StephenButtolph** [comment]
Only the `index-api` surfaces vertices. If that API doesn't give you what you need then there is no such API.
