### ISSUE TITLE
How to get USDC token information like balance, transaction ..etc from avax full node?

### ISSUE THREAD

**Issue by UMANGAWASTHY** [ava-labs/avalanchego#1106]
Hello Team, 
I want to extract all information for 0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E USDC token like balance’s, transactions etc.
I had setup avalanche full node using docker image, currently it is syncing. 
Once its full sync. Will it fulfill my requirement? 
Here is the steps to setup node
https://hub.docker.com/r/avaplatform/avalanchego
1.	docker pull avaplatform/avalanchego
2.	sudo docker run -d --name avalanche-node --rm -v $PWD/data:/root/.avalanchego -ti -p 9650:9650 -p 9651:9651 avaplatform/avalanchego

**Comment by christiankakesa** [comment]
Easy way is to use C-Chain explorer data : https://snowtrace.io/token/0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e

You have documentation of the C-Chain API : https://docs.avax.network/apis/avalanchego/apis/c-chain

Any EVM client tutorial works :

- Golang: https://geth.ethereum.org/docs/developers/dapp-developer/native#tutorial
- NodeJs: https://docs.ethers.org/v6/

Other ways is to use data provider like https://www.covalenthq.com/ or index data with https://github.com/ava-labs/ortelius.

Enjoy!
