### ISSUE TITLE
No possible to reenable pruning

### ISSUE THREAD

**Issue by sebasgoldberg** [ava-labs/avalanchego#1117]
**Describe the bug**
No possible to reenable pruning in a node that was running with pruning disabled.

**To Reproduce**
Steps to reproduce the behavior.
1) Set C-Chain config to:
```
{
    "pruning-enabled": false
}
```
2) systemctl restart avalanchego.service
3) Leave runing avalanchego some time.
4) 
```
{
    "pruning-enabled": true
}
```
5) systemctl restart avalanchego.service
6) The node keeps resarting showing the following error:
`FATAL chains/manager.go:287 error creating required chain {"chainID": "2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5", "error": "error while creating new snowman vm node has operated with pruning disabled, shutting down to prevent missing tries"}`

*Note: I have already tried to perform different combinations using offline-pruning-enabled and pruning-enabled, but non of them was successful.* 

**Expected behavior**
Continue running with pruning enabled.

**Screenshots**
NA

**Logs**
`FATAL chains/manager.go:287 error creating required chain {"chainID": "2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5", "error": "error while creating new snowman vm node has operated with pruning disabled, shutting down to prevent missing tries"}`

**Metrics**
NA

**Operating System**
Ubuntu Server 22.04

**Additional context**
NA

Avalanche Bug Bounty program can be found [here](https://hackenproof.com/avalanche/avalanche-protocol).

**Comment by darioush** [comment]
Hi, in case you want to switch from archive to pruning, you should add the option `"allow-missing-tries": true` to your config along with the other options.
This is to prevent accidentally enabling pruning on a node that has originally been set up as an archive node.

**Comment by sebasgoldberg** [comment]
Hi @darioush, thank you very much for your response.

Does `"allow-missing-tries"` could have other consequences ?
Or is it only use for reenabling pruning?

Additionally, I look for this option on official documentation, and it is not mentioned there: https://docs.avax.network/nodes/maintain/chain-config-flags

Thanks in advance.

**Comment by darioush** [comment]
This is the only use for the option 
I will follow up on documentation today. cc @yulin-dong

**Comment by sebasgoldberg** [comment]
OK @darioush, thank you very much for your response.
