### ISSUE TITLE
Avalanchego with subnet-evm stopped validating suddenly

### ISSUE THREAD

**Issue by ongrid** [ava-labs/avalanchego#1128]
**Describe the bug**
Avalanchego v1.7.18 with subnet-evm v0.2.9 suddenly stoped validation or/and distribution of blocks after uptime of 1 week. Timeframe when it happened is `08-31|03:49` (see logs attached). Process didn't restart, peerings were steady, no infrastructure events were noticed at that time. Avalanchego process restart restored its proper operation.

**Logs**
[stopped-node-log.tar.gz](https://github.com/ava-labs/avalanchego/files/9459210/stopped-node-log.tar.gz)

**Metrics**

08-31 03:49 UTC subnet blocks stopped growing.

![image](https://user-images.githubusercontent.com/7992612/187612289-773a03fb-6211-480f-b832-60a4d4fc54cb.png)

**Operating System**
Ubuntu on AWS
8 CPU x Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
RAM: 32 G
disk 1 TB

**Comment by yulin-dong** [comment]
Were these nodes on Fuji?

**Comment by ongrid** [comment]
no, it was mainnet

**Comment by StephenButtolph** [comment]
Without anything more to go on - I don't think there is really much to do here. If something like this happens again it would probably be good to set the log level to `debug` to try to see what is actually going on under the hood (requires enabling the admin api).

If there is any replication here feel free to re-open this.
