### ISSUE TITLE
`fd-limit` is confused

### ISSUE THREAD

**Issue by PatrickAlphaC** [ava-labs/avalanchego#1136]
**Describe the bug**
I'm getting the following error: 

```
[09-06|15:50:52.445] FATAL process/process.go:74 failed to set fd-limit {"error": "error fd-limit: (32768) greater than max: (4096)"}
```

**To Reproduce**
```
git clone https://github.com/ava-labs/avalanchego.git
cd avalanchego
git pull
./scripts/build.sh
/my_dir/avalanchego/build/avalanchego --http-host=
```

I get the following error:

```
[09-06|15:50:52.445] FATAL process/process.go:74 failed to set fd-limit {"error": "error fd-limit: (32768) greater than max: (4096)"}
```

If I update the `fd-limit` to be `4096` (using the `--fd-limit=4096` flag), I get the following warning:

```
WARN ulimit/ulimit_unix.go:50 fd-limit is less than recommended and could result in reduced performance {"limit": 4096, "recommendedLimit": 32768}
```

**Expected behavior**
It works for the default `32768` fd-limit

**Operating System**
Ubuntu 18.04.4 LTS
go version go1.19.1 linux/amd64
avalanchego 1.8.2

**Comment by PatrickAlphaC** [comment]
Should we just run with the warning? That seems... off.

**Comment by hexfusion** [comment]
Ideally you should increase the limits for your system which right now has a hard limit of 4096.
```
$ ulimit -Hn
4096
```
ref. https://linuxhint.com/increase-open-file-limit-ubuntu

**Comment by PatrickAlphaC** [comment]
Is that a new requirement? I that wasn't an issue for us on 1.7?

**Comment by bensacc** [comment]
also, running ulimit -Hn on the node in questions returns:
```
$ ulimit -Hn
1048576
```

**Comment by hexfusion** [comment]
> Is that a new requirement? I that wasn't an issue for us on 1.7?

The logging change was introduced in v1.7.8[1]

[1] https://github.com/ava-labs/avalanchego/releases/tag/v1.7.8

**Comment by hexfusion** [comment]
> also, running ulimit -Hn on the node in questions returns:
> 
> ```
> $ ulimit -Hn
> 1048576
> ```

Under the hood this is a syscall to Getrlimit[1], so the logic should not of changed. Just to clarify your running the command with the same user that runs avalanchego?

```
$  whoami; ulimit -Hn
```

[1] https://github.com/ava-labs/avalanchego/blob/v1.8.2/utils/ulimit/ulimit_unix.go#L28

**Comment by bensacc** [comment]
We are indeed, the same user running avalancheglo returns the 1048576.  I did notice the soft limit, ulimit -Sn returns 1024 which of which the 4096 referenced is the error is 4x.  This could just be a numerological coincidence, but digging into it a bit, and thanks for your help!

**Comment by hexfusion** [comment]
Sure, if your using the systemd unit file dig on `DefaultLimitNOFILE`.

**Comment by hexfusion** [comment]
Closing as I don't believe this is an issue with avalanchego please reopen if you have additional issues.
