### ISSUE TITLE
Unable to run Curl query on  avalanchego full charged node

### ISSUE THREAD

**Issue by UMANGAWASTHY** [ava-labs/avalanchego#1141]
Hello Team 

**I had setup avalanche full node using down steps.  This node charged fully, I unable to run curl query from server, but curl working fine within container.**

**Docker image** -  sudo docker pull avaplatform/avalanchego:v1.8.2
**Docker container** - sudo docker run -d --name avalanche-mainnet-9650 --rm -v $PWD/data:/data -v $PWD/logs:/root/.avalanchego -ti -p 9650:9650 -p 9651:9651 avaplatform/avalanchego:v1.8.2

**Curl query -- **
curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"info.isBootstrapped",
    "params": {
        "chain":"X"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/info

O/p - curl: (56) Recv failure: Connection reset by peer
O/p within container - {"jsonrpc":"2.0","result":{"isBootstrapped":true},"id":1}

**Comment by StephenButtolph** [comment]
By default the avalanchego http server only binds to localhost. Setting the `--http-host` flag can allow binding to other addresses,
