### ISSUE TITLE
how do I see the block number it's on while I'm syncing?

### ISSUE THREAD

**Issue by chaonaa** [ava-labs/avalanchego#1151]
Hi,
how do I see the block number it's on while I'm syncing?

Thank you.
Chaona

**Comment by AaronKutch** [comment]
`eth_blockNumber` should work, manually you can do something like `curl -s --header "content-type: application/json" --data '{"method":"eth_blockNumber","params":[],"id":93,"jsonrpc":"2.0"}' http://localhost:8545/ext/bc/C/rpc`

**Comment by kcy1019** [comment]
We can't. The RPC is not available until the sync is finished.

**Comment by abi87** [comment]
Hello @chaonaa,
I have a pretty late comment, but hopefully still usefull.
We have just added some documentation explaining the bootstrap process [here](https://docs.avax.network/nodes/maintain/node-bootstrap).
As @kcy1019 mentioned, RPCs are not available during sync. See [this section](https://docs.avax.network/nodes/maintain/node-bootstrap#why-are-avalanchego-apis-disabled-during-bootstrapping) for a technical explaination and pointer to the code which enforces this.
I am going ahead and closing down this issue. You are welcome to open another one, here or in [our docs repo](https://github.com/ava-labs/avalanche-docs/issues) should there be more questions.
