### ISSUE TITLE
Question: What are the difference in evm between ethereum and avalanche

### ISSUE THREAD

**Issue by rakita** [ava-labs/avalanchego#1161]
Hello, I am the author of [revm](https://github.com/bluealloy/revm) and someone opened an issue with the incompatibility of revm with avalanche transaction, I am not familiar with the differences and want to ask if it is only in precompiles or it is something deeper?

The issue in question: https://github.com/bluealloy/revm/issues/241

**Comment by rakita** [comment]
Bug was resolved, it was related to block hash.

If people are present, I am still interested to hear the answer.

**Comment by rakita** [comment]
One diff seems to be that avalanche does not include a refund: https://github.com/bluealloy/revm/pull/264#issuecomment-1315243265

**Comment by aaronbuchwald** [comment]
You can check the differences between Ethereum and Avalanche C-Chain in the Coreth Readme here: https://github.com/ava-labs/coreth.
