### ISSUE TITLE
Transaction hash mismatching in block json in P-Chain getBlock rpc query and explorer.

### ISSUE THREAD

**Issue by UMANGAWASTHY** [ava-labs/avalanchego#1168]
Hello Team 
Unable to get transaction hash in block json in P-Chain getBlock rpc query.
**Explorer Url -** https://avascan.info/blockchain/p/tx/2gZCB2pSLarX8YRsYkxScLZr18PNNVnoJCj1jDh2MUTBCYUP4x
**Curl Query -** curl --location --request POST 'http://127.0.0.1:9651/ext/bc/P' \
--header 'content-type: application/json;' \
--data-raw '{ "jsonrpc": "2.0",  "method": "platform.getBlock",   "params": {  "blockID": "2SqWZicfDEQhebMA7Ab3W9uLHiBv2eMNwQ3w9LSbymCuARiWTZ",  "encoding": "json" }, "id": 1 }'

**O/p -**  
{"jsonrpc":"2.0","result":{"block":{"parentID":"2peK2rrira1UUdFuLWZTMHFdGe3JY8sQeKLfPj5jhPdK8mMAcJ","height":3,"tx":{"unsignedTx":{"networkID":1,"blockchainID":"11111111111111111111111111111111LpoYY","outputs":[],"inputs":[{"txID":"11111111111111111111111111111111LpoYY","outputIndex":11112,"assetID":"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z","fxID":"spdxUxVJQbX85MGxMHbKw1sHxMnSqJ3QBzDyDYEP3h6TLuxqQ","input":{"locktime":1607472000,"input":{"amount":960150000000,"signatureIndices":[0]}}},{"txID":"11111111111111111111111111111111LpoYY","outputIndex":11113,"assetID":"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z","fxID":"spdxUxVJQbX85MGxMHbKw1sHxMnSqJ3QBzDyDYEP3h6TLuxqQ","input":{"locktime":1615248000,"input":{"amount":960150000000,"signatureIndices":[0]}}},{"txID":"11111111111111111111111111111111LpoYY","outputIndex":11114,"assetID":"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z","fxID":"spdxUxVJQbX85MGxMHbKw1sHxMnSqJ3QBzDyDYEP3h6TLuxqQ","input":{"locktime":1623024000,"input":{"amount":960150000000,"signatureIndices":[0]}}},{"txID":"11111111111111111111111111111111LpoYY","outputIndex":11115,"assetID":"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z","fxID":"spdxUxVJQbX85MGxMHbKw1sHxMnSqJ3QBzDyDYEP3h6TLuxqQ","input":{"locktime":1630800000,"input":{"amount":960150000000,"signatureIndices":[0]}}},{"txID":"11111111111111111111111111111111LpoYY","outputIndex":11116,"assetID":"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z","fxID":"spdxUxVJQbX85MGxMHbKw1sHxMnSqJ3QBzDyDYEP3h6TLuxqQ","input":{"locktime":1638576000,"input":{"amount":960150000000,"signatureIndices":[0]}}},{"txID":"11111111111111111111111111111111LpoYY","outputIndex":11117,"assetID":"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z","fxID":"spdxUxVJQbX85MGxMHbKw1sHxMnSqJ3QBzDyDYEP3h6TLuxqQ","input":{"locktime":1646352000,"input":{"amount":960150000000,"signatureIndices":[0]}}}],"memo":"0x00000000","validator":{"nodeID":"NodeID-A6onFGyJjA37EZ7kYHANMR1PFRT8NmXrF","start":1600741115,"end":1604283515,"weight":5760900000000},"stake":[{"assetID":"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z","fxID":"spdxUxVJQbX85MGxMHbKw1sHxMnSqJ3QBzDyDYEP3h6TLuxqQ","output":{"locktime":1607472000,"output":{"addresses":["P-avax1u6xzj47hp5g0atfx4haadhzp6jah52sngfgdvg"],"amount":960150000000,"locktime":0,"threshold":1}}},{"assetID":"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z","fxID":"spdxUxVJQbX85MGxMHbKw1sHxMnSqJ3QBzDyDYEP3h6TLuxqQ","output":{"locktime":1615248000,"output":{"addresses":["P-avax1u6xzj47hp5g0atfx4haadhzp6jah52sngfgdvg"],"amount":960150000000,"locktime":0,"threshold":1}}},{"assetID":"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z","fxID":"spdxUxVJQbX85MGxMHbKw1sHxMnSqJ3QBzDyDYEP3h6TLuxqQ","output":{"locktime":1623024000,"output":{"addresses":["P-avax1u6xzj47hp5g0atfx4haadhzp6jah52sngfgdvg"],"amount":960150000000,"locktime":0,"threshold":1}}},{"assetID":"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z","fxID":"spdxUxVJQbX85MGxMHbKw1sHxMnSqJ3QBzDyDYEP3h6TLuxqQ","output":{"locktime":1630800000,"output":{"addresses":["P-avax1u6xzj47hp5g0atfx4haadhzp6jah52sngfgdvg"],"amount":960150000000,"locktime":0,"threshold":1}}},{"assetID":"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z","fxID":"spdxUxVJQbX85MGxMHbKw1sHxMnSqJ3QBzDyDYEP3h6TLuxqQ","output":{"locktime":1638576000,"output":{"addresses":["P-avax1u6xzj47hp5g0atfx4haadhzp6jah52sngfgdvg"],"amount":960150000000,"locktime":0,"threshold":1}}},{"assetID":"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z","fxID":"spdxUxVJQbX85MGxMHbKw1sHxMnSqJ3QBzDyDYEP3h6TLuxqQ","output":{"locktime":1646352000,"output":{"addresses":["P-avax1u6xzj47hp5g0atfx4haadhzp6jah52sngfgdvg"],"amount":960150000000,"locktime":0,"threshold":1}}}],"rewardsOwner":{"addresses":["P-avax1u6xzj47hp5g0atfx4haadhzp6jah52sngfgdvg"],"locktime":0,"threshold":1}},"credentials":[{"signatures":["0x3d6a9819153edd90e2274f6f8461f007592c8dc4f62db0b47510370de2b917c96b3f9aabaeb3f26b5e79bad25f1352364440d17615e7176ad77b5d30209cd83600"]},{"signatures":["0x3d6a9819153edd90e2274f6f8461f007592c8dc4f62db0b47510370de2b917c96b3f9aabaeb3f26b5e79bad25f1352364440d17615e7176ad77b5d30209cd83600"]},{"signatures":["0x3d6a9819153edd90e2274f6f8461f007592c8dc4f62db0b47510370de2b917c96b3f9aabaeb3f26b5e79bad25f1352364440d17615e7176ad77b5d30209cd83600"]},{"signatures":["0x3d6a9819153edd90e2274f6f8461f007592c8dc4f62db0b47510370de2b917c96b3f9aabaeb3f26b5e79bad25f1352364440d17615e7176ad77b5d30209cd83600"]},{"signatures":["0x3d6a9819153edd90e2274f6f8461f007592c8dc4f62db0b47510370de2b917c96b3f9aabaeb3f26b5e79bad25f1352364440d17615e7176ad77b5d30209cd83600"]},{"signatures":["0x3d6a9819153edd90e2274f6f8461f007592c8dc4f62db0b47510370de2b917c96b3f9aabaeb3f26b5e79bad25f1352364440d17615e7176ad77b5d30209cd83600"]}]}},"encoding":"json"},"id":1}

Thanks
Umang

**Comment by abi87** [comment]
Hello @UMANGAWASTHY,
my answer is late but hopefully still helpful.
There is not really a mismatch here.
The `GetBlock` API with json encoding, returns the block content, i.e. block header + block transactions.
[P-chain transactions do not serialize their ID](https://github.com/ava-labs/avalanchego/blob/master/vms/platformvm/txs/tx.go#L27:L36), which is why you don't see a transaction ID returned. Instead the transaction ID is calculated from the transaction upon parsing, as you can see [here](https://github.com/ava-labs/avalanchego/blob/master/vms/platformvm/txs/tx.go#L63:L86)

**Comment by alecalve** [comment]
Is it impossible to somehow add transaction hashes to the output of `getBlock`? Otherwise getting transaction hashes for P-Chain blocks in another language than Golang requires re-implementing a ton of parsing logic.
