### ISSUE TITLE
Can we get P-Chain transactions for an address up to a given blockheight

### ISSUE THREAD

**Issue by UMANGAWASTHY** [ava-labs/avalanchego#1169]
Hello Team

 Can we get P-Chain transactions for an address up to a given blockheight.  Please let i know rpc curl query.

Thanks
Umang

**Comment by abi87** [comment]
Hello @UMANGAWASTHY,
my answer is late but hopefully still useful.
AvalancheGo node does not provide the kind of historical queries you are looking for.
As a design principle, we strive to keep P-chain lean and store just enough state to validate incoming transactions, but no more.
