### ISSUE TITLE
Transactions are not prioritized based on gasPrice

### ISSUE THREAD

**Issue by dandavid3000** [ava-labs/avalanchego#1174]
**Describe the bug**
Transactions are not prioritized based on gasPrice as they're meant to be.

**To Reproduce**
Checking some random blocks and they have them

**Expected behavior**
TXs should be prioritized by gasPrice

**Logs**
https://snowtrace.io/txs?block=22495145

tx 0 paid Max Priority Fee Per Gas: 0.00000012278 AVAX (122.78 nAVAX)
tx 4 paid Max Priority Fee Per Gas: 0.00000071 AVAX (710 nAVAX)

**Comment by StephenButtolph** [comment]
Build building logic for the C-chain is handled by https://github.com/ava-labs/coreth, not avalanchego. That being said, coreth _does_ prioritize based on gasPrice here: https://github.com/ava-labs/coreth/blob/master/miner/worker.go#L192. It is **not** a requirement for transactions to be sorted on gasPrice for the block to be considered valid.

**Comment by dandavid3000** [comment]
> Build building logic for the C-chain is handled by https://github.com/ava-labs/coreth, not avalanchego. That being said, coreth _does_ prioritize based on gasPrice here: https://github.com/ava-labs/coreth/blob/master/miner/worker.go#L192. It is **not** a requirement for transactions to be sorted on gasPrice for the block to be considered valid.

Could you please elaborate more ? I do not understand that it does prioritize based on gasPrice but the TXs were not arranged based on gasPrice. Is there any mechanism here or it's just random? 
I did not mean they should be sorted to make the block valid. Why don't they just make it FIFO because prioritization is meaningless in this case?

Thanks

**Comment by StephenButtolph** [comment]
> I do not understand that it does prioritize based on gasPrice but the TXs were not arranged based on gasPrice.

Coreth will generate txs sorted by gasPrice. However, it isn't enforced that all blocks are built the same way coreth builds blocks. It's entirely possible that there are modified versions of nodes that build blocks in a different manner.

That being said, all the nodes running unmodified versions of avalanchego and coreth will produce blocks with transactions prioritized solely by gasPrice.
