### ISSUE TITLE
Error with p-chain import after successful export from c-chain to p-chain 

### ISSUE THREAD

**Issue by dineshkumar-zh** [ava-labs/avalanchego#1180]
**Describe the bug**
I have successfully exported Avax token from C-chain and trying to Import it to P-Chain.When I am sending  IssueTx for Import on P-chain It is throwing below error:
**`error="failed to decode client response: couldn't issue tx: failed to verify transfer: expected signature from Jvtnd2BAtnh5wWa98Q3FFAzjN1GWsazZJ but got from 7qCSKw9U1uoZiamCALo3eVrsdqZZyeiCr"`** .
I am using correct address that I  have used in import for p-chain but getting above error.

**To Reproduce**

1. Get the public key string from external signer:i.e:

`047420e2d7b68c0b2442c916f2114cd827912c129139445986e0da83bd5328b9de111353f9d8963957ddb9853dd64a9c5005348e4b2f82e83baf1419a0a1fc6311`

2. Created Public key instance using code : https://github.com/ava-labs/avalanchego/blob/master/utils/crypto/secp256k1r.go#L69 and then generated chain eth address  and pchain byte address ,p-chian string address:
`0xFC9FCd00F506a661c533C456F59F985405705D3c`
`Jvtnd2BAtnh5wWa98Q3FFAzjN1GWsazZJ`
`P-fuji1cj4knhn0lxgg0mnv3hf89wgzk57wnv3tm57wgx`

3. Generated unsigned tx byte for sign 
`0x0000000000050000000000000000000000000000000000000000000000000000000000000000000000013d9bdac0ed1d761330cf680efdeb1a42159eb387d6d2950c96f7d28f61bbe2aa000000070000000253fca1c0000000000000000000000001000000034aee4488e5256bd41888f3b64f9a5ffd986b45ec7bffbe829d9bc06e7f76f10cbd377508ff2650dac4ab69de6ff99087ee6c8dd272b902b53ce9b22b00000000000000007fc93d85c6d62c5b2ac0b519c87010ea5294012d1e407030d6acd0021cac10d5000000017d98ca5dcd95b39776fcf359313673636ffbc4ce0e777bb5e26ebe215541c51b000000003d9bdac0ed1d761330cf680efdeb1a42159eb387d6d2950c96f7d28f61bbe2aa0000000500000002540be4000000000100000000b80f834d`

Message Hash:
`0x7ea5f7649e8a579961da7cb7d0e1323e5155d3aadb3ad7e28491ef2eb80f834ddbc91172`

4. Final Message send to issueTx:
`0x000000000011000000050000000000000000000000000000000000000000000000000000000000000000000000013d9bdac0ed1d761330cf680efdeb1a42159eb387d6d2950c96f7d28f61bbe2aa000000070000000253fca1c0000000000000000000000001000000034aee4488e5256bd41888f3b64f9a5ffd986b45ec7bffbe829d9bc06e7f76f10cbd377508ff2650dac4ab69de6ff99087ee6c8dd272b902b53ce9b22b00000000000000007fc93d85c6d62c5b2ac0b519c87010ea5294012d1e407030d6acd0021cac10d5000000017d98ca5dcd95b39776fcf359313673636ffbc4ce0e777bb5e26ebe215541c51b000000003d9bdac0ed1d761330cf680efdeb1a42159eb387d6d2950c96f7d28f61bbe2aa0000000500000002540be40000000001000000000000000100000009000000012741937b76cd02340365461fbd41d596a769a5e9ba8e02663aea9721023ee962137b5dbe8b9e981ef564380baf057c811245daaefbaab583a3a39d5c6b5dfe7e016acaded9`

**Expected behavior**
The IssueTx should processed successfully without error as export and import address are derived from same public key generated address `Jvtnd2BAtnh5wWa98Q3FFAzjN1GWsazZJ`

**Screenshots**

**Logs**

time="2022-11-27T10:36:58-05:00" level=info msg="Public key from external signer 047420e2d7b68c0b2442c916f2114cd827912c129139445986e0da83bd5328b9de111353f9d8963957ddb9853dd64a9c5005348e4b2f82e83baf1419a0a1fc6311"
time="2022-11-27T10:36:58-05:00" level=info msg="Length of hashed Public key  [196 171 105 222 111 249 144 135 238 108 141 210 114 185 2 181 60 233 178 43]"
time="2022-11-27T10:36:58-05:00" level=info msg="Hashed Publik Key is : c4ab69de6ff99087ee6c8dd272b902b53ce9b22b\n"
time="2022-11-27T10:36:58-05:00" level=info msg="p-Chain Address is : P-fuji1cj4knhn0lxgg0mnv3hf89wgzk57wnv3tm57wgx"
time="2022-11-27T10:36:58-05:00" level=info msg="Length of hashed Public key  [196 171 105 222 111 249 144 135 238 108 141 210 114 185 2 181 60 233 178 43]"
time="2022-11-27T10:36:58-05:00" level=info msg="Hashed Publik Key is : c4ab69de6ff99087ee6c8dd272b902b53ce9b22b\n"
time="2022-11-27T10:36:58-05:00" level=info msg="c-Chain Address. from signer is .........0xFC9FCd00F506a661c533C456F59F985405705D3c"
time="2022-11-27T10:36:58-05:00" level=info msg="Identified short Address is : 0xFC9FCd00F506a661c533C456F59F985405705D3c"
time="2022-11-27T10:36:58-05:00" level=info msg="request Url is :  https://api.avax-test.network/ext/bc/C/rpc"
time="2022-11-27T10:36:58-05:00" level=info msg="method: eth_getBalance  param [0xFC9FCd00F506a661c533C456F59F985405705D3c latest] "
time="2022-11-27T10:36:58-05:00" level=info msg="Request Body is {\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xFC9FCd00F506a661c533C456F59F985405705D3c\",\"latest\"],\"id\":8387201453092835795} "
time="2022-11-27T10:36:58-05:00" level=info msg="uri.RawQuery  "
time="2022-11-27T10:36:58-05:00" level=info msg="Response data is :  &{200 OK 200 HTTP/2.0 2 0 map[Access-Control-Allow-Credentials:[true] Cache-Control:[private, no-cache] Cf-Cache-Status:[DYNAMIC] Cf-Ray:[770bf1457ba31d04-ORD] Content-Type:[application/json] Date:[Sun, 27 Nov 2022 15:36:58 GMT] Server:[cloudflare] Set-Cookie:[api-session=1669563419.512.1202.766659|cb20409036d3cf321560bdac14f6d5ba; Max-Age=172800; Path=/; Secure; HttpOnly; SameSite=None __cflb=02DiuELxtqBwK7NsFWSUGEguYXUWinqey9g7WPtwozGag; SameSite=Lax; path=/; expires=Mon, 28-Nov-22 15:36:58 GMT; HttpOnly] Strict-Transport-Security:[max-age=0] Vary:[Origin, Accept-Encoding] X-Cache:[MISS] X-Execution-Weight:[cheap] X-Robots-Tag:[noindex]] 0x14001504090 -1 [] false true map[] 0x14000778f00 0x140005af8c0}"
time="2022-11-27T10:36:58-05:00" level=info msg="Response Body is : 0x140004386d0"
time="2022-11-27T10:36:58-05:00" level=info msg="GetBalance Response Result is : 0x85c7a54a64de9f18"
time="2022-11-27T10:36:58-05:00" level=info msg="Received HexEncoded Balance is : 85c7a54a64de9f18"
time="2022-11-27T10:36:58-05:00" level=info msg="Balance for  c-chain Address 0xFC9FCd00F506a661c533C456F59F985405705D3c  is 9639855266348310296 :"
time="2022-11-27T10:36:58-05:00" level=info msg="Sender AVAX Balance" C-Chain Balance=9639855266348310296 C-chain Address=0xFC9FCd00F506a661c533C456F59F985405705D3c
time="2022-11-27T10:36:58-05:00" level=info msg="=====Going to process Import from  to P-chain after c-chain export processed successfully=======  "
time="2022-11-27T10:36:58-05:00" level=info msg="p-chain Address to process is : P-fuji1cj4knhn0lxgg0mnv3hf89wgzk57wnv3tm57wgx"
time="2022-11-27T10:36:58-05:00" level=info msg="chainID P ,hrp fuji addres byte īi\xdeo\xf9\x90\x87\xeel\x8d\xd2r\xb9\x02\xb5<\xe9\xb2+ err <nil>"
time="2022-11-27T10:36:58-05:00" level=info msg=ChainIDyH8D7ThNJkxmtkuv2jgBa4P1Rn3Qpr4pPr7QYNfcdoS6k6HWp
time="2022-11-27T10:36:58-05:00" level=info msg="outPutOwner&{0 1 [7qCSKw9U1uoZiamCALo3eVrsdqZZyeiCr CJeV1iTar2pAkvH5xyv6C68fRDq68r2Ri Jvtnd2BAtnh5wWa98Q3FFAzjN1GWsazZJ] <nil>}"
time="2022-11-27T10:36:58-05:00" level=info msg="optionList[0]0x103264700"
time="2022-11-27T10:36:58-05:00" level=info msg="optionList[1]0x103264690"
time="2022-11-27T10:36:58-05:00" level=info msg="Builder data is  &{map[[74 238 68 136 229 37 107 212 24 136 243 182 79 154 95 253 152 107 69 236]:{} [123 255 190 130 157 155 192 110 127 118 241 12 189 55 117 8 255 38 80 218]:{} [196 171 105 222 111 249 144 135 238 108 141 210 114 185 2 181 60 233 178 43]:{}] 0x140006a14c0}"
time="2022-11-27T10:36:58-05:00" level=info msg="p-chain Address to process is : P-fuji1cj4knhn0lxgg0mnv3hf89wgzk57wnv3tm57wgx"
time="2022-11-27T10:36:58-05:00" level=info msg="chainID P ,hrp fuji addres byte īi\xdeo\xf9\x90\x87\xeel\x8d\xd2r\xb9\x02\xb5<\xe9\xb2+ err <nil>"
time="2022-11-27T10:36:58-05:00" level=info msg="Call before  GetAtomicUTXOs .......[Jvtnd2BAtnh5wWa98Q3FFAzjN1GWsazZJ]"
time="2022-11-27T10:36:58-05:00" level=info msg="getting UTXO Data [[0 0 53 2 64 141 68 54 116 138 95 170 113 45 63 176 48 140 189 76 101 207 89 244 143 4 55 169 7 148 225 204 145 229 0 0 0 0 61 155 218 192 237 29 118 19 48 207 104 14 253 235 26 .........]]"

time="2022-11-27T10:36:58-05:00" level=info msg="unsigned message byte0x0000000000050000000000000000000000000000000000000000000000000000000000000000000000013d9bdac0ed1d761330cf680efdeb1a42159eb387d6d2950c96f7d28f61bbe2aa000000070000000253fca1c0000000000000000000000001000000034aee4488e5256bd41888f3b64f9a5ffd986b45ec7bffbe829d9bc06e7f76f10cbd377508ff2650dac4ab69de6ff99087ee6c8dd272b902b53ce9b22b00000000000000007fc93d85c6d62c5b2ac0b519c87010ea5294012d1e407030d6acd0021cac10d5000000017d98ca5dcd95b39776fcf359313673636ffbc4ce0e777bb5e26ebe215541c51b000000003d9bdac0ed1d761330cf680efdeb1a42159eb387d6d2950c96f7d28f61bbe2aa0000000500000002540be4000000000100000000b80f834d"
time="2022-11-27T10:36:58-05:00" level=info msg="Hash for message byte0x7ea5f7649e8a579961da7cb7d0e1323e5155d3aadb3ad7e28491ef2eb80f834ddbc91172"
time="2022-11-27T10:37:05-05:00" level=info msg="Signature hex received from signer 0x2741937b76cd02340365461fbd41d596a769a5e9ba8e02663aea9721023ee962137b5dbe8b9e981ef564380baf057c811245daaefbaab583a3a39d5c6b5dfe7e019dfc23ab"
time="2022-11-27T10:37:05-05:00" level=info msg="Public key received from signer :  047420e2d7b68c0b2442c916f2114cd827912c129139445986e0da83bd5328b9de111353f9d8963957ddb9853dd64a9c5005348e4b2f82e83baf1419a0a1fc6311"
time="2022-11-27T10:37:05-05:00" level=info msg="Public key after Successfully parsing signer Public Key :  Jvtnd2BAtnh5wWa98Q3FFAzjN1GWsazZJ"
time="2022-11-27T10:37:05-05:00" level=info msg="Public key after recovering it from message and signature :  CJeV1iTar2pAkvH5xyv6C68fRDq68r2Ri"
time="2022-11-27T10:37:05-05:00" level=info msg="Verification passed with Recovered  Public key  :  CJeV1iTar2pAkvH5xyv6C68fRDq68r2Ri"
time="2022-11-27T10:37:05-05:00" level=info msg="generated eth Address is : 0xFC9FCd00F506a661c533C456F59F985405705D3c"
time="2022-11-27T10:37:05-05:00" level=info msg="Total length for input to process 1"
time="2022-11-27T10:37:05-05:00" level=info msg="signed byte for issueTx0x000000000011000000050000000000000000000000000000000000000000000000000000000000000000000000013d9bdac0ed1d761330cf680efdeb1a42159eb387d6d2950c96f7d28f61bbe2aa000000070000000253fca1c0000000000000000000000001000000034aee4488e5256bd41888f3b64f9a5ffd986b45ec7bffbe829d9bc06e7f76f10cbd377508ff2650dac4ab69de6ff99087ee6c8dd272b902b53ce9b22b00000000000000007fc93d85c6d62c5b2ac0b519c87010ea5294012d1e407030d6acd0021cac10d5000000017d98ca5dcd95b39776fcf359313673636ffbc4ce0e777bb5e26ebe215541c51b000000003d9bdac0ed1d761330cf680efdeb1a42159eb387d6d2950c96f7d28f61bbe2aa0000000500000002540be40000000001000000000000000100000009000000012741937b76cd02340365461fbd41d596a769a5e9ba8e02663aea9721023ee962137b5dbe8b9e981ef564380baf057c811245daaefbaab583a3a39d5c6b5dfe7e016acaded9"
time="2022-11-27T10:37:05-05:00" level=error msg="Error processing transaction" error="failed to decode client response: couldn't issue tx: failed to verify transfer: expected signature from Jvtnd2BAtnh5wWa98Q3FFAzjN1GWsazZJ but got from 7tPRFjZgwwRbJ49j7dNxFmRCwA26PX9Sp"

**Metrics**
If applicable, please include any metrics gathered from your node to assist us in diagnosing the problem.

**Operating System**
Which OS you used to reveal the bug.

**Additional context**
I also observed that  method-(https://github.com/ava-labs/avalanchego/blob/master/utils/crypto/secp256k1r.go#L87) used at Avalanche node  to check the address match  and throw the error ,I used the same method to recover the public key and generate the address before sending issueTX ,it is always generating  the same address in my local code but it is generating new address  at Avax Node every time.The log for address from recovery in my local code is  :
time="2022-11-27T10:35:55-05:00" level=info msg="Public key received from signer :  047420e2d7b68c0b2442c916f2114cd827912c129139445986e0da83bd5328b9de111353f9d8963957ddb9853dd64a9c5005348e4b2f82e83baf1419a0a1fc6311"
time="2022-11-27T10:35:55-05:00" level=info msg="Public key after Successfully parsing Signer Public Key :  Jvtnd2BAtnh5wWa98Q3FFAzjN1GWsazZJ"
time="2022-11-27T10:35:55-05:00" level=info msg="Public key after recovering it from message and signature :  CJeV1iTar2pAkvH5xyv6C68fRDq68r2Ri"
time="2022-11-27T10:35:55-05:00" level=info msg="Verification passed with Recovered  Public key  :  CJeV1iTar2pAkvH5xyv6C68fRDq68r2Ri"
time="2022-11-27T10:35:55-05:00" level=info msg="generated eth Address is : 0xFC9FCd00F506a661c533C456F59F985405705D3c"
The code I added to get this info it -
```
func (c *AvaxClient) VerifyPChainImportMessage(msg, sig []byte, PublicKey string) (bool, error) {
   keyFactory := new(crypto.FactorySECP256K1R)
   
   pubKeyByte, err := hex.DecodeString(PublicKey)
   if err != nil {
      return false, err
   }
   //log.Info("Public key after Hex Decoding is :  ", pubKeyByte)
   log.Info("Public key received from Signer :  ", PublicKey)
   key, err := keyFactory.ToPublicKey(pubKeyByte)
   if err != nil {
      log.Printf("Error in getting public keys.... from string %s ", PublicKey)
      return false, err
   }
   pubKey := key.(*crypto.PublicKeySECP256K1R)
   log.Info("Public key after Successfully parsing signer Public Key :  ", pubKey.Address())
   verify := pubKey.Verify(msg, sig)
   if verify {
      log.Info("Verification passed with  Public key  :  ", pubKey.Address())
   }
   rKey, err := keyFactory.RecoverPublicKey(msg, sig)
   rPubKey := rKey.(*crypto.PublicKeySECP256K1R)
   if err != nil {
      log.Info("Error in getting public keys.... from Recovery %s ")
   }
   log.Info("Public key after recovering it from message and signature :  ", rPubKey.Address())
   rVerify := rPubKey.Verify(msg, sig)
   if rVerify {
      log.Info("Verification passed with Recovered  Public key  :  ", rPubKey.Address())
   }
   ethAddr := ethcrypto.PubkeyToAddress(*(rPubKey.ToECDSA()))
   log.Printf("generated eth Address is : %s", ethAddr.String())
   return pubKey.Address() == rPubKey.Address(), nil
```
I also found that eth address always generated the same in all case and it is only issue with p-chain address with same public key.

Avalanche Bug Bounty program can be found [here](https://hackenproof.com/avalanche/avalanche-protocol).

**Comment by dineshkumar-zh** [comment]
Example  to Reproduce this issue:

```
curl --location --request POST 'https://api.avax-test.network/ext/bc/P' \
--header 'Content-Type: application/json' \
--header 'Cookie: __cflb=02DiuELxtqBwK7NsFWSUGEguYXUWinqez6C4HpqdArPMn; api-session=1669689445.781.1233.309159|cb20409036d3cf321560bdac14f6d5ba' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "platform.issueTx",
    "params": {
        "tx":"0x000000000011000000050000000000000000000000000000000000000000000000000000000000000000000000013d9bdac0ed1d761330cf680efdeb1a42159eb387d6d2950c96f7d28f61bbe2aa000000070000000253fca1c0000000000000000000000001000000034aee4488e5256bd41888f3b64f9a5ffd986b45ec7bffbe829d9bc06e7f76f10cbd377508ff2650dac4ab69de6ff99087ee6c8dd272b902b53ce9b22b00000000000000007fc93d85c6d62c5b2ac0b519c87010ea5294012d1e407030d6acd0021cac10d5000000017d98ca5dcd95b39776fcf359313673636ffbc4ce0e777bb5e26ebe215541c51b000000003d9bdac0ed1d761330cf680efdeb1a42159eb387d6d2950c96f7d28f61bbe2aa0000000500000002540be40000000001000000000000000100000009000000012741937b76cd02340365461fbd41d596a769a5e9ba8e02663aea9721023ee962137b5dbe8b9e981ef564380baf057c811245daaefbaab583a3a39d5c6b5dfe7e016acaded9",
        "encoding": "hex"
    },
    "id": 1
}'
```

**Comment by StephenButtolph** [comment]
The error here seems to be as reported: `expected signature from Jvtnd2BAtnh5wWa98Q3FFAzjN1GWsazZJ but got from 7qCSKw9U1uoZiamCALo3eVrsdqZZyeiCr`.

The signature provided signing for the input doesn't match the owner of the output that is being consumed.
