### ISSUE TITLE
Why can't I request

### ISSUE THREAD

**Issue by zhaoxiangjunupi** [ava-labs/avalanchego#1182]
This is my request commnd:
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' http://127.0.0.1:9650/ext/bc/C/rpc

Why is this result returned?

API call rejected because chain is not done bootstrapping

**Comment by danlaine** [comment]
Your node isn't done bootstrapping. Once it's done bootstrapping your API call will go through.

**Comment by zhaoxiangjunupi** [comment]
> Your node isn't done bootstrapping. Once it's done bootstrapping your API call will go through.

When will it be finished?
