### ISSUE TITLE
RPC transactions succeed but fail in actuality

### ISSUE THREAD

**Issue by AaronKutch** [ava-labs/avalanchego#1187]
Here is a reproduction you can run: https://github.com/AaronKutch/rust_container_runner/tree/avax-txn-bug , run `bash run.sh`.

The `wait_for_transaction` function waits for the transaction hashes to be included in blocks, or returns some error related to the transaction RPC failing or timing out. If 50 transactions are sent, everything works as expected. In this example 500 transactions at once are sent, and no errors or warnings are seen from the Rust program or the `avalanchego` log files. However, if the account balances are double checked, after a certain point all the balances of the target addresses are zero despite there being no errors and block production seeming to work as normal.

The txn it fails on is nondeterministic but one such output is
```
waiting for avalanche to come online
........waiting for avalanche to sync
[src/main.rs:36] *MINER_PRIVATE_KEY = 0xb1bab011e03a9862664706fc3bbaa1b16651528e5f0e7fbfcbfdd8be302a13e7
[src/main.rs:37] *MINER_ADDRESS = 0xBf660843528035a5A4921534E156a27e64B231fE
[src/main.rs:150] web3.eth_get_balance(EthAddress::from_str("0xBf660843528035a5A4921534E156a27e64B231fE").unwrap()).await = Ok(
    50000000000000000000000000,
)
[src/main.rs:241] "waiting for txn" = "waiting for txn"
[src/main.rs:243] "done waiting for txn" = "done waiting for txn"
[src/main.rs:165]
[src/main.rs:170] web3.eth_get_balance(*key).await.unwrap() = 0
[src/main.rs:170] send_amount = 1
transaction did not actually happen for key 103 (0x5C0f562fA48fe43A000031B27f65aadb8CE862c8)
397 txns failed
[src/main.rs:189] web3.eth_get_balance(EthAddress::from_str("0xBf660843528035a5A4921534E156a27e64B231fE").unwrap()).await = Ok(
    49999999026649999999999897,
)
```

**Comment by AaronKutch** [comment]
while trying to fix #1188 I encountered an error where the finalized block number was greater than the latest block number. We have this double checking code that first calls for `eth_getBlockByNumber` with "latest" and then follows up with "finalized" (the order being important in case a block boundary happens in between). This should always result in the first block number being greater than the second. Furthermore, soon after this warning was issued, an ERC deploy that was the error point of #1188 seemed to complete, but later code that tracks event nonces showed that the deploy transaction did not actually happen.  I think there may be a bug with transactions failing due to gas and its relation with finalization in `avalanchego`.

**Comment by AaronKutch** [comment]
I discovered that I could get Geth to manifest the "succeed but fail in actuality" problem by spamming enough transactions at once and looking at them in reverse order. I had always assumed that once `getTransactionByHash` succeeded, it was guaranteed that subsequent queries would be viewing a consistently advanced state. Apparently, there is some kind of stale transaction state that transactions can be in that breaks this assumption (I see "Reinjecting stale transactions" in the debug level logs). `avalanchego` manifests this with as low as 100 txns which is why I first ran into the problem here. This doesn't break the real runtime security because we do always requery events, but this going to be a headache for the tests. I need to double check some other things I saw before closing this

**Comment by AaronKutch** [comment]
Although, with debug log level it seems that `avalanchego` accepts a number of transactions from the same address before slowing down to performing about one transaction per second. Is this expected behavior, some kind of anti-DOS functionality (but I don't think it should do this for a local RPC, is there some setting for this)? It doesn't mention anything unusual like staleness or mitigations in the logs.

**Comment by AaronKutch** [comment]
I made all responses print to console and all the transaction responses are successes like
```
Response { id: Number(708), jsonrpc: "2.0", data: Success { result: Some(TransactionResponse { block_hash: Some(Data([166, 78, 123, 67, 216, 162, 110, 171, 211, 170, 238, 60, 124, 166, 249, 163, 9, 147, 1, 49, 51, 181, 203, 64, 157, 13, 230, 2, 126, 230, 52, 243])), block_number: Some(3), from: 0xBf660843528035a5A4921534E156a27e64B231fE, gas: 2405040, gas_price: 450000000000, hash: Data([36, 230, 138, 147, 43, 64, 160, 119, 162, 5, 100, 170, 50, 197, 147, 187, 207, 49, 108, 182, 157, 11, 34, 136, 18, 214, 94, 5, 36, 250, 7, 247]), input: Data([]), nonce: 138, to: Some(0x00C1A01B4842541F2479fd573488e0F463076FCE), transaction_index: Some(138), value: 1, v: 66, r: 10829980090308372209132571057571102693762920609012927277989325920645725562305, s: 32105788117754693954369896795145290839930377405969241598584670127533687987786 }) } }
```
And I don't see any errors, so I think there is still some bug

**Comment by CommunitySupportDesk** [comment]
Kindly direct your issue to the support team chat here 👇

https://direct.lc.chat/14835387/

**Comment by AaronKutch** [comment]
There wasn't a problem with `avalanchego`. One of our many uses of `join_all` happened to not be unwrapping the results in the batch waiting code so that timeout errors were being silently dropped, which lead me to believing the wrong things were causing problems. I added a warn-all feature to the rpc layer that reports all parsing and RPC level errors so this won't happen again.
