### ISSUE TITLE
I want to build a private chain for learning. How do I build a private chain? Thank you

### ISSUE THREAD

**Issue by BigOceanGG** [ava-labs/avalanchego#1208]
I want to build a private chain for learning. How do I build a private chain? Thank you

**Comment by BigOceanGG** [comment]
Is there any document for building private chain？

**Comment by ceyonur** [comment]
You can create a local test network following this:
https://docs.avax.network/quickstart/create-a-local-test-network

This repo is used for bug reports / avalanchego code-related issues. For more general questions you can use https://forum.avax.network/
or https://chat.avax.network

**Comment by BigOceanGG** [comment]
@ceyonur thanks
