### ISSUE TITLE
Issue tacker here feels abandoned

### ISSUE THREAD

**Issue by abebeos** [ava-labs/avalanchego#1209]
* Commits do not reference this repos issue-tracker, which means it is not used by the dev team

This is fine, but it makes it quite difficult to follow development:

- #1212

**Comment by ceyonur** [comment]
Could you be a little more specific? Do you think issues here are overlooked or not getting resolved/closed?  

Thank you for your feedback.

**Comment by abebeos** [comment]
Ty for your quick reply.

- Commits do not reference this repos issue-tracker, which means it is not used by the dev team

This is fine, but it makes it quite difficult to follow development.

**Comment by abebeos** [comment]
closing in favor of https://github.com/ava-labs/avalanchego/issues/1212
