### ISSUE TITLE
keystore.createUser -404 page not found 

### ISSUE THREAD

**Issue by BigOceanGG** [ava-labs/avalanchego#1210]
curl --location --request POST '127.0.0.1:9650/ext/keystore' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"keystore.createUser",
    "params" :{
        "username": "username",
        "password": "password"
    }
}'

404 page not found

**Comment by BigOceanGG** [comment]
Why does 404 appear? Is there no such route

**Comment by ceyonur** [comment]
Keystore is disabled by default since 1.9.6, you can enable it by `--api-keystore-enabled` flag.

**Comment by BigOceanGG** [comment]
@ceyonur thanks
