### ISSUE TITLE
It is not possible to follow avalanchego's development

### ISSUE THREAD

**Issue by abebeos** [ava-labs/avalanchego#1212]
(this is "constructive criticism". I want to construct a solution, so development can be followed easier, e.g. apply standard-procedure to this repo)

> [...] (we currently maintain the staging branch in an internal mirror, so this will be committed there first).

_Originally posted by @StephenButtolph in https://github.com/ava-labs/avalanchego/issues/1205#issuecomment-1409337101_

* a) internal branches
* b) commits references unavailable PRs (assuming an internal issue tracker)

Open Sources makes no sense without an Open Project.

How can one follow the development-process (getting access to the non-public repositories/branches/issue-trackers) ?

**Comment by StephenButtolph** [comment]
Yeah, this is definitely an annoying situation. We are planning on transitioning to use the public repo (this repo) for issue tracking. In doing so, we are planning on maintaining the `dev` branch as the next staged release and merging PRs directly into this repo.

This is planned to be done after the release of `v1.10.0` (the next planned network upgrade). So, the hope is that this transition will be happening sooner rather than later.

**Comment by abebeos** [comment]
> This is planned to be done after the release of `v1.10.0`

When would that be?

And may I ask, the current staging/issue tracker is at github?

**Comment by StephenButtolph** [comment]
> When would that be?

Kind of hard to say specifically... There are a number of changes that are currently WIP.. So it certainly isn't going to be happening imminently, but pushing along the development for `v1.10` is my primary focus. Probably in the next couple months.. But at the end of the day it'll be released once we have a high confidence in the security and stability of the upgrade.

> the current staging/issue tracker is at github?

Yes.

**Comment by abebeos** [comment]
> > the current staging/issue tracker is at github?
> 
> Yes.

What hinders you to just open the repository (thus the hard requirement of openness is met)?

**Comment by abebeos** [comment]
Don't want to come off pushy.

To clarify, this is the most important flaw, essentially it obfuscates:

> ) commits reference unavailable PRs (assuming an internal issue tracker)

**Comment by hexfusion** [comment]
> What hinders you to just open the repository (thus the hard requirement of openness is met)?

Time

> Don't want to come off pushy.

We 100% feel your pain, understand the problem and appreciate your patience.

Please allow us time to move our development process to this repo. As @StephenButtolph note this effort is slated for `1.10.0`. Thank you for your contributions and pushing for this!

**Comment by abebeos** [comment]
You're saying with friendly words: "go away".

And you justify what is simply unjustifiable.

But I rest my case.

**Comment by abebeos** [comment]
The presentation (https://www.avax.network/) creates expectations, and when those are not met by the project, the frustration kicks in.

All good, folks, fix it whenever you find the time!

Cu around!

**Comment by hexfusion** [comment]
Very sorry you feel this way. In sincere words I was sayings.
- we agree with you
- thank you for trying to push this forward
- thank you for your contributions
- please allow us some time to resolve the problem

**Comment by abebeos** [comment]
Logic is a brutal thing, my friendly speaking friend.

And thus, sincere words or not, friendly words or not, the essence is *go away*.

In the end it's a matter of mentality, a matter of professional pride.

(fiction: Avalanche CTO: "Seriously? What are you doing there? You alienate contributors, even simple visitors. Halt work. Fix this, and only then you can continue with your daily business")

**Comment by abebeos** [comment]
https://www.avalabs.org/team - no CTO listed.

I guess O'Grady (VP of Engineering) would be the responsible one.

> Experience
We're a world-class team of experts in computer science, economics, finance, and law with offices in New York City and Miami. We're passionate individuals creating a frictionless world by redefining the way people build and use finance applications.

> The Ava Labs team has collective experience from leading Fortune 500 finance and tech companies to high-growth blockchain companies.

One should punish the C-level, and let them triage/solve Issues/PRs here, so they see what happens when (undisputable) hard requirements re project-organization are ignored:

* https://github.com/ava-labs/avalanchego/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc
* https://github.com/ava-labs/avalanchego/pulls?q=is%3Apr+is%3Aopen+sort%3Acreated-asc

Ok, I vented enough, we are now "even".

(to be fair: other $billions market-cap smart-contract-platforms are doing strange things, too, like e.g.: https://github.com/algorandfoundation/grow-algorand/issues/217)
