### ISSUE TITLE
Validate / Introduce Requirement re "newline" at line end

### ISSUE THREAD

**Issue by abebeos** [ava-labs/avalanchego#1213]
Super minor whitespace nit:
```suggestion
```

_Originally posted by @StephenButtolph in https://github.com/ava-labs/avalanchego/pull/1211#discussion_r1098090227_

I'm used to hitting "RETURN" at the end-of-line, even if it is the last line of the file.

nit

To my knowledge, several tools depend on the existents of a "newline", otherwise they do not recognize the line as such.

There's even a standard:

https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206

## Suggestion

Introduce a requirement to always add a newline at the end of a line, even if it is the last line of a document.

**Comment by StephenButtolph** [comment]
There _is_ a trailing newline. That nit was because it was introducing a _second_ trailing newline. I'm down for adding a linter to enforce exactly one trailing newline.

**Comment by abebeos** [comment]
Oh... A double-RETURN, I see...

> adding a linter to enforce exactly one trailing newline though.

+1
