### ISSUE TITLE
my fuji node crash after start

### ISSUE THREAD

**Issue by panchengj** [ava-labs/avalanchego#1220]
my fuji node crashed after start  on centos7  system, I resynchronized from a new data directory，how could i solve the problem?the log like below:

[02-13|10:26:26.931] FATAL <C Chain> handler/handler.go:326 shutting down chain {"reason": "received an unexpected error", "error": "failed to get job ir2hxy6
gWkDVJHrWWTUzZPvCXoHC6YPF85xbN5NhfKFTxpHoa from blocking jobs due to not found while processing sync message: &{\ufffd\u0013A\ufffd\ufffd\ufffdH\u000b\ufffdD\
ufffd&\ufffdv\ufffd\u0007O\\]\ufffd %!s(message.Op=19) %!s(*p2p.Ancestors=&{{{} [] [] <nil>} 0 [] ble, please include any metrics gathered from your node to assist us in diagnosing the problem.

**Comment by hexfusion** [comment]
Hi @panchengj thanks for the report, just a few questions about your node. 
- version of avalanchego?
- are you using release binaries or self compiled?
- if self compiled which version of golang?

Then in general CentOS 7 I believe is EOL next year.  Please see Installation section of README[1] for tested and recommended distros.

[1] https://github.com/ava-labs/avalanchego#installation

**Comment by panchengj** [comment]
v1.9.8  self compiled,go v1.19.4 , it seems ubuntu 22.04 is recommended

**Comment by hexfusion** [comment]
Thanks for the response, could you also attach the full logs for the node and or provide any metrics as outlined by the log message?

possibly related to https://github.com/ava-labs/avalanchego/issues/1071

**Comment by StephenButtolph** [comment]
Closing as there doesn't seem to be much to go off of here.
