### ISSUE TITLE
how to query cchainid/ppm-id and aim-id

### ISSUE THREAD

**Issue by BigOceanGG** [ava-labs/avalanchego#1228]
I build a private chain, how to query cchainid pvm-id and avm-id

**Comment by StephenButtolph** [comment]
If you're looking for `VMID`s, then https://docs.avax.network/apis/avalanchego/apis/info#infogetvms will be your friend.

If you are looking for `ChainID`s, then you can use either: 
- https://docs.avax.network/apis/avalanchego/apis/info#infogetblockchainid
- https://docs.avax.network/apis/avalanchego/apis/p-chain#platformgetblockchains

FWIW, `VMID`s and the P-chain ID are constants across all networks.

**Comment by BigOceanGG** [comment]
@StephenButtolph thanks

**Comment by abi87** [comment]
@BigOceanGG For this kind of questions, I'd invite you to join our Discord server. You could leverage community knowledge and get answers quicker in most cases
