### ISSUE TITLE
How to encode to cb58 format from block number?

### ISSUE THREAD

**Issue by sylviahuang123** [ava-labs/avalanchego#1247]
`curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.getBlock",
    "params": {
        "blockID": "d7WYmb8VeZNHsny3EJCwMm6QA37s1EHwMxw1Y71V3FqPZ5EFG",
        "encoding": "hex"
    },
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/P`
According to the example call, is the blockID represent block height 1000001? I know it is the cb58 format, but I don't know how to encode to the cb58 format from a number block height. thanks for help.

**Comment by StephenButtolph** [comment]
The `blockID` is the hash of the block. Typically the [index API](https://docs.avax.network/apis/avalanchego/apis/index-api) is used for height based queries. The actual `platformvm` unfortunately doesn't index blocks by height.

**Comment by sylviahuang123** [comment]
> The `blockID` is the hash of the block. Typically the [index API](https://docs.avax.network/apis/avalanchego/apis/index-api) is used for height based queries. The actual `platformvm` unfortunately doesn't index blocks by height.

thanks for reply, but how can I know the block hash? Actually I want to query base height, any workaround?
