### ISSUE TITLE
Running an Archival Node

### ISSUE THREAD

**Issue by zhy827827** [ava-labs/avalanchego#1249]
How large a disk is required to running an archival Node ? Does avax provide snapshots?

**Comment by jsvisa** [comment]
In our previous run (<=2023.01.01), we needed 1.7TB+ of disk space.

**Comment by zhy827827** [comment]
thankccc!

**Comment by zhy827827** [comment]
Does avax provide snapshots?

**Comment by jsvisa** [comment]
Sorry, we didn't find any public archive snaphosts
