### ISSUE TITLE
Conflict version

### ISSUE THREAD

**Issue by ThanhVuong0904** [ava-labs/avalanchego#1252]
I am currently setting up my local network with avalanchego 1.9.14, and I am having issues with transfers between C to X and P to X. I have tried using the API for transfers.
`
curl --location 'http://localhost:4652/ext/bc/X' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"avm.import",
    "params" :{
        "username":"myuser",
        "password":"mypass",
        "sourceChain": "C",
        "to":"X-custom1un6yr0ppj4wxsdvxldzytcldwjr22g23ez2tzz"
    }
}'
But return err
`{
    "jsonrpc": "2.0",
    "error": {
        "code": -32000,
        "message": "problem issuing transaction: incompatible feature extension",
        "data": null
    },
    "id": 1
}`

Could please let me know the compatible versions between Avalanchego, the Web wallet, and AvalancheJS? Thank you.

**Comment by StephenButtolph** [comment]
Can you give some details around how the was asset created and how was it exported to the X-chain?

**Comment by StephenButtolph** [comment]
I'm going to close this as there isn't much to go on here. But if there is any more specific information on replicating the issue feel free to re-open with the context.
