### ISSUE TITLE
How to query block detail by block number in P-Chain?

### ISSUE THREAD

**Issue by sylviahuang123** [ava-labs/avalanchego#1253]
Excuse me, I'm new to avalanche, would like to know something, thanks in advance.
Totally speaking, is there any solution to query block detail by block number at P-Chain, just like the method `eth_getBlockByNumber` at EVM?
If [index API](https://docs.avax.network/apis/avalanchego/apis/index-api) is the workaround, how can I decode the `bytes` to content human-readable, which from the response of `index.getContainerByIndex`
BTW, as below, enable indexer may result index incomplete? so I can't get complete data?
`If --index-enabled is changed to false from true, AvalancheGo won't start as doing so would cause a previously complete index to become incomplete, unless the user explicitly says to do so with --index-allow-incomplete. This protects you from accidentally running with indexing disabled, after previously running with it enabled, which would result in an incomplete index.`

**Comment by StephenButtolph** [comment]
The indexer is populated as the node syncs. So the indexer must be enabled when performing the full sync to avoid any incomplete indices.

**Comment by StephenButtolph** [comment]
See linked PR for example usage of the indexer for P-chain blocks.
