### ISSUE TITLE
Add an API call to check isElasticSubnet

### ISSUE THREAD

**Issue by dasconnor** [ava-labs/avalanchego#1255]
It would be nice to have a p-chain API call to check whether or not a Subnet is elastic.

**Comment by najeal** [comment]
You want to return a `Tx` OR a struct containing the `ControlKeys` and `Threshold`. Having the two Fields empty if the subnet is elastic?

**Comment by najeal** [comment]
#2704 is merged and resolved this issue. It can be closed I suppose
