### ISSUE TITLE
About block out time and transaction fee

### ISSUE THREAD

**Issue by BigOceanGG** [ava-labs/avalanchego#1302]
1. Is the transaction fee for this chain destroyed or given to the miners？
2. Whether this chain can only be blocked with transactions and whether it can be set to block at a fixed time is irrelevant to whether there are transactions or not

**Comment by StephenButtolph** [comment]
Generally, these are VM specific questions. AvalancheGo does not specify these for custom blockchains.

If the questions are specifically for the P-chain, X-chain, and C-chain:

1. Fees are burned, they are not distributed to the block producer.
2. Blocks/vertices are not allowed to be produced if they are empty.

However, a custom blockchain could easily reward block producers or allow blocks at fixed time intervals (regardless of pending txs)
