### ISSUE TITLE
About the fee is destroyed

### ISSUE THREAD

**Issue by BigOceanGG** [ava-labs/avalanchego#1309]
The fee is destroyed, and the total amount of coins is fixed. Will one day the transactions reach a certain limit and all the coins will be consumed? What should I do at that time？Is it impossible to initiate a transaction?

**Comment by abi87** [comment]
Hello,
fees are destroyed but new utxos are created whenever a validator is rewarded. Hence a dynamic equilibrium in maintained.
You can find [in our docs](https://docs.avax.network/subnets/reference-elastic-subnets-parameters#reward-formula) more details about the rewarded amount.
