### ISSUE TITLE
Benchmarking for RPCChainVM Latency

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/avalanchego#1311]
Provide a generic benchmarking tool that will take any gRPC service and benchmark the latency that comes from serving it over gRPC.

This means each test will:
- provide mocked data responses to serve over gRPC
- benchmark will run with the mocked responses
- generate a benchmark of the latency serving it over gRPC
- Run a profiler for memory and CPU of serving the data over gRPC

**Comment by StephenButtolph** [comment]
closed by #1326
