### ISSUE TITLE
Keystore user is duplicating on same node

### ISSUE THREAD

**Issue by erknfe** [ava-labs/avalanchego#136]
**Describe the bug**  
When export a keystore user and import it to the same node, the keystore user is duplicated.  
  
**To Reproduce**  
When at the same node, export a keystore user and import this.  
  
**Expected behavior**  
If a keystore user is successfully imported after exporting, it must be deleted from the node in which it was located. This should be at least if this is done in the same node.  
  
**Screenshots**  
![export](https://user-images.githubusercontent.com/7534459/81129576-71a34280-8f4d-11ea-835c-fbd82dd0019f.png)  
![import](https://user-images.githubusercontent.com/7534459/81129595-7f58c800-8f4d-11ea-8ae6-69996922a16c.png)  
![list](https://user-images.githubusercontent.com/7534459/81129597-82ec4f00-8f4d-11ea-9054-904007dfd2bd.png)  
  
**Operating System**  
Ubuntu 18.04  
  
**Additional context**  
Also at the API Documentation, in the keystore.importUser header says that:  
*"Import a user. password must match the user’s password. username doesn’t have to match the username user had when it was exported."*  
I imported keystore user with different password and I did not get an error. The process complated succesfully.  
  
  
By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by StephenButtolph** [comment]
I'm not sure that this is a bug. If a user is exported, and then imported under a new account name. Why should the previous account be removed? For example, what if a user:

1. creates a new account
2. exports the account
3. creates a new address under the account
4. imports the account under a new username

If importing the account were to delete the previous account, then the new address would be dropped. Which could potentially cause fund loss.

I think the current behavior makes more sense, as it avoids any possible fund loss. #141 was just merged, so the account can now be deleted manually.

However, in the additional context, you mention that the passwords don't need to match. This is a bug. We'll work on fixing this.

**Comment by erknfe** [comment]
@StephenButtolph I thought there might be a conflict of data if the account runs in more than one place at a time. I'm still not fully convinced, but you're probably right because you know better.  
  
I'm glad I caught the problem of not matching the passwords. Because I am in "AVA-X Bug Bounty" program and I would be glad if you do what I need.

**Comment by danlaine** [comment]
Closed for age
