### ISSUE TITLE
How to access initial allocated funds in genesis file

### ISSUE THREAD

**Issue by DaveLomber** [ava-labs/avalanchego#1365]
Hi everyone, 

We are interested in running a private blockchain on top of `avalanchego ` platform code. With an empty state on the network, with just initial allocations.

Following the genesis config file, 
https://docs.avax.network/nodes/maintain/avalanchego-config-flags#genesis , I understand we can provide an initial network state with allocations via `allocations ` config field.

Let's sate we have the following allocations:

```
	"allocations": [
		{
			"ethAddr": "0xb3d82b1367d362de99ab59a658165aff520cbd4d",
			"avaxAddr": "X-fuji10d2fqjfl3ghl73z2ez65ufanxwwhccxugq8z2t",
			"initialAmount": 32000000000000000,
			"unlockSchedule": []
		}
	],
```

The question is it's not clear how to access these funds to send them across initial participants or e.g. to faucet wallet.. 
My initial understanding was that both `avaxAddr ` and `ethAddr ` are the addresses of a wallet we can access in a standard way. But for this we need a private key. So it's not clear. 

Could someone guide us how to access the funds.

**Comment by DaveLomber** [comment]
@StephenButtolph much appreciated for the guide

Though there is still one open question.

As I understand, if `unlockSchedule.locktime` provided, then it means these tokens is staked until the `locktime` and then will be transferred to P chain.

But what if `locktime`  is not provided? Does it mean the tokens will be transferred to P chain immediately or is there any default `locktime`  used?

**Comment by StephenButtolph** [comment]
Absolutely! Here is where to make a PR: https://github.com/ava-labs/avalanche-docs/blob/master/docs/nodes/maintain/avalanchego-config-flags.md
