### ISSUE TITLE
fees are destroyed but new utxos are created whenever a validator is rewarded

### ISSUE THREAD

**Issue by BigOceanGG** [ava-labs/avalanchego#1366]
I built a local node and configured the initialStackers' rewardAddress on the Genesis block node. Why didn't I receive the reward. Isn't it that if I participate in the block, I can earn ![image](https://user-images.githubusercontent.com/42688345/232357711-e6f67b13-a073-4a78-a744-47c4c52cf63d.png)

**Comment by ceyonur** [comment]
Block participation does not yield any rewards (all block/tx fee rewards are burned). There is a `initialStakeDuration` and `startTime` and `initialStakeDurationOffset` parameters in the genesis file. Rewards will be issued at `endTime = startTime + initialStakeDuration + initialStakeDurationOffset`.
