### ISSUE TITLE
Runtime errors in x/merkledb/path.go

### ISSUE THREAD

**Issue by dnkolegov** [ava-labs/avalanchego#1368]
**Describe the bug**
Insufficient input validation in `x/merkledb/path.go`.

**To Reproduce**
The following snippets with  `SerializedPath` trigger panics:
```
a = SerializedPath{Value: []byte{}, NibbleLength: 0}
b = SerializedPath{Value: []byte{}, NibbleLength: 1}
a.HasPrefix(b)

```

```
a := SerializedPath{Value: []byte{}, NibbleLength: 0}
a.NibbleVal(0)
```

```
a := SerializedPath{Value: []byte{}, NibbleLength: 0}
a.AppendNibbleVal(-2)
```

**Expected behavior**
No panics, no index out-of-range errors.

**Additional context**
- https://github.com/ava-labs/avalanchego/blob/d0a55ba57a5d8ebaa0717a812994f4a3df49c9d8/x/merkledb/path.go#L49
- https://github.com/ava-labs/avalanchego/blob/d0a55ba57a5d8ebaa0717a812994f4a3df49c9d8/x/merkledb/path.go#L61
- https://github.com/ava-labs/avalanchego/blob/d0a55ba57a5d8ebaa0717a812994f4a3df49c9d8/x/merkledb/path.go#L76

**Comment by patrick-ogrady** [comment]
Nice find!
