### ISSUE TITLE
Get all Transactions and UTXo's Transactions related a pchain address using node rpc query.

### ISSUE THREAD

**Issue by UMANGAWASTHY** [ava-labs/avalanchego#1383]
Hi Team
My requirement is to get all Transactions and UTXo's Transactions related a pchain address using node rpc query.

Using glacier api getting all txns, but my requirement is to get from node.
https://glacier-api.avax.network/v1/networks/mainnet/blockchains/11111111111111111111111111111111LpoYY/transactions?pageSize=20&addresses=P-avax1kgz3ejgjjdftplr9epamh6asz777u92amt67x2

Thanks
Umang Awasthy

**Comment by StephenButtolph** [comment]
Avalanchego does not support indexing all historical transactions by address. The [index API](https://docs.avax.network/apis/avalanchego/apis/index-api) can be used to scan over all blocks to look for this information if needed.
