### ISSUE TITLE
couldn't get next staker change time

### ISSUE THREAD

**Issue by BigOceanGG** [ava-labs/avalanchego#1386]
error message：
[image](https://user-images.githubusercontent.com/42688345/233309892-687a652b-8c06-49c4-a2c0-ad633e0401e0.png)

genesis：
![image](https://user-images.githubusercontent.com/42688345/233310104-04517943-4e19-41d5-99fe-a942669ee496.png)

There were no issues with trading before startTime+initialStackDuration, but the above error occurred after startTime+initialStackDuration

**Comment by BigOceanGG** [comment]
@ceyonur

**Comment by StephenButtolph** [comment]
The primary network should never run out of validators. If there is no one left to validate the primary network the network is unrecoverable.
