### ISSUE TITLE
X-Chain is stuck on 4141250

### ISSUE THREAD

**Issue by past2017** [ava-labs/avalanchego#1420]
version :1.10.0

> [04-26|00:31:23.614] INFO <X Chain> queue/jobs.go:224 executed operations {"numExecuted": 0}
> [04-26|00:31:23.614] INFO <X Chain> bootstrap/bootstrapper.go:595 executing vertices
> [04-26|00:31:23.614] INFO <X Chain> queue/jobs.go:224 executed operations {"numExecuted": 0}
> [04-26|00:31:23.615] INFO <X Chain> bootstrap/bootstrapper.go:123 starting bootstrapper
> [04-26|00:31:35.754] INFO <X Chain> common/bootstrapper.go:244 bootstrapping started syncing {"numVerticesInFrontier": 1}
> [04-26|00:31:35.755] INFO <X Chain> bootstrap/bootstrapper.go:553 executing blocks {"numPendingJobs": 0}
> [04-26|00:31:35.755] INFO <X Chain> queue/jobs.go:224 executed operations {"numExecuted": 0}
> [04-26|00:31:35.755] INFO <X Chain> bootstrap/bootstrapper.go:598 waiting for the remaining chains in this subnet to finish syncing
> [04-26|00:32:30.774] INFO <X Chain> snowman/transitive.go:409 consensus starting {"lastAcceptedBlock": "sqnMvMmwD11jReKJhCFXyWu8gFZUsz8uQ2ZCERFE8N64Z12YQ"}

**Comment by wangzhen130** [comment]
how to solve this？
