### ISSUE TITLE
Missing block hash and transaction hash in api response body

### ISSUE THREAD

**Issue by ichhoa129** [ava-labs/avalanchego#1431]
I am trying to extract block information using the "avm.getBlockByHeight" and "avm.getBlock" and other APIs but I cannot find the block hash and transaction hash in the response. Moreover, I noticed that the "avm.getTx" API requires a transaction ID (txid) as a parameter. Where you can obtain the txid that is needed to use the "avm.getTx" API ( except copying the txid from explorer)

![image](https://user-images.githubusercontent.com/55626329/234757711-291bd95d-e358-4c59-ae78-2adff0c32d91.png)

**Comment by StephenButtolph** [comment]
This has already been implemented in #1408 and will be included in `v1.10.1` as an enhancement.
