### ISSUE TITLE
Long response times on the metrics endpoint

### ISSUE THREAD

**Issue by cryptoklings** [ava-labs/avalanchego#1462]
**Describe the bug**
Slow response times for the metrics endpoint (10+ seconds) on an active validator.

**To Reproduce**
```
time curl -X POST 127.0.0.1:9650/ext/metrics
```

**Expected behavior**
I would expect it to respond within a second or two.

**Screenshots**
N/A

**Logs**
N/A

**Metrics**
Some quick samples for different versions of avalanchego (scripted setup, so all else equal):

*Mainnet:*

1.10.1: 0m11.367s

*Fuji:*

1.10.1: 0m9.063s
1.10.0: 0m14.505s
1.9.16: 0m2.319s

**Operating System**
GCP: `ubuntu-2204-lts`

**Additional context**
N/A

**To best protect the Avalanche community security bugs should be reported in accordance to our [Security Policy](../security/policy)**

**Comment by StephenButtolph** [comment]
Very odd.

When I run this on a mainnet validator (v1.10.1) I see:
```
real    0m0.365s
user    0m0.009s
sys     0m0.008s
```

The only potentially expensive calls made during metrics collection are calls for plugin metrics. Are these nodes running any subnets?
