### ISSUE TITLE
API cannot get height through TxId

### ISSUE THREAD

**Issue by wangzhen130** [ava-labs/avalanchego#1488]
https://avascan.info/blockchain/x/tx/2153bFsg3d5zDTzqWhBwq6nrTc5AkWCVt8woJQoJyMktHern6H
How to use TxId to get height via Node API,I checked all APIs but couldn't find a solution.

**Comment by StephenButtolph** [comment]
There is no API exposed by avalanchego that maps `txIDs` to block heights for either the X-chain or the P-chain.
