### ISSUE TITLE
The method debug_traceTransaction does not exist/is not available in v1.10.1

### ISSUE THREAD

**Issue by UMANGAWASTHY** [ava-labs/avalanchego#1489]
Hello Team

I have avalanchego (v1.10.1) index and full node both. I want to access debug_traceTransaction rpc quesy but it's return us "error": {"code": -32601, "message": "the method debug_traceTransaction does not exist/is not available"}.
Here Is Docker-compose file 

version: '2'
services:
    node-avalanchego:
        image: avaplatform/avalanchego:v1.10.1
        container_name: avalanchego-1332
        restart: always
        ports:
            - "9651:9651"
            - "1332:9650"
        volumes:
            - /localdisk/data:/data
            - /localdisk/logs:/root/.avalanchego
        command:
           # - "--index-enabled=true" //currently commented, using as non-indexer node
           # - "--x-chaos-vm-tracing-enabled=true" //not working 
             - "geth --http --http.rpc.api eth,debug"
        mem_limit: 10g
        entrypoint: "./avalanchego --http-host="

At the place of --x-chaos-vm-tracing-enabled, tried with --trace, --debug-vm-tracing-enabled, --api-debug-enabled, --api-debug but seems node not starting, 
flag - --trace o/p User couldn't configure flags: unknown flag: --trace
flag - --debug-vm-tracing-enabled o/p User couldn't configure flags: unknown flag: --debug-vm-tracing-enabled
flag - --api-debug-enabled o/p User couldn't configure flags: unknown flag: --api-debug-enabled
flag - --api-debug o/p User couldn't configure flags: unknown flag: --api-debug

Thanks
Umang

**Comment by ceyonur** [comment]
The command has wrong flags. AvalancheGo accepts different flags, you can find them under:
https://docs.avax.network/nodes/maintain/avalanchego-config-flags

if you want to run C-Chain (Coreth) with different flags you need to put them under relevant chain config file:
https://docs.avax.network/nodes/maintain/chain-config-flags#c-chain-configs

**Comment by ceyonur** [comment]
You can inspect the official docker image here:
https://hub.docker.com/layers/avaplatform/avalanchego/v1.10.1/images/sha256-d32ea689c0383db1c0c24dcc0c900fbe131395bef86d1718a39d670458ee4d66?context=explore
