### ISSUE TITLE
About the settings for producing blocks

### ISSUE THREAD

**Issue by BigOceanGG** [ava-labs/avalanchego#1491]
Can this chain be set to produce blocks according to time instead of according to transactions? How to modify the configuration, thank you

**Comment by StephenButtolph** [comment]
> Can this chain

By default avalanchego comes with 3 chains. The P-chain, C-chain, and X-chain. None of them support a simple config to specify time based block production.

If you are trying to create a custom virtual machine, it should be fairly simple to introduce time based block issuance.
