### ISSUE TITLE
Non-validator node cannot synchronize from validator node

### ISSUE THREAD

**Issue by shaokun11** [ava-labs/avalanchego#1515]
**Describe the bug**
I created a subnet according to this [timestampvm-rs](https://github.com/ava-labs/timestampvm-rs ),but Non-validator node cannot synchronize from validator node

**To Reproduce**

1. started a validator node on machine A
2.  start a non-validator node on machine B,the data will not be synchronized
3. Let the node of machine B become a validator,the data will be synchronized

**Expected behavior**
Non-validator node can also synchronize from validator node

**Screenshots**
* It will always be stuck on the master as shown in the picture without syncing
![1](https://github.com/ava-labs/avalanchego/assets/40231565/81c15097-a3df-4208-ab39-405e0d091964)

**Logs**

[log.main.zip](https://github.com/ava-labs/avalanchego/files/11494232/log.main.zip)

**Operating System**
Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-1031-aws x86_64)

**Comment by hexfusion** [comment]
@shaokun11 thanks for the issue details taking a look.

**Comment by hexfusion** [comment]
I was able to reproduce this with `AvalancheGo` 1.10.2 and `timestampvm-rs` 0.0.14. Working on a fix and a larger update.

**Comment by hexfusion** [comment]
@shaokun11 can you please test the latest version timestampvm v.0.0.15[1]. This worked for me to synchronize a  non validator node. I also added the validator nodes to `--bootstrap-ips`, `--bootstrap-ids` of the non validator node. This would require AvalancheGo 1.10.1+. 

[1] https://github.com/ava-labs/timestampvm-rs/releases/tag/v0.0.15

**Comment by shaokun11** [comment]
@hexfusion I did a new test and it synced successfully. Thanks for your effort.
