### ISSUE TITLE
platform.getValidatorsAt fails with timeout

### ISSUE THREAD

**Issue by leopaul36** [ava-labs/avalanchego#1549]
**Describe the bug**
The `platform.getValidatorsAt` fails with a timeout on our archival node.

**To Reproduce**
```bash
curl --location 'https://archival01.ash.center:9651/ext/bc/P' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"platform.getValidatorsAt",
    "params" :{
        "height": 3610000,
        "subnetID": "11111111111111111111111111111111LpoYY"
    }
}'
```

**Expected behavior**
Successful query.

**Logs**
Attaching logs with `"log-level": "debug"`.
[avalanchego_logs.tar.gz](https://github.com/ava-labs/avalanchego/files/11563469/avalanchego_logs.tar.gz)

**Metrics**
It seems that the P Chain process gets totally blocked after the request, we can see the "Unprocessed Incoming Messages" spiking.

![image](https://github.com/ava-labs/avalanchego/assets/12017342/2433e9f4-da9d-4762-9c9a-89615e16671e)

**Operating System**
Ubuntu 22.04.2

**Additional context**
We can see the query in `P.log`:

```
P.log:[05-25|09:40:16.868] DEBUG <P Chain> platformvm/service.go:2550 API called {"service": "platform", "method": "getValidatorsAt", "height": 3610000, "subnetID": "11111111111111111111111111111111LpoYY"}
```

Then no more logs until the query times out / is canceled.

**Comment by StephenButtolph** [comment]
`platform.getValidatorsAt` performs reverse diffs of the validator set. The current P-chain height is ~6M. So, requesting the validators set at height ~3M is going to be extremely expensive.

I'm not really sure that this is a bug so much as a documentation request?

**Comment by leopaul36** [comment]
> `platform.getValidatorsAt` performs reverse diffs of the validator set. The current P-chain height is ~6M. So, requesting the validators set at height ~3M is going to be extremely expensive.
> 
> I'm not really sure that this is a bug so much as a documentation request?

Thanks for the explanation @StephenButtolph. I guess our concern was that every API we tested on our node were responding OK except for this one but since this is expected behavior I will close the issue then.
