### ISSUE TITLE
 err="execution reverted: ERC721: invalid token ID"

### ISSUE THREAD

**Issue by cyb3ralbert** [ava-labs/avalanchego#1558]
``` WARN [04-06|13:49:38.674] <2J5AZfDNqWtg9FAXGZkP4qVRUp3SD9XcQrYZz878BmZ7ybpCN5 Chain> github.com/ava-labs/subnet-evm/rpc/handler.go:403: Served eth_call reqid=0  execTime="293.46µs"  procTime="294.168µs" totalTime="294.451µs" err="execution reverted: ERC721: invalid token ID"```

what does it mean?

**Comment by StephenButtolph** [comment]
> <2J5AZfDNqWtg9FAXGZkP4qVRUp3SD9XcQrYZz878BmZ7ybpCN5 Chain>

Means that this was triggered on blockchain `2J5AZfDNqWtg9FAXGZkP4qVRUp3SD9XcQrYZz878BmZ7ybpCN5`.

> github.com/ava-labs/subnet-evm/rpc/handler.go:403

Is the line that this was logged at.

> Served eth_call

Means this log was during the handling of an `eth_call` request to the node's API endpoint

> err="execution reverted: ERC721: invalid token ID"

Is the error message returned from the contract invocation during the API call.

If you are performing API calls against your node, it seems like one of them errored. If you are n't performing APIs calls against your node, then someone else is. The API endpoint should always be restricted to only be accessible by you.
