### ISSUE TITLE
fees are destroyed but new utxos are created whenever a validator is rewarded

### ISSUE THREAD

**Issue by BigOceanGG** [ava-labs/avalanchego#1640]
I built a local node and configured the initialStackers' rewardAddress on the Genesis block node. Why didn't I receive the reward. Isn't it that if I participate in the block, I can earn
Rewards  has not been distributed yet at endTime = startTime + initialStakeDuration + initialStakeDurationOffset，and at this time, I only have one valid verification node. If the distribution is sent on which chain (C/X/P)

**Comment by StephenButtolph** [comment]
What is your question?

Staking rewards are provided at the end of the staking period on the P-chain.

**Comment by BigOceanGG** [comment]
@StephenButtolph  Will rewards be provided only after staking ends? I thought I could get rewards for producing blocks

**Comment by joshua-kim** [comment]
@BigOceanGG rewards are only given to validators upon the end of their staking cycle if your node's perceived uptime is above the reward threshold. Although validators are responsible for producing blocks, there isn't a reward per block produced.
