### ISSUE TITLE
failed to get logs for block #blockNumber

### ISSUE THREAD

**Issue by locrianlocs** [ava-labs/avalanchego#1647]
**Describe the bug**
Starting from last week, public RPC is giving error while getting logs for some specific blocks.

**To Reproduce**
Block 31644089 is one of them.

curl 'https://api.avax.network/ext/bc/C/rpc' -H 'Content-Type: application/json' -XPOST --data '{"method":"eth_getLogs","params":[{"fromBlock":"0x1e2d9b9","toBlock":"0x1e2d9b9"}],"id":491163,"jsonrpc":"2.0"}'

**Expected behavior**
Instead of returning error, return empty array if there are no logs or transactions. Currently there is no way of knowing why it's failing from the error message.

**To best protect the Avalanche community security bugs should be reported in accordance to our [Security Policy](../security/policy)**

**Comment by aaronbuchwald** [comment]
Thanks for reporting!

We've fixed this bug in this PR https://github.com/ava-labs/coreth/pull/270 and deployed to the Public APIs. We're planning to put out the official release next week.

**Comment by bimlas** [comment]
@aaronbuchwald 

When will the fix released? Is it okay to downgrade to v1.10.2 until it comes?

**Comment by StephenButtolph** [comment]
> When will the fix released? Is it okay to downgrade to v1.10.2 until it comes?

We try to keep the "Due Date" of our release milestones up-to-date with our target release time: https://github.com/ava-labs/avalanchego/milestone/5.

It's fine to downgrade.
