### ISSUE TITLE
replacement transaction underpriced

### ISSUE THREAD

**Issue by BigOceanGG** [ava-labs/avalanchego#1726]
I built a local chain and found that sending transactions in bulk from a single address would result in the error 'replacement transaction underpriced'. This should be caused by the nonce error caused by the transaction being sent too quickly. How to solve this problem

**Comment by aaronbuchwald** [comment]
If you issue multiple transactions from the same address, you must increment the nonce for each subsequent transaction. Your transaction issuance logic may not account for this correctly if you either omit incrementing the nonce completely or only fetch the current nonce and use that in your full sequence of transactions without accounting for the fact that you are issuing a sequence of dependent transactions.

If you have further questions related to running the EVM on Avalanche, you should open them on the relevant EVM repo either Coreth or Subnet-EVM (https://github.com/ava-labs/coreth or https://github.com/ava-labs/subnet-evm/)
