### ISSUE TITLE
Title: Issue with tx.gasprice method in DFK Testnet

### ISSUE THREAD

**Issue by amit-supraoracles** [ava-labs/avalanchego#1753]
Hello Team,

I need help with the tx.gasprice method in REMIX IDE on DFK testnet.
The gas price returned seems incorrect or unavailable when deploying and executing a contract

```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

contract GasConract {
    uint256 public gasPriceData;
    function setGasPrice() public {
        gasPriceData = tx.gasprice;
    }
}
```
Any insights or solutions would be appreciated.

Thank you,
Amit Kumar
[SupraOracles](https://supraoracles.com/)

**Comment by aaronbuchwald** [comment]
Hey @amit-supraoracles , could you move this issue to the relevant repo here: https://github.com/ava-labs/subnet-evm/issues/new/choose
