### ISSUE TITLE
Feature: Personal Access Tokens

### ISSUE THREAD

**Issue by collincusce** [ava-labs/avalanchego#176]
Currently all APIs are open on all nodes. I suggest we fix this with Personal Access Tokens:

1. Whitelist 127.0.0.1 as able to access all APIs. 
2. Create an admin call called "createPAT" which generates a PAT for a user already found in the keystore and for the provided endpoints in the createPAT request. 
3. Create admin call called "revokePAT" which removes a PAT for a user. 
4. Make all endpoints check https headers for username:PAT unless there's an entry in the createPAT for that endpoint with the username  "*" .

Using Basic HTTP Authorization headers: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization

**Comment by danlaine** [comment]
Implemented in #266
