### ISSUE TITLE
Approaching the end of the validation on the local network

### ISSUE THREAD

**Issue by Nuttymoon** [ava-labs/avalanchego#1820]
https://github.com/ava-labs/avalanchego/blob/aa481ddce393fbb3ab957e4c8f87d5cd50b5eb4e/genesis/genesis_local.json#L41

**Comment by StephenButtolph** [comment]
#1811

**Comment by StephenButtolph** [comment]
This was just merged into `dev` - so will be included into the next release (before the genesis expires). Thanks for opening this!
