### ISSUE TITLE
Extremely slow C-Chain container execution and P-Chain and C-Chain indexing after v1.10.8 update

### ISSUE THREAD

**Issue by harry-avax** [ava-labs/avalanchego#1848]
**Describe the bug**
Started a new archival node on 2023/08/01 running v1.10.7, P-Chain and X-Chain sync and container execution completed within ~48 hours and C-Chain container execution had an ETA of ~210 hours as of the morning of 2023/08/10.

After updating to v1.10.8 on the 8th, P-Chain indexing and C-Chain container execution are running much slower and ETA has increased to over 2000 hours and is still climbing.

**To Reproduce**
Node was set up using the installation script with the following configuration:

* archival
* index
* state-sync off

**Expected behavior**
I haven't been able to find exact figures, but I don't believe that even an archival node should be taking over 2000 hours to complete container execution and indexing after already running for ~10 days.

**Screenshots**
![Screenshot_20230813_212440](https://github.com/ava-labs/avalanchego/assets/142178820/44edbc61-9fad-4c46-9182-7c375993f0b2)
![Screenshot_20230813_212540](https://github.com/ava-labs/avalanchego/assets/142178820/1f6699be-2b35-426d-b8c8-118b87c9e94e)
![Screenshot_20230813_212614](https://github.com/ava-labs/avalanchego/assets/142178820/952d6501-2ccb-42ca-a8f2-d84cfd326770)

**Logs**
[C.log](https://github.com/ava-labs/avalanchego/files/12330351/C.log)
[P.log](https://github.com/ava-labs/avalanchego/files/12330352/P.log)

**Metrics**
If applicable, please include any metrics gathered from your node to assist us in diagnosing the problem.

**Operating System**
Fresh install of Ubuntu 22.04.3 LTS, kernel version 5.15.0-78-generic.

**Additional context**
CPU: Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz
RAM: 16 GB DDR4
SSD: 1 TB M.2 PCIe Gen4 NVMe

I've been informed that archival nodes use ~4.4 TB so I'll need to upgrade the SSD, but with 540 GB in use currently I can't imagine this causing the issue at the moment.

**To best protect the Avalanche community security bugs should be reported in accordance to our [Security Policy](../security/policy)**

**Comment by aaronbuchwald** [comment]
Thanks for creating this issue. This is most likely caused by the addition of `platform.getBlockByHeight`, which requires adding a new index to the P-Chain.

See the release notes here: https://github.com/ava-labs/avalanchego/releases/tag/v1.10.8 for a brief mention. In order to support the new API call, the node will start a thread to backfill the P-Chain index required to serve this API. Adding the new P-Chain index will compete with the already IO bound C-Chain bootstrapping execution, which will make it slower to execute each C-Chain block.

The bootstrapping estimates are based off of how long it is taking to execute blocks, so if executing blocks is slower than normal (due to competing with the P-Chain indexing for IO) then it will lead to a larger estimate. Once the P-Chain index completes, C-Chain block execution should speed up.

cc @dhrubabasu

**Comment by harry-avax** [comment]
Thanks for getting back to me so quickly. That would make sense, and explains why the estimation shot up after updating to v1.10.8.

I had a quick look through the docs and couldn't see anything mentioning it, but do you know if there is there any way to pause the C-Chain container execution or relaunch the node to exclude it for now, in order to let the P-Chain indexing complete first?

**Comment by StephenButtolph** [comment]
> is there any way to pause the C-Chain container execution or relaunch the node to exclude it for now, in order to let the P-Chain indexing complete first?

There isn't a way to halt either of the indexing operations. Though I wouldn't really expect the indexing to cause any DB thrashing or anything like that (so I'm not sure it makes a lot of sense to turn one of these jobs off to let the other finish). Not a case we have thoroughly benchmarked though for sure.

**Comment by harry-avax** [comment]
> > is there any way to pause the C-Chain container execution or relaunch the node to exclude it for now, in order to let the P-Chain indexing complete first?
> 
> There isn't a way to halt either of the indexing operations. Though I wouldn't really expect the indexing to cause any DB thrashing or anything like that (so I'm not sure it makes a lot of sense to turn one of these jobs off to let the other finish). Not a case we have thoroughly benchmarked though for sure.

Good to know, thanks. The idea was more to get the P-Chain indexing out the way first so I could get a more accurate estimation for the C-Chain execution completion, as both are incredibly slow at the moment. P-Chain still has 5513329 blocks to go as of this morning, after running for a little over 7 days.
