### ISSUE TITLE
flake: github.com/ava-labs/avalanchego/x/merkledb timeout

### ISSUE THREAD

**Issue by marun** [ava-labs/avalanchego#2002]
## Failing jobs
- [Tue, 12 Sep 2023 09:14:48 GMT](https://github.com/ava-labs/avalanchego/actions/runs/6157389907/job/16708015819#step:4:235)
- [Tue, 12 Sep 2023 09:14:58 GMT](https://github.com/ava-labs/avalanchego/actions/runs/6157391389/job/16708019414#step:4:235)
- [Tue, 12 Sep 2023 09:49:41 GMT](https://github.com/ava-labs/avalanchego/actions/runs/6157389907/job/16709166229)

**Comment by dboehm-avalabs** [comment]
Fixed by https://github.com/ava-labs/avalanchego/pull/1990
