### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by KyleMoser** [ava-labs/avalanchego#2085]
**Describe the bug**
[Creating a local testnet](https://docs.avax.network/build/tutorials/platform/create-a-local-test-network/)

The link in the README on the main branch doesn't work. https://docs.avax.network/build/tutorials/platform/create-a-local-test-network/

I want to know what command to run to start up a local test network. I assume it would be in that link.

**Comment by Jesserc** [comment]
Should that be replaced with this?:
https://docs.avax.network/tooling/network-runner

@joshua-kim

**Comment by joshua-kim** [comment]
Fixed on https://github.com/ava-labs/avalanchego/pull/2203
