### ISSUE TITLE
Feature: REST Endpoints

### ISSUE THREAD

**Issue by collincusce** [ava-labs/avalanchego#211]
JSON-RPC is terrible for caching on the host level. 

I would like to see something that translates our endpoints that use JSON-RPC into a REST-y version of the same stuff, directly into Gecko.

We will keep the existing JRPC's.

I would *prefer* this kinda thing be automatic such that it translates "params" into a POST/GET/DELETE/PUT call by some metadata associated with the JRPC Go method itself. 

I want it specifically for the AVM,  Platform VM, Keystore, and Admin endpoints on the default subnet.

**Comment by collincusce** [comment]
![Screenshot from 2020-06-04 13-33-24](https://user-images.githubusercontent.com/6778681/83791647-00e46880-a668-11ea-85e4-f51550dd3a62.png)

Basically like this, but for REST. 

Important reading:
 * https://docs.ava.network/v1.0/en/api/issuing-api-calls/
 * https://docs.ava.network/v1.0/en/api/platform/
 * https://docs.ava.network/v1.0/en/api/avm/
 * https://docs.ava.network/v1.0/en/api/keystore/
 * https://docs.ava.network/v1.0/en/api/admin/

**Comment by glemercier** [comment]
Let me use an example to try and make sure I understand your request. You would like this JSON-RPC API:

__Request:__
```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "avm.createAddress",
    "params": {
        "username":"myUsername",
        "password":"myPassword"
    },
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
```

__Response:__
```
{
    "jsonrpc": "2.0",
    "result": {
        "address": "X-EKpEPX56YA1dsaHBsW8X5nGqNSwJ7JrWH"
    },
    "id": 1
}
```

To be accessible through another REST API which would look like this:

__Request:__
```
curl -u username:password -X POST 127.0.0.1:9650/ext/bc/X/addresses
```

__Response:__
```
{
    "address": "X-EKpEPX56YA1dsaHBsW8X5nGqNSwJ7JrWH"
}
```

Do you confirm this is what you expect? If no can you elaborate on this example for us to understand better?

**Comment by collincusce** [comment]
Clooseee I don't think we need to use basic authentication, though. I would just pass it via the request body for this iteration and keep everything 1:1 with the JSON-RPC. Let TLS do the security for this kinda stuff. At least for now.

**Comment by glemercier** [comment]
Ok, so something like this:

```
curl -X POST --data '{
    "params": {
        "username":"myUsername",
        "password":"myPassword"
    },
}' -H 'content-type:application/json;'  127.0.0.1:9650/ext/bc/X/rest/addresses
```

Then `listAddresses` would be:
```
curl -X GET --data '{
    "params": {
        "username":"myUsername",
        "password":"myPassword"
    },
}' -H 'content-type:application/json;'  127.0.0.1:9650/ext/bc/X/rest/addresses
```

etc...

**Comment by collincusce** [comment]
Yeah and I think the real trick will be some sort of mapping between JRPC <-> REST calls. But totally do-able I believe.

**Comment by collincusce** [comment]
Oh and for the REST body you have, you can remove the JSON and just make it standard POST calls.

**Comment by glemercier** [comment]
Ok then, let me have a look at all the APIs and see if anything would prevent us from doing a direct mapping.

**Comment by collincusce** [comment]
Ex: 

```
curl -X POST -d "username=myUsername&password=myPassword"  -H "Content-Type: application/x-www-form-urlencoded" -X POST 127.0.0.1:9650/ext/bc/X/rest/addresses
```

**Comment by collincusce** [comment]
By the way, I'm suuupperr flexible. Let's just make it make sense and be a really clear user experience. And try to leverage the Go Gorrilla library since we're already using it. Nothing fancy or extra is required, I think.

**Comment by huglester** [comment]
It is usually probably more of an:
```
POST /x/api/users
POST /x/api/wallet
POST /p/api/wallet
GET /x/api/wallet/X-CjgjVNYmzaxW41wRB8dkCSpwXg6A38qhw
POST /x/api/users/export
```
Might add versioning instantly - v1, to later support smth like that: /x/api/v2/users

Would need to think of all REST /endpoints naming - this is crucial


Just my 2c :)

**Comment by collincusce** [comment]
Welllll this isn't a website. These go for individual nodes generally in your own control. Versioning can be handled by routing v1 ... vN  to a node running the appropriate version, and that would be on the application layer which is being built around a node network you own. My 2c is keep is simple. We implement multiple "api"'s so we should probably use "rest" to be extra clear just like we use "ws" for websockets and in some cases "rpc" for the jrpc. 

Let's not shake things up too hard. Let's just get a REST interface and go from there.

**Comment by collincusce** [comment]
Hey guys,

1. Definitely don't hardcode endpoint suffixes. Sorry if I wasn't clear, after looking at the code I don't think it's a good idea to do that.
2. Only complete submissions please. If you want to vet an approach, let me know personally and I'll take a look. Ultimately Stephen and Dan will be the ones merging so you have to pass their litmus test.
3. I'm not a jerk. I know that people who put in effort and get nothing for it because their submission didn't pass muster is ehhhh not fun. I'll probably give a little something if you finish by Sunday with a valid PR but it doesn't get accepted. 

Thanks for the effort so far, I'm ... honestly I'm really impressed. I didn't expect so much interest so early and I'm happy to see it.

**Comment by glemercier** [comment]
I think @harsh-98 proposed solution is pretty efficient and does the job nicely. Even though I have no specific gorilla experience it still feels like the codec is not the place to do it, it would hijack its original purpose which is to serialize/deserialize different content types. The only real issue I see here is that if we want to keep the API and allow other formats later (e.g. protobuf, xml, binary, whatever...) it would have to be implemented in the codec function in a switch/case manner rather than using different codecs as expected by the gorilla library.

Although I agree that it would be a valid assumption that this will likely never happen and it should not prevent us from doing it this way if we feel like it "just because we never know in the future". 

Another way I imagined (but haven't tested yet) would be to add a `router` to the existing list of handlers. Example for the AVM API:
```
diff --git a/vms/avm/vm.go b/vms/avm/vm.go
index e4f5212..97ee478 100644
--- a/vms/avm/vm.go
+++ b/vms/avm/vm.go
@@ -11,6 +11,7 @@ import (
        "time"
 
        "github.com/gorilla/rpc/v2"
+       "github.com/gorilla/mux"
 
        "github.com/ava-labs/gecko/cache"
        "github.com/ava-labs/gecko/database"
@@ -216,12 +217,17 @@ func (vm *VM) Shutdown() error {
 func (vm *VM) CreateHandlers() map[string]*common.HTTPHandler {
        rpcServer := rpc.NewServer()
        codec := cjson.NewCodec()
+       service := Service{vm: vm}
        rpcServer.RegisterCodec(codec, "application/json")
        rpcServer.RegisterCodec(codec, "application/json;charset=UTF-8")
-       rpcServer.RegisterService(&Service{vm: vm}, "avm") // name this service "avm"
+       rpcServer.RegisterService(&service, "avm") // name this service "avm"
+
+       router := mux.NewRouter()
+       router.HandleFunc("/rest", service.HandleREST)
 
        return map[string]*common.HTTPHandler{
                "":        &common.HTTPHandler{Handler: rpcServer},
+               "/rest":   &common.HTTPHandler{Handler: router},
                "/pubsub": &common.HTTPHandler{LockOptions: common.NoLock, Handler: vm.pubsub},
        }
 } 
```

Then have a `HandleREST` function implemented at the service level (`vms/avm/service.go`) that does the mapping between the request and the function to call. Ideally this logic would be implemented in some utils class, so that each service can easily instantiate such an object providing its own mapping as a parameter. Again, just some idea that I have not yet tested.

BTW, I'm not doing this for the reward :-) Just because I have a bit of spare time, I like the project, and it's a great occasion to practice a bit of Go under real life conditions. Whoever gets the rewards is fine for me, I just hope my contribution can help making the implementation as good as possible.

**Comment by collincusce** [comment]
> Even though I have no specific gorilla experience it still feels like the codec is not the place to do it, it would hijack its original purpose which is to serialize/deserialize different content types. 

Now that I dig into it a bit more and see your proposed solution, I agree. Codec are not the way to handle this... "handlers" are lol. 

Can you two work together on this since you're not after the reward? Not sure if you're interested in that, but I do think it would produce a higher quality result.

**Comment by harsh-98** [comment]
See, what i have  done is made one handler to be able to handle two codecs: one for RPC(mapping request data to params and method ) and one for REST(mapping request to uri and params). It is able to handle aliases too.

**Comment by collincusce** [comment]
Yeah @glemercier he's got a PR he's working on here: https://github.com/ava-labs/gecko/pull/215

**Comment by collincusce** [comment]
I talked with Stephen and we think that handlers are the best route to rather than the Codec solution. VMs can route their own endpoints and after discussing, we consider it important that solutions take that into account.

**Comment by harsh-98** [comment]
@glemercier I was written script to show the denali step up with REST endpoints. It is now available in the PR.

**Comment by glemercier** [comment]
I'm currently looking at how to get rid of the codec stuff in @harsh-98's code. I'm getting there and should be able to find something. Only thing is that it involves reflection (to get the function to call, and req/resp struct types before calling the final JRPC function), hopefully it will not make the code too complicated. I will keep you posted and issue a PR to @harsh-98's repo whenever I have something

**Comment by collincusce** [comment]
I know Stephen really prefers not to use Reflection when possible.

**Comment by glemercier** [comment]
Yeah I get it, it's kind of overkill. Although I'm not sure there is any way to avoid it here. The problem is we have a lot of functions like this to handle JRPC requests:

```
func (service *Service) GetTxStatus(r *http.Request, args *GetTxStatusArgs, reply *GetTxStatusReply) error
func (service *Service) GetTx(r *http.Request, args *GetTxArgs, reply *GetTxReply) error
func (service *Service) GetUTXOs(r *http.Request, args *GetUTXOsArgs, reply *GetUTXOsReply) error
etc...
```
Those are implemented this way to comply with gorilla as explained [here](http://www.gorillatoolkit.org/pkg/rpc/v2), which likely uses reflection itself:

```
When a service is registered, the server inspects the service methods and make available the ones that follow these rules:

- The method name is exported.
- The method has three arguments: *http.Request, *args, *reply.
- All three arguments are pointers.
- The second and third arguments are exported or local.
- The method has return type error.
All other methods are ignored.
```

To be able to call the JRPC function we need to get the type of the `args` and `reply` parameters in advance, since they are different for each function.

I will continue looking in some ways to avoid using reflection, maybe there is something in gorilla I missed which could help, but I am afraid we end up using some even more hacky ways. I'll keep you posted if I find anything.

**Comment by glemercier** [comment]
One more thing, here is what we currently use to make the mapping between REST endpoints and JRPC methods:

``` 
var RestMapping map[string]string = map[string]string{                                                                  
  "/tx":                        "GetTx",                                                                                
  "/tx/issue":                  "IssueTx",                                                                              
  "/tx/status":                 "GetTxStatus",                                                                          
  "/tx/send":                   "Send",                                                                                 
  "/tx/mint":                   "CreateMintTx",                                                                         
  "/tx/mint/sign":              "SignMintTx",                                                                           
  "/utxo":                      "GetUTXOs",                                                                             
  "/balance":                   "GetBalance",                                                                           
  "/balance/all":               "GetAllBalances",                                                                       
  "/asset/description":         "GetAssetDescription",                                                                  
  "/asset/cap/fixed/create":    "CreateFixedCapAsset",                                                                  
  "/asset/cap/variable/create": "CreateVariableCapAsset",                                                               
  "/address/create":            "CreateAddress",                                                                        
  "/address/list":              "ListAddresses",                                                                        
  "/key/import":                "ImportKey",                                                                            
  "/key/export":                "ExportKey",                                                                            
  "/ava/import":                "ImportAVA",                                                                            
  "/ava/export":                "ExportAVA",                                                                            
}  
``` 

This is pretty simple and easily extendable, and contains everything we need to call the JRPC function with reflection.
