### ISSUE TITLE
Sync incomplete

### ISSUE THREAD

**Issue by hippke** [ava-labs/avalanchego#2110]
Situation:
I created my first AvalancheGo node locally. It bootstrapped to "true" using "all standard" settings. The block height agrees with snowtrace.io, and I can pull the most recent txs using the RPC interface.

Issue:
It only synced the most recent blocks of the last ~24 hrs. Older blocks are not available. Disk usage is 83 GB.
How to fix? I want to access the txs of older blocks as well.

**Comment by StephenButtolph** [comment]
Seems like you want to disable `state-sync` on the C-chain. See: https://docs.avax.network/nodes/configure/chain-config-flags#state-sync-enabled-boolean

**Comment by hippke** [comment]
Thank you for the advice. I have tried it but the problem persists. I call:
`./avalanchego --config-file config.json`
Content of config.json:
```
{
  "log-level": "debug",
  "state-sync-enabled": "false"
}
```
