### ISSUE TITLE
Feature idea: seperate keystore and network state databases

### ISSUE THREAD

**Issue by moreati** [ava-labs/avalanchego#219]
As I understand it, keystore users/keys (created with `keystore.createUser`) are stored in the same database as the the network state (`~/.gecko/db/denali/v0.5.0`). It would be nice to separate these (e.g. `.../v0.6.0/keystore`, `.../v0.6.0/network`). The intended benefits are
- More selective backups - network state can be downloaded again, private keys can't
- Easier node administration - possible to start bootstrap again, without losing user accounts.
- Better data durability - if the keystore is rarely accessed, then the database can (potentially) be flushed/committed/closed most of the time, less vulnerable to data corruption during a crash or other software failure.

**Comment by StephenButtolph** [comment]
The keystore database is deprecated, we actual did implement this feature... but it was deemed to high risk of a migration... so we're hoping to just remove support for the keystore in its entirety.
