### ISSUE TITLE
Consolidate P-Chain Mempool into a single heap

### ISSUE THREAD

**Issue by joshua-kim** [ava-labs/avalanchego#2193]
Currently the P-Chain has two heaps for decision txs and staker txs. We should consolidate this to be in a single heap.

We can fix PeekTxs ([ref](https://github.com/ava-labs/avalanchego/blob/3c60ac7f61b8d6e94e2053d165409c8108d7b059/vms/platformvm/txs/mempool/mempool.go#L225)) to pop off the heap directly instead of turning both heaps into lists which breaks the heap prioritization.

**Comment by abi87** [comment]
@joshua-kim not sure we can do it right now.
StakersTxs must be picked by their startTime, while other txs (e.g. import/exports createChain/Subnet) will be pick in FIFO order.
So not sure we can ditch the heap andkeep StakerTxs require ordering.
However once we drop the pending stakers idea, we won't need to order stakerTxs by their start time (they won't even have a Start() method) and we can keep a single list for all mempool txs.

**Comment by dhrubabasu** [comment]
We removed the two tx heaps in favor of a linked hashmap in https://github.com/ava-labs/avalanchego/pull/1536. Marking as completed.
