### ISSUE TITLE
"invalid host specified" since last update

### ISSUE THREAD

**Issue by PaTiToMaSteR** [ava-labs/avalanchego#2200]
**Describe the bug**
Since I updated...
this works: http://3.28.173.191:9650/ext/bc/QVbrD172sAF1TgCvN9DZG93nAd2YBGCJVZP4cngdEKCTy2F9v/rpc
this **now** doesn't work: http://ec2-3-28-173-191.me-central-1.compute.amazonaws.com:9650/ext/bc/QVbrD172sAF1TgCvN9DZG93nAd2YBGCJVZP4cngdEKCTy2F9v/rpc
I use AWS Load Balancer and this is disconnecting all my users from https://mainnet.pulsar.game/ext/bc/QVbrD172sAF1TgCvN9DZG93nAd2YBGCJVZP4cngdEKCTy2F9v/rpc

**To Reproduce**
Open the urls in a browser

**Expected behavior**
Like it was before by default.

**Logs**
Not really relevant, no errors

**Operating System**
Linux, x64

**Additional context**
My node.json 
{
  "http-host": "",
  "public-ip": "3.28.157.124",
  "track-subnets": "DxanjptkyaeM1eUew2gzUMngHM3n5ttUyMj7BuHw9riXh9pJC",
  "log-display-level": "INFO",
  "log-level": "INFO"
}

I tried using this, config and removing http-host
{
  "http-host": "ec2-3-28-157-124.me-central-1.compute.amazonaws.com",
  "public-ip": "3.28.157.124",
  "track-subnets": "DxanjptkyaeM1eUew2gzUMngHM3n5ttUyMj7BuHw9riXh9pJC",
  "log-display-level": "INFO",
  "log-level": "INFO"
}

**Comment by StephenButtolph** [comment]
AFAIK this hasn't changed since `v1.10.3` (when `--http-allowed-hosts` was introduced). But I think that's the flag you're looking for.

From the node help text:
```
--http-allowed-hosts strings (default [localhost])

    List of acceptable host names in API requests.
    Provide the wildcard ('*') to accept requests from all hosts.
    API requests where the Host field is empty or an IP address will always be accepted.
    An API call whose HTTP Host field isn't acceptable will receive a 403 error code
```

So, I think you'll want to specify `--http-host=""` and `--http-allowed-hosts="*"`
