### ISSUE TITLE
"fatal error: concurrent map read and map write"

### ISSUE THREAD

**Issue by tzmmtz** [ava-labs/avalanchego#2208]
Upgraded to 1.10.13, a couple days of everything fine, my Node went offline a few hours ago. On my Mac, running 12.6.8, I see this in my terminal window  "fatal error: concurrent map read and map write".  Is this a Mac OS issue or related to 1.10.13? Never seen this error in the past. Never had any Node issues in the past related to this computer. Computer has over 500GB free space.

A", "height": 9408117, "parentTimestamp": "[10-24|02:40:56.000]", "blockTimestamp": "[10-24|02:41:26.000]"}
fatal error: concurrent map read and map write

I am not a programmer. Just a fellow running a validator. Probably not a bug, perhaps some unexpected Mac OS behavior but searched on Discord channel and nothing showed in posts for this error.

Thoughts?

**Comment by tzmmtz** [comment]
It just happened again. Dropping back to 1.10.11.

**Comment by dhrubabasu** [comment]
@tzmmtz Can you share your logs around the time that it happened?

**Comment by dhrubabasu** [comment]
@tzmmtz Can you paste the contents of your log in GitHub's UI? I can't see the attachment

**Comment by tzmmtz** [comment]
You want me to paste right here?

**Comment by dhrubabasu** [comment]
Yes, preferably in a markdown box like this:

```
log
log
log
```

**Comment by tzmmtz** [comment]
No idea what a markdown box is. Not a programmer. I will paste some of it here.

**Comment by tzmmtz** [comment]
[10-24|16:42:12.541] INFO <X Chain> proposervm/block.go:285 built block {"blkID": "k8aHkhJ9XAvvbhP6d43m6Zm4NLogTDbfpYFdKfaPmADrLCbch", "innerBlkID": "omr2rAR4kjoXb72zBVFHoxmdr5rbc7NvF2KNznAvcBNE7Cc4q", "height": 153490, "parentTimestamp": "[10-24|16:39:55.000]", "blockTimestamp": "[10-24|16:42:12.000]"}
[10-24|16:46:08.542] INFO <X Chain> proposervm/block.go:285 built block {"blkID": "w72aR8gMNECdXPtodcbQcBuuxf6nyyLYxpj7sbQf3TjigCJc1", "innerBlkID": "2Kumi6Mmd95DWKPSpudKmbpHZeEY5PoA6eAoW6DcsorLYCSL2G", "height": 153491, "parentTimestamp": "[10-24|16:42:12.000]", "blockTimestamp": "[10-24|16:46:08.000]"}
[10-24|16:46:43.533] INFO <P Chain> validators/logger.go:83 validator weight changed {"subnetID": "11111111111111111111111111111111LpoYY", "nodeID": "NodeID-KK6ifknXca7VGbqB3d5ccUzKta1zJiVM7", "previousWeight ": 268814814953461, "newWeight ": 268789353397862}
fatal error: concurrent map read and map write

goroutine 2573573 [running]:
github.com/ava-labs/avalanchego/vms/components/chain.(*State).getCachedBlock(0xc061784600, {0x61, 0xfd, 0xc2, 0xb6, 0xad, 0x3, 0x6d, 0x21, 0xd4, ...})
	/Users/runner/work/avalanchego-internal/avalanchego-internal/vms/components/chain/state.go:291 +0x32
github.com/ava-labs/avalanchego/vms/components/chain.(*State).GetBlock(0xc061784600, {0x101bad8e8, 0xc000128020}, {0x61, 0xfd, 0xc2, 0xb6, 0xad, 0x3, 0x6d, ...})
	/Users/runner/work/avalanchego-internal/avalanchego-internal/vms/components/chain/state.go:265 +0x48
github.com/ava-labs/avalanchego/vms/components/chain.(*State).GetBlockInternal(0xc0a9598a80?, {0x101bad8e8?, 0xc000128020?}, {0x61, 0xfd, 0xc2, 0xb6, 0xad, 0x3, 0x6d, ...})
	/Users/runner/work/avalanchego-internal/avalanchego-internal/vms/components/chain/state.go:308 +0x3a
github.com/ava-labs/coreth/plugin/evm.(*VM).verifyTx(0xc0425d0700, 0xc020902300, {0x61, 0xfd, 0xc2, 0xb6, 0xad, 0x3, 0x6d, 0x21, ...}, ...)
	/Users/runner/go/pkg/mod/github.com/ava-labs/coreth@v0.12.6-rc.2/plugin/evm/vm.go:1493 +0x7c

**Comment by tzmmtz** [comment]
Update - Reverting back to 1.10.11 seems to have solved my issue. With 1.10.13 it crashed couple times a day. Now up for almost two days.

**Comment by StephenButtolph** [comment]
Hi @tzmmtz! thanks for opening this, we've been making a number of changes to tx gossip recently. Is this issue still happening on the [latest release](https://github.com/ava-labs/avalanchego/releases/tag/v1.10.14)?

**Comment by tzmmtz** [comment]
I went back to .11 on October 26th and everything was fine. Then .14 was released and updated a day later and everything is fine since that time. So assuming it was something in .13 that caused a problem. Thanks for checking up on my issue. Seems to be resolved.
