### ISSUE TITLE
Avalanche Docker Validator image not running properly

### ISSUE THREAD

**Issue by Sir-Deon** [ava-labs/avalanchego#2234]
**Describe the bug**
The Avalanche image doesn't run as required, starting the container without the --http-host flag, allows for it to run but the validator is not accessible out of the docker container, but when the --http-host flag is added it doesn't run at all. 

**To Reproduce**
After downloading the image,
Cd in the scripts directory and run: 

sudo docker run -ti -d -p 9650:9650 -p 9651:9651 --restart=unless-stopped avaplatform/avalanchego:18324b4a /avalanchego/build/avalanchego --network-id=fuji --http-host=3.83.18.119

to view the logs run
sudo docker logs -f {container name}

**Expected behavior**
The container is supposed to run and when the curt command is run it should respond with the node ID
    curl -X POST --data '{
         "jsonrpc":"2.0",
         "id"     :1,
        "method" :"info.getNodeID"
     }' -H 'content-type:application/json' 127.0.0.1:9650/ext/info

**Screenshots**
<img width="1680" alt="Screenshot 2023-10-30 at 09 12 29" src="https://github.com/ava-labs/avalanchego/assets/57288805/ca3e98bd-0b9d-4d2f-858d-e36b3f540b5e">

**Operating System**
Ubuntu 20.04

**Additional context**
When runing the avanlancheJs code to add a validator
<img width="1030" alt="Screenshot 2023-10-30 at 09 22 17" src="https://github.com/ava-labs/avalanchego/assets/57288805/7bbce593-031d-4ce1-8458-922add7cb042">

**Comment by StephenButtolph** [comment]
As the node is reporting, it seems like the docker image doesn't have the ability to bind to `3.83.18.119`. I think it's much more likely that you want to specify `--http-host=""` so that the node will bind on all available interfaces.

I made #2236 to hopefully better document this flow, but feel free to re-open this if you feel like you're running into a different issue.

**Comment by Sir-Deon** [comment]
Yeah, when I don't specify a host, it runs within the container and cannot be accessed out of the container.

**Comment by Sir-Deon** [comment]
When i run without the --http-host flag, it runs but, i get 
<img width="629" alt="Screenshot 2023-10-30 at 19 28 58" src="https://github.com/ava-labs/avalanchego/assets/57288805/2b44e7d0-9b46-4387-bf76-dc612bf44762">
when i run the curl commend.

**Comment by StephenButtolph** [comment]
@Sir-Deon did you try running with `--http-host=""`?
