### ISSUE TITLE
Unable to get node ID

### ISSUE THREAD

**Issue by Sir-Deon** [ava-labs/avalanchego#2237]
**Describe the bug**
When i run without the --http-host flag, it runs but, i can't get the nodeID from the curl command.

**To Reproduce**
curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"info.getNodeID"
}' -H 'content-type:application/json' 127.0.0.1:9650/ext/info

**Expected behavior**
{
  "jsonrpc": "2.0",
  "result": {
    "nodeID": "NodeID-5mb46qkSBj81k9g9e4VFjGGSbaaSLFRzD"
  },
  "id": 1
}

**Screenshots**
<img width="629" alt="Screenshot 2023-10-30 at 19 28 58" src="https://github.com/ava-labs/avalanchego/assets/57288805/f4061aab-1e70-43b8-859b-ec2f7484f547">

**Comment by StephenButtolph** [comment]
When the node starts up - it logs its config under the `initializing node` log. Could you include the node config here? Also, is there any additional information (like if the is node running inside of docker or if there are any other non-info logs being returned) that you could include?

**Comment by Sir-Deon** [comment]
Thank you @StephenButtolph  here are the logs
The node is running in a docker container.
<img width="1674" alt="Screenshot 2023-10-31 at 12 37 54" src="https://github.com/ava-labs/avalanchego/assets/57288805/eb7c55a8-3b84-4f23-b932-0062c66db425">

**Comment by gyuho** [comment]
@Sir-Deon Have you tried `docker run --rm --network host` to run the container as host network mode?

**Comment by Sir-Deon** [comment]
Thank you @gyuho, it works now should I be worried about these warnings 
<img width="1352" alt="Screenshot 2023-11-01 at 09 53 51" src="https://github.com/ava-labs/avalanchego/assets/57288805/39d87ae4-7f3e-4b07-b92f-847e32c6a640">

**Comment by StephenButtolph** [comment]
> Thank you @gyuho, it works now should I be worried about these warnings <img alt="Screenshot 2023-11-01 at 09 53 51" width="1352" src="https://user-images.githubusercontent.com/57288805/279624442-39d87ae4-7f3e-4b07-b92f-847e32c6a640.png">

If this node is going to be a validator, you'll want to be publicly discoverable to ensure you're well connected to all the validators. If this node isn't a validator, then you can safely ignore those warnings.

If you have any more questions I think the [discord](https://chat.avax.network/) will be the best place. But if there are any feature requests or bugs feel free to open another issue.
