### ISSUE TITLE
Duplicate service registration in subnet-evm

### ISSUE THREAD

**Issue by ashucoder9** [ava-labs/avalanchego#2243]
**Describe the bug**
A developer is trying to run AvalancheGo 1.10.14 with SubnetEVM 0.5.8 and running into the following error:

```bash
ERROR server/server.go:185 failed to create handlers {"chainName": "guvaqv679hxAjtD3Xq9QPVCAtqHERdazVz7eb8dPJYnj36kaw", "error": "rpc error: code = Unknown desc = failed to register service for admin API due to rpc: service already defined: \"admin\""}
```

Block production is working but RPC is not functioning. Talked to @jpop32 and he recommends that the platform team should be aware of this issue. Please check it and let us know possible fixes.

**Expected behavior**
RPC should be up and running while the node is working.

**Additional Info**
While running AvalancheGo v1.10.9 and SubnetEVM 0.5.5, all routes work fine.

**Comment by ceyonur** [comment]
This seems like an issue for Subnet-EVM. Could you reopen the issue in subnet-evm [repository](https://github.com/ava-labs/subnet-evm)?

**Comment by ceyonur** [comment]
Admin API is not activated by default and Public RPC nodes **should not** activate this API for security reasons. You can temporarily fix this issue on your node by deactivating it in chain configs. I.e`admin-api-enabled` should not be `true`. We will investigate the issue in subnet-evm.

**Comment by StephenButtolph** [comment]
I'm going to close this as it seems to be a subnet-evm issue + has been patched for the next subnet-evm release. As an existing workaround disabling the admin API should allow the node to start.
