### ISSUE TITLE
User missing when updating gecko

### ISSUE THREAD

**Issue by nitaxmx** [ava-labs/avalanchego#230]
**Describe the bug**
My staking time ran out so I stopped my node and did git pull before restaking. Built and ran the node. When trying to sing the staking transaction my username is not recognized.
My node id and balance in P account are still there.
The user is gone and I can't create a new one.

**To Reproduce**
Git pull
Build
keystore.listAccounts
Returns empty brackets

**Expected behavior**
I expected to sing my transaction to restake

**Screenshots**
![IMG_20200608_140911](https://user-images.githubusercontent.com/66643244/84072807-65b7ff80-a995-11ea-8e35-ec6aaf3a423c.jpg)
![IMG_20200608_141342](https://user-images.githubusercontent.com/66643244/84072821-6c467700-a995-11ea-8ad4-f49a3612bf83.jpg)

**Operating System**
Ubuntu Mate 18.04

**Additional context**
Node running on raspi

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
Closing this for age. @nitaxmx Please let us know if you experience this issue again
