### ISSUE TITLE
Delegate to multiple validators in one tx

### ISSUE THREAD

**Issue by collincusce** [ava-labs/avalanchego#2385]
**Context and scope**
Delegate to multiple validators in one transaction.

A single validator can fail to meet uptime goals. Spreading delegation to multiple would be more ideal. There should be a web wallet interface for this so you can select the validators based on past performance and time remaining. The transaction should just be a list of validators and amount to delegate to them.

**Comment by dhrubabasu** [comment]
This belongs in the ACP repo as it is an execution change, please follow the process outlined there: https://github.com/avalanche-foundation/ACPs
