### ISSUE TITLE
Feature Request: get --public-ip from domain to enable DynDNS

### ISSUE THREAD

**Issue by otherpaco** [ava-labs/avalanchego#246]
When one runs gecko from home, e.g RaspberryPi or Desktop PC, they often don't own a static IP.
So you can not use `--public-ip` or you need a script to restart gecko on reconnect etc etc.
One solution is NAT Traversal but what about something like:
`--public-ip-via-domain`
When you use DynDNS services like duckDNS your DynDNS-Domain resolves to your current IP so gecko needs to check every x seconds to what IP your domain resolves and set that value as your public-ip.
When your router reconnects your DynDNS domain provides the new IP.

**Comment by moreati** [comment]
I might take this on. Ideally I'd like to rename `--public-ip` to e.g. `--public-address`. However I know IP addresses of nodes are baked into the protocol, so this might be more involved than it first appears.

**Comment by tasinco** [comment]
The feature has been released.
