### ISSUE TITLE
Please upgrade `golang.org/x/exp` 🙏 

### ISSUE THREAD

**Issue by ntauth** [ava-labs/avalanchego#2595]
**Context and scope**
The package has been upgraded in `coreth` but not yet in `avalanchego`. For projects depending on `avalanchego`, this causes conflicts with other packages that rely on different versions of the package because of the differing `slices.Sort` signature

**Comment by ricardogolez** [comment]
we got the same issue!

**Comment by dhrubabasu** [comment]
Duplicate of #2592
