### ISSUE TITLE
FATAL chains/manager.go:350 error creating required chain

### ISSUE THREAD

**Issue by altshiftwp** [ava-labs/avalanchego#2621]
Hi... I set up my validator. I believe it went through boostrapping ok. 

My set up is an AWS Ubuntu VM. 
I'm running avalanche/1.10.15 [database=v1.4.5, rpcchainvm=30, commit=20f3580b4912f29adc602ad883e84897f0965cc1, go=1.21.3]

When I type in avalanchego i receive this error: 
FATAL chains/manager.go:350 error creating required chain
"error": "error while creating new snowman vm failed to create atomic backend: duplicated operation on provided value"

**Comment by StephenButtolph** [comment]
This issue should have been fixed by [v1.10.17](https://github.com/ava-labs/avalanchego/releases/tag/v1.10.17).
> - Fixed `duplicated operation on provided value` error when executing atomic operations after state syncing the C-chain

I'm going to close this issue, but if the problem persists after updating to either `v1.10.17` or `v1.10.18` please create a new issue.
