### ISSUE TITLE
Feature request: Improve EVM web3_clientVersion output

### ISSUE THREAD

**Issue by michaelbnewman** [ava-labs/avalanchego#276]
As noted in the [EVM API docs](https://docs.avax.network/v1.0/en/api/evm/), the EVM's RPC output for web3_clientVersion gives the output:
`Athereum 1.0`

That is probably a leftover value when Athereum was in early development. It would be better to provide something more up to date and informative. Here are some examples from two other ETH clients:

`Geth/v1.9.15-stable-0f77f34b/linux-amd64/go1.14.2`

`Nethermind/v1.8.58-0-636a41449-20200701/X64-Linux 5.4.0-1015-aws/Core3.1.5`

I'd suggest something like: `Gecko-EVM/v0.5.7/linux-amd64/go1.13.12`
Bonus points if you can include the github commit ID in the version number. Might want to list coreth versioning in there too I suppose.

**Comment by michaelbnewman** [comment]
I noticed currently with Avalanchego v1.0.4 that the web3_clientVersion call now returns:

**Comment by aaronbuchwald** [comment]
Thanks for catching this. This has been changed to return `coreth-v0.3.x` now.
