### ISSUE TITLE
Add BLS signers to local network genesis

### ISSUE THREAD

**Issue by Nuttymoon** [ava-labs/avalanchego#2786]
**Context and scope**
After the Durango upgrade, validators must use the `AddPermissionlessValidatorTx` to join the Primary Network. This tx takes a `signer` field containing the node BLS public key and proof of possession. A BLS private key will be used by each validator to sign AWM messages and it has to strictly match the BLS pub key + PoP specified in the `signer` field.

The `local` network validators are not added using `AddPermissonlessValidatorTx` but are defined through the `initialStakers` config in the [genesis_local.json](https://github.com/ava-labs/avalanchego/blob/master/genesis/genesis_local.json) file:

https://github.com/ava-labs/avalanchego/blob/e9ca612faafda09abd5946a32d54d4872f42f1f5/genesis/genesis_local.json#L47-L52

At this time, the `signer` field is not specified in this file, which forces developers, such as myself, to create a custom network with a custom genesis file, network ID, etc. This complicates the development environment setup on Avalanche.

**Discussion and alternatives**
The changes are pretty straightforward:
- Add a static BLS private (secret) key for each local validator in the [staking/local](https://github.com/ava-labs/avalanchego/blob/master/genesis/genesis_local.json) folder
- Add a `signer` field for each validator in `initialStakers` in the [genesis_local.json](https://github.com/ava-labs/avalanchego/blob/master/genesis/genesis_local.json) file:
  ```json
    "initialStakers": [
      {
        "nodeID": "NodeID-7Xhw2mDxuDS44j42TCB6U5579esbSt3Lg",
        "rewardAddress": "X-local18jma8ppw3nhx5r4ap8clazz0dps7rv5u00z96u",
        "delegationFee": 1000000,
        "signer": {
          "publicKey": "0x[...]",
          "proofOfPossession": "0x[...]"
        }
      },
  ```

**Open questions**
None

**Comment by Nuttymoon** [comment]
I'd be happy to open a PR for this.

**Comment by StephenButtolph** [comment]
@Nuttymoon Makes total sense to me. Would love a PR for this.
