### ISSUE TITLE
Gas estimation errored "code": -32000, "message": "method handler crashed" 

### ISSUE THREAD

**Issue by gpersoon** [ava-labs/avalanchego#287]
**Describe the bug**
When deploying a contract on the C-chain you get the error message : Gas estimation errored "code": -32000, "message": "method handler crashed" 

**To Reproduce**
Stop and start ./ava
Wait till you see:
```js
<C Chain> /snow/engine/snowman/transitive.go#111: bootstrapping finished with .. as the last accepted block
```
In metamask configure to use the local endpoint (http://localhost:9650/ext/C/rpc)
Start remix ide (http://remix.ethereum.org)
Select Injected Web3
Compile and try to deploy a smart contract
When you press "deploy" you see the error message:
```js
Gas estimation failed
Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending?
[object Object] { "code": -32000, "message": "method handler crashed" }
```
When you ignore the error messages the contract can be deployed without a problem.
The next contract you deploy doesn't give the error message.
When you restart ./ava the error message present again

Can also be reproduced with:
```js
curl -H "Content-Type: application/json" --request POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"to":"0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48","data":"0xa9059cbb0000000000000000000000007cb57b5a97eabe94205c07890be4c1ad31e486a80000000000000000000000000000000000000000000000000000000000000001"}],"id":34}' http://localhost:9650/ext/C/rpc
```
This direct call also runs ok after a deployment from remix ide

**Expected behavior**
Expected the eth_estimateGas the run without errors
{"jsonrpc":"2.0","id":34,"result":"0x5958"}

**Screenshots**

**Operating System**
Windows 10 + wsl2 + Ubuntu 20.04

**Additional context**

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
Hey @Determinant can you please look into this? I don't know enough about Ethereum. Thanks!

**Comment by danlaine** [comment]
@gpersoon Is this still an issue for you?

**Comment by Determinant** [comment]
@danlaine Yeah I believe we fixed similar issues to this. @gpersoon do you still have the issue?

**Comment by gpersoon** [comment]
I can't reproduce the original scenario on a short term. For me it's not any issue anymore because i'm using the external links like:  https://api.avax-test.network/ext/bc/C/rpc
