### ISSUE TITLE
High CPU usage on MacOS 10

### ISSUE THREAD

**Issue by gholadr** [ava-labs/avalanchego#299]
**Describe the bug**
running gecko client on my MacBook Air (Retina, 13-inch, 2018) results in high CPU usage overtime. 
Note the issue seems to happen when the client fetches vertices 

**To Reproduce**
Install mac binary 0.5.7 and run ./ava in terminal. Watch CPU usage steadily climb in the Activity monitor

**Expected behavior**
a low CPU usage.

**Screenshots**
<img width="671" alt="Screenshot 2020-07-20 at 5 22 12 PM" src="https://user-images.githubusercontent.com/4038613/87988026-9cf9f000-caad-11ea-9ec6-6fa5afc6e5e3.png">
<img width="1434" alt="Screenshot 2020-07-20 at 5 20 49 PM" src="https://user-images.githubusercontent.com/4038613/87988033-a2573a80-caad-11ea-9277-721143fc6f83.png">

Also attaching a sample of the ava process (.txt file):
[Sample of ava.txt](https://github.com/ava-labs/gecko/files/4950123/Sample.of.ava.txt)

**Operating System**
MacOS Catalina
Mem 8 GB 2133 MHz LPDDR3
Processor 1.6 GHz Dual-Core Intel Core i5

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by mbehrsf** [comment]
High CPU usage during bootstrapping is normal. You need to wait a few hours until the bootstrapping process is done, then your CPU usage should go down.

**Comment by danlaine** [comment]
Closing due to age. @gholadr Thanks for reporting and let us know if you have any issues going forward.
