### ISSUE TITLE
Node bootstrap failed

### ISSUE THREAD

**Issue by Sir-Deon** [ava-labs/avalanchego#3006]
**Describe the bug**
The node is unable to bootstrap

**To Reproduce**
I ran this command
"sudo docker run --rm --network host  -ti -d -p 9650:9650 --name=avalancheNode avaplatform/avalanchego:18324b4a /avalanchego/build/avalanchego"

**Logs**
![Screenshot 2024-05-09 at 14 20 32](https://github.com/ava-labs/avalanchego/assets/57288805/79385fe2-8ca2-4a74-92e1-73982541c461)

**Operating System**
Ubuntu

**Comment by StephenButtolph** [comment]
`avaplatform/avalanchego:18324b4a` is not a supported release. The minimum version allowed on mainnet is `v1.11.0`.

```sh
sudo docker run --rm --network host -ti -d -p 9650:9650 --name=avalancheNode avaplatform/avalanchego:v1.11.5 /avalanchego/build/avalanchego
```
Seems to work as expected.
