### ISSUE TITLE
Feature Request: Golang client for Gecko's API endpoints

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/avalanchego#303]
Currently there is no golang implementation to interact with gecko's health, admin, info, etc. endpoints as well as the VM endpoints.

We should implement a golang interface for querying all of gecko's API endpoints alongside their definitions within gecko.

**Comment by danlaine** [comment]
Can you elaborate on this a little bit @aaronbuchwald? By `golang implementation to interact with gecko's health, admin, info, etc. endpoints` do you mean a Go implementation of a CLI?

**Comment by adasari** [comment]
@aaronbuchwald could you elaborate the the problem it solves ? avalance.js is hitting gecko endpoints. it is a client of gecko apis.

**Comment by aaronbuchwald** [comment]
@adasari this feature request is simply to add support for golang.
