### ISSUE TITLE
Unusual disk usage when bootstrapping from scratch with v1.11.6

### ISSUE THREAD

**Issue by roonodz** [ava-labs/avalanchego#3060]
**Describe the bug**
I'm observing erratic disk usage while bootstrapping from scratch using the latest v1.11.6. The configuration file is provided below, and state-sync is enabled.

The last time I performed this operation, it completed in less than 48 hours. The attached screen captures show the disk usage differences between v1.11.5 and v1.11.6.

Notably, the configuration and server specifications are identical for both runs, with the only variable being the avalanchego version. The server specs are as follows:
- 16 vCPU cores
- 32GB RAM
- 400GiB SSD NVMe
- location: France

Please see the screen captures and configuration file below for further details.

**To Reproduce**
Start a new instance with an empty database with the following C-Chain configuration:
```json
{
    "state-sync-enabled": true
}
```

**Expected behavior**

Reduced synchronization time and, more importantly, lower disk usage. As shown in the screenshot, there was a spike exceeding 80%.
This issue might be related to a Core-ETH bug that I've already reported. Here is the fix: https://github.com/ava-labs/coreth/pull/565

**Screenshots**
Here is a screenshot of the disk usage from a bootstrap I performed two weeks ago using v1.11.5:
![avalanchego-v1 11 5](https://github.com/ava-labs/avalanchego/assets/135046224/425c6fe9-f5fe-42a4-8ebf-84f4eebf98b2)

Here is a screenshot of the disk usage from the current bootstrap with the v1.11.6:
![avalanchego-v1 11 6](https://github.com/ava-labs/avalanchego/assets/135046224/a22a77f1-9300-479a-94d9-254aac121e2b)

**Logs**
Please find attached the log file.

**Metrics**
Please find attached the metrics.log

**Operating System**
Ubuntu 22.04 LTS

**To best protect the Avalanche community security bugs should be reported in accordance to our [Security Policy](../security/policy)**
[metrics.log](https://github.com/ava-labs/avalanchego/files/15501523/metrics.log)

**Comment by StephenButtolph** [comment]
@roonodz I see that you said `Please find attached the log file.` but I don't actually see a log file, did you mean to attach one?

**Comment by roonodz** [comment]
Please find attached the log file. Apologies for the oversight, I forgot to include it earlier.
[avalanchego.log](https://github.com/ava-labs/avalanchego/files/15501658/avalanchego.log)

**Comment by StephenButtolph** [comment]
The linked PR seems to have addressed the the performance regression during my testing... But if any additional issues come up with the syncing flow (in either `v1.11.7` or `master` after the linked PR was merged) please re-open this issue or make a new issue. Thanks for all the details!
