### ISSUE TITLE
High memory usage on Raspberry Pi4 8GB 

### ISSUE THREAD

**Issue by tolon** [ava-labs/avalanchego#307]
**Describe the bug**

High memory usage on Raspberry Pi4 8GB 

The gecko 0.5.7 version I compiled on Raspberry Pi 4 / Ubuntu 20.04 uses high ram.

**Expected behavior**

Using up to 4 GB of ram

**Operating System**
Ubuntu 20.04 Server Raspberry V.   On Docker  19.03.12

![386bJHTkqk](https://user-images.githubusercontent.com/1315633/88985062-15e01f80-d2d8-11ea-8173-f760122d7699.png)

![8mHMuCdCpy](https://user-images.githubusercontent.com/1315633/88985099-255f6880-d2d8-11ea-8e9e-761e60a1e4cb.png)

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by jpop32** [comment]
Same here. RasPi4 with 8GB. Some two hours into bootstrapping (without ever getting to 'fetched X vertices part'), memory shoots up considerably:

<img width="463" alt="Annotation 2020-08-01 211746" src="https://user-images.githubusercontent.com/6398640/89108879-aa639280-d43c-11ea-9a0a-052ec3e5ff26.png">

Then it starts to eat up swap space, and the whole computer becomes unusable so I have to stop the node.

Here's the complete log output:
[gecko.out.txt](https://github.com/ava-labs/gecko/files/5011130/gecko.out.txt)

It might be interesting to note that, as far as I can tell, this started happening once I updated to the latest commit on the repo (did a git pull and rebuilt). Haven't noticed that behavior on the official 0.5.7 version (commit tagged with 0.5.7).

**Comment by jpop32** [comment]
Tried bootstrapping again, ended up with runaway memory consumption again, two hours into the process. I am currently unable to run the node.

Attached are the profiles and the output.

[profiles.zip](https://github.com/ava-labs/gecko/files/5011314/profiles.zip)

**Comment by tolon** [comment]
Something interesting happened
When I run the node again the next day, it continued using 1 GB of ram. I think this problem happens when the node first runs, similar problem happened in windows client .

**Comment by danlaine** [comment]
@tolon Have you had this issue on 0.8.0?

**Comment by danlaine** [comment]
Closing this. Thanks for reporting and let us know if you have this issue in the future.
