### ISSUE TITLE
Running custom network leads to “subnets not bootstrapped” error

### ISSUE THREAD

**Issue by ku9nov** [ava-labs/avalanchego#3164]
**Describe the bug**
Hello AvalancheGo team,

We want to try deploying custom the "Fuji" network on our test servers, but we are experiencing a really strange behavior. After changing the bootstrap files and deploying this app to 5 servers, the subnets never bootstrap. It's important to note that it seems to work in version v1.10.0 (health check is success), but none of the higher versions work. The logs in the current AvalancheGo version do not contain any errors.

Health check result (latest code, master branch):
```
{
  "jsonrpc": "2.0",
  "result": {
    "checks": {
      "C": {
        "message": {
          "engine": {
            "consensus": {},
            "vm": null
          },
          "networking": {
            "percentConnected": 1
          }
        },
        "timestamp": "2024-07-02T13:52:49.735782692Z",
        "duration": 3967
      },
      "P": {
        "message": {
          "engine": {
            "consensus": {},
            "vm": null
          },
          "networking": {
            "percentConnected": 1
          }
        },
        "timestamp": "2024-07-02T13:52:49.735777223Z",
        "duration": 12651
      },
      "X": {
        "message": {
          "engine": {
            "consensus": {},
            "vm": null
          },
          "networking": {
            "percentConnected": 1
          }
        },
        "timestamp": "2024-07-02T13:52:49.735783865Z",
        "duration": 5303
      },
      "bootstrapped": {
        "message": [
          "11111111111111111111111111111111LpoYY"
        ],
        "error": "subnets not bootstrapped",
        "timestamp": "2024-07-02T13:52:49.73578457Z",
        "duration": 646,
        "contiguousFailures": 2,
        "timeOfFirstFailure": "2024-07-02T13:52:19.735349444Z"
      },
      "database": {
        "timestamp": "2024-07-02T13:52:49.735756495Z",
        "duration": 9998
      },
      "diskspace": {
        "message": {
          "availableDiskBytes": 43942944768
        },
        "timestamp": "2024-07-02T13:52:49.735763242Z",
        "duration": 3384
      },
      "network": {
        "message": {
          "connectedPeers": 4,
          "sendFailRate": 0,
          "timeSinceLastMsgReceived": "735.753932ms",
          "timeSinceLastMsgSent": "1.735753932s"
        },
        "timestamp": "2024-07-02T13:52:49.735758946Z",
        "duration": 9173
      },
      "router": {
        "message": {
          "longestRunningRequest": "952.377331ms",
          "outstandingRequests": 1
        },
        "timestamp": "2024-07-02T13:52:49.735776707Z",
        "duration": 3255
      }
    },
    "healthy": false
  },
  "id": 1
}
```

**To Reproduce**
We are changing `genesis/bootstrappers.json` for the Fuji network with our new 5 node-IDs and public IPs.

In `genesis/checkpoints.json`, the Fuji checkpoint was changed to this:
```
"fuji": {

}
```
We also tried using this configuration but had the same result:
```
"fuji": {
    "11111111111111111111111111111111LpoYY": [
    ],
    "2JVSBoinj9C2J33VntvzYtVJNZdN2NKiwwKjcumHUWEb5DbBrm": [
    ],
    "yH8D7ThNJkxmtkuv2jgBa4P1Rn3Qpr4pPr7QYNfcdoS6k6HWp": [
    ]
}
```
In `genesis/genesis_fuji.json`, we changed `startTime` to `1719497203` and updated `initialStakers` to our 5 nodes.

In `genesis/validators.json`, we changed the Fuji validators to our 5 nodes.

The last change was in `version/constants.go`:
```
ApricotPhase4MinPChainHeight = map[uint32]uint64{
    constants.MainnetID: 0,
    constants.FujiID:    0,
}
```
**Expected behavior**
Subnets is bootstraped.

**Logs**
Logs [here](https://gist.github.com/ku9nov/5143507da496093bfbd8ec1bdf50bd91#file-ava-logs) (latest code, master branch)

**Operating System**
Ubuntu 22

**Comment by StephenButtolph** [comment]
These files are part of the compiled binary, they are not configurations. While making changes to the codebase is allowed (the license is very permissive), I don't think we're going to be able to help debug and support external changes to the codebase.

That being said, if the desire is to run a test network outside of Fuji, either the `local` network configuration or a custom network can be deployed. If running a custom network, the `--genesis-file` or `--genesis-file-content` flags can be used to specify a custom genesis.
