### ISSUE TITLE
Local network initial stake period almost passed

### ISSUE THREAD

**Issue by leopaul36** [ava-labs/avalanchego#3223]
**Context and scope**
https://github.com/ava-labs/avalanchego/blob/master/genesis/genesis_local.json#L41
```
"startTime": 1690862400,
"initialStakeDuration": 31536000,
```

1690862400 + 31536000 = 1722398400, 31/07/2024 06:00:00. Past this date, the local network won't be working properly.

**Discussion and alternatives**
Bump `startTime` to a closer date.

**Comment by leopaul36** [comment]
That was fast! :dash: Thanks @ceyonur

**Comment by ceyonur** [comment]
I also encountered this today, was about to push it :D
