### ISSUE TITLE
Fixed Cap Asset balance and send

### ISSUE THREAD

**Issue by HugeRoo** [ava-labs/avalanchego#324]
User can create and send a newly created Fixed Cap Asset to an address. The asset appears against the address on the Explorer. However, getBalance for the Asset via Terminal will not return a balance for the asset. 

The asset also cannot be sent to another address due to no balance. 

Note: the node is bootstrapped and getBalance for AVAX will return a balance.

OS: Ubuntu 20.04

Assets were created and sent to myself. I can see the Asset on the Explorer: https://explorer.avax.network/address/X-everest1du2pp8z5qh2u2wyhmqu7am68rpemeufk5mr44c 

getBalance via the terminal does not return a balance for the asset

curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"avm.getBalance",
    "params" :{
        "address":"X-everest1du2pp8z5qh2u2wyhmqu7am68rpemeufk5mr44c",
        "assetID"  :"2quRTmhcevcUhiMX8As42Y5wrapet4W2qxhhtQibWGM6AtpPrv"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
                        {"jsonrpc":"2.0","result":{"balance":"0","utxoIDs":[]},"id":1} 

Steps to recreate via Tutorial at https://docs.avax.network/v1.0/en/tutorials/fixed-cap-asset/

When creating a new asset and sending it to a web wallet, the asset will be visible, but attempting to send an asset from the web wallet will fail.

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
Closing for age
