### ISSUE TITLE
High CPU usage if NAT traversal fails

### ISSUE THREAD

**Issue by jpop32** [ava-labs/avalanchego#335]
**Describe the bug**
When NAT traversal fails, indicated in the log as
`/main/main.go#83: NAT traversal has failed. The node will be able to connect to less nodes.`
CPU usage is very high (maxing out all 4 cores on my node).
<img width="764" alt="Annotation 2020-08-26 235744" src="https://user-images.githubusercontent.com/6398640/91361373-6f187180-e7f8-11ea-9e63-85c8ac169aa4.png">

When UPNP manages to get the external IP and the log shows:
`INFO [08-26|19:29:20] /nat/nat.go#94: Mapped Protocol TCP Internal 9651 External 9651.`
`INFO [08-26|19:29:20] /nat/nat.go#94: Mapped Protocol TCP Internal 9650 External 9650.`
CPU usage remains low, on the order of 10%.

I couldn't determine the reason UPNP fails, but it mostly fails (9 out of 10 times, I'd say). To prove NAT traversal is the problem, I looked up my external IP, and entered it as --public-ip command line switch. Log shows:
`/main/main.go#79: NAT traversal has failed. Unless the node is connected directly to a public network, the node will be able to connect to less
nodes.`
The CPU usage stays low.
<img width="742" alt="Annotation 2020-08-27 000417" src="https://user-images.githubusercontent.com/6398640/91361594-f1a13100-e7f8-11ea-91fa-5cef50cf604a.png">

**To Reproduce**
Start the node, if NAT traversal fails, CPU usage is high.

**Expected behavior**
Failure to map external IP should not cause high CPU usage.

**Operating System**
Running Ubuntu Server 20.04, on Raspberry Pi4, arm64 arch. Gecko built from source (go 1.14.4), version 0.6.4.
Node has a static IP, connected over WiFi.
Router is D-Link (Model Name: DIR-842, Hardware Version: B1, Firmware Version: 2.02), with UPNP enabled.

**Additional context**
CPU profile taken while CPU usage was high:
[cpu.zip](https://github.com/ava-labs/gecko/files/5132935/cpu.zip)

Also, possibly indicative of a problem, when the CPU usage is high, network traffic is also much higher:
<img width="417" alt="Annotation 2020-08-27 000337" src="https://user-images.githubusercontent.com/6398640/91361805-5d839980-e7f9-11ea-9c2a-10d154619ef8.png">
~400kb with UPNP failed, ~40KB when UPNP works, or I enter the IP manually.

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
Ohhhh this is really interesting, thanks.

Can you run both scenarios for 10 minutes each and at the end of the 10 minutes, get the metrics by doing:
```
curl --location --request POST 'http://localhost:9650/ext/metrics' \
--data-raw ''
```

And post both here? That would be super helpful. Thanks as always!

**Comment by StephenButtolph** [comment]
Interestingly enough, it seems that the CPU time is coming from the p2p networking socket. So I wonder what could cause the nat package to cause the networking socket to do a lot of work.

**Comment by jpop32** [comment]
Hm. tried to recreate the situation today, and could not. Restarted the client a dozen times and each time NAT traversal succeeded. To provoke the bug, tried turning off UPNP on the router - as expected, NAT traversal failed, but it did not result in high CPU usage. I suspect that it's a problem with my crappy D-Link router, because I noticed a situation when it did start up correctly, but eventually the log started filling with:
```
ERROR[08-26|19:44:20] /nat/nat.go#116: Renewing port mapping from external port 9650 to internal port 9650 failed with goupnp: error performing SOAP HTT
P request: Post "http://192.168.0.1:65530/ctl/IPConn": read tcp 192.168.0.12:55432->192.168.0.1:65530: read: connection reset by peer
ERROR[08-26|19:44:20] /nat/nat.go#116: Renewing port mapping from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTT
P request: Post "http://192.168.0.1:65530/ctl/IPConn": EOF
ERROR[08-26|19:59:20] /nat/nat.go#116: Renewing port mapping from external port 9650 to internal port 9650 failed with goupnp: error performing SOAP HTT
P request: Post "http://192.168.0.1:65530/ctl/IPConn": dial tcp 192.168.0.1:65530: connect: connection refused
ERROR[08-26|19:59:20] /nat/nat.go#116: Renewing port mapping from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTT
P request: Post "http://192.168.0.1:65530/ctl/IPConn": dial tcp 192.168.0.1:65530: connect: connection refused
E
```
And after that, when I restarted the node, NAT traversal failed, and high CPU usage bug manifested. So it looks like my router is acting up and messing the UPNP. Still, it would be nice if gecko handled it gracefully. :-)

Will keep trying to reproduce the bug and capture the metrics (unfortunately, away for most of the weekend).

**Comment by jpop32** [comment]
And here it is, this morning the same situation, first the router started refusing connections:
```
ERROR[08-28|00:25:05] /nat/nat.go#116: Renewing port mapping from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTT
P request: Post "http://192.168.0.1:65530/ctl/IPConn": EOF
ERROR[08-28|00:25:05] /nat/nat.go#116: Renewing port mapping from external port 9650 to internal port 9650 failed with goupnp: error performing SOAP HTT
P request: Post "http://192.168.0.1:65530/ctl/IPConn": read tcp 192.168.0.12:54868->192.168.0.1:65530: read: connection reset by peer
ERROR[08-28|00:40:05] /nat/nat.go#116: Renewing port mapping from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTT
P request: Post "http://192.168.0.1:65530/ctl/IPConn": dial tcp 192.168.0.1:65530: connect: connection refused
ERROR[08-28|00:40:05] /nat/nat.go#116: Renewing port mapping from external port 9650 to internal port 9650 failed with goupnp: error performing SOAP HTT
P request: Post "http://192.168.0.1:65530/ctl/IPConn": dial tcp 192.168.0.1:65530: connect: connection refused
```
And then when I restarted the node, high CPU usage, with much higher network traffic.

Here are the metric outputs:
[metrics-nat-ok.txt](https://github.com/ava-labs/gecko/files/5140192/metrics-nat-ok.txt)
[metrics-nat-failed.txt](https://github.com/ava-labs/gecko/files/5140193/metrics-nat-failed.txt)

**Comment by quasarati** [comment]
I see the same thing. My setup:
router -> Synology NAS -> Docker container

If have port 9651 forwarded from router to the NAS
Port 9651 is open to the world on the NAS firewall
port 9651 is mapped from the NAS to the docker container

I always get the NAT traversal warning:
WARN [09-27|10:35:57] main/main.go#96: NAT traversal has failed. The node will be able to connect to less nodes.            
INFO [09-27|10:35:57] node/node.go#736: Node version is: avalanche/1.0.0                                                    

CPU is slowly going throug the roof since mainnet launch. Restart of the client only helps for a short while.
I also see a buildup of network traffic corresponding to cpu usage.

I am a bit worried my client is  about to die as it is hitting 100% CPU soon.

In the picture, ignore the spikes as that is other stuff on the NAS. The pattern should be clear to see.

![cpu](https://user-images.githubusercontent.com/69383057/94360716-e8cda480-00af-11eb-956b-e30249a66bba.png)
![network](https://user-images.githubusercontent.com/69383057/94360718-eb2ffe80-00af-11eb-817c-d0c977c22422.png)
![network1](https://user-images.githubusercontent.com/69383057/94360743-19add980-00b0-11eb-8d7c-d358cbdc5438.png)
![network2](https://user-images.githubusercontent.com/69383057/94360745-1c103380-00b0-11eb-87d2-0d9955a92d47.png)
![network3](https://user-images.githubusercontent.com/69383057/94360746-1e728d80-00b0-11eb-8aaa-15b9ddf71dbd.png)

**Comment by danlaine** [comment]
@quasarati You shouldn't start with `--public-ip=`
You should either omit this argument or specify your public IP

**Comment by quasarati** [comment]
Oh, yes. I did start with --public-ip=<external IP of router>. I removed the IP for privacy

**Comment by quasarati** [comment]
github is filtering out some text.  I typed: --public-ip=*smaller than*public router ip*greater than*

**Comment by danlaine** [comment]
@quasarati I'd like to know what messages are getting sent to/from your node to figure out what's going on.
Can you please set up node monitoring (https://docs.avax.network/v1.0/en/tutorials/node-monitoring/) and look at the dashboards to see what kind of messages are being sent? Or share screenshots of the Grafana dashboards

**Comment by quasarati** [comment]
In hindsight my observation had nothing to do with NAT traversal as it was set up correctly and as I learned it doesn't even run when --public-ip="external ip" is used. I got confused by the warning.

High CPU for me was caused by this issue (corrupt database):
https://github.com/ava-labs/avalanchego/issues/470

Whether

**Comment by tasinco** [comment]
same issue as: https://github.com/ava-labs/avalanchego/issues/470
