### ISSUE TITLE
Build fails on Go v1.23(.1)

### ISSUE THREAD

**Issue by ThatOneCalculator** [ava-labs/avalanchego#3393]
**Describe the bug**
Build following the [docs]() fails

**To Reproduce**
Steps to reproduce the behavior.
```
cd $GOPATH/src/github.com/ava-labs/avalanchego
./scripts/build.sh
Downloading dependencies...
Building AvalancheGo...
# command-line-arguments
link: github.com/fjl/memsize: invalid reference to runtime.stopTheWorld
```

**Expected behavior**
Build succeeds 

**Operating System**
Arch Linux x86_64

**Additional info**
May be related to https://github.com/ethereum/go-ethereum/issues/30100 / https://github.com/fjl/memsize/issues/4 / https://github.com/fjl/memsize/issues/5

**Comment by yacovm** [comment]
should be fixed in https://github.com/ava-labs/avalanchego/pull/3399

**Comment by ThatOneCalculator** [comment]
Never got the notification for this fix -- thank you!
