### ISSUE TITLE
XSVM incompatible with Avalanche CLI

### ISSUE THREAD

**Issue by ivansukach** [ava-labs/avalanchego#3484]
**Describe the bug**
Avalanche CLI require the genesis in JSON format and the structure of genesis should be like Subnet EVM genesis struct. XSVM is able to generate and process genesis is binary or hex format.
So, the error occurs: "invalid character '\x00' looking for begging of value.

**To Reproduce**
Go through the steps of XSVM README.
You will retrieve the error during creation of subnet configuration:

Create a genesis file
xsvm chain genesis --encoding binary > xsvm.genesis
Create Subnet A and Subnet B
avalanche subnet create subnetA --custom --genesis <path_to_genesis> --vm <path_to_vm_binary> 

**Expected behavior**
Compatibility between latest XSVM and latest Avalanche CLI.

**Screenshots**
![image](https://github.com/user-attachments/assets/e081c813-c93c-4e2d-ac81-5e98d49c36df)

**Operating System**
Linux

**Comment by StephenButtolph** [comment]
This seems like an `avalanche-cli` issue - not an XSVM issue. Avalanche does not require or expect genesis bytes to be encoded in json format.

The P-chain and X-chain genesis bytes are also not formatted as json.
