### ISSUE TITLE
please update go-ethereum lib

### ISSUE THREAD

**Issue by godlovericea** [ava-labs/avalanchego#3503]
go mod tidy
go: finding module for package github.com/ava-labs/avalanchego/wallet/subnet/primary
go: finding module for package github.com/ava-labs/avalanchego/ids
go: finding module for package github.com/ava-labs/avalanchego/genesis
go: finding module for package github.com/ava-labs/avalanchego/vms/secp256k1fx
go: found github.com/ava-labs/avalanchego/genesis in github.com/ava-labs/avalanchego v1.11.12
go: found github.com/ava-labs/avalanchego/ids in github.com/ava-labs/avalanchego v1.11.12
go: found github.com/ava-labs/avalanchego/vms/secp256k1fx in github.com/ava-labs/avalanchego v1.11.12
go: found github.com/ava-labs/avalanchego/wallet/subnet/primary in github.com/ava-labs/avalanchego v1.11.12
go: finding module for package github.com/ethereum/go-ethereum/crypto/bls12381
go: kerying_learn/address imports
        github.com/ava-labs/avalanchego/genesis tested by
        github.com/ava-labs/avalanchego/genesis.test imports
        github.com/ava-labs/coreth/core imports
        github.com/ava-labs/coreth/core/vm imports
        github.com/ethereum/go-ethereum/crypto/bls12381: module github.com/ethereum/go-ethereum@latest found (v1.14.11), but does not contain package github.com/ethereum/go-ethereum/crypto/bls12381

**Comment by StephenButtolph** [comment]
Updating geth is performed in https://github.com/ava-labs/coreth. Feel free to re-open this request there... But updating geth is an on-going maintenance task.
