### ISSUE TITLE
Insufficient Funds Transaction Failure (Boundary Condition)

### ISSUE THREAD

**Issue by dbrisinda** [ava-labs/avalanchego#352]
**Describe the bug**
When making a transaction on the X-chain and P-chain with the full amount in my wallet, I get the following errors. This transaction/error on the X-chain:

curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"avm.exportAVAX",
    "params" :{
        "username": "XXX",
        "password": "XXX",
        "to":"P-everest1wk4h4eyjkk0hq6j360ust9zpxtgj3pgw25jht0",
        "amount": 120000000
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X

RESULT:
{"jsonrpc":"2.0","error":{"code":-32000,"message":"insufficient funds","data":null},"id":1}

And this transaction/error on the P-chain:

curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.addValidator",
    "params": {
        "username":"XXX",
        "password":"XXX",
        "nodeID":"NodeID-3mhpr7e1eEKMfQP8Zi325RCchcAP5XUXj",
        "rewardAddress":"P-everest1wk4h4eyjkk0hq6j360ust9zpxtgj3pgw25jht0",
        "startTime":'$(gdate --date="15 minutes" +%s)',
        "endTime":1629032852,
        "stakeAmount":118000000,
        "delegationFeeRate":0
    },
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/P

RESULT:
{"jsonrpc":"2.0","error":{"code":-32000,"message":"couldn't create tx: couldn't generate tx inputs/outputs: provided keys have balance (unlocked, locked) (1000000, 117000000) but need (1000000, 118000000)","data":null},"id":1}

(Incidentally, the above error reporting is a huge improvement for the P-chain. As now I see that I need to validate with less funds since the transaction fee is deducted from the remaining balance.)

This may be problematic in the future, as the transaction fee will most likely change over time. Ideally, the user should not have to know the exact transaction fee before issuing a transaction (s/he knows it's going to be small, just not exactly how small). 

Instead, it might be better to automatically deduct the transaction fee from the amount specified in all transaction requests. That way the full amount in the X-chain or P-chain wallet can be specified, and any transaction fee is automatically deducted from that amount.

Alternatively, it might be useful to have an option for the user to specify within the transaction, if the transaction fee should be deducted from the transaction amount (default), or from the wallet balance.

**To Reproduce**
Make any transaction on the X-chain or P-chain.

**Expected behavior**
The full amount of funds in the X-chain wallet and/or P-chain wallet can be specified when making a transaction, and the transaction fee is automatically deducted from the amount specified.

**Screenshots**
n/a

**Operating System**
macOS 10.15.6

**Additional context**
n/a

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by StephenButtolph** [comment]
Thanks for putting this together!

Is this a suggested improvement to change the meaning of `stakeAmount` in `platform.addValidator` (and probably other calls) to include the fee for the transaction?

I think tooling for projects like Ethereum typically try to separate the amount to send with the fee used to send it (e.g. https://eth.wiki/json-rpc/API#eth_sendtransaction). This ensures that people don't feel like they lost money unexpectedly. Once we introduce dynamic fees I think it makes sense to add to the API an optional fee parameter.

**Comment by dbrisinda** [comment]
No worries.

Yes, it's a suggested improvement for all transactions that involve fees, allowing the user to specify where they want the transaction fee deducted: 1) wallet balance or 2) transaction amount. Most banks provide this option for wire transfers, and most exchanges give you the option to specify how the transaction fee is to be deducted. Also PayPal provides a version of  this when you send funds.

One of the annoyances with sending funds on many blockchains is that when you wish to make a transaction that transfers your entire wallet balance, you don't know how much of a fee to supply, so you end up having to leave an arbitrary amount much larger than the actual transaction fee in your wallet so that the transaction succeeds.

I would like to say something like: "Transfer ALL funds so that a zero balance remains, and deduct the appropriate transaction fee from the sent amount."

What you said about separating the fee from transaction amount by default makes sense, so the user doesn't feel like they lost money.

So yes, an optional parameter that specifies where to deduct the fee from: transaction amount, or wallet balance (default) makes good sense.

**Comment by danlaine** [comment]
There are now `from` and `changeAddr` fields in send,
