### ISSUE TITLE
Avalanchego MAC version 1.11.12 errors with "bad CPU type in executable" 

### ISSUE THREAD

**Issue by tzmmtz** [ava-labs/avalanchego#3534]
My node ended last Monday on my Mac so I do the usual and check for operating system software updates. In this case Mac Sonoma to 14.7.1 from 14.6. Restart for a new validation cycle. I downloaded the latest version 1.11.12 and I get "bad CPU type in executable". I download the earlier version 1.11.11 and it works fine. What’s up with 1.11.12? By the way, no notification like usual that a new version was uploaded since my last avalanchego in July.

avalanchego % ./build/avalanchego --public-ip=xx.xxx.xxx.xxx
zsh: bad CPU type in executable: ./build/avalanchego

With version 1.11.11 it works fine...
[11-09|09:44:52.123] INFO node/node.go:143 initializing node {"version": "avalanchego/1.11.11", "nodeID......

Mac Pro Late 2013 3.5 GHz 6-Core Intel Xeon E5, AMD FirePro D500 3 GB, 48GB 1866 MHz DDR3.

**Comment by yacovm** [comment]
Try to do `go get github.com/supranational/blst@v0.3.13` it should solve it. 

You need to upgrade the BLST dependency like [in this pull request](https://github.com/ava-labs/avalanchego/pull/3506) which didn't get to 1.11.12.

**Comment by yacovm** [comment]
Try to do `go get github.com/supranational/blst@v0.3.13` and then build it via `./scripts/build_avalanche.sh` it should be able to build it. 

You need to upgrade the BLST dependency like [in this pull request](https://github.com/ava-labs/avalanchego/pull/3506) which didn't get to 1.11.12.

**Comment by yacovm** [comment]
The version of BLST that is in 1.11.12 is not compatible with Mac 14.7, so you need to upgrade BLST and then build the binary yourself.

Try to do `go get github.com/supranational/blst@v0.3.13` and then build it via `./scripts/build_avalanche.sh` it should be able to build it. 

You need to upgrade the BLST dependency like [in this pull request](https://github.com/ava-labs/avalanchego/pull/3506) which didn't get to 1.11.12.

**Comment by tzmmtz** [comment]
The problem, unless it has been resolved, /scripts doesn't work on Mac. I went back and forth with devs over the years and as of last year it wasn't supported on Mac. I don't know if that has changed.

**Comment by yacovm** [comment]
> The problem, unless it has been resolved, /scripts doesn't work on Mac. I went back and forth with devs over the years and as of last year it wasn't supported on Mac. I don't know if that has changed.

I'm not sure what you mean by `/scripts/` doesn't work on Mac, but I can confirm that at least the `build_avalanche.sh` script in the [scripts folder](https://github.com/ava-labs/avalanchego/tree/master/scripts) works on Mac.

**Comment by yacovm** [comment]
Are you sure you have git cloned the [repository](https://github.com/ava-labs/avalanchego/tree/v1.11.12) and are executing the go mod command when the local directory is the one containing the `go.mod` file? 

Maybe you want to hop on [discord](https://discord.com/invite/avax
) and ask there?

**Comment by tzmmtz** [comment]
Let me ask a simpler question. I can leave it at 1.11.11. Will there be a future version of avalanchego that will work with my Mac as is without having to do any of the above steps?

**Comment by yacovm** [comment]
Yeah there would be. The next version would work on your 14.7 Mac. 

But you can just solve it yourself now without waiting for a new version to come out, just do:

```
git clone git@github.com:ava-labs/avalanchego.git

cd avalanchego

git fetch origin

git checkout tags/v1.11.12 

go get github.com/supranational/blst@v0.3.13

./scripts/build_avalanche.sh
```

**Comment by tzmmtz** [comment]
Gave it a try but so many issues come back. First it wants Xcode. Ok downloaded that. Then it says avalanchego already exists and is not an empty directory. Move that out and Permission denied. Sudo that and you get "The authenticity of host 'github.com (140.82.113.4)' can't be established.......Are you sure you want to continue connecting (yes/no/[fingerprint]. I don't know what that means so not taking a chance and said no.

I'm twice your age guys. I don't have the knowledge and don't want to mess up my operating system and start from scratch. Did that once and was a nightmare to rebuild as the ./scripts didn't work on Mac.. Now days....I just want an avalanchego update that works. I'll wait for the next one.

Appreciate your efforts in assisting...

**Comment by yacovm** [comment]
i replied to your message on discord, feel free to ping me and i can walk you through step by step how to fix the issue.

**Comment by tzmmtz** [comment]
I can never message directly on Discord. Always bounces back with "Your message could not be delivered. This is usually because you don't share a server with the recipient or the recipient is only accepting direct messages from friends

**Comment by tzmmtz** [comment]
Quick question -

Previously you gave me the below instructions to fix the bad cpu warning I get when a new build comes out. It has worked fine until today when I tried to build for 1.13.1

Now I get this after step "go get ***@***.*** ***@***.***>” below.

It now says downgraded where it never said that before and the build script now doesn't work.

Thoughts?




***@***.*** test % git clone https://github.com/ava-labs/avalanchego.git
Cloning into 'avalanchego'...
remote: Enumerating objects: 200146, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 200146 (delta 6), reused 20 (delta 0), pack-reused 200090 (from 1
Receiving objects: 100% (200146/200146), 132.03 MiB | 50.73 MiB/s, done.
Resolving deltas: 100% (153899/153899), done.
***@***.*** test % cd /Users/remote/test/avalanchego                    
***@***.*** avalanchego % git fetch origin
***@***.*** avalanchego % git checkout tags/v1.13.1  
Note: switching to 'tags/v1.13.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 9d1f232b7 Update version to v1.13.1 (#3985)
***@***.*** avalanchego % go get ***@***.***
go: downgraded github.com/ava-labs/coreth v0.15.1-rc.0.0.20250530184801-28421010abae => v0.15.0
go: downgraded github.com/supranational/blst v0.3.14 => v0.3.13
***@***.*** avalanchego % ./scripts/build_avalanche.sh
zsh: no such file or directory: ./scripts/build_avalanche.sh
***@***.*** avalanchego % ./scripts/build_avalanche.sh

**Comment by yacovm** [comment]
Try to just cloning the repo, switching to the tags/v1.13.1 branch, and running `scripts/build.sh` without doing the `go get`

**Comment by tzmmtz** [comment]
Same error. “no such file or directory”

But if I change tags to the previous version of 1.13.0 the Build script works.

Thoughts?

Thanks.


Last login: Sun Jun 15 09:20:17 on ttys000
***@***.*** ~ % cd /Users/remote/test 
***@***.*** test % git clone https://github.com/ava-labs/avalanchego.git
Cloning into 'avalanchego'...
remote: Enumerating objects: 200146, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 200146 (delta 6), reused 20 (delta 0), pack-reused 200090 (from 1
Receiving objects: 100% (200146/200146), 132.02 MiB | 50.63 MiB/s, done.
Resolving deltas: 100% (153832/153832), done.
***@***.*** test % cd /Users/remote/test/avalanchego 
***@***.*** avalanchego % git checkout tags/v1.13.1 
Note: switching to 'tags/v1.13.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 9d1f232b7 Update version to v1.13.1 (#3985)
***@***.*** avalanchego % ./scripts/build_avalanche.sh
zsh: no such file or directory: ./scripts/build_avalanche.sh
***@***.*** avalanchego % git checkout tags/v1.13.0  
Previous HEAD position was 9d1f232b7 Update version to v1.13.1 (#3985)
HEAD is now at 65564a435 Update versions for v1.13.0 (#3810)
***@***.*** avalanchego % ./scripts/build_avalanche.sh
Building AvalancheGo...
***@***.*** avalanchego %

**Comment by yacovm** [comment]
Ping me on discord I'll help you

**Comment by tzmmtz** [comment]
Problem resolved. Yacovm was a big help. Unlike previous times using ./scripts/build_avalanche.sh this time I had to use scripts/build.sh and it worked and built avalanchego.
