### ISSUE TITLE
[Question] is Etna for mainnet  a hard fork ?

### ISSUE THREAD

**Issue by lcmmhcc** [ava-labs/avalanchego#3582]
hi, there
 the desccription  for this release says "Should Upgrade" , but "MUST Upgrade" as in Pre-release for fuji.

but [ACP-131](https://github.com/avalanche-foundation/ACPs/blob/main/ACPs/131-cancun-eips/README.md) Activate Cancun EIPs on C-Chain and Subnet-EVM chains  seems a hardfork.

i'm confused,  can somebody help ? 

Thanks a lot.

**Comment by aaronbuchwald** [comment]
Yes, it is a network upgrade. The description states that they should upgrade before the activation time, whereas patch versions (not mandatory) do not have a specific time included. Hope this clarifies that the upgrade is mandatory.

Will leave to @StephenButtolph on if he wants to change the wording as looking back at the past network upgrades, the language has consistently been "should upgrade before activation time".

**Comment by lcmmhcc** [comment]
got it. thanks again

---- Replied Message ----
| From | ***@***.***> |
| Date | 12/06/2024 23:16 |
| To | ava-labs/avalanchego ***@***.***> |
| Cc | lcmmhcc ***@***.***>,
Author ***@***.***> |
| Subject | Re: [ava-labs/avalanchego] [Question] is Etna for mainnet a hard fork ? (Issue #3582) |

Yes, it is a network upgrade. The description states that they should upgrade before the activation time, whereas patch versions (not mandatory) do not have a specific time included. Hope this clarifies that the upgrade is mandatory.

Will leave to @StephenButtolph on if he wants to change the wording as looking back at the past network upgrades, the language has consistently been "should upgrade before activation time".
