### ISSUE TITLE
I can't get data from X chain

### ISSUE THREAD

**Issue by yigitraphy** [ava-labs/avalanchego#3590]
We have a config file set up as follows: 
```
{
  "http-host": "0.0.0.0",
  "http-allowed-hosts": "*",
  "db-dir": "/avalanchego/data",
  "index-enabled": true,
  "index-transactions": true,
  "api-admin-enabled": true
}
```
We synced our node from scratch with this configuration, but the X-Chain indexer is not working. When we run the following query:
```
curl -k --request POST http://localhost:9650/ext/bc/X --header 'Content-Type: application/json' --data-raw '{
    "jsonrpc":"2.0",
    "id"     : 1,
    "method" :"avm.getAddressTxs",
    "params" :{
        "address":"X-avax19ee5luvp5ha2eelt55pet7j8yygfk35224wsyq",
        "assetID":"AVAX",                                         
        "pageSize":20
    }                
}'
```
We receive a null response: 
``` {"jsonrpc":"2.0","result":{"txIDs":null,"cursor":"0"},"id":1} ```
Despite following all the steps in the Avalanche documentation correctly and the query working fine on public nodes, the X-Chain indexer is not functioning on our private node.

**Comment by StephenButtolph** [comment]
`index-transactions` is an X-chain config, not a top level avalanchego config. From the [docs](https://docs.avax.network/nodes/chain-configs/x-chain):
> In order to specify a config for the X-Chain, a JSON config file should be placed at {chain-config-dir}/X/config.json.
> 
> For example if chain-config-dir has the default value which is $HOME/.avalanchego/configs/chains, then config.json can be placed at $HOME/.avalanchego/configs/chains/X/config.json.
> 
> This allows you to specify a config to be passed into the X-Chain. The default values for this config are:
> 
> ```
> {
>   "index-transactions": false,
>   "index-allow-incomplete": false,
>   "checksums-enabled": false
> }
> ```

**Comment by yigitraphy** [comment]
Thank you very much
