### ISSUE TITLE
Handle blockchains that are assigned to subnets with 0 validators

### ISSUE THREAD

**Issue by arikan** [ava-labs/avalanchego#362]
**Describe the bug**
There are blockchains assigned to subnets with 0 validators. There is no way to make a call to a blockchain when no one is running it.

**To Reproduce**
Go to [AVAX Explorer](https://explorer.avax.network/subnets?tab=blockchains) and look for subnet `ASXXLbDQcW3jYyAvbJv1zH3bjb3eo64cH23PJKWe9wH2L8D6m`

**Expected behavior**
P-chain should either auto delete these chains from its records (when the number of validators for the validating subnet is 0 or below a threshold), or auto-label them as "idle blockchain". 

**Screenshots**
<img width="894" alt="Screen Shot 2020-09-04 at 12 00 25 PM" src="https://user-images.githubusercontent.com/6969/92261545-94b41380-eea7-11ea-9d1b-019e0cf92d1f.png">

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by StephenButtolph** [comment]
I'm not sure that the P-chain really has anything to handle here, as the subnet owner could add validators to that subnet at a later point. Is the suggestion to have the explorer note that this subnet has no validators additionally to displaying the number of validators?
