### ISSUE TITLE
unexpected fund/asset moves between the X-Chain addresses

### ISSUE THREAD

**Issue by aktorun** [ava-labs/avalanchego#382]
**Describe the bug**
I have 3 X-Chain addresses, lets call them XC1, XC2, XC3
All of them have more than enough funds (AVAX) lets say 10M on each.
And I am trying to send 200K AVAX to specific P-Chain address.
What I observe is :
first it automatically sends 1M AVAX from XC3 to XC1
than it sends 200K AVAX from XC1 to mentioned P-Chain address.

**To Reproduce**
create 3 X-Chain addresses under the same user.
top-up enough AVAX to all 3 of them
try to send AVAX to a P-Chain address. (avm.exportAVAX -> platform.imortAVAX)
check the status of all 3 X-Chain addresses

**Expected behavior**
I was expecting there will be no need AVAX transfer between the X-Chain addresses since all of them have enough AVAX to cover the amount I am trying to send

**Screenshots**
![image](https://user-images.githubusercontent.com/35613099/92653602-44014800-f2f7-11ea-84f8-4a5adb1460ad.png)
[GitHub - unexpected fund transfer between X-Chain addresses.txt](https://github.com/ava-labs/gecko/files/5197944/GitHub.-.unexpected.fund.transfer.between.X-Chain.addresses.txt)

**Operating System**
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

**Additional context**

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by StephenButtolph** [comment]
Thanks for opening this! I'm going to change this from a bug report to a documentation/feature request.

When a transaction is generated that is attempting to move an amount less than the balance in a UTXO, a change UTXO is created. This UTXO is sent to _one_ of the addresses that the user owns. The address isn't guaranteed to be the same address used to spend the UTXO.

Specifically, XC3 seems to be the address that is used to consume the UTXOs first, while XC1 is the address that is being named for the change UTXO.

**Comment by aktorun** [comment]
Thanks for the explanation. Actually, happy to hear that it is not a bug :)
Though, it is not still clear to me why XC3 moves 1.000.0000.000 to XC1 while requested and transferred amount is only 200.000.000

**Comment by StephenButtolph** [comment]
The faucet drip size is currently 1 AVAX = 1,000,000,000 nAVAX. So I'm guessing that you used the faucet 4 times to set up the balance on XC3. This would mean that when sending funds from XC3 the amount spent is going to be a multiple of 1 AVAX with the remainder being sent to the change address.
