### ISSUE TITLE
Missing CORS Header on C-Chain RPC

### ISSUE THREAD

**Issue by mertgonul** [ava-labs/avalanchego#400]
**Describe the bug**
CORS error while accessing to C-Chain RPC

<img width="815" alt="CleanShot 2020-09-13 at 10 22 28@2x" src="https://user-images.githubusercontent.com/1537176/93012704-10e6df00-f5ab-11ea-80a0-5fc142be63d0.png">

**To Reproduce**
Send POST/GET req from any frontend framework 

**Expected behavior**
C-Chain RPC should include "Access-Control-Allow-Origin: *" in response

**Screenshots**
X-Chain RPC is including required CORS header and there is no problem to access it
![CleanShot 2020-09-13 at 10 12 30@2x](https://user-images.githubusercontent.com/1537176/93012619-80100380-f5aa-11ea-8d75-9de46ac1e76b.png)

C-Chain RPC is not including CORS header
<img width="600" alt="CleanShot 2020-09-13 at 10 11 53@2x" src="https://user-images.githubusercontent.com/1537176/93012644-aa61c100-f5aa-11ea-982e-04f524f02aea.png">

**Operating System**
Brave/Chrome/Firefox/Safari

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by kraikov** [comment]
This is a huge blocker for our team. Any ETA?
