### ISSUE TITLE
v0.5.7 & v0.8.3- API /ext/bc/C/rpc not available unless calling locally using 127.0.0.1

### ISSUE THREAD

**Issue by thearchitectt** [ava-labs/avalanchego#419]
**Describe the bug**
Can not call the EVM API /ext/bc/C/rpc from another node and only works internally on the node by using 127.0.0.1

Is there some sort of missing CLI flag to make this API public?

**To Reproduce**
This works
```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "web3_clientVersion",
    "params": [],
    "id": 1
}' -H 'Content-Type: application/json' \
   -H 'cache-control: no-cache' \
  127.0.0.1:9650/ext/bc/C/rpc

{"jsonrpc":"2.0","id":1,"result":"Athereum 1.0"}
```

This one doesn't work
```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "web3_clientVersion",
    "params": [],
    "id": 1
}' -H 'Content-Type: application/json' \
   -H 'cache-control: no-cache' \
  10.8.0.28:9650/ext/bc/C/rpc

404 Not Found
```

**Expected behavior**
Should return 
```
{"jsonrpc":"2.0","id":1,"result":"Athereum 1.0"}
```

**Operating System**
Ubuntu 18.04

**Additional context**
This functionality has worked in earlier versions

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
@thearchitectt 
Yup, you need to supply CLI `-http-host=` in order to access the node's APIs from an external machine.
See https://docs.avax.network/v1.0/en/references/command-line-interface

Closing this for now. If you have any problems feel free to re-open. Cheers.

**Comment by thearchitectt** [comment]
I've also built and tested this on `0.8.3` this morning and the same thing happens.

I specify `--http-host= ` as per the documentation, as I have had this error before on a previous earlier ticket using `0.5.3`.

**Comment by danlaine** [comment]
@thearchitectt Can you try donig `--http-host=[public IP of your machine]` ?

**Comment by thearchitectt** [comment]
Thank you for re-opening, adding the public IP throws this error and shuts down the node on `0.8.3`

```
FATAL[09-16|14:01:04] node/node.go#292: API server initialization failed with listen tcp <my_public_ip>:9650: bind: cannot assign requested address
INFO [09-16|14:01:04] node/node.go#788: shutting down the node
```

Running returns no ports mapped
```
sudo lsof -i:9650
```

**Comment by thearchitectt** [comment]
@danlaine  Ok so after some further debugging, it's not working through my DNS name or my public load balancer, these are both GCP managed and set up correctly. But it is working through the public IP address of my node? Previously this worked in `0.5.3`

**Comment by thearchitectt** [comment]
Seems to have started working now, maybe I had a dodgy node that's now working
