### ISSUE TITLE
Require API auth only on some endpoints

### ISSUE THREAD

**Issue by danlaine** [ava-labs/avalanchego#432]
Right now when a node is started with `--api-auth-required=true`, all API endpoints require an auth token.
This may be undesirable. We should allow node operators to specify specific endpoints to block/unblock.

**Comment by tbrunain** [comment]
I think adding a `--api-auth-disabled-endpoints` flag (not happy with the name but can't think of anything else atm), accepting a comma separated list of endpoints would be the best approach.
Am less fan of doing the opposite (only protect explicitly mentioned endpoints).


But then not sure if this list should be `--api-auth-disabled-endpoints=/ext/bc/X,ext/bc/C` or just `--api-auth-disabled-endpoints=C,X` , have to dig a bit in the code to see how it works .

Or is there another approach that would make more sense ?

From what I see it would require changes in `config.go` , `server.go` , `auth.go` and relevant tests. 

I can have a look at that tomorrow/this weekend.

**Comment by danlaine** [comment]
This was implemented (docs [here](https://docs.avax.network/build/avalanchego-apis/auth-api))
