### ISSUE TITLE
Make auth API return JSON RPC format

### ISSUE THREAD

**Issue by danlaine** [ava-labs/avalanchego#433]
Almost all API methods return a response that fulfills the JSON RPC 2.0 spec.

If `--api-ath-required=true` and you make an API call without prociding the auth token, you get a non-JSON RPC response (`auth token not provided` or  `token is invalid format`)

These (and all API calls) should also be returned in JSON RPC 2.0 format

See [here](https://docs.avax.network/build/avalanchego-apis/issuing-api-calls#json-rpc-formatted-apis) and [here](https://docs.avax.network/build/avalanchego-apis/auth-api) for more context

**Comment by kadir96** [comment]
I would like to work on this one :)

**Comment by danlaine** [comment]
Closed because this is addressed in #714.
Thanks again @kadir96!
