### ISSUE TITLE
Fatal Error at Startup of v0.8.4 (mainnet live)

### ISSUE THREAD

**Issue by dbrisinda** [ava-labs/avalanchego#437]
**Describe the bug**
Followed the instructions to install avalanchego on GitHub repo, building from scratch, and running gives a fatal error:
FATAL[09-21|20:44:08] node/node.go#185: Failed to connect to bootstrap nodes. Node shutting down...

**To Reproduce**
Run the node.

**Expected behavior**
Execution without fatal error.

**Screenshots**
INFO [09-21|20:43:52] nat/nat.go#94: Mapped Protocol TCP Internal 9651 External 9651.
INFO [09-21|20:43:52] node/node.go#734: Node version is: avalanche/0.8.4
INFO [09-21|20:43:52] node/node.go#379: Set node's ID to MN5iMsrspoUjYwPJhx8w39qQ2sraRYhQ2
INFO [09-21|20:43:52] node/node.go#441: Initializing API server
INFO [09-21|20:43:53] node/node.go#565: initializing keystore
INFO [09-21|20:43:53] node/node.go#576: initializing keystore API
INFO [09-21|20:43:53] api/server.go#152: adding route /ext/keystore
INFO [09-21|20:43:53] node/node.go#592: initializing metrics API
INFO [09-21|20:43:53] api/server.go#152: adding route /ext/metrics
INFO [09-21|20:43:53] node/node.go#557: initializing SharedMemory
INFO [09-21|20:43:53] api/server.go#152: adding route /ext/vm/rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT
INFO [09-21|20:43:53] api/server.go#152: adding route /ext/vm/jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq
INFO [09-21|20:43:53] node/node.go#608: skipping admin API initialization because it has been disabled
INFO [09-21|20:43:53] node/node.go#624: initializing info API
INFO [09-21|20:43:53] api/server.go#152: adding route /ext/info
INFO [09-21|20:43:53] node/node.go#648: initializing Health API
INFO [09-21|20:43:53] api/server.go#152: adding route /ext/health
INFO [09-21|20:43:53] node/node.go#686: skipping ipc API initializaion because it has been disabled
INFO [09-21|20:43:53] node/node.go#699: initializing aliases
INFO [09-21|20:43:53] node/node.go#425: initializing chains
INFO [09-21|20:43:53] chains/manager.go#188: creating chain:
    ID: 11111111111111111111111111111111LpoYY
    VMID:rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT
INFO [09-21|20:43:53] <P Chain> vms/platformvm/vm.go#369: Initializing last accepted block as HHAZsK9nCVqMBr9ZT1u4tcJoV4KxUQxbtaGWxZj5Hi2UkrgUF
INFO [09-21|20:43:53] <P Chain> snow/engine/snowman/transitive.go#58: initializing consensus engine
INFO [09-21|20:43:53] api/server.go#136: adding route /ext/bc/11111111111111111111111111111111LpoYY
INFO [09-21|20:43:53] api/server.go#82: HTTP API server listening on "127.0.0.1:9650"
FATAL[09-21|20:44:08] node/node.go#185: Failed to connect to bootstrap nodes. Node shutting down...
INFO [09-21|20:44:08] node/node.go#808: shutting down the node
INFO [09-21|20:44:08] <P Chain> snow/engine/snowman/transitive.go#133: shutting down consensus engine
INFO [09-21|20:44:08] <P Chain> snow/networking/router/handler.go#487: finished shutting down chain
INFO [09-21|20:44:08] node/node.go#814: node shut down successfully
INFO [09-21|20:44:08] nat/nat.go#140: Unmapped all ports

**Operating System**
macOS 10.15.6

**Additional context**
n/a

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
The first mainnet node (v1.0.0) has not been released yet so this is expected
