### ISSUE TITLE
Fatal errors - socket + log: too many open files (macOS, mainnet v1.0.0)

### ISSUE THREAD

**Issue by dbrisinda** [ava-labs/avalanchego#441]
**Describe the bug**
Fatal errors after running for many hours without issue:

ERROR[09-22|03:11:58] nat/nat.go#116: Renewing port mapping from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTTP request: Post "http://192.168.1.254:5431/uuid:941b0148-a0f4-4f24-a549-f694da024585/WANIPConnection:1": dial tcp 192.168.1.254:5431: socket: too many open files

FATAL[09-22|04:25:32] <P Chain> snow/networking/router/handler.go#257: forcing chain to shutdown due to: open /Users/dalmazio/.avalanchego/db/mainnet/v1.0.0/000046.log: too many open files

(full output below)

**To Reproduce**
Nothing special. Just run node, and let it run for a while.

**Expected behavior**
Runs without fatal errors.

**Screenshots**
Franks-iMac:/Users/dalmazio/go/src/github.com/ava-labs/avalanchego(master)$ ./build/avalanchego
     _____               .__                       .__
    /  _  \___  _______  |  | _____    ____   ____ |  |__   ____    ,_ o
   /  /_\  \  \/ /\__  \ |  | \__  \  /    \_/ ___\|  |  \_/ __ \   / //\,
  /    |    \   /  / __ \|  |__/ __ \|   |  \  \___|   Y  \  ___/    \>> |
  \____|__  /\_/  (____  /____(____  /___|  /\___  >___|  /\___  >    \\
          \/           \/          \/     \/     \/     \/     \/
INFO [09-22|00:41:57] nat/nat.go#94: Mapped Protocol TCP Internal 9651 External 9651.
INFO [09-22|00:41:57] node/node.go#736: Node version is: avalanche/1.0.0
INFO [09-22|00:41:58] node/node.go#379: Set node's ID to PgQM5J7frZbViH2ErjvXkLh6NB3xL5gNe
INFO [09-22|00:41:58] node/node.go#441: Initializing API server
INFO [09-22|00:41:58] node/node.go#567: initializing keystore
INFO [09-22|00:41:58] node/node.go#578: initializing keystore API
INFO [09-22|00:41:58] api/server.go#152: adding route /ext/keystore
INFO [09-22|00:41:58] node/node.go#594: initializing metrics API
INFO [09-22|00:41:58] api/server.go#152: adding route /ext/metrics
INFO [09-22|00:41:58] node/node.go#559: initializing SharedMemory
INFO [09-22|00:41:59] api/server.go#152: adding route /ext/vm/rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT
INFO [09-22|00:41:59] api/server.go#152: adding route /ext/vm/jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq
INFO [09-22|00:41:59] node/node.go#610: skipping admin API initialization because it has been disabled
INFO [09-22|00:41:59] node/node.go#626: initializing info API
INFO [09-22|00:41:59] api/server.go#152: adding route /ext/info
INFO [09-22|00:41:59] node/node.go#650: initializing Health API
INFO [09-22|00:41:59] api/server.go#152: adding route /ext/health
INFO [09-22|00:41:59] node/node.go#688: skipping ipc API initializaion because it has been disabled
INFO [09-22|00:41:59] node/node.go#701: initializing aliases
INFO [09-22|00:41:59] node/node.go#425: initializing chains
INFO [09-22|00:41:59] chains/manager.go#188: creating chain:
    ID: 11111111111111111111111111111111LpoYY
    VMID:rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT
INFO [09-22|00:42:00] \<P Chain> vms/platformvm/vm.go#399: Initializing last accepted block as CE1Xoqd5CNUa4iK1uWpfYKnag7YZsuvqNJyqAiEqykXru1kfz
INFO [09-22|00:42:00] \<P Chain> snow/engine/snowman/transitive.go#58: initializing consensus engine
INFO [09-22|00:42:00] api/server.go#136: adding route /ext/bc/11111111111111111111111111111111LpoYY
INFO [09-22|00:42:00] api/server.go#82: HTTP API server listening on "127.0.0.1:9650"
INFO [09-22|00:42:01] \<P Chain> snow/engine/common/bootstrapper.go#177: Bootstrapping started syncing with 1 vertices in the accepted frontier
INFO [09-22|00:42:01] \<P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#244: bootstrapping fetched 0 blocks. executing state transitions...
INFO [09-22|00:42:01] \<P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#285: executed 0 blocks
INFO [09-22|00:42:02] \<P Chain> snow/engine/snowman/transitive.go#114: bootstrapping finished with CE1Xoqd5CNUa4iK1uWpfYKnag7YZsuvqNJyqAiEqykXru1kfz as the last accepted block
INFO [09-22|00:42:02] chains/manager.go#188: creating chain:
    ID: 2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM
    VMID:jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq
INFO [09-22|00:42:02] \<X Chain> snow/engine/avalanche/transitive.go#62: Initializing consensus engine
INFO [09-22|00:42:02] api/server.go#136: adding route /ext/bc/2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM
INFO [09-22|00:42:02] api/server.go#136: adding route /ext/bc/2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM/pubsub
INFO [09-22|00:42:02] chains/manager.go#188: creating chain:
    ID: 2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5
    VMID:mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6
INFO [09-22|00:42:02] \<C Chain> snow/engine/snowman/transitive.go#58: initializing consensus engine
INFO [09-22|00:42:02] api/server.go#136: adding route /ext/bc/2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5/ws
INFO [09-22|00:42:02] api/server.go#136: adding route /ext/bc/2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5/rpc
INFO [09-22|00:42:02] api/server.go#136: adding route /ext/bc/2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5/avax
INFO [09-22|00:42:02] \<X Chain> snow/engine/common/bootstrapper.go#177: Bootstrapping started syncing with 2 vertices in the accepted frontier
INFO [09-22|00:42:06] \<X Chain> snow/engine/avalanche/bootstrap/bootstrapper.go#351: bootstrapping fetched 3 vertices. executing transaction state transitions...
INFO [09-22|00:42:06] \<X Chain> snow/engine/avalanche/bootstrap/bootstrapper.go#395: executed 3 operations
INFO [09-22|00:42:06] \<X Chain> snow/engine/avalanche/bootstrap/bootstrapper.go#357: executing vertex state transitions...
INFO [09-22|00:42:06] \<X Chain> snow/engine/avalanche/bootstrap/bootstrapper.go#395: executed 3 operations
INFO [09-22|00:42:06] \<X Chain> snow/engine/avalanche/transitive.go#98: bootstrapping finished with 1 vertices in the accepted frontier
INFO [09-22|00:42:22] \<C Chain> snow/engine/common/bootstrapper.go#177: Bootstrapping started syncing with 1 vertices in the accepted frontier
INFO [09-22|00:42:22] \<C Chain> snow/engine/snowman/bootstrap/bootstrapper.go#244: bootstrapping fetched 0 blocks. executing state transitions...
INFO [09-22|00:42:22] \<C Chain> snow/engine/snowman/bootstrap/bootstrapper.go#285: executed 0 blocks
INFO [09-22|00:42:22] \<C Chain> snow/engine/snowman/transitive.go#114: bootstrapping finished with NwH5W45Ho9TgNwPbsmX8hQqwmshaks3issR1Nza8ULNdyYsGE as the last accepted block
INFO [09-22|01:59:55] api/info/service.go#84: Info: GetNodeID called
INFO [09-22|02:16:59] \<P Chain> vms/platformvm/service.go#737: Platform: GetPendingValidators called
INFO [09-22|02:17:34] \<P Chain> vms/platformvm/service.go#607: Platform: GetCurrentValidators called
INFO [09-22|02:46:05] \<P Chain> vms/platformvm/service.go#1849: Platform: GetTx called
ERROR[09-22|03:11:58] nat/nat.go#116: Renewing port mapping from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTTP request: Post "http://192.168.1.254:5431/uuid:941b0148-a0f4-4f24-a549-f694da024585/WANIPConnection:1": dial tcp 192.168.1.254:5431: socket: too many open files
ERROR[09-22|03:26:58] nat/nat.go#116: Renewing port mapping from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTTP request: Post "http://192.168.1.254:5431/uuid:941b0148-a0f4-4f24-a549-f694da024585/WANIPConnection:1": dial tcp 192.168.1.254:5431: socket: too many open files
ERROR[09-22|03:41:58] nat/nat.go#116: Renewing port mapping from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTTP request: Post "http://192.168.1.254:5431/uuid:941b0148-a0f4-4f24-a549-f694da024585/WANIPConnection:1": dial tcp 192.168.1.254:5431: socket: too many open files
ERROR[09-22|03:56:58] nat/nat.go#116: Renewing port mapping from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTTP request: Post "http://192.168.1.254:5431/uuid:941b0148-a0f4-4f24-a549-f694da024585/WANIPConnection:1": dial tcp 192.168.1.254:5431: socket: too many open files
ERROR[09-22|04:11:58] nat/nat.go#116: Renewing port mapping from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTTP request: Post "http://192.168.1.254:5431/uuid:941b0148-a0f4-4f24-a549-f694da024585/WANIPConnection:1": dial tcp 192.168.1.254:5431: socket: too many open files
FATAL[09-22|04:25:32] \<P Chain> snow/networking/router/handler.go#257: forcing chain to shutdown due to: open /Users/dalmazio/.avalanchego/db/mainnet/v1.0.0/000046.log: too many open files
INFO [09-22|04:25:32] \<P Chain> snow/engine/snowman/transitive.go#133: shutting down consensus engine
ERROR[09-22|04:25:32] \<P Chain> snow/networking/router/handler.go#485: Error while shutting down the chain: open /Users/dalmazio/.avalanchego/db/mainnet/v1.0.0/000046.log: too many open files
INFO [09-22|04:25:32] \<P Chain> snow/networking/router/handler.go#487: finished shutting down chain
ERROR[09-22|04:25:50] \<X Chain> vms/avm/unique_tx.go#154: Failed to commit accept Ejr3wQUj3s557yaNtAAJXgsTgWZkVcRYdp1481PahdMcRD3qK due to open /Users/dalmazio/.avalanchego/db/mainnet/v1.0.0/000046.log: too many open files
FATAL[09-22|04:25:50] \<X Chain> snow/networking/router/handler.go#257: forcing chain to shutdown due to: open /Users/dalmazio/.avalanchego/db/mainnet/v1.0.0/000046.log: too many open files
INFO [09-22|04:25:50] \<X Chain> snow/engine/avalanche/transitive.go#132: shutting down consensus engine
INFO [09-22|04:25:50] \<X Chain> snow/networking/router/handler.go#487: finished shutting down chain
ERROR[09-22|04:25:57] snow/networking/router/chain_router.go#375: QueryFailed(Fg3L1eo53UWpf3J9Y45PK2ksQ1zyqajHL, 2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM, 15412) dropped due to unknown chain
ERROR[09-22|04:25:57] snow/networking/router/chain_router.go#375: QueryFailed(Fg3L1eo53UWpf3J9Y45PK2ksQ1zyqajHL, 2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM, 15415) dropped due to unknown chain
ERROR[09-22|04:25:57] snow/networking/router/chain_router.go#375: QueryFailed(Fg3L1eo53UWpf3J9Y45PK2ksQ1zyqajHL, 2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM, 15416) dropped due to unknown chain
ERROR[09-22|04:25:57] snow/networking/router/chain_router.go#375: QueryFailed(GXrrnggKkYmEsNLFc7utBekRjdz1pBr94, 2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM, 15416) dropped due to unknown chain
ERROR[09-22|04:25:57] snow/networking/router/chain_router.go#375: QueryFailed(4kCLS16Wy73nt1Zm54jFZsL7Msrv3UCeJ, 2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM, 15416) dropped due to unknown chain

[... hundreds of ERROR messages like above ...]

ERROR[09-22|04:26:58] nat/nat.go#116: Renewing port mapping from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTTP request: Post "http://192.168.1.254:5431/uuid:941b0148-a0f4-4f24-a549-f694da024585/WANIPConnection:1": dial tcp 192.168.1.254:5431: socket: too many open files
ERROR[09-22|04:41:58] nat/nat.go#116: Renewing port mapping from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTTP request: Post "http://192.168.1.254:5431/uuid:941b0148-a0f4-4f24-a549-f694da024585/WANIPConnection:1": dial tcp 192.168.1.254:5431: socket: too many open files
ERROR[09-22|04:56:58] nat/nat.go#116: Renewing port mapping from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTTP request: Post "http://192.168.1.254:5431/uuid:941b0148-a0f4-4f24-a549-f694da024585/WANIPConnection:1": dial tcp 192.168.1.254:5431: socket: too many open files
ERROR[09-22|05:11:58] nat/nat.go#116: Renewing port mapping from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTTP request: Post "http://192.168.1.254:5431/uuid:941b0148-a0f4-4f24-a549-f694da024585/WANIPConnection:1": dial tcp 192.168.1.254:5431: socket: too many open files
ERROR[09-22|05:26:58] nat/nat.go#116: Renewing port mapping from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTTP request: Post "http://192.168.1.254:5431/uuid:941b0148-a0f4-4f24-a549-f694da024585/WANIPConnection:1": dial tcp 192.168.1.254:5431: socket: too many open files

[... dozens of ERROR messages like above ...]

**Operating System**
macOS 10.15.6.

**Additional context**
n/a

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by dbrisinda** [comment]
Subsequent running of node after pulling latest with tag v1.0.0-c gives "too many open files" error and node doesn't launch:

Franks-iMac:/Users/dalmazio/go/src/github.com/ava-labs/avalanchego(master)$ ./build/avalanchego
     _____               .__                       .__
    /  _  \___  _______  |  | _____    ____   ____ |  |__   ____    ,_ o
   /  /_\  \  \/ /\__  \ |  | \__  \  /    \_/ ___\|  |  \_/ __ \   / //\,
  /    |    \   /  / __ \|  |__/ __ \|   |  \  \___|   Y  \  ___/    \>> |
  \____|__  /\_/  (____  /____(____  /___|  /\___  >___|  /\___  >    \\
          \/           \/          \/     \/     \/     \/     \/
WARN [09-23|06:52:34] main/main.go#96: NAT traversal has failed. The node will be able to connect to less nodes.
INFO [09-23|06:52:34] node/node.go#736: Node version is: avalanche/1.0.0
INFO [09-23|06:52:35] node/node.go#379: Set node's ID to PgQM5J7frZbViH2ErjvXkLh6NB3xL5gNe
INFO [09-23|06:52:35] node/node.go#441: Initializing API server
INFO [09-23|06:52:35] node/node.go#567: initializing keystore
INFO [09-23|06:52:35] node/node.go#578: initializing keystore API
INFO [09-23|06:52:35] api/server.go#152: adding route /ext/keystore
INFO [09-23|06:52:35] node/node.go#594: initializing metrics API
INFO [09-23|06:52:35] api/server.go#152: adding route /ext/metrics
INFO [09-23|06:52:35] node/node.go#559: initializing SharedMemory
INFO [09-23|06:52:36] api/server.go#152: adding route /ext/vm/rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT
INFO [09-23|06:52:36] api/server.go#152: adding route /ext/vm/jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq
INFO [09-23|06:52:37] node/node.go#610: skipping admin API initialization because it has been disabled
INFO [09-23|06:52:37] node/node.go#626: initializing info API
INFO [09-23|06:52:37] api/server.go#152: adding route /ext/info
INFO [09-23|06:52:37] node/node.go#650: initializing Health API
INFO [09-23|06:52:37] api/server.go#152: adding route /ext/health
INFO [09-23|06:52:37] node/node.go#688: skipping ipc API initializaion because it has been disabled
INFO [09-23|06:52:37] node/node.go#701: initializing aliases
INFO [09-23|06:52:37] node/node.go#425: initializing chains
INFO [09-23|06:52:37] chains/manager.go#188: creating chain:
    ID: 11111111111111111111111111111111LpoYY
    VMID:rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT
INFO [09-23|06:52:38] \<P Chain> vms/platformvm/vm.go#399: Initializing last accepted block as cZyrD8NYwYETPYKvWGAENyfMubDPcwbahrQ8qeArKePdU7ysi
INFO [09-23|06:52:38] \<P Chain> snow/engine/snowman/transitive.go#58: initializing consensus engine
INFO [09-23|06:52:38] api/server.go#136: adding route /ext/bc/11111111111111111111111111111111LpoYY
INFO [09-23|06:52:38] api/server.go#82: HTTP API server listening on "127.0.0.1:9650"
INFO [09-23|06:52:40] \<P Chain> snow/engine/common/bootstrapper.go#177: Bootstrapping started syncing with 2 vertices in the accepted frontier
INFO [09-23|06:52:42] \<P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#211: fetched 2500 blocks
INFO [09-23|06:52:44] \<P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#211: fetched 5000 blocks
INFO [09-23|06:52:46] \<P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#211: fetched 7500 blocks
INFO [09-23|06:52:48] \<P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#211: fetched 10000 blocks
FATAL[09-23|06:52:49] \<P Chain> snow/networking/router/handler.go#257: forcing chain to shutdown due to: open /Users/dalmazio/.avalanchego/db/mainnet/v1.0.0/000050.ldb: too many open files
INFO [09-23|06:52:49] \<P Chain> snow/engine/snowman/transitive.go#133: shutting down consensus engine
ERROR[09-23|06:52:49] \<P Chain> snow/networking/router/handler.go#485: Error while shutting down the chain: open /Users/dalmazio/.avalanchego/db/mainnet/v1.0.0/000044.ldb: too many open files
INFO [09-23|06:52:49] \<P Chain> snow/networking/router/handler.go#487: finished shutting down chain
^CINFO [09-23|06:53:18] node/node.go#810: shutting down the node
INFO [09-23|06:53:18] node/node.go#816: node shut down successfully
INFO [09-23|06:53:18] nat/nat.go#140: Unmapped all ports

**Comment by dbrisinda** [comment]
Ah. I see this hasn't yet been merged:

https://github.com/ava-labs/avalanchego/pull/346

**Comment by aaronbuchwald** [comment]
Thanks for reporting this @dbrisinda . Yup once that PR is merged it should take care of the issue with too many open files on macOS. This looks like a strange edge case in how the shutdown is handled, that we should improve on.

What is the end result of this? Could you share the final log messages or does it print those same error messages until you eventually need to kill it manually? If the node does shut down, how long does it take after the original failure message for it to shutdown?

**Comment by dbrisinda** [comment]
Yes, it just keeps going and I need to kill it manually.

**Comment by danlaine** [comment]
Should be fixed by v1.0.1

Let us know if issues persist
