### ISSUE TITLE
avm.getTx hangs on FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z [mainnet]

### ISSUE THREAD

**Issue by ang-st** [ava-labs/avalanchego#445]
this is the avax token genesis and while not systematic, call to getTx can hang forever

**Comment by danlaine** [comment]
@ang-st 
Thanks for reporting this. It took 90s for me to get a response.
I think what's happening is that the genesis is really large, so encoding it in cb58 takes a really long time.
We're adding the option to encode responses in hex, and hopefully that will resolve this.
https://github.com/ava-labs/avalanchego/pull/477

**Comment by danlaine** [comment]
I just tried with the changes in that PR and now it takes "only" 47 seconds...still not great. In practice the genesis is the only tx that should be anywhere near this size, so I don't think this is an issue in general.
