### ISSUE TITLE
avm.getUTXOs isn't refreshed after a transaction broadcast

### ISSUE THREAD

**Issue by ang-st** [ava-labs/avalanchego#446]
When issuing several transaction in a row and not using batching, avm.getUTXOs apparenrtly return the same utxoset causing following transactions to be rejected. Still those transaction have a txid returned by avalanchego.

**Comment by aaronbuchwald** [comment]
@ang-st this is a result of the fact that getUTXOs returns the UTXO set based on the current state of the network. Therefore, if you send a transaction that spends some UTXOs and creates some UTXOs, getUTXOs will not reflect the change to the UTXO set until that transaction has been accepted.

If you want to create a string of transactions based off of the output of getUTXOs you can do the following:

If getUTXOs returns UTXO A, then you can create tx1 that spends UTXO A and creates UTXO B. You can then create tx2 that spends UTXO B and produces a new UTXO C. In this case, you can issue the second transaction to the node before the first has been accepted.
