### ISSUE TITLE
Can't reach API outside docker container

### ISSUE THREAD

**Issue by PatrickAlphaC** [ava-labs/avalanchego#453]
**Describe the bug**
When running the docker container, I expect to be able to call the API through the exposed port. It might be my docker noobness here, but I can't seem to be able to call the port. On my curls I keep getting:

```
curl: (52) Empty reply from server
```

**To Reproduce**
1. Build docker image
```
git clone https://github.com/ava-labs/avalanchego && cd avalanchego
./scripts/build_image.sh
./scripts/build.sh
```

2. Run the docker image
```
docker run --restart=always -p 9650:9650 -p 9651:9651 --name ava-node-primary  -it avalanchego-54757073 ./build/avalanchego --network-id=fuji --staking-enabled=false --snow-sample-size=1 --snow-quorum-size=1
```

3. Curl the API 
```
curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"info.isBootstrapped",
    "params": {
        "chain":"X"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/info
```

**Expected behavior**
The node should respond with something like:
```
{"jsonrpc":"2.0","result":{"isBootstrapped":true},"id":1}
```

It should be noted, that when running the `curl` inside the docker container, I am able to get a response fine, I just can't seem to be able to get in through the port. 

Example command to get into the docker volume
`docker exec -it ava-node-primary sh`

**Operating System**
MacOS Catalina 10.15.6
Docker version 19.03.12, build 48a66213fe

Avalanche docker image
avalanchego-54757073   latest              4c64016f00e8

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by PatrickAlphaC** [comment]
Not sure if this helps, but I tried what I thought were the suggestions here: https://github.com/moby/moby/issues/2522

Any help appreciated.

**Comment by PatrickAlphaC** [comment]
Ah ok, I fixed it by doing this:  `httpHost := fs.String("http-host", "0.0.0.0", "Address of the HTTP server")` in params.go

Not sure what the thoughts on that are.

**Comment by PatrickAlphaC** [comment]
This also fixed the websocket not being able to connect

**Comment by PatrickAlphaC** [comment]
However, I'm not getting any new heads when I subscribe to the websocket

**Comment by aaronbuchwald** [comment]
It looks like there are a few things going wrong with the parameters. You can set the parameter '--http-host=' to open the port.

One other note, the instructions for using the docker image are actually referencing creating a local network with the docker image. The other parameters that you're setting staking-enabled, snow-sample-size, and snow-quorum-size should all be kept the same for the whole network. So if you're going to connect to Fuji, you should not be setting those parameters.

Try running with the command:

```
docker run -ti -p 9650:9650 -p 9651:9651 avalanchego-xxxxxxxx /avalanchego/build/avalanchego --network-id=fuji --http-host=
```

**Comment by PatrickAlphaC** [comment]
Ah, I'll give this a whirl tomorrow. Do you know if that flag works for websockets too?

**Comment by PatrickAlphaC** [comment]
Ah this worked for me too. I'll close this. Thank you!
