### ISSUE TITLE
Incorrect uptime sometimes returned by getCurrentValidators

### ISSUE THREAD

**Issue by severalif** [ava-labs/avalanchego#464]
The uptime results from getCurrentValidators seem to be incorrect from time to time, where almost all validators get good uptime. The result fluctuates between the calls (between the buggy result and the normal result). It seems to have gotten worse with the latest release of avalanche.

Buggy result (almost all validators have good uptime): 
- https://avax.dev/data/buggy-validator.json

Normal result: 
- https://avax.dev/data/ok-validator.json

These results were received by consecutive getCurrentValidators calls to the node with minutes in between (and without restarting the node). 

Versions/configuration: 
- avalanche/1.0.1 [database=v1.0.0, network=mainnet]
- CLI arguments: --snow-quorum-size=14 --snow-virtuous-commit-threshold=15
- OS: Debian GNU/Linux 10 (buster)

**Comment by danlaine** [comment]
Are you querying one of our API nodes? (https://api.avax-dev.com)

**Comment by severalif** [comment]
> What node are you querying uptime from?

From the node on the same machine.

**Comment by danlaine** [comment]
And you're only querying one node? Not a bunch of nodes behind a load balancer or something?

**Comment by severalif** [comment]
> And you're only querying one node? Not a bunch of nodes behind a load balancer or something?

Yes, I have a single node on a VPS and I'm querying the node locally using curl. No load balancer or any other complicated setup.

**Comment by danlaine** [comment]
Honestly I have no idea what could cause this.
@StephenButtolph @aaronbuchwald any ideas?

**Comment by Phistr90** [comment]
I have also seen this behavior.

**Comment by gaia** [comment]
Same here

**Comment by danlaine** [comment]
@severalif Are you still seeing this behavior?

**Comment by gaia** [comment]
yes, these were done today aboiut 1 second apart 
![image](https://user-images.githubusercontent.com/87547/96010414-9e119380-0df6-11eb-8640-ae4a47356c55.png)

**Comment by danlaine** [comment]
I'm taking up this issue today. I assume this is still an issue for you all?

**Comment by gaia** [comment]
I am not sure it still happens. i could not reproduce it today.

**Comment by danlaine** [comment]
Nobody I've talked to seems able to reproduce this issue anymore. Seems to be resolved. Please re-open if you can reproduce this again. Thanks all for reporting.
