### ISSUE TITLE
cchain bootstrap error

### ISSUE THREAD

**Issue by mahofmahof** [ava-labs/avalanchego#481]
My system is w10 x64, WSL 2, ubuntu 18.04
i have deleted the db under .avalanchego but it did not solve the problem
INFO [10-04|16:12:44] chains/manager.go#188: creating chain:
    ID: 2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5
    VMID:mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6
ERROR[10-04|16:12:44] chains/manager.go#197: Error while creating new chain: error while creating vm: fork/exec build/plugins/evm: no such file or directory
INFO [10-04|17:32:11] chains/manager.go#188: creating chain:
    ID: 2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5
    VMID:mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6
ERROR[10-04|17:32:11] chains/manager.go#197: Error while creating new chain: error while creating vm: fork/exec build/plugins/evm: no such file or directory
INFO [10-04|17:35:08] chains/manager.go#188: creating chain:
    ID: 2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5
    VMID:mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6
ERROR[10-04|17:35:08] chains/manager.go#197: Error while creating new chain: error while creating vm: fork/exec build/plugins/evm: no such file or directory
INFO [10-04|17:37:48] chains/manager.go#188: creating chain:
    ID: 2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5
    VMID:mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6
ERROR[10-04|17:37:48] chains/manager.go#197: Error while creating new chain: error while creating vm: fork/exec build/plugins/evm: no such file or directory

**Comment by aaronbuchwald** [comment]
Thanks for reporting this @mahofmahof , this error is caused when the evm binary is not where it's expected to be. How are you running into this error? Are you using one of the binary releases? Are you moving any of the binaries around from their original locations?

**Comment by mahofmahof** [comment]
no i did not move anything just installed the latest avalanchego-1.0.1 version
i made a folder called /build/plugins/evm and copied the /avalanchego-1.0.1/plugins/evm to that folder
it solced my problem
but it will be better if it is corrected at the source
we had same situation before at 0.8.3 and it is solved at the source

**Comment by danlaine** [comment]
Glad you solved this
