### ISSUE TITLE
Avalanchego cant handle internet reconnect with new ip being issued

### ISSUE THREAD

**Issue by Phistr90** [ava-labs/avalanchego#483]
**Describe the bug**
Avalanche node just fcked up my whole local network, got pings of more than 1s within the network, almost no bandwidth available. 
Needed to restart avalanchego, during shutdown got lot of these kinds of errors :

`ERROR[10-05|02:19:34] snow/networking/router/chain_router.go#385: QueryFailed(Mwd1UzuQe4x4VpGwn4BSz9JjXxwdSi3pU, 2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM, 5630099) dropped due to unknown chain `

My network was fine again after shutting down avalanche.

Metrics during network crash time:
* consensus pipelining skyrocketed to 3.2 million, 
* high number of failed msgs: 250k/s, 
* msg sent 15k/s,
* high spike in cpu load

All that started after I had the ordinary 24h disconnect by my ISP, providing a new IP.

**To Reproduce**
Everything is reproducible with reconnecting to the internet on the router and getting a new ip.

**Expected behavior**
Avalanchego should reconnect to peers and resume procedures as normal

**Operating System**
Ubuntu 18, built form source `038ae3550859b7920530c437d88332df575778c4`

**Additional context**
Maybe related to https://github.com/ava-labs/avalanchego/issues/461 and https://github.com/ava-labs/avalanchego/issues/470 or https://github.com/ava-labs/avalanchego/issues/335

I am **not** running the  `public-ip` flag as my ISP cant provide me with a static ip.

**Comment by fenicks** [comment]
This is related to https://github.com/ava-labs/avalanchego/issues/246

**Comment by danlaine** [comment]
@Phistr90 How long is your node in this pathological state? Or does it stay like that until it gets killed?

**Comment by Phistr90** [comment]
@danlaine As for what I have observed yesterday, I cant really tell how long it would stay in this state before or whether it would crash. I needed to restart avalanchego to make the local network usable again. I dont know whether the effects on the local network go away after a while. However, I have experienced high cpu load and ram spikes (until I get an OOM) in the past. So I would assume that after a while network gets somewhat usable again but high cpu load etc stays until the node crashes with an OOM.

**Comment by Phistr90** [comment]
I'd like to give https://github.com/ava-labs/avalanchego/pull/485 a shot later. What parameter should I use? ` --dynamic-public-ip default` ?

**Comment by tasinco** [comment]
dynamic-public-ip takes in two options 'ifconfig' or 'opendns'.  You would need to choose one.
Version 1.0.2 is not officially released, so you should use at your own risk.

**Comment by Phistr90** [comment]
So I tried it with `--dynamic-public-ip` flag and still some behavior and still kills my network. It says that it updates the ipv6 though.

**Comment by tasinco** [comment]
i don't understand what you man by updates the ipv6..
The dynamic public ip will only tell node to find update and user your external IP address.

What you are explaining is a onslaught of network when you start your node.

There are a few things you should check.
1) make sure your node is not exposed on your firewall on more than 2 ports.  That can cause some weirdness.  If you previously had UPnP enabled you should stop it, let the routes clear and restart it.  If you use port forwarding you should make sure only one route is exposed.
2) It is possible that there could be an issue with your db..  That could cause a large number of requests to your node.  You can backup any keys you have created.  Move the old db out of the way and restart the node.  You can re-import your keys..

The bootstrap process will recreate the DB and it will take a little time.

**Comment by Phistr90** [comment]
`The dynamic public ip will only tell node to find update and user your external IP address.`
Yes thats what I mean it says "it find an update".

To your 2 suggestions. Pretty sure I already checked everything. But will give it another try later. 

That being said, I am using this router and my setup with various blockchain p2p networks. With none of them I experienced these kind of issues. From my point of view this issue is not a misconfiguration on my end but something weird going on with avalanchego.

**Comment by danlaine** [comment]
@Phistr90 Can you please share screenshots of your Grafana dashboards when your node is in a bad state? That would be helpful in debugging this.

**Comment by tasinco** [comment]
@Phistr90 
Can you try https://github.com/ava-labs/avalanchego/pull/518 ?

**Comment by Phistr90** [comment]
@danlaine 

![3](https://user-images.githubusercontent.com/12374491/95639357-73db7100-0a98-11eb-8af5-31f686e30c15.jpg)
![2](https://user-images.githubusercontent.com/12374491/95639359-750c9e00-0a98-11eb-9ab0-2c2c2421e190.jpg)
![1](https://user-images.githubusercontent.com/12374491/95639360-750c9e00-0a98-11eb-8e7b-e0a7a0338e8f.jpg)

This was without the `--dynamic-public-ip` flag.

I am going to try to run my node node with the parameters mentioned by tascino.

**Comment by Phistr90** [comment]
@tasinco I tried https://github.com/ava-labs/avalanchego/pull/518 with

`--dynamic-public-ip=ifconfig --dynamic-update-duration=1m`
and with
`--dynamic-public-ip=opendns --dynamic-update-duration=1m`

Whereas ifconfig didnt show any difference in behavior, metrics and output on the node logs,
opendns updated the external ip, first ipv6, then ipv4, then ipv6 and 1 failed query.
Also during the test run with opendns, my peers droped without me reconnected or cutting the connection (see below).

These are the metrics during the runs:

Let me break it down into phases what happened when:

A: Starting the node with `--dynamic-public-ip=ifconfig --dynamic-update-duration=1m` and let it sync and peer up
B: Reconnect on the modem, getting a new external ip
C: Network pings over 700ms, no successful queries, consensus pipelining skyrocketing, no output on the node indicating updating the external ip 
D: I shutdown the node after 5mins
E: I bring ithe node up again with same parameters, strangely no improvement this time (usually it then operates normally again)
F: I shut it down again
G: I start it with `--dynamic-public-ip=opendns --dynamic-update-duration=1m`, everything looks healthy again
H: Reconnect on the modem, getting a new external ip, network gets fucked up again
I-K: logs on the node updating ext IP:  first ipv6, then ipv4, then ipv6 and 1 failed query, network stays scred with pings of aprox 1s


![1](https://user-images.githubusercontent.com/12374491/95641185-2ca5ae00-0aa1-11eb-9bbe-97f1dda6ee91.jpg)
![2](https://user-images.githubusercontent.com/12374491/95641188-316a6200-0aa1-11eb-89d4-034f65bd48d8.jpg)
![3](https://user-images.githubusercontent.com/12374491/95641199-392a0680-0aa1-11eb-9ea0-750a75bc91a3.jpg)

**Comment by Phistr90** [comment]
As I already told @danlaine via dm, I could reproduce this undesired behavior with current `master` branch as well as `dev` with cli flag `--conn-meter-reset-duration=15s`.

**Comment by Phistr90** [comment]
Important update:

I cut the local network connection of the machine, waited a bit and reconnected to local network. (I tested that a while back but most likely didnt wait long enough, similar to pulling out the cable just for a short period -see above) 
I ended up in the bad state as well. So this has nothing to do with change in public IP. Sorry for misleading. 
So it is about losing the internet connection for a sign. time, as pulling the cable and directly plugging it in doesnt do the bad state trick.

**Comment by tasinco** [comment]
@Phistr90 if you node falls behind (similar to disconnecting the node from the network) for a while we will try to catchup.  That can absolutely increase network and CPU as the node is re-fetching and approving missing blocks.
Eventually the node should get it self out of this situation and catch up. 

Can you explain your hardware setup and network bandwidth?

As far as Send-Q it means your packets are not leaving your box.  Indicating a backlog somewhere.  And that again could exhibit in the node as a bunch more retries to fulfill blocks.

**Comment by Phistr90** [comment]
x-chain metrics before and in bad state: 

![x2](https://user-images.githubusercontent.com/12374491/96153059-8842c200-0f0d-11eb-92cc-df90bf31476e.jpg)
![x1](https://user-images.githubusercontent.com/12374491/96153062-88db5880-0f0d-11eb-9830-361184091e23.jpg)

**Comment by tasinco** [comment]
@Phistr90 

Can you run these commands repeatedly

$ dig +short myip.opendns.com @resolver1.opendns.com
$ curl ifconfig.co

Do you see the IP change from v4 to v6 ?

**Comment by Phistr90** [comment]
@tasinco 

$ dig +short myip.opendns.com @resolver1.opendns.com
Gives no output
$ curl ifconfig.co
Gives me v6

**Comment by tasinco** [comment]
If dig is not working for you with command line.  It won't work for you in node.

Do you see the same v6 address from ifconfig.co as you run it?

**Comment by Phistr90** [comment]
@tasinco yes

I did a lot more test runs. Bottom line is: The node doesnt get into the bad state whenever I have `--log-level=debug` set.
I know that is strange but that's what's happening... :confused:

**Comment by HugeRoo** [comment]
Similar issue for me after upgrading from 1.0.1 to 1.0.5. 

My ISP changed my IP a couple of days ago. CPU utilisation went from 2.5% to well over 70%. I waited over a day and the CPU utilisation didn't come back down again.

I rebooted the node with '--dynamic-public-ip=opendns' to the command line. The CPU utilisation went down, but peer count went down. I fixed a problem with the virtual server open port, rebooted and everything ran smoothly until I lost my internet connection today (twice). CPU utilisation went straight back up until I rebooted the node. This happened both times.

During one of the longer downtimes, the node attempted to connect to 10.0.0.1 before the ISP issued a new IP a couple of minutes earlier.

FYI, I'm running on an old gaming laptop (and it usually validates like a dream).

Node: 1.0.5
IP: Dynamic
OS: Ubuntu 20.04
CPU: i7 2.3GHz x8
RAM: 11.7 GiB
Disk Capacity: 878 GB
Internet Connection: 100Mbps
Connection: Wired

Thanks AVA Labs team for making such an unbelievable technology. Hope this helps iron out a glitch in the matrix.

**Comment by Phistr90** [comment]
Short feedback on my end. So far nothing has changed, problem still exists. I have recently re-setup everything on a clean OS. Same issue. Only workaround for me is running in log-level=debug. @HugeRoo maybe worth a try as well. Not really a long-term solution but might be a workaround for the time being.

**Comment by Phistr90** [comment]
My workaround no longer works for me. Please help :(

**Comment by danlaine** [comment]
Working with @Phistr90 in DMs to figure out what's happening and resolve it

**Comment by danlaine** [comment]
Closing for age. AvalancheGo has changed quite a lot since this issue was opened. Please open a new issue if you are still having this issue, or a similar one. Thank you!

**Comment by nyetwurk** [comment]
`--public-ip` should work with hostname, not just an IPv4 address.
