### ISSUE TITLE
1 out of 3 Nodes on same network exhibiting high CPU utilization & seemingly was behind vs. others

### ISSUE THREAD

**Issue by berkozdogan** [ava-labs/avalanchego#494]
**Describe the bug**
I have 3 nodes as follows:
- 3 Raspberry Pi 4 8GB
- Ubuntu 20.04 (same exact OS image with GO 1.15 flashed to all devices)
- All Running 1.0.0 with the parameters advised by the ava-labs team after the issue
- Same LAN (different local IPs but same external IP)

1 out of the 3 has been exhibiting very high CPU utilization (100-300% and load averages 3.0+) vs. the other 2 nodes (10-20%/1.0)

I did have a crash on the 27th as well, and had removed the DB to re-bootstrap and have been running ok generally.
I did have other episodes of high CPU utilization across all nodes, however simple restart had solved them.

This time around the restart doesn't seem to make a difference (i.e. utilization is still very high vs. the other nodes) and after the restart, the node went through a partial bootstrap (i.e. it fetched blocks for both P & X chains even though I had barely any downtime, leading me to believe it was no longer healthy to process transactions before the restart).

**To Reproduce**
Unknown

**Expected behavior**
The expected CPU utilization is around 10-30% (By looking at the other two nodes).

**Screenshots**
[details.tar.gz](https://github.com/ava-labs/avalanchego/files/5336827/details.tar.gz)

**Operating System**
Ubuntu 20.04

**Additional context**

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
@berkozdogan Are you running node monitoring on this node by any chance?

**Comment by tasinco** [comment]
The node was re-bootstrapped, CPU normalized.
