### ISSUE TITLE
Update Travis CI build scripts

### ISSUE THREAD

**Issue by sbellem** [ava-labs/avalanchego#506]
Here's a high-level view of some points that may benefit from being reviewed/updated:

- [ ] The codecov token is no longer needed as it was necessary for the private repository. https://github.com/ava-labs/avalanchego/blob/038ae3550859b7920530c437d88332df575778c4/.travis.yml#L8

- [ ] Link new repo, (*avalanchego*) with codecov so that uploaded report are available. See comment https://github.com/ava-labs/avalanchego/issues/506#issuecomment-706322070.

- [ ] Add Travis CI and codecov badges to the README.

- [x] The dockerhub repository could perhaps be renamed to match the new name. https://github.com/ava-labs/avalanchego/blob/038ae3550859b7920530c437d88332df575778c4/.travis.yml#L12

- [x] Extra work, which probably costs time to the Travis build, could probably be saved by reviewing the exact purpose of https://github.com/ava-labs/avalanchego/blob/038ae3550859b7920530c437d88332df575778c4/.travis.yml#L29 The 2 lines in https://github.com/ava-labs/avalanchego/blob/038ae3550859b7920530c437d88332df575778c4/.ci/run_docker.sh#L11-L12 are probably not needed. The last one most certainly not as it just invokes `scripts/build.sh` which is already run when the image is built. As for the line that runs the tests, it appears to me that it does exactly the same as what https://github.com/ava-labs/avalanchego/blob/038ae3550859b7920530c437d88332df575778c4/.travis.yml#L28 does. To be more precise, the 2 lines do the same as `.ci/build_and_test.sh` but in a reverse order. Moreover the docker-based instruction builds avalanche twice. So considerable time may be saved on Travis builds by reviewing this part. It may be enough to just build the docker image to make sure it builds and to push it to DockerHub for others to use. But also note that DockerHub can also be used to build images, such that new builds are triggered by updates on the linked GitHub repository. Doing so could save additional time on Travis builds.

**Comment by aaronbuchwald** [comment]
Hey @sbellem great to hear from you! There is actually already a PR to clean up the travis build by removing the extra run of tests within docker and renaming the repo here: https://github.com/ava-labs/avalanchego/pull/447/files. I'll make another PR to remove the unused code coverage token.

As for DockerHub, the CI currently needs to to build the docker image to use in our E2E test suite, so for now we need to build the docker image within Travis.

**Comment by sbellem** [comment]
Hi @aaronbuchwald! Ah okay, I had not seen the PR. I had based my comments on the `master` branch and did not look at the `dev` branch :smile: .

As for the codecov integration, the repository should be linked in codecov so that the coverage report is uploaded and available to the public. As of now it's still `gecko`. See https://codecov.io/github/ava-labs/gecko/commit/45afeba513651169c78bbccd5846fe4049a24fe5 for instance. This will lead to a 404 for the general public: https://codecov.io/github/ava-labs/gecko/commit/45afeba513651169c78bbccd5846fe4049a24fe5.

Since we are it, it may a be a good idea to add Travis CI and codecov badges to the README as this provides a quick link to the current status of the repository with respect to builds and code coverage.

**Comment by danlaine** [comment]
closing because we don't use travis anymore. Thanks, though!
