### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by HankFit247** [ava-labs/avalanchego#517]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Operating System**
Which OS you used to reveal the bug.

**Additional context**
Docker Image,
Build the docker image of latest avalanchego branch by

add "./" to scripts/build_image.sh

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
Hi @HankFit247 I'm not sure I understand what you're saying here...are you suggesting an update to the documentation? If so, can you please make an issue or PR to https://github.com/ava-labs/avalanche-docs ?
Thanks

**Comment by HankFit247** [comment]
Just stating that page: https://github.com/ava-labs/avalanchego
is missing an instruction set.

under "Docker Install"
Line reads:
"Build the docker image of latest avalanchego branch by scripts/build_image.sh ."

Line should read:
"Build the docker image of latest avalanchego branch by ./scripts/build_image.sh ."

![Untitled](https://user-images.githubusercontent.com/69835341/95643003-eb49da00-0a71-11eb-8aa3-ff1d18b83b32.png)

**Comment by danlaine** [comment]
Fixed in above PR

**Comment by HankFit247** [comment]
Thanks!  Something of noob here.  Wanna save other noobs from making similar mistakes.
