### ISSUE TITLE
1.0.2 Renewing port mapping failed

### ISSUE THREAD

**Issue by Blindripper** [ava-labs/avalanchego#523]
**Describe the bug**
Node drops constantly this error:

`ERROR[10-09|06:50:39] nat/nat.go#86: Renewing port mapping try #2 from external port 9651 to internal port 9651 failed with goupnp: SOAP `

**To Reproduce**
Port forwarding activated, UPnP activated. Error occurs after upgrade to 1.0.2 and restart of the node.

**Expected behavior**
Node should run without dropping Errors.

**Operating System**
Linux Debian (MX Linux)

![Screenshot-68](https://user-images.githubusercontent.com/39067706/95625823-6fec2680-0a79-11eb-9781-28b42273c987.png)

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by tasinco** [comment]
@Blindripper you router is providing us this message.  and it does mean that we were unable to issue a UPnP route update.
This should be an ERROR.

**Comment by Blindripper** [comment]
As mentioned UPnP is activated. 
![Screenshot-69](https://user-images.githubusercontent.com/39067706/95631380-e4c45e00-0a83-11eb-9c4e-7728ce0e80f5.png)

**Comment by Blindripper** [comment]
Everything else looks fine.

![Screenshot-71](https://user-images.githubusercontent.com/39067706/95638130-e433c380-0a93-11eb-8375-3fc3b8b2ca51.png)

**Comment by tasinco** [comment]
@Blindripper 
I believe if you have routes for those ports on your router, and you have UPnP on your router will give you a 500.
If node is configured for UPnP we attempt to perform that operation.  And as noted you router is telling us the routes already exist.
This is an ERROR and should remain.

If you don't want the ERROR disable UPnP or disable the static routing on your router.

**Comment by Blindripper** [comment]
I understand, port forwarding isn't something "uncommon" so please consider to remove the Error; it unsettles one.
