### ISSUE TITLE
Unable to run app second time

### ISSUE THREAD

**Issue by ramilexe** [ava-labs/avalanchego#525]
Version:  v1.0.2

Ran app first time `./avalanchego` and successfully got the message:

```
<X Chain> avalanchego/snow/engine/avalanche/transitive.go#98: bootstrapping finished with 1 vertices in the accepted frontier
```
Then created account and address. No issue. Then I stopped app to tried to run it again using the same command and get error:

```
parsing parameters returned with error couldn't create db at /root/.avalanchego/db/mainnet/v1.0.0: resource temporarily unavailable
```

**Comment by danlaine** [comment]
https://docs.avax.network/v1.0/en/faq/#starting-node-fails-with-parsing-parameters-returned-with-error-couldnt-create-db-at

You probably have a node running on the machine already. Kill it and try agagin

**Comment by danlaine** [comment]
Any luck resolving this @ramilexe  ?

**Comment by ramilexe** [comment]
Yes, thank you, it works
