### ISSUE TITLE
there is a problem with the transfer status

### ISSUE THREAD

**Issue by 90hacker** [ava-labs/avalanchego#530]
**Describe the bug**
The browser view my transaction information is successful。
https://explorer.avax.network/tx/qHFV91dSx8PdQ75kyeRRCjo9ApHDB7zZyvZn8FaYr7fugZbs4.
My node is always in Processing state through API query。

**To Reproduce**
curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"avm.getTxStatus",
    "params" :{
        "txID":"qHFV91dSx8PdQ75kyeRRCjo9ApHDB7zZyvZn8FaYr7fugZbs4"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X

**Screenshots**
![image](https://user-images.githubusercontent.com/15024497/95842667-631d4a80-0d79-11eb-853a-5d8790df65ab.png)

**Operating System**
Ubuntu 18.04.4 LTS

**Comment by tasinco** [comment]
This generally means you issued simultaneous transactions quickly.  The second transaction was not valid.
To determine why the transaction was invalid you can res-submit the signed tx bytes.

To avoid this, you should submit the first tx and wait for it to be submitted or rejected before processing the next transaction.

**Comment by 90hacker** [comment]
Is caused by this problem

https://docs.avax.network/v1.0/en/faq/#node-prints-upnp-or-nat-pmp-router-attach-failed-you-may-not-be-listening-publicly-on-startup
