### ISSUE TITLE
C Chain: failed to persist clean trie cache

### ISSUE THREAD

**Issue by jpop32** [ava-labs/avalanchego#535]
**Describe the bug**
Since Oct. 9th, regularly, once an hour, C chain log shows:
`ERROR[10-09|08:25:41.951] Failed to persist clean trie cache       error="cannot move temporary dir \"fastcache.tmp.218806484\" to \"\": rename fastcache.tmp.218806484 : no such file or directory"`

No obvious anomalies in node operation is visible.

**To Reproduce**
No special steps, shows regularly in normal operation. Observe the log file at .avalanchego/log/chain/C/0.log

**Expected behavior**
No ERROR logs.

**Operating System**
Running node compiled from source, latest public version (v1.0.2), on RaspberryPi4, Ubuntu Server 20.04, arm64.

**Additional context**
Appearance of errors seems to coincide with the v1.0.2 release.

Screenshots of C Chain Grafana dashboard available if needed.

Output of `grep -EHrin error` from the log directory is here: [errors.txt](https://github.com/ava-labs/avalanchego/files/5379738/errors.txt)

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
@jpop32 Are you still having this issue?

**Comment by jpop32** [comment]
Yep. This is from today:

```
chain/C/1.log:1203:ERROR[11-13|08:42:59.060] Failed to persist clean trie cache       error="cannot move temporary dir \"fastcache.tmp.790187955\" to \"
\": rename fastcache.tmp.790187955 : no such file or directory"
chain/C/1.log:2405:ERROR[11-13|09:42:59.059] Failed to persist clean trie cache       error="cannot move temporary dir \"fastcache.tmp.964441462\" to \"
\": rename fastcache.tmp.964441462 : no such file or directory"
chain/C/1.log:3607:ERROR[11-13|10:42:59.060] Failed to persist clean trie cache       error="cannot move temporary dir \"fastcache.tmp.630813789\" to \"
\": rename fastcache.tmp.630813789 : no such file or directory"
chain/C/1.log:4808:ERROR[11-13|11:42:59.053] Failed to persist clean trie cache       error="cannot move temporary dir \"fastcache.tmp.796284440\" to \"
\": rename fastcache.tmp.796284440 : no such file or directory"
chain/C/1.log:6010:ERROR[11-13|12:42:59.053] Failed to persist clean trie cache       error="cannot move temporary dir \"fastcache.tmp.247948951\" to \"
\": rename fastcache.tmp.247948951 : no such file or directory"
chain/C/1.log:7212:ERROR[11-13|13:42:59.060] Failed to persist clean trie cache       error="cannot move temporary dir \"fastcache.tmp.949192970\" to \"
\": rename fastcache.tmp.949192970 : no such file or directory"
chain/C/1.log:8413:ERROR[11-13|14:42:59.055] Failed to persist clean trie cache       error="cannot move temporary dir \"fastcache.tmp.017352929\" to \"
\": rename fastcache.tmp.017352929 : no such file or directory"
```

**Comment by michaelbnewman** [comment]
I see the same behavior happening still in v1.1.1 (Ubuntu Server 20.04, amd64)

**Comment by romeshniriella** [comment]
Im also having this issue. v1.3.2

**Comment by danlaine** [comment]
This should be resolved now
