### ISSUE TITLE
parsing failed errors and panic/crash in 1.0.4-update-id-1

### ISSUE THREAD

**Issue by cryptonote-social** [ava-labs/avalanchego#577]
After upgradeing to 1.0.4-update-id-1 from 1.0.3, my validator regularly prints out errors of the form:

ERROR[10-31|09:08:06] <X Chain> snow/engine/avalanche/state/state.go#35: Parsing failed on saved vertex.
Prefixed key = 
....

Not sharing the full output since I don't know if it contains sensitive data, but let me know if it's safe to do so.

**Operating System**
Ubuntu 18

**Additional context**
I also had a panic/crash in the middle of the night, not sure if related or an issue on its own. Note that 1.0.3 had none of these problems and ran perfectly since the day it was released.

FATAL[10-31|03:12:02] <X Chain> utils/logging/log.go#269: Panicing due to:
runtime error: invalid memory address or nil pointer dereference
From:
goroutine 5295 [running]:
github.com/ava-labs/avalanchego/utils/logging.Stacktrace.String(0x434600, 0xc00002cf01, 0x7f7678097ba8)
        /home/cs/src/github.com/ava-labs/avalanchego/utils/logging/stack.go:20 +0x71
fmt.(*pp).handleMethods(0xc00d8dc000, 0x73, 0x6400000001)
        /usr/local/go/src/fmt/print.go:630 +0x302
fmt.(*pp).printArg(0xc00d8dc000, 0xec3f20, 0xc00135c440, 0x73)
        /usr/local/go/src/fmt/print.go:713 +0x1e4
fmt.(*pp).doPrintf(0xc00d8dc000, 0xfe8a0c, 0x1c, 0xc00002d508, 0x2, 0x2)
        /usr/local/go/src/fmt/print.go:1030 +0x15a
fmt.Sprintf(0xfe8a0c, 0x1c, 0xc00002d508, 0x2, 0x2, 0xc0044d0960, 0x47)
        /usr/local/go/src/fmt/print.go:219 +0x66
github.com/ava-labs/avalanchego/utils/logging.(*Log).format(0xc0029745b0, 0x1, 0xfe8a0c, 0x1c, 0xc00002d508, 0x2, 0x2, 0x8, 0xc000062a80)
        /home/cs/src/github.com/ava-labs/avalanchego/utils/logging/log.go:187 +0x123
github.com/ava-labs/avalanchego/utils/logging.(*Log).log(0xc0029745b0, 0x1, 0xfe8a0c, 0x1c, 0xc00002d508, 0x2, 0x2)
        /home/cs/src/github.com/ava-labs/avalanchego/utils/logging/log.go:157 +0x113
github.com/ava-labs/avalanchego/utils/logging.(*Log).Fatal(...)
        /home/cs/src/github.com/ava-labs/avalanchego/utils/logging/log.go:202
github.com/ava-labs/avalanchego/utils/logging.(*Log).StopOnPanic(0xc0029745b0)
        /home/cs/src/github.com/ava-labs/avalanchego/utils/logging/log.go:269 +0xf4
panic(0xe7d220, 0x1e3c5a0)
        /usr/local/go/src/runtime/panic.go:967 +0x15d
github.com/ava-labs/avalanchego/snow/engine/avalanche/state.(*innerVertex).Bytes(...)
        /home/cs/src/github.com/ava-labs/avalanchego/snow/engine/avalanche/state/vertex.go:58
github.com/ava-labs/avalanchego/snow/engine/avalanche/state.(*uniqueVertex).Bytes(0xc00a9a3ef0, 0x15df460e84ee9f04, 0xb62a9f7251373a2b, 0x4aff26723b4b7624)
        /home/cs/src/github.com/ava-labs/avalanchego/snow/engine/avalanche/state/unique_vertex.go:232 +0xd
github.com/ava-labs/avalanchego/snow/engine/avalanche.(*Transitive).Get(0xc002b52280, 0xc00796dd20, 0x84ee9f0400002c14, 0x51373a2b15df460e, 0x3b4b7624b62a9f72, 0xcd09b1cb4aff2672, 0xc0f29b0a98, 0xc00297464c, 0x14d2160)
        /home/cs/src/github.com/ava-labs/avalanchego/snow/engine/avalanche/transitive.go:140 +0x86
github.com/ava-labs/avalanchego/snow/networking/router.(*Handler).handleValidatorMsg(0xc002b52a00, 0x7, 0xc00796dd20, 0x84ee9f0400002c14, 0x51373a2b15df460e, 0x3b4b7624b62a9f72, 0xcd09b1cb4aff2672, 0xf29b0a98, 0x0, 0x0, ...)
        /home/cs/src/github.com/ava-labs/avalanchego/snow/networking/router/handler.go:538 +0x552
github.com/ava-labs/avalanchego/snow/networking/router.(*Handler).dispatchMsg(0xc002b52a00, 0x7, 0xc00796dd20, 0x84ee9f0400002c14, 0x51373a2b15df460e, 0x3b4b7624b62a9f72, 0xcd09b1cb4aff2672, 0xf29b0a98, 0x0, 0x0, ...)
        /home/cs/src/github.com/ava-labs/avalanchego/snow/networking/router/handler.go:267 +0x493
github.com/ava-labs/avalanchego/snow/networking/router.(*Handler).Dispatch(0xc002b52a00)
        /home/cs/src/github.com/ava-labs/avalanchego/snow/networking/router/handler.go:213 +0x6bf
github.com/ava-labs/avalanchego/utils/logging.(*Log).RecoverAndPanic(0xc0029745b0, 0xc0041f2920)
        /home/cs/src/github.com/ava-labs/avalanchego/utils/logging/log.go:276 +0x4f
created by github.com/ava-labs/avalanchego/chains.(*manager).buildChain
        /home/cs/src/github.com/ava-labs/avalanchego/chains/manager.go:364 +0xfd7

**Comment by cryptonote-social** [comment]
I am running v1.0.4-hotfix now, and so far no parsing errors, for what it's worth.

**Comment by danlaine** [comment]
`1.0.4-update-id-1` is not a release.
You should only count on build listed here to work: https://github.com/ava-labs/avalanchego/releases

**Comment by danlaine** [comment]
Oh, I see that that tag actually _is_ on the releases page. This was a mistake and it will be removed. My apologies.

**Comment by danlaine** [comment]
Apparently Github puts every tag on the releases tab (albeit presented differently than a release) and there's no way to disable this: https://github.community/t/tag-without-release/857

This is not ideal but I don't think there's much we can do about it.
You should only count on the _releases_ (i.e. the ones that say "released this X days ago") to work, not all tags

**Comment by cryptonote-social** [comment]
Good to know. I just assumed the tag on the top was the most recent release. Live and learn.
