### ISSUE TITLE
Getting this error missing dependencies after the upgrade!

### ISSUE THREAD

**Issue by zillabytes** [ava-labs/avalanchego#578]
INFO [11-01|01:28:29] avalanchego/main/main.go#133: IP: 51.75.170.74:9651
INFO [11-01|01:28:29] avalanchego/node/node.go#757: Node version is: avalanche/1.0.4
INFO [11-01|01:28:30] avalanchego/node/node.go#387: Set node's ID to 32bxLRLZCbfkYcC8MhCL9Ksfewrnuc1kS
INFO [11-01|01:28:30] avalanchego/node/node.go#449: Initializing API server
INFO [11-01|01:28:30] avalanchego/node/node.go#587: initializing keystore
INFO [11-01|01:28:30] avalanchego/node/node.go#598: initializing keystore API
INFO [11-01|01:28:30] avalanchego/api/server.go#152: adding route /ext/keystore
INFO [11-01|01:28:30] avalanchego/node/node.go#614: initializing metrics API
INFO [11-01|01:28:30] avalanchego/api/server.go#152: adding route /ext/metrics
INFO [11-01|01:28:30] avalanchego/node/node.go#579: initializing SharedMemory
INFO [11-01|01:28:31] avalanchego/node/node.go#670: initializing Health API
INFO [11-01|01:28:31] avalanchego/api/server.go#152: adding route /ext/health
INFO [11-01|01:28:32] avalanchego/api/server.go#152: adding route /ext/vm/rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT
INFO [11-01|01:28:32] avalanchego/api/server.go#152: adding route /ext/vm/jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq
INFO [11-01|01:28:32] avalanchego/node/node.go#630: skipping admin API initialization because it has been disabled
INFO [11-01|01:28:32] avalanchego/node/node.go#646: initializing info API
INFO [11-01|01:28:32] avalanchego/api/server.go#152: adding route /ext/info
INFO [11-01|01:28:32] avalanchego/node/node.go#709: skipping ipc API initializaion because it has been disabled
INFO [11-01|01:28:32] avalanchego/node/node.go#722: initializing aliases
INFO [11-01|01:28:32] avalanchego/node/node.go#433: initializing chains
INFO [11-01|01:28:32] avalanchego/chains/manager.go#200: creating chain:
    ID: 11111111111111111111111111111111LpoYY
    VMID:rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT
INFO [11-01|01:28:33] <P Chain> avalanchego/vms/platformvm/vm.go#378: Initializing last accepted block as 2gVf4irm992ZM54ZCXQ3hUFv2nEbVoVBs5a8HbMdMWRc9mUscf
INFO [11-01|01:28:33] <P Chain> avalanchego/snow/engine/snowman/transitive.go#58: initializing consensus engine
INFO [11-01|01:28:33] avalanchego/api/server.go#136: adding route /ext/bc/11111111111111111111111111111111LpoYY
INFO [11-01|01:28:33] avalanchego/api/server.go#82: HTTP API server listening on "127.0.0.1:9650"
INFO [11-01|01:28:40] <P Chain> avalanchego/snow/engine/common/bootstrapper.go#185: Bootstrapping started syncing with 1 vertices in the accepted frontier
INFO [11-01|01:28:46] <P Chain> avalanchego/snow/engine/snowman/bootstrap/bootstrapper.go#246: bootstrapping fetched 4 blocks. executing state transitions...
_FATAL[11-01|01:28:46] <P Chain> avalanchego/snow/networking/router/handler.go#271: forcing chain to shutdown due to: attempting to accept a block with missing dependencies_
INFO [11-01|01:28:46] <P Chain> avalanchego/snow/engine/snowman/transitive.go#135: shutting down consensus engine
INFO [11-01|01:28:47] <P Chain> avalanchego/snow/networking/router/handler.go#505: finished shutting down chain
INFO [11-01|01:28:47] avalanchego/node/node.go#833: shutting down the node
INFO [11-01|01:28:47] avalanchego/node/node.go#839: node shut down successfully
INFO [11-01|01:28:47] avalanchego/nat/nat.go#152: Unmapped all ports

**Comment by danlaine** [comment]
@zillabytes Hi, thanks for reporting.

Can you reproduce this issue?

Was this immediately after you did a version upgrade?

Was this node started with an empty database?

What command line arguments did you run with?

**Comment by danlaine** [comment]
Any updates, @zillabytes ?

**Comment by danlaine** [comment]
Closing for now. Feel free to re-open and comment with the answers to my questions above. Thanks.
