### ISSUE TITLE
Assets and balance disappear from node wallet

### ISSUE THREAD

**Issue by mahofmahof** [ava-labs/avalanchego#586]
**Describe the bug**
I created assets and nfts from the wallet at my nod,now i cannot see them when i try get all balances::
curl -X POST --data '{
"jsonrpc":"2.0",
"id" : 1,
"method" :"avm.getAllBalances",
"params" :{
"address":"X-avax1n9fvwa976dqjz9ypytw7hpvqywc8ue8x6dzjls"
}
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
{"jsonrpc":"2.0","result":{"balances":[{"asset":"2Kry7Gn8AJTmbMeWuQdGLUwdhzj3g8VCG6KLMB7eg4AbNVHXN2","balance":"19051905"},{"asset":"64hgTXXSDNaaeQFsjZZWXWmVNKJmJHTMrhSZgoATyGhwsupDc","balance":"19029990"}]},"id":1}

but from explorer i can see them there are 16 assets: https://explorer.avax.network/address/X-avax1n9fvwa976dqjz9ypytw7hpvqywc8ue8x6dzjls

and also at the last situation i sent 1 avax to this wallet minted 2 nfts from node balance is 0 but from explorer 0.002 fee is burned and there is 5.8 avax https://explorer.avax.network/address/X-avax1n9fvwa976dqjz9ypytw7hpvqywc8ue8x6dzjls
my node version is avalanche/1.0.4 [network=mainnet, database=v1.0.0, commit=032a79a3dcb928f7bc0fcac7f30ed13ab6e7aae6]
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Operating System**
Ubuntu 20.04
my node version is avalanche/1.0.4 [network=mainnet, database=v1.0.0

**Additional context**

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by mahofmahof** [comment]
i figured it out i was not writing "changeAddr" during creating nft because of that the balance and assets disapper from the wallet at node, now i tried different address and create nft  with "changeAddr" and the balance did not disapperar, but for the other wallet still cannot see the balances and assets from node. but i can see at the explorer. The address is this: X-avax1n9fvwa976dqjz9ypytw7hpvqywc8ue8x6dzjls  How can i get them back?

**Comment by danlaine** [comment]
Based on discussion on Discord, the "missing" tokens are because `getAllBalances` currently only works as expected when the given address has <= 1024 UTXOs. We're working on a fix for this.
