### ISSUE TITLE
avm.getBalance on new blockchain return "404 page not found"

### ISSUE THREAD

**Issue by quentingosset** [ava-labs/avalanchego#623]
**Describe the bug**
When creating a blockchain on a previously created subnet it is impossible to access the balance of this blockchain. We get an error "404 page not found".

**To Reproduce**
**All calls were made via the Postman collection provided by Avalanche.**

1. Create a Local Test Network : [https://docs.avax.network/build/tutorials/platform/create-a-local-test-network](url)
don't use avash, execute 5 sparate node in command line
2.  Create a Subnet : [https://docs.avax.network/build/tutorials/platform/create-a-subnet](url)
![image](https://user-images.githubusercontent.com/6824137/100651870-6b8c0d80-3346-11eb-838d-eed8c68da189.png)
![image](https://user-images.githubusercontent.com/6824137/100651916-8068a100-3346-11eb-88f5-5f74f514406b.png)
![image](https://user-images.githubusercontent.com/6824137/100651931-86f71880-3346-11eb-99af-c8c751302f32.png)
![image](https://user-images.githubusercontent.com/6824137/100652004-9aa27f00-3346-11eb-8e02-5b7b7ae356d0.png)
![image](https://user-images.githubusercontent.com/6824137/100652016-9ece9c80-3346-11eb-97d9-b65aa31297fe.png)
![image](https://user-images.githubusercontent.com/6824137/100652046-a726d780-3346-11eb-8d0a-9aa0de970ba6.png)

3. Adding a Subnet Validator : [https://docs.avax.network/build/tutorials/nodes-and-staking/add-a-validator#adding-a-subnet-validator](url)
![image](https://user-images.githubusercontent.com/6824137/100652083-b0b03f80-3346-11eb-96a7-d166e2204e01.png)

4. Create a Blockchain : [https://docs.avax.network/build/tutorials/platform/create-a-new-blockchain](url)
- I created an address on the X-Chain that will be the address that will hold the created token.
![image](https://user-images.githubusercontent.com/6824137/100652314-084eab00-3347-11eb-8891-558ee2ef7571.png)

![image](https://user-images.githubusercontent.com/6824137/100652406-2e744b00-3347-11eb-8cc4-2b92670ec62b.png)
![image](https://user-images.githubusercontent.com/6824137/100652521-5663ae80-3347-11eb-91d0-4fc29dadc1a7.png)
![image](https://user-images.githubusercontent.com/6824137/100652587-6e3b3280-3347-11eb-8595-e6c2b693ddc4.png)
![image](https://user-images.githubusercontent.com/6824137/100655518-b2303680-334b-11eb-9696-1370e7d9233f.png)

**Expected behavior**
I need to get the token number of "asset1" for the address provided on the previously created blockchain as on the tutorial so the answer should be :
`{
    "jsonrpc": "2.0",
    "result": {
        "balance": "100000"
    },
    "id": 1
}`

**Operating System**
Ubuntu 18.04.5 LTS

**Comment by StephenButtolph** [comment]
Thanks for filling this out! On the node that you want validating this new subnet, did you add this subnet to the [node's whitelist](https://docs.avax.network/build/tutorials/nodes-and-staking/add-a-validator#whitelisting-the-subnet)? This is required for the node to actually run the subnet (and all of it's chains). Otherwise the chain will be ignored and you'll see this 404.

**Comment by quentingosset** [comment]
I work in sandbox mode so I don't use a "database" record. If I follow your resonance it means that I have to activate the database knowing that the whitelist requires a restart of my node?

Otherwise, I tried your technique and I have the same error BUT this time I have an error that appeared in my node at launch.
![image](https://user-images.githubusercontent.com/6824137/100667382-b9127580-335a-11eb-8083-91e6123bbc54.png)

**Comment by StephenButtolph** [comment]
Ah! Well, those errors aren't good! I've submitted a PR, #624, to fix that issue.

On your end though, it seems that you're trying to create a `timestampvm`, while you're passing in genesis data for the `avm`. Inside the `platform.createBlockchain` call, did you intend to pass in `"vmID":"avm"` rather than `"vmID":"timestamp"`?

**Comment by quentingosset** [comment]
I admit that there is not much explanation about the vmId "Timestamp" & "avm" so I did the tests on the 2 x) 
I have the same problem whether it's vmId="avm" or vmId="timestamp" I just did a test again with vmId="avm" and still 404 page not found in ayantt whitelist the newly created subnet.

tomorrow I'm going to put a video of the complete manipulation with the creation of a blockchain of vmID of type "timestamp" and a vmID of type "avm" so that you'll be able to analyze this in more detail (maybe there's a step I'm skipping but it seems weird to me)

**Comment by quentingosset** [comment]
Hello @StephenButtolph ,
Here is the complete video of the creation of a local testnet + keystore + subnet + subnetvalidator + genesis + blockchain x) with the value "avm" as vmId.

I've also added some pictures because the above mentioned error that is submitted in your PR seems to be maybe the cause because normally it should have the mapping right after what it doesn't seem to have.

[](https://drive.google.com/file/d/1V1jv_hK-UE90I0jdXmmfkDDEVWv3AQYI/view?usp=sharing)

![image](https://user-images.githubusercontent.com/6824137/100739425-53180380-33d7-11eb-9e13-2d3646701a86.png)
![image](https://user-images.githubusercontent.com/6824137/100739579-8e1a3700-33d7-11eb-9759-5315af4a7863.png)
![image](https://user-images.githubusercontent.com/6824137/100739729-d2a5d280-33d7-11eb-85de-5911b4c4fca2.png)

**Comment by quentingosset** [comment]
@StephenButtolph 
After debug, I noticed that for the mapping of a chain, it performs a search on the validator set which is in a list "subnetToVdrs" however I notice that this list is overwritten and not updated. 
In my screen, you can see the creation of the P-Chain, this one has correctly the 2 subnets in its "subnetToVdrs" array however from the X-Chain, the "subnetToVdrs" array has only the main subnet and not the recently created subnet. 
The X-Chain being on the "main" subnet there is no problem of research however when we arrive at the creation of "MY-CHAIN" the only subnet available in the array is the main subnet and therefore it exits because it does not find the subnet relative to "MY-CHAIN".

P-Chain
![image](https://user-images.githubusercontent.com/6824137/100946471-b1da9b80-3503-11eb-9fe8-6c9d9bfa5727.png)

X-Chain
![image](https://user-images.githubusercontent.com/6824137/100946689-26153f00-3504-11eb-8ef5-04c43b6f61c6.png)

MY-CHAIN
![image](https://user-images.githubusercontent.com/6824137/100946710-35948800-3504-11eb-9a1c-47ab759bbb8b.png)

**Comment by tbrunain** [comment]
Am trying to do the same as @quentingosset and am getting the same kind of error message .

```
INFO [12-04|17:17:01] /Users/tbrunain/Codespace/AVA/gecko/chains/manager.go#197: creating chain:
    ID: 2VPESvi3TaRGZrkrSBR3sNDqcU7GZRbqjw7VnQcqbR8cSiboiG
    VMID:jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq
INFO [12-04|17:17:01] <C Chain> /Users/tbrunain/Codespace/AVA/gecko/snow/engine/snowman/bootstrap/bootstrapper.go#243: bootstrapping fetched 0 blocks. executing state transitions...
INFO [12-04|17:17:01] <C Chain> /Users/tbrunain/Codespace/AVA/gecko/snow/engine/snowman/bootstrap/bootstrapper.go#284: executed 0 blocks
INFO [12-04|17:17:01] <2VPESvi3TaRGZrkrSBR3sNDqcU7GZRbqjw7VnQcqbR8cSiboiG Chain> /Users/tbrunain/Codespace/AVA/gecko/vms/avm/vm.go#651: initializing with AssetID 2TgzHyTFSwmq53KkabyNYTHZ9xiZAj2XQD9qSbi5C8z7PpiT8t
INFO [12-04|17:17:01] <2VPESvi3TaRGZrkrSBR3sNDqcU7GZRbqjw7VnQcqbR8cSiboiG Chain> /Users/tbrunain/Codespace/AVA/gecko/snow/engine/avalanche/transitive.go#62: initializing consensus engine
ERROR[12-04|17:17:01] /Users/tbrunain/Codespace/AVA/gecko/chains/manager.go#206: Error while creating new chain: unknown validator set for provided chain
INFO [12-04|17:17:01] /Users/tbrunain/Codespace/AVA/gecko/chains/manager.go#197: creating chain:
    ID: 2VPESvi3TaRGZrkrSBR3sNDqcU7GZRbqjw7VnQcqbR8cSiboiG
    VMID:jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq
ERROR[12-04|17:17:01] /Users/tbrunain/Codespace/AVA/gecko/chains/manager.go#206: Error while creating new chain: error while creating new avalanche vm error during vm's Initialize: duplicate metrics collector registration attempted
INFO [12-04|17:17:01] /Users/tbrunain/Codespace/AVA/gecko/chains/manager.go#197: creating chain:
    ID: 2VPESvi3TaRGZrkrSBR3sNDqcU7GZRbqjw7VnQcqbR8cSiboiG
    VMID:jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq
ERROR[12-04|17:17:01] /Users/tbrunain/Codespace/AVA/gecko/chains/manager.go#206: Error while creating new chain: error while creating new avalanche vm error during vm's Initialize: duplicate metrics collector registration attempted
INFO [12-04|17:17:01] <C Chain> /Users/tbrunain/Codespace/AVA/gecko/snow/engine/snowman/transitive.go#116: bootstrapping finished with NwH5W45Ho9TgNwPbsmX8hQqwmshaks3issR1Nza8ULNdyYsGE as the last accepted block
```

**Comment by cgcardona** [comment]
Hi. I just tested and everything is working for me

```zsh
curl --location --request POST 'http://localhost:9650/ext/bc/2VQW9WHsn7JMQZHaV1grhpW74dJSd57jDeLkWmRJrYA2Hu8h8Q' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "id"     : 1,
    "method" :"avm.getAllBalances",
    "params" :{
        "address":"2VQW9WHsn7JMQZHaV1grhpW74dJSd57jDeLkWmRJrYA2Hu8h8Q-local18jma8ppw3nhx5r4ap8clazz0dps7rv5u00z96u"
    }
}'
{
    "jsonrpc": "2.0",
    "result": {
        "balances": [
            {
                "asset": "asset1",
                "balance": "100000"
            }
        ]
    },
    "id": 1
}
```

Some questions

1. Are you using [avash](https://github.com/ava-labs/avash)? If so, our `master` branch doesn't support `--whitelisted-subnets`. I've created this PR to add support. So try rebuilding `avash` from the `whitelisted-subnets` branch.
2. Are you restarting your validating node w/ the `--whitelisted-subnets` flag?

**Comment by danlaine** [comment]
Closing for age
