### ISSUE TITLE
NAT Traversal / UPnP doesn't work on Windows

### ISSUE THREAD

**Issue by ssg** [ava-labs/avalanchego#638]
**Describe the bug**
When starting avalanchego.exe, NAT traversal/UPnP always fails despite that it's available on Windows and other apps work fine with UPnP.

**To Reproduce**
Start avalanchego.exe
Observe message: `ERROR[12-04|13:42:47] avalanchego/main/main.go#92: UPnP or NAT-PMP router attach failed, you may not be listening publicly, please confirm the settings in your router`

**Expected behavior**
It should work without problems.

**Operating System**
Windows 10 Pro 20H2 (Build 19042.630)

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
UPnP can be fickle and every networking setup is a little different.
That means that unfortunately, it's hard to diagnose/fix issues like this.
Your best bet is to forward the staking port (9651 by default) on your router,
Going to close this but feel free to open an issue for improving UPnP with the enhancement tag.
