### ISSUE TITLE
Add database benchmarks

### ISSUE THREAD

**Issue by danlaine** [ava-labs/avalanchego#654]
AvalancheGo has a database interface type used across the code base: https://github.com/ava-labs/avalanchego/blob/master/database/database.go

There are several implementations of that interface: https://github.com/ava-labs/avalanchego/blob/master/database/database.go

We'd like a set of benchmark tests that we can run to see how well a given database implementation performs at various operations (reads, writes, iterates, etc.). Ideally the benchmarks should be formatted the same as the correctness tests: https://github.com/ava-labs/avalanchego/blob/master/database/test_database.go

**Comment by kadir96** [comment]
I'm working on this

**Comment by danlaine** [comment]
This has been implemented https://github.com/ava-labs/avalanchego/blob/master/database/test_database.go
