### ISSUE TITLE
List blockchains published via IPC 

### ISSUE THREAD

**Issue by danlaine** [ava-labs/avalanchego#669]
Add a new endpoint to the [IPC API](https://docs.avax.network/build/avalanchego-apis/ipc-api) that allows a user to list the blockchains publishing to Unix domain sockets

**Comment by kadir96** [comment]
Hey @danlaine

I would like to work on this one if possible. What should the response look like? Is returning an array of chain ids enough or their consensus and decision urls are also required?

**Comment by danlaine** [comment]
Just a list of chain IDs suffices. Thanks!

**Comment by kadir96** [comment]
There you go #712! Hope I understood correctly 🤞

**Comment by aaronbuchwald** [comment]
Fixed by #726
