### ISSUE TITLE
AvalancheGo broadcasts the wrong public IP address when using reverse tunneling on the network

### ISSUE THREAD

**Issue by feux07** [ava-labs/avalanchego#672]
**Describe the bug**

I am using reverse tunneling  on my network that  my remote  machine (168.119.228.145:9651)  forwarding  all network traffics to my local machine that runs AvalancheGo but AvalancheGo broadcasts the wrong public IP address.  When I check node`s  health,  logs etc. everything is ok.

**To Reproduce**

1-) Setup a VPS ,and open port 9651

2-) Add `GatewayPorts yes` to end of /etc/ssh/sshd_config file

3-) Setup local machine with AvalancheGo with docker

4-)  Create avalanche_ssh_tunnel.service file in  /etc/systemd/system/ and  put into following content to setup simple reverse tunneling as a service
```
[Unit]
Description=AvalancheGo Tunnel systemd service.
StartLimitIntervalSec=0
[Service]
Type=simple
User=ubuntu
ExecStart=/usr/bin/ssh -N -R 9651:localhost:9651 YOUR_USERNAME@YOUR_VPS_IP
Restart=always
RestartSec=1
[Install]
WantedBy=multi-user.target
```

Enable service
```bash
sudo systemctl enable avalanche_ssh_tunnel.service
```

Reload systemctl
```bash
sudo systemctl daemon-reload
```

Start service
```bash
sudo systemctl start avalanche_ssh_tunnel.service
```

5-) Start AvalancheGo with docker  
```bash
docker run -v ~/.avalanchego/:/root/.avalanchego/ -d -p 9651:9651 YOUR_AVALANCHE_GO_DOCKER_IMAGE_ID /avalanchego/build/avalanchego --public-ip=YOUR_VPS_PUBLIC_IP
``` 

**Expected behavior**
Avalanche Go should broadcast  the address given via --public-ip

**Screenshots**

My public IP on AvalancheGo`s logs

![image](https://user-images.githubusercontent.com/6668062/103156888-765b8600-47be-11eb-98cb-fd64b7a06ad2.png)

My node health status

![image](https://user-images.githubusercontent.com/6668062/103156903-a014ad00-47be-11eb-8775-1cf12ee6334b.png)

My public ip on some peers 

![image](https://user-images.githubusercontent.com/6668062/103156924-dce0a400-47be-11eb-9244-a2e716cd8a00.png)

My P2P port status

![image](https://user-images.githubusercontent.com/6668062/103156956-49f43980-47bf-11eb-83c5-688ba1dfffef.png)

How others see my Node Uptime (The differences are too high)

![image](https://user-images.githubusercontent.com/6668062/103157013-db63ab80-47bf-11eb-943d-b1fee68e9d49.png)

![image](https://user-images.githubusercontent.com/6668062/103157014-e1f22300-47bf-11eb-8017-5562080d5472.png)

![image](https://user-images.githubusercontent.com/6668062/103157015-e6b6d700-47bf-11eb-92d1-fd114531dc05.png)

**Operating System**
Ubuntu 20.04

**Additional context**

My Node id : NodeID-46qmbCukcwv6VgLse5mmQbPmpNdMxXKyf
My node`s public IP: 168.119.228.145

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by aaronbuchwald** [comment]
Thanks for bringing up this issue @feux07 . It looks like the issue here is that your node only listens for inbound connections on this port, whereas when it creates outbound connections to other nodes, that traffic is no longer going through your server so there's a discrepancy between the public IP your node is broadcasting and the IP that the connection is actually made from.

As a result, other nodes don't trust the public IP and set it to nil. In order to fix this issue, I would recommend setting up a VPN instead of reverse tunneling, so that all of your traffic comes from the same IP. You can also use SSH to setup your proxy, but this will most likely come with more overhead and less official support than if you use an official VPN.

**Comment by danlaine** [comment]
Closing in light of the above comment.

Let us know if you have any other problems.
