### ISSUE TITLE
Optimize log files and logrotation

### ISSUE THREAD

**Issue by holisticode** [ava-labs/avalanchego#699]
Currently the nesting of log files is a bit messy for the avalanchego node.
As an example:
```
$ tree .avalanchego
.avalanchego
├── 0.log
├── chain
│   ├── C
│   │   ├── 0.log
│   │   └── http
│   │       └── 0.log
│   ├── P
│   │   ├── 0.log
│   │   └── http
│   │       └── 0.log
│   └── X
│       ├── 0.log
│       ├── 1.log
│       ├── 10.log
│       ├── 11.log
│       ├── 12.log
│       ├── 13.log
│       ├── 14.log
│       ├── 15.log
│       ├── 16.log
│       ├── 17.log
│       ├── 18.log
│       ├── 19.log
│       ├── 2.log
│       ├── 20.log
│       ├── 21.log
│       ├── 22.log
│       ├── 23.log
│       ├── 24.log
│       ├── 25.log
│       ├── 26.log
│       ├── 27.log
│       ├── 28.log
│       ├── 29.log
│       ├── 3.log
│       ├── 30.log
│       ├── 31.log
│       ├── 32.log
│       ├── 33.log
│       ├── 34.log
│       ├── 35.log
│       ├── 36.log
│       ├── 37.log
│       ├── 38.log
│       ├── 39.log
│       ├── 4.log
│       ├── 40.log
│       ├── 41.log
│       ├── 42.log
│       ├── 43.log
│       ├── 44.log
│       ├── 45.log
│       ├── 46.log
│       ├── 5.log
│       ├── 6.log
│       ├── 7.log
│       ├── 8.log
│       ├── 9.log
│       └── http
│           └── 0.log
└── http
    └── 0.log
```

Apart from being difficult to locate log files, this constitutes a challenge for log collectors like datadog and other log aggregators, which have to catch all of these files in order to send the logs to their aggregation service.

This is aggravated by the fact that log-rotation doesn't keep 0.log the latest file, but creates subsequent files 1.log, 2.log etc. until wrapping around eventually and starting at 0.log again.

This issue is to suggest a simplification of the log structure and keep only one level of log directories, e.g.

```
|- main.0.log
|- C.0.log
|- X.0.log
|- P.0.log
|- http.0.log
```

Additionally, log rotation can be "extracted" to the OS level so that the code is freed from having to manage it, as described in

https://www.digitalocean.com/community/tutorials/how-to-manage-logfiles-with-logrotate-on-ubuntu-16-04

**Comment by benber86** [comment]
i'll give this a try

**Comment by adasari** [comment]
@benber86  and @danlaine - original request requests two changes
1. log structure (folder and name)
2. log rotation extractions from OS level

if # 1 is not competed, let me know. will raise pull request. Thanks.

**Comment by danlaine** [comment]
Log file format was changed in v1.4.8
