### ISSUE TITLE
API call rejected because chain is not done bootstrapping

### ISSUE THREAD

**Issue by liuxh-go** [ava-labs/avalanchego#716]
I called avm.getTxstatus method returned an error:API call rejected because chain is not done bootstrapping.

Then I called the health.getLiveness method and returned the following information:
```
{
    "jsonrpc": "2.0",
    "result": {
        "checks": {
            "C": {
                "message": {},
                "timestamp": "2021-01-19T07:54:11.267927062Z",
                "duration": 294407,
                "contiguousFailures": 0,
                "timeOfFirstFailure": null
            },
            "P": {
                "message": {
                    "percentConnected": 0.9779923966399147
                },
                "timestamp": "2021-01-19T07:54:10.96395912Z",
                "duration": 638320781,
                "contiguousFailures": 0,
                "timeOfFirstFailure": null
            },
            "X": {
                "timestamp": "2021-01-19T07:11:11.237840495Z",
                "duration": 221537115,
                "contiguousFailures": 0,
                "timeOfFirstFailure": null
            },
            "chains.default.bootstrapped": {
                "error": {
                    "message": "X-Chain not bootstrapped"
                },
                "timestamp": "2021-01-19T07:54:09.243269312Z",
                "duration": 4330,
                "contiguousFailures": 122,
                "timeOfFirstFailure": "2021-01-19T05:53:59.242106218Z"
            },
            "network.validators.heartbeat": {
                "message": {
                    "heartbeat": 1611042849
                },
                "timestamp": "2021-01-19T07:54:09.243267845Z",
                "duration": 2974,
                "contiguousFailures": 0,
                "timeOfFirstFailure": null
            }
        },
        "healthy": false
    },
    "id": 1
}
```

How can i fix this error

**Comment by StephenButtolph** [comment]
What version of Avalanchego are you running? Assuming you are running `v1.1.3` then bootstrapping the node can take a couple hours. How long has the node been running for? If you're running an older version, then I'd try upgrading, as there was previously a bug that caused bootstrapping to take extremely long.

**Comment by liuxh-go** [comment]
Thanks, this problem is solved

**Comment by liuxh-go** [comment]
Now there is a new problem, I used utxo to assemble the transaction locally, call avm.issueTx method to send the transaction, but the error of `missing utxo` is returned

**Comment by danlaine** [comment]
Can you provide more information? How are you creating the transaction, exactly?

**Comment by liuxh-go** [comment]
This is my transaction string:00000000000000000001ed5f38341e436e5d46e2bb00b45d62ae97d1b050c64bc634ae10626739e35c4b0000000221e67317cbc4be2aeb00677ad6462778a8f52274b9d605df2591b23027a87dff00000007000000000098968000000000000000000000000100000001bccef25230e5af7fadb5e9d2f1732ba0c106c0e221e67317cbc4be2aeb00677ad6462778a8f52274b9d605df2591b23027a87dff000000070000000004b571c000000000000000000000000100000001c41bb1baf09d290aed9e148e9c4d76c962af8dd20000000134ac56cf2302253ab23359a4285b030c409d0c103f3e822a9ed8020137b3d35f0000000021e67317cbc4be2aeb00677ad6462778a8f52274b9d605df2591b23027a87dff0000000500000000055d4a80000000010000000000000004746573740000000100000009000000011bbcd66711ace96027f46939e403528260f4c6e65a0ff1d397123303139681577b8f683b9bffa5e10307c6148f4846796c36512cb8de2a497f1ad3a5a117064100

**Comment by liuxh-go** [comment]
Sorry, I just wrote the wrong transaction string, it’s mine now

**Comment by liuxh-go** [comment]
this cb58 encoding tx:111111111AQnUUBw3qSDsQPjSMpfHDaEBEKNrTJ7RaYqYmrA9iMR1nW6Tcd26a8C4K9oR55DDYRKSXsJ3dgtTYYMhq7EKfbtCnfmowbgjPnTqJ6SXPwFWrqvfkm9zXJ974As6NkfWtgEtmjwyc8Jk29TsGbvEM7QLyM4CBWrLyBq7kXP55sMLLQtbFUtqyKaibXogdbUv6e4roH5ahokebTwB2a18TuBy7Y3TkaTHjUfZDaM8zw2X3npiTVSnQqo3sn2oqF2BAnntQdSt8cPC47kBoT42FPsoKto8BU5PtZr8fg4yzcZjhyaFXVC6kXCFBrAbyeH5XBQLSrPw9xqW8cWb383KoKhbeVNho32DKZtWvhi7uuoo58HtFi43rWs6yPCqq4qnjvzR4HST1eH8NZ5eSFSiaB6V2ZsNkHgyzKnzBBh7YQvFdHyMNs2nT8waqL4J4TZfuXXcV7Giwbtb5nSczYoMNCaChAnWXgZ6kystT8ECJHvmKyTk4up5gZZWffHRs1

**Comment by liuxh-go** [comment]
@danlaine can you help me?

**Comment by liuxh-go** [comment]
I'm very sorry, I double-checked my transaction and found that I used a duplicate utxo. There is no problem now, thank you
