### ISSUE TITLE
avalanchego uses all of my server memory and swap ram, oom killed

### ISSUE THREAD

**Issue by smalleke** [ava-labs/avalanchego#717]
when avalanchego is running( now its v1.1.3) on ubuntu 20.04, after a while it's using all of my memory (32gig physical and 34gig swap memory), so the ubuntu kills the process with oom killer.

did the bootstrap couple of times, but it keeps coming back. also the server is only used now for running avalanche

![Screenshot_20210119_190939_com google android apps photos_2](https://user-images.githubusercontent.com/77693676/105079595-ed1f3280-5a8f-11eb-8d24-57268847457c.jpg)
![Screenshot_20210119_190947_com google android apps photos_2](https://user-images.githubusercontent.com/77693676/105079598-edb7c900-5a8f-11eb-8656-a59bc2c9a115.jpg)

log file when ubuntu killed the process

09:12:33 kernel: oom_reaper: reaped process 2110 (avalanchego), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
09:12:33 kernel: Out of memory: Killed process 2110 (avalanchego) total-vm:69267648kB, anon-rss:31916260kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:130868kB oom_score_adj:0
09:12:33 kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/cron.service,task=avalanchego,pid=2110,uid=1000
09:12:33 kernel: [   7799]     0  7799     2704      153    57344        7             0 cron
09:12:29 kernel: Tasks state (memory values in pages):
09:12:29 kernel: 0 pages hwpoisoned
09:12:29 kernel: 169955 pages reserved
09:12:29 kernel: 0 pages HighMem/MovableOnly
09:12:29 kernel: 8379718 pages RAM
09:12:29 kernel: Total swap = 35651580kB
09:12:29 kernel: Free swap  = 0kB
09:12:29 kernel: Swap cache stats: add 27352916, delete 27354770, find 5989604/10518494
09:12:29 kernel: 92 pages in swap cache
09:12:29 kernel: 2319 total pagecache pages
09:12:29 kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
09:12:28 kernel: lowmem_reserve[]: 0 0 0 0 0
09:12:28 kernel: Node 0 Normal free:60996kB min:61408kB low:91192kB high:120976kB reserved_highatomic:0KB active_anon:27364152kB inactive_anon:1811140kB active_file:1492kB inactive_file:284kB unevictable:5136kB writepending:4kB present:30408700kB managed:29794500kB mlocked:0kB kernel_stack:14336kB pagetables:136440kB bounce:0kB free_pcp:3548kB local_pcp:140kB free_cma:0kB
09:12:28 kernel: lowmem_reserve[]: 0 0 29088 29088 29088
09:12:27 kernel: Node 0 DMA32 free:122416kB min:6136kB low:9112kB high:12088kB reserved_highatomic:0KB active_anon:2850472kB inactive_anon:32036kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:4kB present:3094192kB managed:3028656kB mlocked:0kB kernel_stack:16kB pagetables:11228kB bounce:0kB free_pcp:1008kB local_pcp:120kB free_cma:0kB
09:12:27 kernel: lowmem_reserve[]: 0 2908 31996 31996 31996
09:12:27 kernel: Node 0 DMA free:11784kB min:32kB low:44kB high:56kB reserved_highatomic:0KB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15980kB managed:15896kB mlocked:0kB kernel_stack:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
09:12:27 kernel: active_anon:7553573 inactive_anon:461230 isolated_anon:32
 active_file:235 inactive_file:20 isolated_file:0
 unevictable:1284 dirty:1 writeback:1
 slab_reclaimable:22691 slab_unreclaimable:47830
 mapped:1545 shmem:1387 pagetables:36917 bounce:0
 free:48799 free_pcp:1139 free_cma:0
09:12:27 kernel: Mem-Info:
09:12:26 kernel: R13: 0000000000000000 R14: 00000000015b20aa R15: 0000000000000000
09:12:26 kernel: R10: 0000000000000004 R11: 0000000000000202 R12: 0000000000000018
09:12:26 kernel: RBP: 000000c0006f7888 R08: 00000000015e9a20 R09: 000000000000da5a
09:12:26 kernel: RDX: 0000000000001746 RSI: 000000000068d434 RDI: 0000000000017460
09:12:26 kernel: RAX: 0000000001b86dc0 RBX: 00000000016306b0 RCX: 000000000000595b
09:12:26 kernel: RSP: 002b:000000c0006f7878 EFLAGS: 00010206
09:12:26 kernel: Code: Unable to access opcode bytes at RIP 0x457a52.
09:12:26 kernel: RIP: 0033:0x457a7c
09:12:26 kernel:  asm_exc_page_fault+0x1e/0x30
09:12:20 kernel: Call Trace:
09:12:20 kernel: Hardware name: HP ProLiant DL360p Gen8, BIOS P71 07/01/2015
09:12:19 kernel: CPU: 2 PID: 2121 Comm: avalanchego Tainted: G          I       5.8.0-38-generic #43~20.04.1-Ubuntu
09:12:18 kernel: avalanchego invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0

**Comment by danlaine** [comment]
Did you ever run AvalancheGo version 1.0.0 on this computer? There's a known issue with that version that might lead to this happening. If so, you can fix this issue by re-bootstrapping your node. To do so, delete the database folder ($HOME/.avalanchego/db by default) and start the node again. Be sure to export any private keys held in the node before doing so. Also, be sure not to delete your staking cert/key (~/.avalanchego/staking by default.)

**Comment by smalleke** [comment]
Hi,

I already did this. And the problem was still there, but I think I fixed
the problem for now.
Instead of using the pre build version of avalanchego, I build it myself
from source code and now it's running like it should. So maybe there's
something wrong with the prebuild versions, used version 1.1.2. And 1.1.3.

Op vr 22 jan. 2021 15:30 schreef danlaine <notifications@github.com>:

**Comment by danlaine** [comment]
Hmm I don't see why the pre-built binary should make any difference but in any case, since you're not having this issue anymore, I'm going to close this. Let us know if it becomes an issue again.
