### ISSUE TITLE
Crash due to wrong path used for evm in the release packages?

### ISSUE THREAD

**Issue by ssg** [ava-labs/avalanchego#727]
**Describe the bug**
avalanchego tries to look for evm under `build/plugins/evm` while it's under `plugins/evm` in the release package `avalanchego-linux-amd64-v1.1.3.tar.gz`. Not sure if the crash is directly related though but still causes node to fail creating a new chain.

**To Reproduce**
Download release package.
Run avalanchego.

**Expected behavior**
evm should be run without issues.

**Screenshots**
Observe these errors: 

```
ERROR[01-15|18:20:00] avalanchego/chains/manager.go#210: Error while creating new chain: error while creating vm: fork/exec build/plugins/evm: no such file or directory
INFO [01-15|18:30:36] avalanchego/chains/manager.go#201: creating chain:
    ID: 2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5
    VMID:mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6
ERROR[01-15|18:30:36] avalanchego/chains/manager.go#210: Error while creating new chain: error while creating vm: fork/exec build/plugins/evm: no such file or directory
INFO [01-15|18:31:23] avalanchego/chains/manager.go#201: creating chain:
    ID: 2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5
    VMID:mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6
ERROR[01-15|18:31:23] avalanchego/chains/manager.go#210: Error while creating new chain: error while creating vm: fork/exec build/plugins/evm: no such file or directory
INFO [01-15|18:39:41] avalanchego/chains/manager.go#201: creating chain:
    ID: 2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5
    VMID:mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6
ERROR[01-15|18:39:41] avalanchego/chains/manager.go#210: Error while creating new chain: error while creating vm: fork/exec build/plugins/evm: no such file or directory
INFO [01-15|18:41:04] avalanchego/chains/manager.go#201: creating chain:
    ID: 2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5
    VMID:mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6
ERROR[01-15|18:41:04] avalanchego/chains/manager.go#210: Error while creating new chain: error while creating vm: fork/exec build/plugins/evm: no such file or directory
ERROR[01-16|06:30:11] avalanchego/nat/nat.go#90: Renewing port mapping try #1 from external port 9651 to internal port 9651 failed with goupnp: error performing SOAP HTTP request: Post "http://***LOCAL_GATEWAY_IP***:5555/ctl/IPConn": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
FATAL[01-16|06:43:48] <X Chain> avalanchego/snow/networking/router/handler.go#273: forcing chain to shutdown due to: failed to get parents for vertex with status: Processing
INFO [01-16|06:43:54] <X Chain> avalanchego/snow/engine/avalanche/transitive.go#132: shutting down consensus engine
```

**Operating System**
Linux x86_64

**Additional context**
avalanchego version: 1.1.3

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
This error:
```
ERROR[01-15|18:30:36] avalanchego/chains/manager.go#210: 
```
is unrelated to your node shutting down. It is saying that it can't find the C-Chain binary.
You can specify the location with the `--plugin-dir` command line argument. For example:
```
./avalanchego --plugin-dir=/path/to/plugins/directory
```
The `plugins` directory (the one you want to point to) is in the `build` directory created when you run the build script.

As for the fatal error: did you ever run AvalancheGo version 1.0.0 on this computer? There's a known issue with that version that might lead to this happening. If so, you can fix this issue by re-bootstrapping your node. To do so, delete the database folder (`$HOME/.avalanchego/db` by default) and start the node again. Be sure to export any private keys held in the node before doing so. Also, be sure **not** to delete your staking cert/key (`~/.avalanchego/staking` by default.)

Let me know if you have any questions/

**Comment by ssg** [comment]
Thanks @danlaine. I want to point out that the release package doesn't work due to default plugin directory pointing at the wrong location. You have to use --plugin-dir, while docker images have the right folder structure. Perhaps, plugins folder can be moved under build in release packages as well, or a note can be added to the README or release notes. I expect release binaries work out of the box without additional configuration and that isn't the case currently.

**Comment by danlaine** [comment]
The issue with the EVM plugin not running should be fixed in #739. Thanks for reporting that.

Did you try deleting your database and restarting? @ssg

**Comment by ssg** [comment]
@danlaine no, I just plain restarted it with correct plugin directory and it hasn't crashed since.

**Comment by danlaine** [comment]
Hmm, ok. I'm not sure why that would be the case, but if that resolved the issue then I'm going to close this.
Please let us know if it happens again, and thanks for reporting.
