### ISSUE TITLE
I wanted to test avalanche in docker, but I had a problem

### ISSUE THREAD

**Issue by hdyhdy** [ava-labs/avalanchego#741]
When I use the create local test network instruction to generate five nodes in the Ubuntu system in the virtual machine, the nodes are interconnected, and each node can complete bootstrapping.

But when I use docker to load different nodes in different containers, only one node can find all the other nodes, while the other nodes can only find the boot node.

I tried to use the ping command to confirm whether the nodes can communicate, and found that there is no problem using the ping command with each other.

**Comment by abebeos** [comment]
@hdyhdy , you need to provide the exact cli commands you used.

Most possibly you did not open the ports in the containers.

**Comment by abebeos** [comment]
@StephenButtolph , should be closable (outdated/inactive)
