### ISSUE TITLE
method handler crashed for call to: debug_traceTransaction

### ISSUE THREAD

**Issue by tasinco** [ava-labs/avalanchego#752]
**Describe the bug**
Calls to debug_traceTransaction producing on fuji:
`[{"jsonrpc":"2.0","id":0,"error":{"code":-32000,"message":"method handler crashed"}}]`

Trace from logging:
WARN [02-04|12:24:01.665] Served debug_traceTransaction            conn=127.0.0.1:53589 reqid=0          t=16.266656ms  err="method handler crashed"
DEBUG[02-04|12:24:01.692] Served txpool_content                    conn=127.0.0.1:44497 reqid=1          t="61.844µs"
DEBUG[02-04|12:24:01.760] Served debug_traceTransaction            conn=127.0.0.1:56889 reqid=0          t=501.570025ms
ERROR[02-04|12:24:01.785] RPC method debug_traceTransaction crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 78115 [running]:
github.com/ava-labs/coreth/rpc.(*callback).call.func1(0xc002af42c0, 0x16, 0xc00275bd28)
	/home/runner/go/pkg/mod/github.com/ava-labs/coreth@v0.3.17/rpc/service.go:200 +0xba
panic(0x10cf900, 0x1df6160)
	/opt/hostedtoolcache/go/1.15.5/x64/src/runtime/panic.go:969 +0x1b9
github.com/ava-labs/coreth/eth/tracers.(*dbWrapper).pushObject.func3(0xc0012700c0, 0x7ff576327780)
	/home/runner/go/pkg/mod/github.com/ava-labs/coreth@v0.3.17/eth/tracers/tracer.go:213 +0x100
gopkg.in/olebedev/go-duktape%2ev3.goFunctionCall(0x7ff51e217990, 0x10)
	/home/runner/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/duktape.go:157 +0xb8
gopkg.in/olebedev/go-duktape%2ev3._cgoexpwrap_f81c1a3ad1a4_goFunctionCall(0x7ff51e217990, 0xf6b179)
	_cgo_gotypes.go:3633 +0x2b
gopkg.in/olebedev/go-duktape%2ev3._Cfunc_duk_pcall_prop(0x7ff51e217990, 0x200000000, 0x0)
	_cgo_gotypes.go:2341 +0x4d
gopkg.in/olebedev/go-duktape%2ev3.(*Context).PcallProp.func1(0xc001270048, 0x0, 0x2, 0x7ff509399820)
	/home/runner/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/api.go:786 +0x71
gopkg.in/olebedev/go-duktape%2ev3.(*Context).PcallProp(0xc001270048, 0x0, 0x2, 0x2)
	/home/runner/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/api.go:786 +0x3f
github.com/ava-labs/coreth/eth/tracers.(*Tracer).call(0xc0016204d0, 0x125b012, 0x6, 0xc00275a408, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/ava-labs/coreth@v0.3.17/eth/tracers/tracer.go:513 +0x110
github.com/ava-labs/coreth/eth/tracers.(*Tracer).GetResult(0xc0016204d0, 0x1579be0, 0xc001ce7380, 0xc003358fa0, 0xc002ee99b0, 0x0)
	/home/runner/go/pkg/mod/github.com/ava-labs/coreth@v0.3.17/eth/tracers/tracer.go:641 +0x458
github.com/ava-labs/coreth/eth.(*PrivateDebugAPI).traceTx(0xc0002a21d8, 0x156e6c0, 0xc0026f6d40, 0x1579be0, 0xc001ce7380, 0x143aa38, 0x143aa30, 0x143aa50, 0x143aa48, 0xc002ee8e70, ...)
	/home/runner/go/pkg/mod/github.com/ava-labs/coreth@v0.3.17/eth/api_tracer.go:814 +0x9c5
github.com/ava-labs/coreth/eth.(*PrivateDebugAPI).TraceTransaction(0xc0002a21d8, 0x156e6c0, 0xc0026f6d40, 0x862d6cb70730f3c0, 0xf3949b974ec3cd75, 0x180bbe728577b4aa, 0x176a6f68d4bb1551, 0xc000f709c0, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/ava-labs/coreth@v0.3.17/eth/api_tracer.go:718 +0x270
reflect.Value.call(0xc00032ff80, 0xc0002a2ae0, 0x13, 0x125850b, 0x4, 0xc0017c4780, 0x4, 0x4, 0xc0017c47b0, 0xc0013a61b0, ...)
	/opt/hostedtoolcache/go/1.15.5/x64/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0xc00032ff80, 0xc0002a2ae0, 0x13, 0xc0017c4780, 0x4, 0x4, 0x16, 0x10, 0x0)
	/opt/hostedtoolcache/go/1.15.5/x64/src/reflect/value.go:337 +0xb9
github.com/ava-labs/coreth/rpc.(*callback).call(0xc0010e6a80, 0x156e6c0, 0xc0026f6d40, 0xc002af42c0, 0x16, 0xc0013a61b0, 0x2, 0x2, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/ava-labs/coreth@v0.3.17/rpc/service.go:206 +0x2c5
github.com/ava-labs/coreth/rpc.(*handler).runMethod(0xc000e7f320, 0x156e6c0, 0xc0026f6d40, 0xc0001a88c0, 0xc0010e6a80, 0xc0013a61b0, 0x2, 0x2, 0x2)
	/home/runner/go/pkg/mod/github.com/ava-labs/coreth@v0.3.17/rpc/handler.go:389 +0x8a
github.com/ava-labs/coreth/rpc.(*handler).handleCall(0xc000e7f320, 0xc002dfbe90, 0xc0001a88c0, 0x8)
	/home/runner/go/pkg/mod/github.com/ava-labs/coreth@v0.3.17/rpc/handler.go:337 +0x294
github.com/ava-labs/coreth/rpc.(*handler).handleCallMsg(0xc000e7f320, 0xc002dfbe90, 0xc0001a88c0, 0xc0034ca048)
	/home/runner/go/pkg/mod/github.com/ava-labs/coreth@v0.3.17/rpc/handler.go:298 +0x1be
github.com/ava-labs/coreth/rpc.(*handler).handleBatch.func2(0xc002dfbe90)
	/home/runner/go/pkg/mod/github.com/ava-labs/coreth@v0.3.17/rpc/handler.go:119 +0xf6
github.com/ava-labs/coreth/rpc.(*handler).startCallProc.func1(0xc000e7f320, 0xc0026f6cc0)
	/home/runner/go/pkg/mod/github.com/ava-labs/coreth@v0.3.17/rpc/handler.go:226 +0xd2
created by github.com/ava-labs/coreth/rpc.(*handler).startCallProc
	/home/runner/go/pkg/mod/github.com/ava-labs/coreth@v0.3.17/rpc/handler.go:222 +0x66

**To Reproduce**
curl -X POST --data @q.txt -H "Content-Type: application/json" http://127.0.0.1:9651/ext/bc/evm/rpc

[q.txt](https://github.com/ava-labs/avalanchego/files/5927181/q.txt)

Hash with issues: 0xc0f33007b76c2d8675cdc34e979b94f3aab4778572be0b185115bbd4686f6a17

**Expected behavior**
No panic

**Screenshots**

**Operating System**
linux

**Additional context**

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by aaronbuchwald** [comment]
@tasinco Could you include the complete API call to `debug_traceTransaction` that generated this error?

**Comment by tasinco** [comment]
Look at the attachment.  q.txt

**Comment by aaronbuchwald** [comment]
Ah ok, thank you I missed that

**Comment by aaronbuchwald** [comment]
Fixed by ava-labs/coreth#98
