### ISSUE TITLE
Add a timestamp (and more info) to node death console output

### ISSUE THREAD

**Issue by Met7** [ava-labs/avalanchego#756]
When I find a dead node, I see the outputs from shortly after node start, and the next line says "Killed", and that's it.
At least having a timestamp at it, to know how long it has been dead, would be helpful. But some reason for the death would be great too.

**Comment by danlaine** [comment]
The `Killed` message is coming from the Go runtime, not AvalancheGo, so we can't add a timestamp to that message.
This usually happens when the machine runs out of memory.
This shouldn't be happening, though.
Can you provide any other information as to what happens before your node dies?
Logs, CPU/memory profile, etc.

Did you ever run `v1.0.0` on this computer?

**Comment by Met7** [comment]
Ok, I understand.

The computer is older, with 4gb memory, i5, Ubuntu 20.04. I don't recall seeing it run it oom but will keep an eye out, follow the memory usage and provide more info when it happens.

Unfortunately the node dies a lot, seemingly randomly. I just find it closed, sometimes with the "Killed", sometimes without. Rarely it gives a valid reasons. On the last death it did - clock desync. I don't know why, but I suspect overloaded CPU as the computer was hot and unresponsive some time before that.
The logs never gave me any extra information.

**Comment by Met7** [comment]
Got it, see the attachments @danlaine. It is a sudden memory usage surge.
Forgot to answer your question - yes, I have ran every version since 1.0.0.
[0.log](https://github.com/ava-labs/avalanchego/files/5954
[terminal_output.txt](https://github.com/ava-labs/avalanchego/files/5954687/terminal_output.txt)
686/0.log)
![Screenshot from 2021-02-09 23-34-34](https://user-images.githubusercontent.com/2080031/107438158-5bf02880-6b30-11eb-9244-71b98885bdd4.png)

**Comment by Met7** [comment]
Had the crash again on 1.2.0, with a clean db.
Looks like duplicate with https://github.com/ava-labs/avalanchego/issues/767.

**Comment by danlaine** [comment]
@Met7

We fixed some bootstrapping issus in v1.2.1. Have you had this issue running v1.2.1? 
Thanks.

**Comment by Met7** [comment]
I started running 1.2.1 the moment it came out and it hasn't finished boot strapping yet. But no, I haven't had this exact issue in 1.2.1.
I tried going back to 1.2.0, which was running ok until it ended with "killed" again.

**Comment by danlaine** [comment]
Hi @Met7 sorry for the delay in getting back to you. Are you still having this issue?

**Comment by Met7** [comment]
Hi, no, i am on 1.2.3 which runs perfectly.
