### ISSUE TITLE
Use non-zero return value when node dies

### ISSUE THREAD

**Issue by Met7** [ava-labs/avalanchego#757]
When a node closes, for whatever reason, it returns 0. I understand that it is sort of ok since the node did not crash and ended in a controlled fashion. But it still died because of some failure.

What I suggest is to return 0 only on a manual closing of the node, and return different values otherwise.

It would be useful for the node handling. I wanted to make a simple script that would start the node again if it ends in a bad way - which would increase my uptime a lot as the node dies frequently (I am assuming changing ip being the culprit, there is an issue for that) and starting it again is all it needs. But I have no way to tell if it died by an error or by my hand.

**Comment by danlaine** [comment]
We do this now :)
