### ISSUE TITLE
Feature: Progressive chainID addressing

### ISSUE THREAD

**Issue by collincusce** [ava-labs/avalanchego#76]
Suggestion per Gun:

Current addressing is \<chainID>-\<address> . This isn't great because chainIDs are 32 byte w/4 byte checksum postfixed and then base 58 encoded. Very long. Very cumbersome. Gun had the idea of doing progressive chainIDs. The first time a chain with the chainID beginning with 7 is registered on the P-chain, from then on it can be referenced as 7-\<address>. The next time something begins with a 7 you take its second character. So say the next 7's second character is n, then you can be 7n-\<address> from then on and the system will know what you mean. The next time a 7n comes up, say the third letter is g, then you can go 7ng-\<address> and that's your short-hand for your full chainID.

**Comment by StephenButtolph** [comment]
This is a reasonable standard... But I'm not sure we want to commit to this at the client level. This would result in address parsing needing to know the full state of the P-chain... which is really annoying for implementers.
