### ISSUE TITLE
How to know the current state of my node during the synchronization

### ISSUE THREAD

**Issue by tropicar** [ava-labs/avalanchego#791]
I am a developer from [DAppNode](https://github.com/dappnode/),I am creating a visual interface for the state of the node to show the user when the node is syncing or it had already done. I read the Avalanche API documentation but I did not find methods to do it.
For example, in another project, we obtain the state of the blockchain and the current state of our node.
I tried to use the API call 
 `platform.getHeight` but during synchronization process return this message `API call rejected because chain is not done bootstrapping`
I ask this because on the logs you can see this information but I don't know if it is possible to get it using the API.
`INFO [03-02|11:30:46] <P Chain> avalanchego/snow/engine/snowman/bootstrap/bootstrapper.go#278: executed 245000 blocks`

Overall, my questions is how can I know the current state of the node during the synchronization process?

**Comment by melozo** [comment]
Hi tropicar (Colmenero),

This method can give you information about the status of all `127.0.0.1:9650/ext/health`[1] , I think the string "**healthy**" could help you. In the other hand, the synchronization of the different strings (X, C, P) is done separately.

The method I usually use to know if the node is synchronized is `info-isbootstrapped`

[1]https://docs.avax.network/build/avalanchego-apis/health-api
[2]https://docs.avax.network/build/avalanchego-apis/info-api#info-isbootstrapped

**Comment by tropicar** [comment]
Thanks for the answer! It's what I wanted to know.

**Comment by aaronbuchwald** [comment]
This would be a good feature to have to improve the information available to users during syncing, so reopening this as a feature request.

**Comment by danlaine** [comment]
On linear chains (P-Chain and C-Chain), AvalancheGo now prints `fetched X of Y blocks` when bootstrapping, so I'm going to mark this as closed. Note that for DAG chains (the X-Chain) we still don't have this because it's not possible during bootstrapping to calculate the number of vertices between the network's accepted frontier and your node's accepted frontier.

**Comment by cyberience** [comment]
I am having trouble finding this fetched X of Y blocks, could you link to the docs where this is indicated, or post the curl to get it?

**Comment by bd21** [comment]
`sudo journalctl -u avalanchego -f`

**Comment by bd21** [comment]
> I am having trouble finding this fetched X of Y blocks, could you link to the docs where this is indicated, or post the curl to get it?

`sudo journalctl -u avalanchego -f`
