### ISSUE TITLE
 forcing chain to shutdown due to: block nfCyHM7CCD8tLkms9GncjpzjzN1npC1YydqssFMpA8C9cUHxX 

### ISSUE THREAD

**Issue by tinshen** [ava-labs/avalanchego#803]
FATAL[03-12|13:54:24] <P Chain> avalanchego/snow/networking/router/handler.go#300: forcing chain to shutdown due to: failed to boostrap the chain after 50 attempts
INFO [03-12|13:54:24] <P Chain> avalanchego/snow/engine/snowman/transitive.go#148: shutting down consensus engine
INFO [03-12|13:54:25] avalanchego/node/node.go#914: shutting down node
INFO [03-12|13:54:25] avalanchego/ipcs/chainipc.go#101: shutting down chain IPCs
INFO [03-12|13:54:25] avalanchego/chains/manager.go#678: shutting down chain manager
INFO [03-12|13:54:25] avalanchego/snow/networking/router/chain_router.go#176: shutting down chain router
INFO [03-12|13:54:25] <X Chain> avalanchego/snow/engine/avalanche/transitive.go#137: shutting down consensus engine
WARN [03-12|13:54:30] avalanchego/snow/networking/router/chain_router.go#199: timed out while shutting down the chains
INFO [03-12|13:54:30] avalanchego/network/network.go#920: shutting down network
INFO [03-12|13:54:31] avalanchego/node/node.go#932: finished node shutdown
INFO [03-12|13:54:31] avalanchego/nat/nat.go#152: Unmapped all ports
FATAL[03-12|13:54:31] <C Chain> avalanchego/snow/networking/router/handler.go#300: forcing chain to shutdown due to: block nfCyHM7CCD8tLkms9GncjpzjzN1npC1YydqssFMpA8C9cUHxX failed verification during bootstrapping due to: rpc error: code = Unknown desc = unknown ancestor
INFO [03-12|13:54:31] <C Chain> avalanchego/snow/engine/snowman/transitive.go#148: shutting down consensus engine

**Comment by danlaine** [comment]
Hi, thanks for reporting. Can you please provide more information, including:
* Operating System
* Method of installation
* Command line flags in use
* AvalancheGo version

Did you ever run AvalancheGo v1.0.0 on this computer?

And any other information about this run. Thank you!

**Comment by tinshen** [comment]
ubuntu 18.04
avalanchego
version 1.2.3

**Comment by danlaine** [comment]
I think this:
```
FATAL[03-12|13:54:31] avalanchego/snow/networking/router/handler.go#300: forcing chain to shutdown due to: block nfCyHM7CCD8tLkms9GncjpzjzN1npC1YydqssFMpA8C9cUHxX failed verification during bootstrapping due to: rpc error: code = Unknown desc = unknown ancestor
```

is a red herring and not the actual issue. This is just appearing because the node is shutting down due to this:
```
failed to boostrap the chain after 50 attempts
```

which probably happened due to the internet connection being flaky.

Do you have this issue every time you run?
