### ISSUE TITLE
Node will only work the first time, and then always fails to stay up

### ISSUE THREAD

**Issue by bsdhsr** [ava-labs/avalanchego#804]
**Describe the bug**

It's the third time I'm going through this, and the third time I had to remove the db (for whatever reason, then it works, read on for more details).

After the node bootstraps, which takes days on my residential connection, as things stand it seems that the moment the daemon is stopped, it will never come back again.

It repeatedly and predictably fails with **"Failed to connect to bootstrap nodes. Node shutting down"**.

**To Reproduce**
In my setup, simply running the node again after it was successful once is enough to reliably reproduce this issue. The software becomes unusable.

**Expected behavior**

Node starts and rejoins the network without issues.

**Operating System**
FreeBSD 12.2-RELEASE-p4 amd64

**Additional context**

I've also tried to recompile the node (**v1.2.3, self-compiled**), changing (node/node.go)  "beaconConnectionTimeout = 1  * time.Minute" to 10.

Possibly relevant daemon flags (I've ran many combinations now, I seem to recall that only changing node/node.go really changed things) include:

 --disconnected-check-frequency=0 --bootstrap-retry-enabled --bootstrap-retry-max attempts=10000 --restart-on-disconnected
 
When the node starts, there are outrageous network burts, and particularly in upstream (upwards of 400KB/s - as we'll see, this is likely related). My ISP unfortunately throttles upstream at such rates, and this is likely causing something to go awry - elsewhere, pages (loaded from my workstation) start timing out, packet loss starts rising to upwards of 50%, etc. Again, the connection gets throttled.

**Now you may say "the problem is the ISP and the throttling, that's too bad**, but the very curious thing is that I was able to synchronize/bootstrap the node, even as sometimes in the process there were such bursts of bandwidth which slowed things down.

**It's like the process the node goes through when starting up is somehow much less resilient versus starting from scratch and downloading everything**.

I never got the "**Failed to connect to bootstrap nodes. Node shutting down**" error - *not even once* - under the following conditions:

- Initial sync after building the software, no database present.
- Resuming a sync aborted before the daemon managed to synchronized with the network previously.
- After nuking the database and starting over, it works, that one time.

It seems clear that there is some fragility under the specific scenario of getting back on the network once synchronization had been achieved in the past. I don't know what that could be, because at first glance it doesn't makes sense.

But I do know that I cannot join the network anymore. The only way would be deleting the db folder and starting over, but that's a lot of gigabytes, a lot of CPU time, a lot of time, **and the same thing will just end up happening again the next time I restart the daemon**.

There has to be a better way.

p.s: "**forcing chain to shutdown due to: failed to boostrap the chain after 10 attempts**" is the version of the error above that appears when using **--bootstrap-retry-max-attempts** - I've tried setting it to some insanely high number, and then the upstream bandwidth is permanently at 400KB/s or so, destroying the entire connection in the process - but it still strikes me as rather odd that *not even one attempt out of 10000 succeeds**, or that **this does not happen the first time after nuking the database**.

Feedback appreciated. I'd really like to run this node at home.

**Comment by bsdhsr** [comment]
Ok, for a moment it seemed like it was going to work (I didn't change anything, just let the node offline while attending to other things).. this doesn't make sense to me.

It's clear from the log below that the node had good connectivity and then, abruptly, it suicides..

INFO [03-13|21:26:17] node/node.go#496: initializing API server
INFO [03-13|21:26:17] node/node.go#645: initializing keystore
INFO [03-13|21:26:17] node/node.go#658: initializing keystore API
INFO [03-13|21:26:17] api/server.go#167: adding route /ext/keystore
INFO [03-13|21:26:17] node/node.go#674: initializing metrics API
INFO [03-13|21:26:17] api/server.go#167: adding route /ext/metrics
INFO [03-13|21:26:17] node/node.go#637: initializing SharedMemory
INFO [03-13|21:26:17] node/node.go#732: initializing Health API
INFO [03-13|21:26:17] api/server.go#167: adding route /ext/health
INFO [03-13|21:26:18] api/server.go#167: adding route /ext/vm/rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT
INFO [03-13|21:26:18] node/node.go#690: skipping admin API initialization because it has been disabled
INFO [03-13|21:26:18] node/node.go#706: initializing info API
INFO [03-13|21:26:18] api/server.go#167: adding route /ext/info
INFO [03-13|21:26:18] node/node.go#783: skipping ipc API initialization because it has been disabled
INFO [03-13|21:26:18] node/node.go#796: initializing aliases
INFO [03-13|21:26:18] node/node.go#480: initializing chains
INFO [03-13|21:26:18] chains/manager.go#209: creating chain:
    ID: 11111111111111111111111111111111LpoYY
    VMID:rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT
INFO [03-13|21:26:23] <P Chain> vms/platformvm/vm.go#333: initializing last accepted block as 2qbkfpjtAc8ND3qc92b2GCxKHsrQLuSXkcggWCyg1qQXR97gJu
INFO [03-13|21:26:23] <P Chain> snow/engine/snowman/transitive.go#62: initializing consensus engine
INFO [03-13|21:26:23] <P Chain> snow/engine/common/bootstrapper.go#68: Starting bootstrap...
INFO [03-13|21:26:23] api/server.go#88: HTTP API server listening on "192.168.90.10:9650"
INFO [03-13|21:26:23] api/server.go#151: adding route /ext/bc/11111111111111111111111111111111LpoYY
INFO [03-13|21:26:56] <P Chain> snow/engine/common/bootstrapper.go#296: Bootstrapping started syncing with 1 vertices in the accepted frontier
INFO [03-13|21:27:07] <P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#261: bootstrapping fetched 299 blocks. executing state transitions...
INFO [03-13|21:27:25] <P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#342: executed 299 blocks
INFO [03-13|21:27:25] <P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#275: bootstrapping is checking for more blocks before finishing the bootstrap process...
INFO [03-13|21:27:25] <P Chain> snow/engine/common/bootstrapper.go#339: Checking for new frontiers...
INFO [03-13|21:27:41] <P Chain> snow/engine/common/bootstrapper.go#296: Bootstrapping started syncing with 1 vertices in the accepted frontier
INFO [03-13|21:27:41] <P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#261: bootstrapping fetched 0 blocks. executing state transitions...
INFO [03-13|21:27:41] <P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#342: executed 0 blocks
INFO [03-13|21:27:41] <P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#281: bootstrapping fetched enough blocks to finish the bootstrap process...
INFO [03-13|21:27:41] chains/manager.go#209: creating chain:
    ID: 2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM
    VMID:jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq
INFO [03-13|21:27:41] <X Chain> snow/engine/avalanche/transitive.go#67: initializing consensus engine
INFO [03-13|21:27:41] <X Chain> snow/engine/common/bootstrapper.go#68: Starting bootstrap...
INFO [03-13|21:27:41] chains/manager.go#209: creating chain:
    ID: 2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5
    VMID:mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6
INFO [03-13|21:27:41] api/server.go#151: adding route /ext/bc/2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM/wallet
INFO [03-13|21:27:41] api/server.go#151: adding route /ext/bc/2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM/pubsub
INFO [03-13|21:27:41] api/server.go#151: adding route /ext/bc/2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM
INFO [03-13|21:27:42] <C Chain> snow/engine/snowman/transitive.go#62: initializing consensus engine
INFO [03-13|21:27:42] <C Chain> snow/engine/common/bootstrapper.go#68: Starting bootstrap...
INFO [03-13|21:27:42] <P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#295: bootstrapping is waiting for the remaining chains in this subnet to finish syncing...
INFO [03-13|21:27:42] <P Chain> snow/engine/common/bootstrapper.go#339: Checking for new frontiers...
INFO [03-13|21:27:42] api/server.go#151: adding route /ext/bc/2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5/ws
INFO [03-13|21:27:42] api/server.go#151: adding route /ext/bc/2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5/rpc
INFO [03-13|21:27:42] api/server.go#151: adding route /ext/bc/2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5/avax
INFO [03-13|21:28:38] health/service.go#114: "P" became healthy with: {"message":{"consensus":{},"vm":{"percentConnected":0.877519562690969}},"timestamp":"2021-03-13T21:28:36.116251289Z","duration":2489681661,"contiguousFailures":0,"timeOfFirstFailure":null}
FATAL[03-13|21:29:15] <P Chain> snow/networking/router/handler.go#300: forcing chain to shutdown due to: failed to boostrap the chain after 10 attempts
INFO [03-13|21:29:15] <P Chain> snow/engine/snowman/transitive.go#148: shutting down consensus engine
INFO [03-13|21:29:17] node/node.go#914: shutting down node
INFO [03-13|21:29:17] ipcs/chainipc.go#101: shutting down chain IPCs
INFO [03-13|21:29:17] chains/manager.go#678: shutting down chain manager
INFO [03-13|21:29:17] snow/networking/router/chain_router.go#176: shutting down chain router
INFO [03-13|21:29:17] <C Chain> snow/engine/snowman/transitive.go#148: shutting down consensus engine
INFO [03-13|21:29:17] <X Chain> snow/engine/avalanche/transitive.go#137: shutting down consensus engine
INFO [03-13|21:29:17] network/network.go#920: shutting down network
INFO [03-13|21:29:18] node/node.go#932: finished node shutdown
INFO [03-13|21:29:18] nat/nat.go#152: Unmapped all ports

**Comment by bsdhsr** [comment]
So, last night I left the node on a timer to restart after 4h, which checking back today, it did.

However, it appears to have stopped doing anything productive and today when I checked on it, there were roughly 1000 (!) TCP connections established, and CPU usage was 15%. But it didn't synchronize, just sat there doing whatever.

```
INFO [03-14|01:42:20] <P Chain> vms/platformvm/vm.go#333: initializing last accepted block as 2twSpLetRYLki1JfRvd2ARubd5wNR893nXwgT3mzXjAyCirsf4                                                                                                                                                                             
INFO [03-14|01:42:20] <P Chain> snow/engine/snowman/transitive.go#62: initializing consensus engine                                                                                                                                                                                                                          
INFO [03-14|01:42:20] <P Chain> snow/engine/common/bootstrapper.go#68: Starting bootstrap...                                                                                                                                                                                                                                 
INFO [03-14|01:42:20] api/server.go#88: HTTP API server listening on "xxx.xxx.xxx.xxx:9650"                                                                                                                                                                                                                                    
INFO [03-14|01:42:20] api/server.go#151: adding route /ext/bc/11111111111111111111111111111111LpoYY                                                                                                                                                                                                                          
INFO [03-14|01:42:33] <P Chain> snow/engine/common/bootstrapper.go#296: Bootstrapping started syncing with 1 vertices in the accepted frontier                                                                                                                                                                               

INFO [03-14|01:43:30] <P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#261: bootstrapping fetched 163 blocks. executing state transitions...                                                                                                                                                                          
INFO [03-14|01:43:46] <P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#342: executed 163 blocks                                                                                                                                                                                                                       
INFO [03-14|01:43:46] <P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#275: bootstrapping is checking for more blocks before finishing the bootstrap process...                                                                                                                                                       
INFO [03-14|01:43:46] <P Chain> snow/engine/common/bootstrapper.go#339: Checking for new frontiers...                                                                                                                                                                                                                        
INFO [03-14|01:44:05] health/service.go#114: "P" became healthy with: {"message":{"consensus":{},"vm":{"percentConnected":0.8047684133259139}},"timestamp":"2021-03-14T01:44:03.198095977Z","duration":2331238627,"contiguousFailures":0,"timeOfFirstFailure":null}
```

Nothing in the logs, nothing in stdout.

I don't understand why it didn't fail with the usual "forcing chain to shutdown due to: failed to boostrap the chain after 10 attempts", nor do I understand why it just sat there for hours, using bandwidth and CPU, but not updating the database or downloading blocks.

**Comment by bsdhsr** [comment]
To add some more further information, once again I left a timer that when expired starts the node while attending to other things, and we can see..

```
INFO [03-14|17:31:33] <P Chain> snow/engine/common/bootstrapper.go#296: Bootstrapping started syncing with 1 vertices in the accepted frontier
INFO [03-14|17:33:04] <P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#261: bootstrapping fetched 403 blocks. executing state transitions...
INFO [03-14|17:34:03] <P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#342: executed 741 blocks
INFO [03-14|17:34:03] <P Chain> snow/engine/snowman/bootstrap/bootstrapper.go#275: bootstrapping is checking for more blocks before finishing the bootstrap process...
INFO [03-14|17:34:03] <P Chain> snow/engine/common/bootstrapper.go#339: Checking for new frontiers...
INFO [03-14|17:34:51] health/service.go#114: "P" became healthy with: {"message":{"consensus":{},"vm":{"percentConnected":0.801990074715049}},"timestamp":"2021-03-14T17:34:49.219540655Z","duration":2329773724,"contiguousFailures":0,"timeOfFirstFailure":null}
FATAL[03-14|17:34:53] <P Chain> snow/networking/router/handler.go#300: forcing chain to shutdown due to: failed to boostrap the chain after 5 attempts
INFO [03-14|17:34:53] <P Chain> snow/engine/snowman/transitive.go#148: shutting down consensus engine
```

Since the "**forcing chain to shutdown due to: failed to boostrap the chain after 5 attempts**" is the same error message as "**Failed to connect to bootstrap nodes. Node shutting down**" but when *--bootstrap-retry-max attempts* is set, it seems to me there is a bug here.

If we examine the above messages, " Bootstrapping started syncing", and then "bootstrapping fetched 403 blocks".. so if it *started* syncing and then *fetched* blocks, how could have *failed to connect to bootstrap nodes* ?

**Comment by danlaine** [comment]
Do you have these issues running on Ubuntu? We don't support other linux distributions (though AvalancheGo may work on some OSs).

`it appears to have stopped doing anything productive`
What do you mean by this, exactly? Did it report unhealthy?

`when I checked on it, there were roughly 1000 (!) TCP connections established, and CPU usage was 15%.`
That's expected; your node is connecting to the rest of the network.

Not immediately sure why you would have issues only when restarting the node, but not with a fresh database. Will talk with the rest of the team and comment again.

**Comment by bsdhsr** [comment]
I have not tried running on Ubuntu, or even Linux for that matter.

> What do you mean by this, exactly? Did it report unhealthy?

As I wrote above, "Nothing in the logs, nothing in stdout." -- as far as I can see, it's just using huge amounts of bandwidth and moderate CPU, but not downloading any blocks.

> That's expected; your node is connecting to the rest of the network.

None of the other daemons I run does even close to 1000 connections. There should probably be a disclaimer about this in the requirements for running a node page, it's certainly not normal. Is that number expected to go up with more nodes joining the network, and can the protocol still work if there was an option to limit it? (see #805)

> Not immediately sure why you would have issues only when restarting the node, but not with a fresh database. Will talk with the rest of the team and comment again.

Please do. FWIW, I highly doubt that this is related to the operating system by the way, though to be sure in a pluralistic world it good practice to support more than just Linux.

If you have any ideas for troubleshooting let me know.

**Comment by bsdhsr** [comment]
Any news?

**Comment by danlaine** [comment]
`None of the other daemons I run does even close to 1000 connections.`

Which daemons are you referring to here?

`it's certainly not normal.`

In the context of the Avalanche network it is indeed normal, but you're right that we should include this in the hardware requirements. Can you tell me about this node's internet connection?

`Is that number expected to go up with more nodes joining the network, and can the protocol still work if there was an option to limit it?`

At present, a validator has to be connected to every node in the network. We will likely change the networking layer in the future so that a node only needs to be connected to a subset of the network.

` it's just using huge amounts of bandwidth and moderate CPU, but not downloading any blocks.`

So the node is not dying, right? It just isn't printing anything to the logs?

Again, we don't officially support FreeBSD so you may have more luck on Ubuntu.

**Comment by bsdhsr** [comment]
> Which daemons are you referring to here?

bitcoin, monero, ethereum, lightning network daemon.

> In the context of the Avalanche network it is indeed normal, but you're right that we should include this in the hardware requirements.

Absolutely! Keep in mind that in many areas of the world, people don't have gigabit connections with low latency.

>  If your ISP is throttling you or limiting your TCP connections, I'm not confident your node will be able to run.

Unfortunately I am beginning to think the same.

> At present, a validator has to be connected to every node in the network. We will likely change the networking layer in the future so that a node only needs to be connected to a subset of the network.

Wow, yeah, that's a problem. Or has the potential to be. I suggest you guys add this to the documentation, it's an important detail.

> So the node is not dying, right? It just isn't printing anything to the logs?

That is the case. It just sits there using CPU and tcpdump is more active than a coke den at midnight, but the daemon is making no progress according to the logs (there are no entries).

> Again, we don't officially support FreeBSD so you may have more luck on Ubuntu.

I've compiled and run all sorts of exotic software in Go, Rust and C++ that was made for Linux and works just fine on BSD or Solaris. I *really* doubt that is the problem here - 99% of the time, if it compiles and doesn't segfault in the first minute, it'll be fine.

Instead, I believe the code was written with the assumption that there is a powerful (high bandwidth, low latency) connection underneath, and it just doesn't deal very well with the situations when that is not the case.

Considering that this is supposed to be a decentralized network where anyone can participate, I think it's worth investigating deeper what the issue is here, and if you are willing to help, I'm willing to try things out (patches, etc) on my end.

If we commit to finding out why it's not working - and bear in mind, when it's not working, it's *still* bursting at 400KB/s upstream and about the same downstream, which is no joke - I am willing to spin a linux vm and copy the avalanche datadir there to rule the OS out.

**Comment by danlaine** [comment]
@bsdhsr Hi sorry for the very long delay in responding to you. Are you still having this issue? We've made some changes in since this issue was opened that should help to alleviate problems with high network usage.

**Comment by danlaine** [comment]
Going to close this. Please open a new issue if you're having issues. Thanks.

**Comment by densone** [comment]
Out of the box bsd comes with low defaults in the kernel. I suspect adjusting somaxconn rona much higher number would help.
