### ISSUE TITLE
Feature Request: Network Resource Limits

### ISSUE THREAD

**Issue by bsdhsr** [ava-labs/avalanchego#805]
At present there does not seem to be any way to configure basic network resource consumption/usage limits, namely the following.

  - Incoming peer count.
  - Outgoing peer count.
  - Max download KB/s.
  - Max upload KB/s.

Decentralization is said to be a core part of Avalanche's philosophy, and the protocol is advertised as being "lightweight" in resource usage.

I wouldn't exactly call 400KB/s multi-minute bursts of upstream traffic and 1000+ TCP connections established to all corners of this earth exactly that.

Every time I launch my avalanche node, it breaks the Internet here. The sustained 400KB/s are enough to kill the connection temporarily because of ISP throttling.

If the protocol can work at all without such demands on peer connection counts and upstream bandwidth usage, then please consider adding tunables for limiting resource consumption according to the limitations that may be present for this or that node operator's network.

**Comment by bsdhsr** [comment]
> Every time I launch my avalanche node, it breaks the Internet here. The sustained 400KB/s are enough to kill the connection temporarily because of ISP throttling.

Just further comment on this, and related to #804, for whatever reason (there's nothing in the logs or in stdout/err) this massive burst just runs continuously now, it's like it's failing to do something at startup and just bruteforcing its way - whereas, were I to delete the database and start over, the burst would happen, then it would occasionally happen, but most of the time bandwidth usage would be within acceptable range.

For reasons unknown it doesn't do that any time after it's synced the first time, but that's #804.

It is possible that implementing the features suggested here would work around this problem, as the failure that induces the node to happily suicide itself might be caused by the bruteforce way it does whatever it's trying to do when it starts up now. I'm hoping someone familiar with the code will have better insight and more specifics, I can only offer a general picture.

**Comment by ortug** [comment]
I am not the member of ava-labs team. This may not be consistent with their opinion.

You can limit the bandwidth usage on docker or on operation system.

For docket you can check the address: https://stackoverflow.com/questions/25497523/how-can-i-rate-limit-network-traffic-on-a-docker-container.

**Comment by heki-ru** [comment]
Vote for this, currently 1200+ established connections is an overkill. For the most blockchain nodes around, 50 inbound / 50 outbound connections more than enough to keep network healthy

**Comment by jummy123** [comment]
I would also find this feature useful. My network goes completely unusable while trying to sync a node, I would like the ability to throttle the node (even if it makes syncing slower) and still use my connection.

**Comment by ceyonur** [comment]
@jummy123 Take a look at rate-limiting CLI configs: 
https://docs.avax.network/build/references/command-line-interface#message-rate-limiting
https://docs.avax.network/build/references/command-line-interface#connection-rate-limiting

**Comment by jummy123** [comment]
@ceyonur thank you for this. I have used `--outbound-connection-throttling-rps=10 --inbound-connection-throttling-max-conns-per-sec=10` and this is working in my case. Thank you, issue resolved for me.

**Comment by StephenButtolph** [comment]
> Vote for this, currently 1200+ established connections is an overkill. For the most blockchain nodes around, 50 inbound / 50 outbound peer connections more than enough to keep network healthy

Avalanche consensus uses direct peer-to-peer polling to efficiently perform consensus. It is not possible to limit the number of peers to a number smaller than the current validator set.
