### ISSUE TITLE
Can't use the created private blockchain

### ISSUE THREAD

**Issue by hdyhdy** [ava-labs/avalanchego#810]
I used the official textbook to generate the private blockchain。Among them, before creating a private blockchain, you need to set up the genesis data. I set the address of the x chain of the local node I control X-local1s5f4dh7m5pgxtrklw0djknjhe6v66pp8clymgj in which local1s5f4dh7m5pgxtrklw0djknjhe6v66pp8clymgj is set to the address of the reward. After completing the creation of the private blockchain, I can also check that the address WnN32BvqZEine492ee7PAJ3V2fEpnwgzp7b7K1CWjCRGk6sCy-local1s5f4dh7m5pgxtrklw0djknjhe6v66pp8clymgj has a balance. But when I want to operate on the balance of this address, I use the account password of X-local1s5f4dh7m5pgxtrklw0djknjhe6v66pp8clymgj which I originally controlled the x chain, the system will display "error":{"code":-32000,"message":"problem retrieving private key for address D8e3EeT2whXPC1Qw4gntSF5j3E7P9dXoY: not found","data":null},"id":1}, is it one of my steps that went wrong?

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
You need to import the private key to the new blockchain. 
Note that support for custom blockchains is pretty minimal at the moment.

**Comment by hdyhdy** [comment]
> You need to import the private key to the new blockchain.
> Note that support for custom blockchains is pretty minimal at the moment.

I would also like to ask why it is 404 not found to find the content of new block chain after setting subnet as white list sometimes?

**Comment by danlaine** [comment]
@hdyhdy I think your questions are resolved by https://github.com/ava-labs/avalanchego/issues/819 and https://github.com/ava-labs/avalanchego/issues/812. Please open another issue if you still have questions. Thank you and apologies for the long delay in responding.
