### ISSUE TITLE
Problems with new blockchain transfer

### ISSUE THREAD

**Issue by hdyhdy** [ava-labs/avalanchego#812]
Hello, I finished building a new blockchain according to the tutorial a few days ago and found the number of balances I created. However, when I transferred these balances, I made an error. 
First of all, p-local18jma8ppw3nhx5r4ap8clazz0dps7rv5u00z96u is an address with avax set by the system, while jauupbjhcrymsdgmdnianwnt v4judtualmd98iedwcx6febbe-local18jma8ppw3nhx5r4ap8clazz0dps7rv5u00z96u is an address with new balance on the new chain. The difference between their addresses lies in the prefix. All are controlled by one account password. But I think there is a problem with the new balance transfer of jauupbjhcrymsdgmdnianwv4judtuald98iedwcx6febbe-local18jma8ppw3nhx5r4ap8clazz0dps7rv5u00z96u. What is the problem：
curl -X POST --data '{
"jsonrpc":"2.0",
"id" :1,
"method" :" avm.send ",
"params" :{
"assetID" : "asset1",
"amount" : 100,
"to" : "JAUUpBJhcRymSdGMDNiANwNTV4jUDTuALmd98ieDWCx6febbe-local1s3ps6gjer5twylsm7t5q4hvt6wfahcpy8d0nhh",
"from" : ["JAUUpBJhcRymSdGMDNiANwNTV4jUDTuALmd98ieDWCx6febbe-local18jma8ppw3nhx5r4ap8clazz0dps7rv5u00z96u"],
"changeAddr": "JAUUpBJhcRymSdGMDNiANwNTV4jUDTuALmd98ieDWCx6febbe-local18jma8ppw3nhx5r4ap8clazz0dps7rv5u00z96u",
"memo" : "hi, mom!",
"username" : "Hdy1234",
"password" : "Hdy1234hdy1234"
}

}' -H 'content- type:application/json; ' 127.0.0.1:9650/ext/bc/JAUUpBJhcRymSdGMDNiANwNTV4jUDTuALmd98ieDWCx6febbe
{"jsonrpc":"2.0","error":{"code":-32000,"message":"want to spend 1000000 of asset 2fombhL7aGPwj3KH4bfrmJwW6PVnMobf9Y2fn9GwxiAAJyFDbe but only have 0","data":null},"id":1}。
The asset of the error prompt seems to be avax. I have not found a way to make jauupbjhcrymsdgmdnianwntv4judtualmd98iedwcx6febbe-local18jma8ppw3nhx5r4ap8clazz0dps7rv5u00z96u get avax
How to solve this problem

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
@hdyhdy AvalancheGo only began supporting transfers of assets on custom AVM instances in v1.4.8. For information on how to do this, see here.
