### ISSUE TITLE
A node that is out of sync returns stale data, rather than error.

### ISSUE THREAD

**Issue by nonsense** [ava-labs/avalanchego#818]
**Describe the bug**
During the fork earlier today, one of my nodes was not updating and it was returning stale data for a long time after it was no longer synced with the network.

**To Reproduce**
N/A

**Expected behavior**
I think if a node goes out of sync, it should return an error, and not return stale data.

**Additional context**
I believe the node was on 1.2.x version, rather than on the new 1.3.0 or 1.3.1 if this helps.

**Comment by danlaine** [comment]
If the node's health check returns that the node is unhealthy, you should assume that data about chain state may not be accurate. I'll add that to the API docs.
