### ISSUE TITLE
Don't know how to transfer balance on the new blockchain

### ISSUE THREAD

**Issue by hdyhdy** [ava-labs/avalanchego#819]
root@1b7651e98431:/go/src/github.com/ava-labs/avalanchego# curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     : 1,
    "method" :"avm.getAllBalances",
    "params" :{
        "address":"JAUUpBJhcRymSdGMDNiANwNTV4jUDTuALmd98ieDWCx6febbe-local1gxk659xx3x2gdpsarjcjuum723asxvs5xgknh9"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/JAUUpBJhcRymSdGMDNiANwNTV4jUDTuALmd98ieDWCx6febbe
{"jsonrpc":"2.0","result":{"balances":[{"asset":"asset1","balance":"10000000"}]},"id":1}
Hello everyone, as you can see from the above picture, this address has new blockchain assets. But when I want to transfer this asset, the system prompts me that I lack assets 2fombhL7aGPwj3KH4bfrmJwW6PVnMobf9Y2fn9GwxiAAJyFDbe
root@1b7651e98431:/go/src/github.com/ava-labs/avalanchego# curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"avm.send",
    "params" :{
        "assetID"   : "asset1",
        "amount"    : 100,
        "to"        : "JAUUpBJhcRymSdGMDNiANwNTV4jUDTuALmd98ieDWCx6febbe-local18jma8ppw3nhx5r4ap8clazz0dps7rv5u00z96u",
        "from"      : ["JAUUpBJhcRymSdGMDNiANwNTV4jUDTuALmd98ieDWCx6febbe-local1gxk659xx3x2gdpsarjcjuum723asxvs5xgknh9"],
        "changeAddr": "JAUUpBJhcRymSdGMDNiANwNTV4jUDTuALmd98ieDWCx6febbe-local1gxk659xx3x2gdpsarjcjuum723asxvs5xgknh9",
        "memo"      : "hi, mom!",
        "username"  : "Hdy1234",
        "password"  : "Hdy1234hdy1234"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/JAUUpBJhcRymSdGMDNiANwNTV4jUDTuALmd98ieDWCx6febbe
{"jsonrpc":"2.0","error":{"code":-32000,"message":"want to spend 1000000 of asset 2fombhL7aGPwj3KH4bfrmJwW6PVnMobf9Y2fn9GwxiAAJyFDbe but only have 0","data":null},"id":1}
And this asset I remember is an asset on the p/x chain, how will I transfer the assets of the p/x chain to the new blockchain address so that I can transfer the assets of the new blockchain?

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
@hdyhdy AvalancheGo only began supporting transfers of assets on custom AVM instances in v1.4.8. For information on how to do this, see [here](https://docs.avax.network/build/tutorials/platform/create-avm-blockchain#create-the-genesis-data).
