### ISSUE TITLE
Explorer displays data incorrectly.

### ISSUE THREAD

**Issue by vedatturgut** [ava-labs/avalanchego#829]
https://cchain.explorer.avax.network/address/0x764Ff763A123c0c05153eBeB5F5DA8dC73d87BfB/transactions

https://avascan.info/blockchain/c/address/0x764Ff763A123c0c05153eBeB5F5DA8dC73d87BfB

Data is correct in avascan. I have no avax balance in my C-cha. I sent them to the X-chaine.

**Comment by tasinco** [comment]
The data could of have been cached in our c-chain explorer code.  Some settings have been updated to reduce the TTL on the cache.
The balances are in sync now.
Please re-open if you are seeing different results on your display, and provide screen shots.
