### ISSUE TITLE
Validator node cannot bootstrap and restarts due to fatal c-chain block verification error

### ISSUE THREAD

**Issue by arikan** [ava-labs/avalanchego#841]
I upgraded my validator node from 1.4.0 to 1.4.2 on the weekend, after the new version released. I noticed failing health checks today and had to reboot the instance on AWS. Avalanche systemd service restarted after the reboot. 

But I noticed it returns `isBootstrapped: false`. I checked the logs, it shows (below) C-Chain fatal error due to a failed verification on a block, that says `invalid gas used`.  After some time, it restarts itself and goes into a loop, giving the same fatal error on the same block and restarting again. 

I'd appretiate any suggestions on how to fix this issue. 

```
May 11 08:17:45 ip-x-x-x-x avalanchego[2581]: INFO [05-11|08:17:45] <C Chain> snow/engine/snowman/bootstrap/bootstrapper.go#295: bootstrapping fetched 136 blocks. Executing state transitions...
May 11 08:17:45 ip-x-x-x-x avalanchego[2581]: FATAL[05-11|08:17:45] <C Chain> snow/networking/router/handler.go#306: forcing chain to shutdown due to: block 2LTam8L6sXKzfUX1izhB9SaSD9zJj8TEwkm3qmYkjngJZNuHpK failed verification during bootstrapping due to: rpc error: code = Unknown desc = invalid gas used (remote: 376190 local: 374369)
May 11 08:17:45 ip-x-x-x-x avalanchego[2581]: INFO [05-11|08:17:45] <C Chain> snow/engine/snowman/transitive.go#150: shutting down consensus engine
May 11 08:17:45 ip-x-x-x-x avalanchego[2581]: INFO [05-11|08:17:45] node/node.go#963: shutting down node
May 11 08:17:45 ip-x-x-x-x avalanchego[2581]: INFO [05-11|08:17:45] ipcs/chainipc.go#101: shutting down chain IPCs
May 11 08:17:45 ip-x-x-x-x avalanchego[2581]: INFO [05-11|08:17:45] chains/manager.go#693: shutting down chain manager
May 11 08:17:45 ip-x-x-x-x avalanchego[2581]: INFO [05-11|08:17:45] snow/networking/router/chain_router.go#169: shutting down chain router
May 11 08:17:45 ip-x-x-x-x avalanchego[2581]: INFO [05-11|08:17:45] <X Chain> snow/engine/avalanche/transitive.go#139: shutting down consensus engine
May 11 08:17:45 ip-x-x-x-x avalanchego[2581]: INFO [05-11|08:17:45] <P Chain> snow/engine/snowman/transitive.go#150: shutting down consensus engine
May 11 08:17:45 ip-x-x-x-x avalanchego[2581]: INFO [05-11|08:17:45] network/network.go#920: shutting down network
May 11 08:17:45 ip-x-x-x-x avalanchego[2581]: INFO [05-11|08:17:45] node/node.go#984: finished node shutdown
May 11 08:17:45 ip-x-x-x-x avalanchego[2581]: INFO [05-11|08:17:45] nat/nat.go#152: Unmapped all ports
May 11 08:17:47 ip-x-x-x-x systemd[1]: ava.service: Service hold-off time over, scheduling restart.
```

**Operating System**

Ubuntu 18.04.4 LTS on AWS

This instance has 100 Gib volume, and current `.avalanchego/db/mainnet/v1.0.0` size is 30G.

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
My guess is that you're building with Go < 1.15 so when you run the build script, it's failing to compile Coreth. (You should see an error when building with Go < 1.15). If you are building from source, and you're using Go < 1.15, please upgrade to Go >= 1.15.5 and build again. That should resolve this.

If you are not building from source or you are using Go >= 1.15.5, please let me know.

**Comment by arikan** [comment]
Thank you @danlaine I upgraded to go 1.16.4 and continued with the pre-built binary.
