### ISSUE TITLE
DAP link in the bug template on GitHub points to a missing URL

### ISSUE THREAD

**Issue by ssg** [ava-labs/avalanchego#855]
The link "Developer Accelerator Program" in the text below points to https://avalabs.org/dap which is a 404.

> By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by cgcardona** [comment]
This issue has been resolved in https://github.com/ava-labs/avalanchego/pull/857
