### ISSUE TITLE
Node always shutdown with --index-enabled

### ISSUE THREAD

**Issue by txsdev** [ava-labs/avalanchego#862]
**Describe the bug**
Start local node with params `--index-enabled=true` is not work. and node always `shutdown`

**Screenshots**
![image](https://user-images.githubusercontent.com/12888745/119944892-68a56900-bfc7-11eb-9bdf-700a6f3d4350.png)

**Operating System**
- Macos
- Node version: `avalanche/1.4.6`
- Start Command: `avalanchego --index-enabled=true --network-id=local --staking-enabled=false --snow-sample-size=1 --snow-quorum-size=1`

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by txsdev** [comment]
Node has run now by add param `--index-allow-incomplete=true`

**Comment by panbhatt** [comment]
As per my knowledge and trial since last two days, staking-enabled false option on the MAINNET render the whole system useless.
