### ISSUE TITLE
1.4.7 hangs at startup with a brand new configuration folder

### ISSUE THREAD

**Issue by ssg** [ava-labs/avalanchego#868]
**Describe the bug**
(Maybe this is an unsupported scenario, but then I wonder how you plan to onboard new nodes to the ecosystem?)

Starting avalanchego without a pre-built database causes it to hang at the start. This seems to be only recourse as migration issues (#854 #867) haven't been resolved.

```
     _____               .__                       .__
    /  _  \___  _______  |  | _____    ____   ____ |  |__   ____    ,_ o
   /  /_\  \  \/ /\__  \ |  | \__  \  /    \_/ ___\|  |  \_/ __ \   / //\,
  /    |    \   /  / __ \|  |__/ __ \|   |  \  \___|   Y  \  ___/    \>> |
  \____|__  /\_/  (____  /____(____  /___|  /\___  >___|  /\___  >    \\
          \/           \/          \/     \/     \/     \/     \/
INFO [05-31|19:08:18] main/main.go#51: using build directory at path '/go/src/github.com/ava-labs/avalanchego/build'
INFO [05-31|19:08:18] main/node_manager.go#232: starting latest node version in normal execution mode
```

**To Reproduce**
Start Avalanchego 1.4.7, experience very low CPU usage for hours.

**Expected behavior**
It should start up normally like pre-1.4.5 versions.

**Operating System**
Linux 3.10.105 x86_64

**Additional context**
- 8GB RAM, 2.9TB free disk space, Intel Braswell 1.6 (2.5Ghz boost) CPU (didn't have any issues before 1.4.5)
- No log file entries were created other than reported above.
- Some files under `db/mainnet/v1.4.5` get created:

```
-rw-r--r-- 1 root root    0 May 31 12:35 000002.log
-rw-r--r-- 1 root root   16 May 31 12:35 CURRENT
-rw-r--r-- 1 root root   16 May 31 12:35 CURRENT.bak
-rw-r--r-- 1 root root    0 May 31 12:34 LOCK
-rw-r--r-- 1 root root 1011 May 31 12:35 LOG
-rw-r--r-- 1 root root   41 May 31 12:35 MANIFEST-000003
```

The `LOG` file contains:

```
=============== May 31, 2021 (UTC) ===============
19:34:07.692611 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
19:34:07.933870 db@open opening
19:34:07.939002 version@stat F·[] S·0B[] Sc·[]
19:34:08.034154 db@janitor F·2 G·0
19:34:08.034252 db@open done T·100.310746ms
19:34:08.034451 db@close closing
19:34:08.034605 db@close done T·151.715µs
=============== May 31, 2021 (UTC) ===============
19:35:14.521085 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
19:35:14.521565 version@stat F·[] S·0B[] Sc·[]
19:35:14.521652 db@open opening
19:35:14.521790 journal@recovery F·1
19:35:14.523877 journal@recovery recovering @1
19:35:14.526408 version@stat F·[] S·0B[] Sc·[]
19:35:14.756684 db@janitor F·2 G·0
19:35:14.756782 db@open done T·235.086608ms
19:35:14.756974 db@close closing
19:35:14.757173 db@close done T·188.079µs
```

That's pretty much about it.

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by ssg** [comment]
This issue doesn't happen when avalanchego is run outside of docker (with the same configuration/db folder)

**Comment by ssg** [comment]
This happens outside Docker too. Consecutive runs occasionally work but with a 50% probability, avalanchego would freeze at startup. This issue has never happened with pre-1.4.5.

**Comment by danlaine** [comment]
Are you still having this issue?

**Comment by ssg** [comment]
No @danlaine , not since I decided to synchronize the database from scratch. I don't know the issue is fixed or not though, I just stopped having the problem.
