### ISSUE TITLE
Query timeout cycle eats up all CPU and bandwidth

### ISSUE THREAD

**Issue by cryptonote-social** [ava-labs/avalanchego#874]
**Describe the bug**
AvalancheGo occasionally starts eating up all my CPU (4-core i5 processor) and bandwith (business class cable internet, 30mb/s).

**To Reproduce**
Unclear how to reproduce but it seems related to congestion on the internet  connection.

**Expected behavior**
CPU and bandwidth usage should not become saturated as my cpu and network should be plenty fast.

**Screenshots**
none

**Operating System**
ubuntu 20

**Additional context**
Attached is a cpu profile. You can see that the bulk of the time is spent in github.com/ava-labs/avalanchego/snow/networking/router.(*ChainRouter).QueryFailed which is called after PullQuery timeout. Traced it as far as 
(*Transitive).QueryFailed which calls (*Transitive).Chits() ... is that queuing another request that ends up in a timeout cycle?

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by cryptonote-social** [comment]
Sorry cpu profile attachment failed as it doesn't support the format. Attaching it again after gzipping.
[cpu.profile.gz](https://github.com/ava-labs/avalanchego/files/6650161/cpu.profile.gz)

**Comment by cryptonote-social** [comment]
FYI problem still seems to exist in the new release (1.4.8)

**Comment by cryptonote-social** [comment]
Had the problem surface again, this time in 1.4.9, and with my patch applied. Captured a CPU profile and attached it below. It looks very similar to the previous one with the exception that the TLS connection overhead is now much reduced (thanks to my PR). Still seeing the pull query timeout loop though with most of the CPU overhead now in generate request IDs:

```
...
crypto/sha256.Sum256
github.com/ava-labs/avalanchego/utils/hashing.ComputeHash256Array (inline)
github.com/ava-labs/avalanchego/snow/networking/router.(*ChainRouter).createRequestID
github.com/ava-labs/avalanchego/snow/networking/router.(*ChainRouter).QueryFailed
```

I also added WARN logging for the message send throttling to my validator, and interestingly that is NOT getting triggered, so the issue does not seem to involve a backlogged send message queue. The validator is getting d-doss'd by the network somehow when it's in this state.

**Comment by cryptonote-social** [comment]
Whoa, these are some really tight timeouts:

```
fs.Duration(NetworkInitialTimeoutKey, 5*time.Second, "Initial timeout value of the adaptive timeout manager.")
fs.Duration(NetworkMinimumTimeoutKey, 2*time.Second, "Minimum timeout value of the adaptive timeout manager.")
fs.Duration(NetworkMaximumTimeoutKey, 10*time.Second, "Maximum timeout value of the adaptive timeout manager.")
```

When the timeout triggers, a new Pull query is issued (without really cancelling the previous one as far as I can tell -- you'd need to close the connection or similar to do that).  I can see why this might snowball into a cascade of pull queries..... 

I will try to up the max timeout but I am not sure if this is just papering over the issue.... probably when a validator times out like this you should immediately close the connection to truly "cancel" the pending response.

**Comment by danlaine** [comment]
@cryptonote-social I'm hoping v1.4.10 resolves this. Please let us know if you still have this issue. Thanks.

**Comment by danlaine** [comment]
@cryptonote-social Have you had this issue since v1.4.10?

**Comment by cryptonote-social** [comment]
Unfortunately I've been unable to run 1.4.10 due to the crash issue from RocksDB.

**Comment by danlaine** [comment]
Ah, ok. v1.4.11 should resolve that issue

**Comment by danlaine** [comment]
@cryptonote-social Let us know how things go once you're on [v1.4.11](https://github.com/ava-labs/avalanchego/releases/tag/v1.4.11) (which should resolve the rocksDB issue). Thanks!

**Comment by cryptonote-social** [comment]
thanks, running it now. So far so good!

**Comment by danlaine** [comment]
@cryptonote-social Going to close this issue for now. Please re-open if you encounter this issue again. Thanks for reporting!

**Comment by cryptonote-social** [comment]
Ironically I just experienced the issue again (1.4.12) ... I was in the middle of a video conf so didn't have a chance to grab profile/stats unfortunately, just had to shut the validator down to get my network connection back and resume the call.

**Comment by ramilexe** [comment]
@cryptonote-social how do you collect cpu profile?

**Comment by cryptonote-social** [comment]
@ramilexe run the validator with --api-admin-enabled=true and then follow instructions in the Admin API doc for CPU profiling (https://docs.avax.network/build/avalanchego-apis/admin-api)

BTW I've had no issues with my validator since my last update.

**Comment by dzmitrykliapkou** [comment]
Looks like we have the same issue on 1.5.2

**Comment by danlaine** [comment]
@dzmitrykliapkou Can you please open a new issue and provide as much information and documentation as possible?

Preferably Including:

* Hardware Information
* OS
* AvalancheGo version
* Go version
* [Grafana dashboard screenshots](https://docs.avax.network/build/tutorials/nodes-and-staking/setting-up-node-monitoring)
* Any ERROR or WARNING logs
* The issue you're experiencing

Thanks

**Comment by cryptonote-social** [comment]
I've also had this issue again on 1.5.2 but didn't have the time to collect the stats & profile.

1.5.3 so far has been rock solid.
