### ISSUE TITLE
High network traffic after "snowman consensus is not healthy" warning

### ISSUE THREAD

**Issue by EmreNOP** [ava-labs/avalanchego#876]
**Describe the bug**
If nw connection drop somehow for 1 2 second, node is becoming unhealthy and after this node starting to upload data to other nodes. My upload is around 50Mbps, waited a couple of hour and that upload is not ending until restart node. 
limited to node upload due to this problem. thats why you 'll see around 20Mbps upload. 

**To Reproduce**
Network restart/reset/drop etc. 

**Expected behavior**

**Screenshots**
interface rates ss as attached upload 
![image](https://user-images.githubusercontent.com/72916436/122649157-dc511680-d12c-11eb-8125-6da4373b8363.png)

**Operating System**
kernel = 5.10.16-arch1-1 #1 SMP
arch linux container working on docker. 

**Additional context**
N/A

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by danlaine** [comment]
I think this is the same issue as #874  so closing in favor of that issue
