### ISSUE TITLE
One month later and still cannot complete upgrade to 1.4.5 or greater

### ISSUE THREAD

**Issue by dbrisinda** [ava-labs/avalanchego#880]
**Describe the bug**
I've been trying to upgrade my validator on a very lightly used 2012 iMac with HDD to no success. Plenty of memory, plenty of hard drive, decent CPU, all specs check to run an Avalanche node.

iMac (21.5-inch, Late 2012)
Processor 2.7 Ghz Quad-Core Intel Core i5
Memory 8 GB 1600 MHz DDR3
Hard Drive 700 GB available of 1 TB

 It's been running fine up until the 1.4.5 database upgrade. I've followed everything in the upgrade document to no avail. The upgrade process was running and populating the v1.4.5 database folder for about 3-4 weeks. I was noticing the database files getting populated, and the last file number was 1722820.ldb. But then yesterday it just quit with log output:

INFO [06-28|22:37:19] tmp/network/peer.go#676: beacon Fv3t2shrpkmvLnvNzcv1rqRKbDAYFnUor attempting to connect with newer version avalanche/1.4.9. You may want to update your client

[...many more messages like the above deleted...]

INFO [06-28|22:37:19] tmp/network/peer.go#676: beacon Fv3t2shrpkmvLnvNzcv1rqRKbDAYFnUor attempting to connect with newer version avalanche/1.4.9. You may want to update your client
INFO [06-28|22:37:29] tmp/node/node.go#964: shutting down node
INFO [06-28|22:37:29] tmp/ipcs/chainipc.go#101: shutting down chain IPCs
INFO [06-28|22:37:29] tmp/chains/manager.go#702: shutting down chain manager
INFO [06-28|22:37:29] tmp/snow/networking/router/chain_router.go#178: shutting down chain router
INFO [06-28|22:37:31] tmp/network/network.go#918: shutting down network
INFO [06-28|22:37:31] tmp/node/node.go#985: finished node shutdown
INFO [06-28|22:37:31] tmp/nat/nat.go#152: Unmapped all ports

When I pop into the v1.4.5 folder and do a du -k I see the database is about 45GB.

***

**To Reproduce**
I simply get the latest repo from GitHub (git pull) and latest is v1.4.9. Then I build and run. 

***

**Expected behavior**
After running the node, I'm expecting the database to eventually be upgraded, even if it takes a few days or even a week or two, which would then allow me to run node version 1.4.9. 

**Screenshots**
None.

**Operating System**
macOS 10.15.7 

**Additional context**
I *was* still running v1.4.4. However, after running the upgrade process for 3-4 weeks (slow HDD I guess), it just quit on me yesterday with a message similar to the above except:

INFO [06-29|21:18:55] tmp/network/peer.go#676: beacon DAtCoXfLT6Y83dgJ7FmQg8eR53hz37J79 attempting to connect with newer version avalanche/1.4.9. You may want to update your client

[... many more messages as above deleted...]

WARN [06-29|21:18:56] tmp/node/node.go#210: Failed to connect to bootstrap nodes. Node shutting down...
INFO [06-29|21:18:56] tmp/node/node.go#964: shutting down node
INFO [06-29|21:18:56] tmp/ipcs/chainipc.go#101: shutting down chain IPCs
INFO [06-29|21:18:56] tmp/chains/manager.go#702: shutting down chain manager
INFO [06-29|21:18:56] tmp/snow/networking/router/chain_router.go#178: shutting down chain router
INFO [06-29|21:18:56] <P Chain> tmp/snow/engine/snowman/transitive.go#150: shutting down consensus engine
INFO [06-29|21:18:57] tmp/network/peer.go#676: beacon HiFv1DpKXkAAfJ1NHWVqQoojjznibZXHP attempting to connect with newer version avalanche/1.4.9. You may want to update your client
INFO [06-29|21:18:58] tmp/network/network.go#918: shutting down network
INFO [06-29|21:18:58] tmp/node/node.go#985: finished node shutdown
INFO [06-29|21:18:58] tmp/nat/nat.go#152: Unmapped all ports
ERROR[06-29|21:18:58] main/main.go#71: error while running migration: previous version node stopped with exit code 0

Everytime I re-run it just goes through the motions with the above log message again and again. I do notice that a few more database files are added each time, but it then quits and needs to be rerun manually. The node will not startup and complete the upgrade process on its own.

Help!

**Comment by dbrisinda** [comment]
I'd like to move the apparently broken v1.4.5 database to the name v1.4.5.broken and restart the upgrade process. But I'd like to populate all the ldb files in the freshly created v1.4.5 folder with the v1.4.5.broken ldb files up to 800000.ldb or so before the unexpected termination occurred, so I don't have to download EVERYTHING again (45 GB), just the last 10 or 20 MB. Is this possible? Or am I looking for trouble? Specifically, I'm not sure  how MANIFEST-xxxxxx would need to change since it's a binary file.

**Comment by danlaine** [comment]
At this point, I suggest just deleting the v1.0.0 database (by default at `$HOME/.avalanchego/db/mainnet/v1.0.0`) and re-syncing from scratch

**Comment by dbrisinda** [comment]
Okay. Syncing from scratch now. Very curious to see how quick the C-chain bootstrapping will be with pruning enabled.

**Comment by danlaine** [comment]
@dbrisinda Still experiencing this issue?

**Comment by dbrisinda** [comment]
It took a few days, but I'm now successfully upgraded to v1.4.9. Thanks.
