### ISSUE TITLE
Avalanchego FATAL error during bootstrap

### ISSUE THREAD

**Issue by tbrunain** [ava-labs/avalanchego#898]
**Describe the bug**

I am helping someone setting up a new AvalancheGo (1.4.12) node on his VPS and it failed during the CChain's block execution phase .
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/29312251/129801772-5905b982-3c2b-4273-a784-36bbb6cc9124.png">

**To Reproduce**
We tried to restart the node several times and it always fails on the same block (aiC5329....)

**Expected behavior**
Well.. no crash ? ;P 

**Screenshots**
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/29312251/129801772-5905b982-3c2b-4273-a784-36bbb6cc9124.png">

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/29312251/129803565-6b0bac98-d311-465b-8aab-099b0318e437.png">

**Operating System**
Ubuntu 20.04.1 LTS

**Additional context**
Plenty of disk space left, fresh VPS

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by aaronbuchwald** [comment]
We believe this is most likely fixed by v1.5.0. Could you try running with v1.5.0?

**Comment by danlaine** [comment]
AvalancheGo v1.5.0 is out and should resolve this issue. @tbrunain Can you please try upgrading to that version and seeing if that fixes this? Thanks

**Comment by tbrunain** [comment]
The node is bootstrapping in version 1.5.0 and so far it looks ok (Started the process this morning, still ongoing but we went further than last time ^^) . Thanks and great job ;)

**Comment by StephenButtolph** [comment]
Marking this as resolved - if it comes back up feel free to re-open.
