### ISSUE TITLE
how to stop the node sync but node should  running.

### ISSUE THREAD

**Issue by UMANGAWASTHY** [ava-labs/avalanchego#908]
Hi Team

how to stop the node sync but node should running.

**Comment by aaronbuchwald** [comment]
I'm not sure that I understand the question. Are you running the node, but it is not syncing or you are not able to shut down your node? Could you try to be more specific?

**Comment by UMANGAWASTHY** [comment]
> I'm not sure that I understand the question. Are you running the node, but it is not syncing or you are not able to shut down your node? Could you try to be more specific?

Hello @aaronbuchwald 
     i like to run the node, but data should not sync.
     i.e. setup & run node without bootstrapping.
     
    Thanks
    Umang

**Comment by danlaine** [comment]
@UMANGAWASTHY 

You can't run a node on mainnet without syncing it.

I think this is what you're looking for: https://docs.avax.network/build/tutorials/platform/create-a-local-test-network
