### ISSUE TITLE
I found the X-chain can  not get the height and can not get the txidList , I  want to know that how to monitor deposit fot exchange

### ISSUE THREAD

**Issue by malingzhao** [ava-labs/avalanchego#911]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Operating System**
Which OS you used to reveal the bug.

**Additional context**

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by otherview** [comment]
Please use Discord for posting questions.
