### ISSUE TITLE
What's the main purpose for Snowstorm consensus?

### ISSUE THREAD

**Issue by 3for** [ava-labs/avalanchego#920]
I've only read the Snowball and Snowman consensus protocol in the [Avalanche official doc](https://docs.avax.network/learn/platform-overview/avalanche-consensus), there's a realization of Snowstorm consensus in the code, What's the main purpose for Snowstorm? And the difference between Snowman?

**Comment by otherview** [comment]
Hi @3for , can you please use the official Discord channel for these questions ? The #research channel would be the best place to ask these. Thank you.
