### ISSUE TITLE
`info.peers` API call returns invalid public IP addresses.

### ISSUE THREAD

**Issue by ssg** [ava-labs/avalanchego#922]
**Describe the bug**
The seemingly optional `publicIP` field gets always serialized and causes invalid output if a given peer doesn't have a `publicIP` set.

Ideally, the address should be omitted in the JSON output if the peer doesn't have a `publicIP` set. It would save bandwidth too.

**To Reproduce**
Issue an `info.peers` request to an avalanchego API.

**Expected behavior**
If there's no public IP present, the resulting JSON shouldn't include the seemingly optional `publicIP` field.

**Actual Result**
```
"publicIP": "\u003cnil\u003e:0",
```

Non-Go clients will have to handle this exotic output explicitly which creates an unnecessary edge case.

**Possible Solution**
Return nil for the field value if `publicIP` is empty. 

**Operating System**
Linux 3.10.108 x86_64 Braswell.

**Notes**
This might be a backwards compatibility issue if any client relies on this behavior or assumes `publicIP` field will always be present. I don't know how prevalent the internal API usage is.

I haven't checked other API calls. It's possible that similar serialization issues may exist in other places.

I don't know if `IP.IsEmpty() && Port > 0` is a valid `IPDesc` state though. In that case, my solution suggestion may not be ideal.

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by ceyonur** [comment]
Thank you for the report. We're looking into this.

**Comment by StephenButtolph** [comment]
This is resolved in #934.
