### ISSUE TITLE
Punishing Long Term Validators?

### ISSUE THREAD

**Issue by iamnathanwindsor** [ava-labs/avalanchego#923]
This AvalancheGo upgrade punishes long term validators. Without a discussion, voting period, or Snapshot governance vote, Ava Labs issued an upgrade to AvalancheGo that forced the validator uptime to 80% almost overnight. This decision was not decentralized in any way and severely punishes long term validators who staked under the conditions at the time of their stake, which was before this network upgrade.

This type of behavior is effectively a silent vote and strips long term validators of a significant reward for not having 99.99% uptime.

**The solution is very simple:** find the set of validators who staked before this network upgrade and honor them at their agreed upon lower uptime threshold of 60%.

As it stands now, validation transactions are not final and immutable, even though they claim to be; they are subject to random threshold upgrades like this one. Therefore long term validators who are abiding by the terms of their P-Chain transaction can be punished by potential de facto network upgrade by Ava Labs.

There are other running validators running on AVAX who are experiencing a significant loss due to the most recent arbitrary network upgrade from 60% to 80% uptime threshold.

This is a pretty serious flaw here for a validator like ours. There are at least 20 other validators in the Discord who have voiced this concern, but no patch has been issued.

Could we please issue a AvalancheGo update to honor these long term validators who staked at the lower threshold?

Here's the poll is the Validator discord channel:
https://discordapp.com/channels/578992315641626624/757576823570825316/889900250305814549

Additionally there is no single source of truth for the *actual uptime* of any validator, and this is deeply problematic for the community as a whole. The existing block explorers all show different uptimes for the same node.

**Comment by ssg** [comment]
> ... forced the validator uptime to 80% ...
> ... for not having 99.99% uptime

Did you mean "for not having 80% uptime"?
