### ISSUE TITLE
Proposed feature: avalanchego-installer.sh script checks latest release version against running version before stopping service

### ISSUE THREAD

**Issue by ahelwer** [ava-labs/avalanchego#925]
Currently, if you run `avalanchego-installer.sh` then it stops the service even if the service's version is the same as the latest release version on github. It would be nice to be able to run `avalanchego-installer.sh` as a cron job once a day or so, to get automatic updates without stopping the service for no reason. Thus I propose that upon detecting a running avalanche service, the update script should retrieve its version and compare it to the latest release version from github; if they are the same, then it should exit successfully while taking no further action. The script already has a `--reinstall` parameter if someone wants to run the script regardless of whether this check passes.

**Comment by ceyonur** [comment]
Docs repo would be much more suitable for this issue, as it contains installer.sh: 
https://github.com/ava-labs/avalanche-docs

**Comment by ahelwer** [comment]
Moved to https://github.com/ava-labs/avalanche-docs/issues/334
