### ISSUE TITLE
Possibility of adding ancient to slow HDD

### ISSUE THREAD

**Issue by soltrac** [ava-labs/avalanchego#930]
Geth clients allow to add ancient data to a directory on a slow cheap HDD.

It would be great to add this possibility to avalanchego client. Not sure if possible.

**Comment by aaronbuchwald** [comment]
Coreth (the C-Chain VM) does not use ancients, so it is not possible to migrate ancient data to a directory in the same way that is done in geth.

If you have a specific use case in mind, feel free to open up a feature request on coreth: https://github.com/ava-labs/coreth.
