### ISSUE TITLE
I want to know that the avax how to get the blockheight and the txIds ,  I found the blockchain doesn't provided the api

### ISSUE THREAD

**Issue by malingzhao** [ava-labs/avalanchego#932]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Operating System**
Which OS you used to reveal the bug.

**Additional context**

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by ceyonur** [comment]
See: https://docs.avax.network/build/avalanchego-apis/platform-chain-p-chain-api#platform-getheight
For transactions you need to enable indexer: https://docs.avax.network/build/avalanchego-apis/index-api

Please use [chat.avax.network ](chat.avax.network) for further questions. Also please don't put everything in the title, use provided template to create issues.
