### ISSUE TITLE
Failed to parse cb58 format when using avalancehgo`s built-in method

### ISSUE THREAD

**Issue by raojianli** [ava-labs/avalanchego#939]
**Describe the bug**
1. I got the data in cb58 format through api
  `    "jsonrpc": "2.0",
          "result": {
              "id": "2QRUg5cEmuJGm9mzx3b7FgWShhgvB5aNocLjSmKhcczsS76VN2",
              "bytes": "111111111BBGmbo1AWTcAfp4oqPvse2QNK5S1Z7t42egPKrexbEWukxFm1yentVNjx9muqHxDz9DAuu2T9Z4qHcQjCYJUmPsuvDPm6GQKBFcTrfRbuBM3KEwG6p2VnqqVKe8RSQLhvV5tEvSgoEDV7y8UPfEJHuwo36FFcAQpxRhyNTVM7cGiS4YveK1rHXrwLigMcSadtZ6JzSoGsfSe6jgRmHGFxq9u5itUAEkJiL7Ek1D6b34p7HvGkq3K2MmjRNSFqGbmXqDkBqggAEbNChW6o29fwGi8vjFpBJdQGaW6jiu6PnNk1TP6cje7XV15hXiyEncpmFieNDqBaARMfYeSW6EwbdvsA27g8bqLUBdeBuDsqpCD8CQ4Epcz1nBhtjYYsvmHwuUqsRuTL18rVYUbfdHi1TaaLYcJgFS5YtDFhVmV4DH1X6NnjCN5kyJuCgBUwsQQUq3rjfWmAJ7xGJF3dNfGnHoDsDFuHwUSXsFpZm1XCkUkybk4SrRFuXpddhmwGBixZ7dvNEv2xdPpHBf7",
              "timestamp": "2021-10-29T01:46:47.696586719Z",
              "encoding": "cb58",
              "index": "464622"
          },
          "id": 1
      }`

2. I parse the data using avalanchego's built-in method    https://github.com/ava-labs/avalanchego/blob/ef63270e177a6b8bb577cdf4330cb745aceaf890/utils/formatting/encoding.go#L160

3. but it It doesn't work

    `func TestCb58Decode(t *testing.T){
	bytes, err := formatting.Decode(formatting.CB58, "111111111BBGmbo1AWTcAfp4oqPvse2QNK5S1Z7t42egPKrexbEWukxFm1yentVNjx9muqHxDz9DAuu2T9Z4qHcQjCYJUmPsuvDPm6GQKBFcTrfRbuBM3KEwG6p2VnqqVKe8RSQLhvV5tEvSgoEDV7y8UPfEJHuwo36FFcAQpxRhyNTVM7cGiS4YveK1rHXrwLigMcSadtZ6JzSoGsfSe6jgRmHGFxq9u5itUAEkJiL7Ek1D6b34p7HvGkq3K2MmjRNSFqGbmXqDkBqggAEbNChW6o29fwGi8vjFpBJdQGaW6jiu6PnNk1TP6cje7XV15hXiyEncpmFieNDqBaARMfYeSW6EwbdvsA27g8bqLUBdeBuDsqpCD8CQ4Epcz1nBhtjYYsvmHwuUqsRuTL18rVYUbfdHi1TaaLYcJgFS5YtDFhVmV4DH1X6NnjCN5kyJuCgBUwsQQUq3rjfWmAJ7xGJF3dNfGnHoDsDFuHwUSXsFpZm1XCkUkybk4SrRFuXpddhmwGBixZ7dvNEv2xdPpHBf7")
	if err!=nil{
		panic(err)
	}
	fmt.Println(string(bytes))
}
`
4. The parsed content is garbled
`Faucet drip	�X:�u��n\��P�\�g5�
F`

**Comment by StephenButtolph** [comment]
What is the expected result? Transactions are issued in a binary format - not a UTF-8 format.

**Comment by raojianli** [comment]
> What is the expected result? Transactions are issued in a binary format - not a UTF-8 format.

Actually I want to convert it to json, I found that there is a codec manager in the code to parse the data, is there any structure to parse the vertices?

**Comment by StephenButtolph** [comment]
This is probably what you're looking for https://github.com/ava-labs/avalanchego/blob/master/snow/engine/avalanche/vertex/parser.go#L18

**Comment by raojianli** [comment]
> This is probably what you're looking for https://github.com/ava-labs/avalanchego/blob/master/snow/engine/avalanche/vertex/parser.go#L18

thanks ,it`s so helpful, and Is there any data structure conversion of the c chain block?

**Comment by danlaine** [comment]
> > This is probably what you're looking for https://github.com/ava-labs/avalanchego/blob/master/snow/engine/avalanche/vertex/parser.go#L18
> 
> thanks ,it`s so helpful, and Is there any data structure conversion of the c chain block?

You can use `eth_getBlockByHash` or `eth_getBlockByNumber` to get a C-Chain block. See https://eth.wiki/json-rpc/API and https://docs.avax.network/build/avalanchego-apis/contract-chain-c-chain-api

**Comment by danlaine** [comment]
If you have questions (as opposed to bug reports) please ask on our Discord: https://chat.avax.network
