### ISSUE TITLE
Generating staking cert and node id on my own

### ISSUE THREAD

**Issue by areller** [ava-labs/avalanchego#943]
I have a situation where I need to generate staking cert (key + cert files) and a node id on my own (without launching avalanche)

The way I do it right now, is by reusing some of the avalanchego repo internal libraries

the code looks like this

```golang
import (
        ...
        "github.com/ava-labs/avalanchego/ids"
	"github.com/ava-labs/avalanchego/staking"
	"github.com/ava-labs/avalanchego/utils/hashing"
)

...

func GenerateAvalancheKeys() (string, []byte, []byte) {
	certBytes, keyBytes, err := staking.NewCertAndKeyBytes()
	if err != nil {
		return nil, fmt.Errorf("failed to generate staking certificate and key: %w", err)
	}

	cert, err := createTLSCert(certBytes, keyBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to generate TLS certificate for staking: %w", err)
	}

	nodeId, err := ids.ToShortID(hashing.PubkeyBytesToAddress(cert.Leaf.Raw))
	if err != nil {
		return nil, fmt.Errorf("failed to extract node id from TLS certificate: %w", err)
	}

	return fmt.Sprintf("NodeID-%s", nodeId), certBytes, keyBytes
}

func createTLSCert(certBytes []byte, keyBytes []byte) (*tls.Certificate, error) {
	cert, err := tls.X509KeyPair(certBytes, keyBytes)
	if err != nil {
		return nil, err
	}
	cert.Leaf, err = x509.ParseCertificate(cert.Certificate[0])
	if err != nil {
		return nil, err
	}
	return &cert, nil
}

```

I was wondering if there're plans to either provide a CLI method for generating those keys, something like `avalanchego create-keys` or exporting a golang SDK for doing that (instead of having to use internal libraries)

What are you thoughts about that? would you accept a PR that does that?

**Comment by StephenButtolph** [comment]
Yeah I think this makes sense. Although generally avalanchego doesn't pass around `string`s for nodeIDs - it keeps them as `ids.ShortID`s. So it would probably be best to just return the `nodeID`.

**Comment by danlaine** [comment]
You can also do generate a key/cert pair like this:

```
openssl req -x509 -newkey rsa:4096 -keyout staker.key -out staker.crt -days 36500 -nodes -subj '/CN=localhost' -set_serial 0
```

**Comment by danlaine** [comment]
> You can also do generate a key/cert pair like this:
> 
> ```
> openssl req -x509 -newkey rsa:4096 -keyout staker.key -out staker.crt -days 36500 -nodes -subj '/CN=localhost' -set_serial 0
> ```

@areller You can use the above solution or [this function ](https://github.com/ava-labs/avalanchego/blob/master/staking/tls.go#L110) to make a staking key/cert.
