### ISSUE TITLE
 how long does  it take to bootstrap an Avalanche node ?

### ISSUE THREAD

**Issue by wxf-kine** [ava-labs/avalanchego#947]
I installed an Avalanche node yesterday with avalanchego-installer.sh on ubuntu，it still show false when i "curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"info.isBootstrapped",
    "params": {
        "chain":"X"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/info"
{"jsonrpc":"2.0","result":{"isBootstrapped":false},"id":1}

and log shows like this  "
![image](https://user-images.githubusercontent.com/93694051/141064903-1813cf31-723b-4558-836c-672ec0e8e2de.png)
"
Is this normal?

**Comment by 3nprob** [comment]
This doesn't look like a bug - it's still bootstrapping.

However, it would be very useful if the target number of operations would be shown in logs. Like `executed X/Y operations`.

**Comment by wxf-kine** [comment]
> This doesn't look like a bug - it's still bootstrapping.
> 
> However, it would be very useful if the target number of operations would be shown in logs. Like `executed X/Y operations`.

Yes, it had been bootstraped successfully for 4 days. thanks
