### ISSUE TITLE
failed to verify block in bootstrapping: block P-chain height larger than current P-chain height" while processing message

### ISSUE THREAD

**Issue by TriptonPt** [ava-labs/avalanchego#954]
ERROR[11-25|06:40:14] <P Chain> snow/engine/snowman/bootstrap/block_job.go#86: block vfCp1HpHbAJoLTTZejrediBSusMsbjW2JbRKr9KifH5mzG7aZ failed verification during bootstrapping due to block P-chain height larger than current P-chain height
FATAL[11-25|06:40:14] <P Chain> snow/networking/router/handler.go#144: chain shutting down due to error "failed to execute job vfCp1HpHbAJoLTTZejrediBSusMsbjW2JbRKr9KifH5mzG7aZ due to failed to verify block in bootstrapping: block P-chain height larger than current P-chain height" while processing message: (Op: multi_put, NodeID: NodeID-A7GwTSd47AcDVqpTVj7YtxtjHREM33EJw, RequestID: 3, NumContainers: 709)

Unable to continue syncing node after this error .

**Screenshots**

https://imgur.com/2NCpMjD

**Operating System**
Ubunyu 20.04

**Comment by StephenButtolph** [comment]
Thanks for raising this - will look into it.

**Comment by danlaine** [comment]
@TriptonPt and I discussed on Discord. They were using flag `--staking-enabled=false`, which was the source of the error.
