### ISSUE TITLE
Windows avalanchego v1.7.0 experimental shuts down

### ISSUE THREAD

**Issue by KingBaba** [ava-labs/avalanchego#955]
When the executable in avalanchego-win-v1.7.0 is started, it immediately shuts down.

**Comment by ceyonur** [comment]
could you provide logs, screenshots, configs, your startup flags?

**Comment by KingBaba** [comment]
I tried again to generate logs and it’s working…

**Comment by txsdev** [comment]
@KingBaba  I got same problem，You have fixed it ?
