### ISSUE TITLE
What extra space does the node use？

### ISSUE THREAD

**Issue by wo4zhuzi** [ava-labs/avalanchego#959]
Excuse me, I have two servers to synchronize the avax node. One is built before, and 200g is synchronized to the latest block. A node has been built recently. It takes nearly 500g to synchronize to the latest block. Does anyone know what this is?

**Comment by danlaine** [comment]
@wo4zhuzi 

Do `du -h $HOME/.avalanchego` to see the disk space used by AvalancheGo. What does that command show for you?

**Comment by danlaine** [comment]
@wo4zhuzi bump

**Comment by wo4zhuzi** [comment]
> @wo4zhuzi
> 
> Do `du -h $HOME/.avalanchego` to see the disk space used by AvalancheGo. What does that command show for you?

One server
![image](https://user-images.githubusercontent.com/20334885/151092798-9b911a60-3c00-4ca9-9b52-4e47a6537d3f.png)

Another server
![image](https://user-images.githubusercontent.com/20334885/151092955-aa17cb5b-46ad-42bf-86f7-34e31d40695f.png)
