### ISSUE TITLE
Memory leak in 1.7.1 & 1.7.2 for /avalanchego/build/plugins/evm 

### ISSUE THREAD

**Issue by jun0tpyrc** [ava-labs/avalanchego#961]
**Describe the bug**
docker `avaplatform/avalanchego:v1.7.1`,

process`/avalanchego/build/plugins/evm`
taking up memory quickly , using up > 50GB in a few hours

**To Reproduce**
running it over a few hours , if necessary , put ortelius:v1.7.1-log-fix indexer before it

**Expected behavior**
no mem leak in past versions (was upgrading from 1.6), serving same amount of traffic 

**Screenshots**

**Operating System**
Which OS you used to reveal the bug.

**Comment by jun0tpyrc** [comment]
issues are still there in v1.7.2

**Comment by jun0tpyrc** [comment]
push

**Comment by ceyonur** [comment]
Could you enable profiling and send your results? 
https://docs.avax.network/build/references/command-line-interface/#continuous-profiling
