### ISSUE TITLE
chainId and networkId is different in (at least) fuji testnet

### ISSUE THREAD

**Issue by huahuayu** [ava-labs/avalanchego#962]
Hi, I found that chainId(43113) and networkId(1) is different in fuji testnet, which make's my program get an error when send tx: "invalid sender"

This is kind of strange, I used to think they are the same and for most of the evm chain they are actually the same. 

What's more, from the [code base of ethereum](https://github.com/ethereum/go-ethereum/blob/93f196c4b052983dd89d8ba749dcdc98a80cf69c/ethclient/ethclient.go#L316),  it is clearly commented:

```go
// NetworkID returns the network ID (also known as the chain ID) for this chain.
func (ec *Client) NetworkID(ctx context.Context) (*big.Int, error) {
    ......
}
```

I have do some google search for this ([here](https://medium.com/@pedrouid/chainid-vs-networkid-how-do-they-differ-on-ethereum-eec2ed41635b)), and find some chain also have different chainId and networkId, how's that?

**Comment by Abhishekkochar** [comment]
They are different in both mainnet and testnet. Network id seems to be 1 in both of these. I recommend using: web3.eth.getChainId()
