### ISSUE TITLE
`~/.avalanchego/configs` was not created. Do I have to manually create `~/.avalanchego/configs/node.js` in order to prune my node?

### ISSUE THREAD

**Issue by jerzybrzoska** [ava-labs/avalanchego#964]
I've installed AvalanchGo 1.7.1 on my Ubuntu 20.04 LTS Desktop via `apt`.
[From what I read][2], the config file is supposed to be in `~/.avalanchego/configs/node.json`.
Although `~/.avalanchego` was created when I launched the node, no subdirectory named `configs`
was created inside of `~/.avalanchego`.
My intention is to run a pruned node to the target size of 200GB. How might I configure my node so that the blockchain size does not exceed 200GB? 
P.S. Would be great if some time in the future someone answered to this question on [avalanche.stackexchange][4]
 
[2]: https://docs.avax.network/build/tutorials/nodes-and-staking/set-up-node-with-installer
[3]: https://docs.avax.network/build/references/command-line-interface
[4]: https://area51.stackexchange.com/proposals/126412/avalanche/126414#126414

**Comment by ceyonur** [comment]
`~/.avalanchego/configs/node.json` won't be available by default if you have installed with `apt`. That page uses a different installer script. You can check https://docs.avax.network/build/references/command-line-interface/ for CLI flags to configure your node. The pruning is available by default, so you don't need to do any additional config.

**Comment by jerzybrzoska** [comment]
When I ran `go get -v -d github.com/ava-labs/avalanchego/... && cd $GOPATH/src/github.com/ava-labs/avalanchego` I got:
`bash: cd: /home/jerzy/go/src/github.com/ava-labs/avalanchego: No such file or directory`
And so I decided to `git clone` and then proceed:
`git clone https://github.com/ava-labs/avalanchego.git cd avalanchego && ./scripts/build.sh && ~/avalanchego/build/avalanchego` . This worked fine but as with `apt` `~/.avalanchego/configs/node.json` is not available by default. I created it manually and pasted in the following content:
```
{
    "log-level": "debug",
    "pruning-enabled": true
}
```
The node work fine. Now my question is:
* Does it prune what it can without any customization possible? E.g. `prune=245000` in `bitcoin.conf` prunes the Bitcoin blockchain so that in cannot grow above 250GB.

**Comment by ceyonur** [comment]
`~/.avalanchego/configs/node.json` is not the default config location for standard installations. You should start your node with `--config-file` e.g. `~/avalanchego/build/avalanchego --config-file=$HOME/.avalanchego/configs/node.json`. or simply `~/avalanchego/build/avalanchego --log-level=debug` since pruning is enabled by default.

There is no customization for `pruning` currently.

**Comment by jerzybrzoska** [comment]
> `~/.avalanchego/configs/node.json` is not the default config location for standard installations. You should start your node with `--config-file` e.g. `~/avalanchego/build/avalanchego --config-file=$HOME/.avalanchego/configs/node.json`. 

Thanks, I knew that already, just haven't mentioned that in my reply. 

>There is no customization for pruning currently.

Everything is clear to me now. Thanks for your assistance. I'm closing this issue.
