### ISSUE TITLE
IPCS not working since 1.6.X ? 

### ISSUE THREAD

**Issue by ang-st** [ava-labs/avalanchego#968]
**Describe the bug**
avalanchego does not send any data on the ipcs unix sockets 

**To Reproduce**
run 
```
./avalanchego  --http-host 0.0.0.0 --api-ipcs-enabled=true --network-id=1  --api-admin-enabled=false  --api-keystore-enabled=false --ipcs-chain-ids=2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM
```
connect a client to it : 
```
nc -U /tmp/1-2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM-consensus
````
no data are spitted out

**Expected behavior**

getting ipcs message  defined in https://docs.avax.network/build/avalanchego-apis/ipc-api#ipc-message-format

**Operating System**

```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

```
uname -a
Linux AVAX-sweet-banzai 4.15.0-154-generic #161-Ubuntu SMP Fri Jul 30 13:04:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional context**

for debugging purpose i started the node with : 

```
strace -f -e trace=process,socketpair,open,close,dup,dup2,read,write,connect -o /tmp/c.log ./avalanchego --log-dir /home/avax/mainnet/logs --db-dir /home/avax/mainnet/gecko/  --http-host 0.0.0.0 --api-ipcs-enabled=true --network-id=1  --api-admin-enabled=false  --api-keystore-enabled=false --ipcs-chain-ids=2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM 
```
 
waited it bootstrap completely;  issued ipcs.unpublishBlockchain and ipcs.publishBlockchain yet i can't see any activity on the unix socket ... 
 
```
$ grep connect /tmp/c.log  | grep UNIX
29454 connect(21, {sa_family=AF_UNIX, sun_path="/tmp/plugin3162815508"}, 24) = 0
29450 connect(21, {sa_family=AF_UNIX, sun_path="/tmp/plugin2155274526"}, 24) = 0
29450 connect(25, {sa_family=AF_UNIX, sun_path="/tmp/plugin1061097939"}, 24) = 0
29455 connect(26, {sa_family=AF_UNIX, sun_path="/tmp/plugin2266360884"}, 24 <unfinished ...>
29444 connect(451, {sa_family=AF_UNIX, sun_path="/tmp/plugin3613209767"}, 24) = 0
29482 connect(12, {sa_family=AF_UNIX, sun_path="/tmp/plugin205590985"}, 23 <unfinished ...>
29490 connect(13, {sa_family=AF_UNIX, sun_path="/tmp/plugin2987470769"}, 24) = 0
29489 connect(14, {sa_family=AF_UNIX, sun_path="/tmp/plugin96810"}, 19 <unfinished ...>
29490 connect(15, {sa_family=AF_UNIX, sun_path="/tmp/plugin480007044"}, 23 <unfinished ...>
... 

```
only plugins one ... despite the files being created 

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by matricore** [comment]
same problem +++

**Comment by mujdatdinc** [comment]
A signature problem. [Fix](https://github.com/mujdatdinc/avalanchego/commit/f3babe68b837974e3c9050137181634c010dc5c5)

**Comment by ang-st** [comment]
> A signature problem. [Fix](https://github.com/mujdatdinc/avalanchego/commit/f3babe68b837974e3c9050137181634c010dc5c5)

I applied patch and it works ! Thanks @mujdatdinc !
I'll let avalanche team close the issue once merged

**Comment by huahuayu** [comment]
Hi guys, what is the IPCS API used for, subscribing new transactions and new blocks?
