### ISSUE TITLE
runing avalanchego can't finish 

### ISSUE THREAD

**Issue by maomaozhou** [ava-labs/avalanchego#969]
this is my config.json 

{
	"index-allow-incomplete":true,
	"log-dir": "/data/services/avax/log",
	"db-dir": "/data/services/avax/data",
	"http-port": 9650,
	"index-enabled": true,
	"network-id": "fuji"
}

I have been running for a whole day, and the health interface is still not completed

The interfaces under avm all return this

API call rejected because chain is not done bootstrapping

Some interfaces are good, such as index.xx

{
    "jsonrpc": "2.0",
    "result": {
        "checks": {
            "C": {
                "message": {
                    "consensus": {},
                    "vm": {}
                },
                "timestamp": "2021-12-11T20:26:41.660434579Z",
                "duration": 4741880,
                "contiguousFailures": 0,
                "timeOfFirstFailure": null
            },
            "P": {
                "message": {
                    "consensus": {},
                    "vm": {
                        "percentConnected": 0.999946458783374
                    }
                },
                "timestamp": "2021-12-12T03:37:28.51985536Z",
                "duration": 30987,
                "contiguousFailures": 0,
                "timeOfFirstFailure": null
            },
            "X": {
                "message": {
                    "consensus": {},
                    "vm": null
                },
                "timestamp": "2021-12-12T03:37:11.594509725Z",
                "duration": 3071,
                "contiguousFailures": 0,
                "timeOfFirstFailure": null
            },
            "isNotBootstrapped": {
                "message": [
                    "'P'",
                    "'X'",
                    "'C'"
                ],
                "error": {
                    "message": "primary subnet has not finished bootstrapping"
                },
                "timestamp": "2021-12-12T03:37:28.028084205Z",
                "duration": 6139,
                "contiguousFailures": 1548,
                "timeOfFirstFailure": "2021-12-11T14:44:18.027613584Z"
            },
            "network": {
                "message": {
                    "connectedPeers": 25,
                    "sendFailRate": 0.4261355368920442,
                    "timeSinceLastMsgReceived": "1.0281194s",
                    "timeSinceLastMsgSent": "2.0281194s"
                },
                "timestamp": "2021-12-12T03:37:28.028089146Z",
                "duration": 11899,
                "contiguousFailures": 0,
                "timeOfFirstFailure": null
            },
            "router": {
                "message": {
                    "longestRunningRequest": "5.599753137s",
                    "outstandingRequests": 50
                },
                "timestamp": "2021-12-12T03:37:28.028090726Z",
                "duration": 3678,
                "contiguousFailures": 0,
                "timeOfFirstFailure": null
            }
        },
        "healthy": false
    },
    "id": 1
}

**Comment by ceyonur** [comment]
From what i see, It's not reporting any anomaly. You've enabled indexer, so it is expected to take longer than expected sync time. Can you check the logs to see if there is anything else beside this? You should be seeing some progress logs like `fetched xxx of yyy blocks` or  `executed xxx operations`

You can also use chat.avax.network for your questions.

**Comment by maomaozhou** [comment]
Thank god, I waited for 1.5 days and finally completed, test node
