### ISSUE TITLE
How to decrypt base 58

### ISSUE THREAD

**Issue by maomaozhou** [ava-labs/avalanchego#970]
I get the following results through api
I want to decrypt the content like json, such as tx, hash

I use nodejs avalanchejs cb58Decode to decrypt

How can I convert the result to json normally

{
     "jsonrpc": "2.0",
     "result": {
         "id": "QGQCtccNj8Hcz2wP6j5w68zhHPjnRfUWYVqjzcypJshG1hcT4",
         "Bytes": "111111111BBGmbo1AWTcAfp4oqPvse2QNK5S1Z7t42egPKrexbEWukxFm1yentVNjx9muqHxDz9DAuu2T9Z4qHcQjCYJUmPsuvDPm6GQKBFcTrfRbuBM3KEwG6p2VnqqVKe8RSQLhvV5sb42RwVZvHRwaiKCaFE3CGb2i4bde4tf4a15X9NxQScGa8EuyJixicL1YQWy4GYXGSDAAdqCFFfccLgZQ9vUjAYMNKHAQu5mvh5L4jTLR3cNVoBCQcXkZxJZhb1hKCrfs8GqD9jvKWJbhAEzKM2b5rUqow5SW6Rr85PXxmoeb2Rvfdc4jWzY2UGMD2QShxRceb1SmRZ4Nzrg7Cbq5qz6NrSXAUEiifwyaEdBNKHA2PxeiBshoPdBc6kB86Hr1PCysQuod3GEVnbwZZtgrRWYz9f2WH25sE2kvwaJo6XssnXFzGC4LQKDiJ34uvBdeNCY7QWWyKLrpHUEN3KzoaxZfECt2QUcfS4CbDzjzbyc3DTD9QT3x5x7f5ccQF3Y4bynMiKWCJADBUNuV",
         "timestamp": "2021-12-12T01:38:08.448637448Z",
         "encoding": "cb58",
         "index": "473179"
     },
     "id": 1
}

const bintools = BinTools.getInstance()

const cb58 = bintools.cb58Decode("111111111BBGmbo1AWTcAfp4oqPvse2QNK5S1Z7t42egPKrexbEWukxFm1yentVNjx9muqHxDz9DAuu2T9Z4qHcQjCYJUmPsuvDPm6GQKBFcTrfRbuBM3KEwG6p2VnqqVKe8RSQLhvV5sb42RwVZvHRwaiKCaFE3CGb2i4bde4tf4a15X9NxQScGa8EuyJixicL1YQWy4GYXGSDAAdqCFFfccLgZQ9vUjAYMNKHAQu5mvh5L4jTLR3cNVoBCQcXkZxJZhb1hKCrfs8GqD9jvKWJbhAEzKM2b5rUqow5SW6Rr85PXxmoeb2Rvfdc4jWzY2UGMD2QShxRceb1SmRZ4Nzrg7Cbq5qz6NrSXAUEiifwyaEdBNKHA2PxeiBshoPdBc6kB86Hr1PCysQuod3GEVnbwZZtgrRWYz9f2WH25sE2kvwaJo6XssnXFzGC4LQKDiJ34uvBdeNCY7QWWyKLrpHUEN3KzoaxZfECt2QUcfS4CbDzjzbyc3DTD9QT3x5x7f5ccQF3Y4bynMiKWCJADBUNuV");

console.log(cb58.toString("utf8"))

�h��B�\�v�6�
            Ym����z��e���8ʔ�=����v0�h��B����ҕ
                                             ��ҏa���k
                                                     �C���Щ�;��x&E�t��D��>;�#F��|v{���9�����; �I*O�=����v0�h��B������,[*���p�R�-@p0֬���=����v0�h��B����ҕ
                                                ��ҏa������C���Щ�;��x&E�t�	.l="��t)P��S��pHA��Rf�]�>"w���*i��-���a|ow�tZ��KI�1���Qx]�;

How can I convert the result to json normally

**Comment by danlaine** [comment]
You can decode cb58 with [this function](https://github.com/ava-labs/avalanchego/blob/master/utils/formatting/encoding.go#L160)

If you're trying to get information about an X-Chain transaction, use this [X-Chain API method](https://docs.avax.network/build/avalanchego-apis/exchange-chain-x-chain-api/#avm.gettx)
