### ISSUE TITLE
It takes a very long time to synchronise a node

### ISSUE THREAD

**Issue by AndrewTheRocket** [ava-labs/avalanchego#971]
Hi!

Trying to deploy your node, just as described in the guide on this link:
https://docs.avax.network/build/tutorials/nodes-and-staking/set-up-node-with-installer/

Synchronisation has been going on for over two days now. Is this normal?

**Comment by danlaine** [comment]
It depends on your node's hardware and internet connection, but it can certainly take multiple days to bootstrap a node from an empty database.

**Comment by panbhatt** [comment]
Still after days, the NODE is not able to SYNC and we are not able to HIT THE RPC API. any idea or command where we can hit the API at least with some data.
