### ISSUE TITLE
EIP-1559  eth_call fails when using maxPriorityFeePerGas  without maxFeePerGas

### ISSUE THREAD

**Issue by mjay0** [ava-labs/avalanchego#973]
**Describe the bug**
When doing eth_call with EIP-1559 transaction with maxPriorityFeePerGas and without maxFeePerGas, transaction fails.
`Returned error: err: max priority fee per gas higher than max fee per gas: address 0x0000000000000000000000000000000000000123, maxPriorityFeePerGas: 50000000000, maxFeePerGas: 0 (supplied gas 1500000)`
Same transaction with eth_sendtransaction works fine.

**To Reproduce**
eth_call smart contract function with maxPriorityFeePerGas  specified and without maxFeePerGas

**Expected behavior**
Would expect eth_call and eth_sendtransaction to both be either fine without maxFeePerGas or both fail without maxFeePerGas

**Operating System**
Ubuntu 20.04 - avalanche/1.7.2

**Comment by aaronbuchwald** [comment]
Can you supply the exact details of the two calls that you're making?
