### ISSUE TITLE
Transactions stuck at processing state

### ISSUE THREAD

**Issue by mohd109** [ava-labs/avalanchego#974]
Hi, 
I'm deploying the five_node_staking.lua script on out local network. After creating a user, importing the private key for predefined AVAX value in the network, and creating another address for my user, I'm not able to create a fixed cap or any other type of assets. The thing is it responds with assetID (which can be used with getAssetDescription method successfully) but the asset won't go to the initial holders' address. So the getAllBalances or getBalance methods won't return anything except 0. When I try to send AVAX from my first address to second one, the API responds with txid but when I check that with getTxStatus it responds with Processing state. So, the transactions won't work. I completely followed the Avalanche tutorials step by step. Any help will be appreciated. 

avalanche version 1.7.2
commit=f0a3bbb7d745be99d4970fb3b8fba3c7da87b891

Thanks for your time.

**Comment by danlaine** [comment]
Can you please provide an exact set of steps for reproducing?
