### ISSUE TITLE
Node becomes unhealthy, then auto shutdown fails with RPC error message 

### ISSUE THREAD

**Issue by fraggle222** [ava-labs/avalanchego#980]
**Describe the bug**
Validator node became unhealthy with message:
WARN [12-22|14:07:30] health/service.go#133: "C" became unhealthy with: {"message":{"consensus":{"longestRunningBlock":"2m40.408318737s","outstandingBlocks":79},"vm":{}},"error":{"message":"snowman
 consensus is not healthy reason: block processing time 2m40.408318737s \u003e 2m0s"},"timestamp":"2021-12-22T14:07:01.680702292Z","duration":28830640097,"contiguousFailures":1,"timeOfFirstFailure":"2021-12-22T14:07:01.680702292Z"}

**Followed 2min later by**

FATAL[12-22|14:09:19] <C Chain> snow/networking/router/handler.go#145: chain shutting down due to error "rpc error: code = Unavailable desc = connection error: desc = \"transport: error while diali
ng: dial unix /tmp/plugin3148387957: connect: connection refused\"" while processing message: (Op: app_gossip, NodeID: NodeID-5mmVqScHrzTiSa2WVjo99g2yzL83EBS6W, len(AppMsg): [0 0 0 0 0 1 0 0 17 30 249 17 2 .." => this array continues for some time

It is unclear whether this "rpc error.." thing has anything to do with the reason node became unhealthy in the first place, why are there 79 outstanding blocks, is VM just too slow?" 

**To Reproduce**
Run avalanchego using avalanchgo-installer
This is on an AWS VM  with image id =  **ami-0817d428a6fb68645**

Instance type is c5.large which is 2Vcpu and 4Gib memory

uname -a gives:
"Linux ip-<hidden> 5.4.0-1056-aws #59~18.04.1-Ubuntu SMP Mon Aug 23 23:07:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux"

sudo lshw -c memory
  *-firmware                
       description: BIOS
       vendor: Amazon EC2
       physical id: 0
       version: 1.0
       date: 10/16/2017
       size: 64KiB
       capabilities: pci edd acpi virtualmachine
  *-memory
       description: System memory
       physical id: 1
       size: 3696MiB

**Expected behavior**
I expect the node to never fail like this. If there is a problem with the VM I expect that problem to be shown in logs (memory issue, system too slow, networking issue). It is unclear with the above errors if the "RPC" error message shown was the cause of the issue or if issue was due to something else. 

**Screenshots**

**Operating System**
Ubuntu linux 18.04

**Additional context**
Node was running fine for weeks on 1.7.2, then I got similar error last night and updated to 1.7.3 using avalanchgo-installer, then this error occurred today and seems same as previous one. 

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://www.avax.network/avalanche-x).

**Comment by StephenButtolph** [comment]
We've since found and fixed a number of issues in the grpc library used for the plugin interface. If this issue resurfaces in any of the newer releases please feel free to re-open and we'll dive into it.
