### ISSUE TITLE
how to open websocket port on avax node

### ISSUE THREAD

**Issue by kissing009** [ava-labs/avalanchego#987]
I use the command " ./avalanchego -h " to get help for open websocket port, but just find http-port is 9650, cannot find the websocket port.

--http-host string                                           Address of the HTTP server (default "127.0.0.1")
--http-port uint                                             Port of the HTTP server (default 9650)

how to open websocket port on avax node ?
thanks!

**Comment by StephenButtolph** [comment]
There is not a designated websocket port. The `http` is used for all requests - including websocket requests.
