### ISSUE TITLE
Introduce address exclusion in `platform.exportAVAX` and other platform APIs.

### ISSUE THREAD

**Issue by arijitAD** [ava-labs/avalanchego#988]
**Describe the bug**
Over time an account might have to manage p-chain multiple addresses since it uses the UTXO model. It will be helpful if there is field in `exportAVAX` API where we can also exclude an address.

Current API:
```
platform.exportAVAX(
    {
        amount: int,
        from: []string, //optional
        to: string,
        changeAddr: string, //optional
        username: string,
        password: string
    }
) -> 
{
    txID: string,
    changeAddr: string
}
```

Expected:
```
platform.exportAVAX(
    {
        amount: int,
        from: []string, //optional
        excludeAddr: []string, //optional
        to: string,
        changeAddr: string, //optional
        username: string,
        password: string
    }
) -> 
{
    txID: string,
    changeAddr: string
}
```

**Comment by StephenButtolph** [comment]
The node APIs are designed as simple convenience methods. To improve generality and security, it is recommend to use a wallet service that does not require keys to be placed onto a running node.
