### ISSUE TITLE
I use the avlanchego version is 1.7.4 , but I get the error

### ISSUE THREAD

**Issue by malingzhao** [ava-labs/avalanchego#991]
FATAL[01-19|16:38:32] app/process/process.go#162: error initializing node: couldn't initialize chain manager: invalid vmID avalanchego

**Comment by malingzhao** [comment]
INFO [01-19|16:43:00] database/leveldb/db.go#120: leveldb config: {"blockCacheCapacity":12582912,"blockSize":0,"compactionExpandLimitFactor":0,"compactionGPOverlapsFactor":0,"compactionL0Trigger":0,"compactionSourceLimitFactor":0,"compactionTableSize":0,"compactionTableSizeMultiplier":0,"compactionTableSizeMultiplierPerLevel":null,"compactionTotalSize":0,"compactionTotalSizeMultiplier":0,"openFilesCacheCapacity":64,"writeBuffer":6291456,"filterBitsPerKey":10}
FATAL[01-19|16:43:00] app/process/process.go#94: couldn't create "leveldb" db manager at /data/blockdata/avax/data/mainnet: couldn't create db at /data/blockdata/avax/data/mainnet/v1.4.5: resource temporarily unavailable
[root@ip-172-30-147-253 avax]# exit

**Comment by danlaine** [comment]
@malingzhao 
```
couldn't create "leveldb" db manager at /data/blockdata/avax/data/mainnet: couldn't create db at /data/blockdata/avax/data/mainnet/v1.4.5: resource temporarily unavailable
```

This suggests that there is another node already running on this machine

**Comment by StephenButtolph** [comment]
> FATAL[01-19|16:38:32] app/process/process.go#162: error initializing node: couldn't initialize chain manager: invalid vmID avalanchego

This error suggests that you have a file called `avalanchego` inside of your plugin directory.
