### ISSUE TITLE
Private network in avalanche

### ISSUE THREAD

**Issue by osiz-blockchainapp** [ava-labs/avalanchego#997]
Hi,
 How to run local/private network in avalanche?
 Can you provide detail document to node setup?

**Comment by ceyonur** [comment]
Hello,
Take a look at: https://docs.avax.network/build/tutorials/platform/create-a-local-test-network/
This is for reporting bugs or any other issue with the AvalancheGo. For questions you can use: chat.avax.network

**Comment by osiz-blockchainapp** [comment]
> Hello, Take a look at: https://docs.avax.network/build/tutorials/platform/create-a-local-test-network/ This is for reporting bugs or any other issue with the AvalancheGo. For questions you can use: [chat.avax.network](https://chat.avax.network)

Hi,
 Setting up local test network, but it doesn't create 5 staker.cert and staking.key file
