### ISSUE TITLE
"failed to update base fee" logs error

### ISSUE THREAD

**Issue by JamesCropcho** [ava-labs/avalanchego#999]
Hello:

I hope you are well today.

I see that my Avalanchego logs have a number of messages like the following:

```
Jan 26 19:27:21 avax-node avalanchego[591]: ERROR[01-26|19:27:21.816] failed to update base fee                currentHead=7b7f15..57515b err="cannot calculate base fee for timestamp (1643243241) prior to parent timestamp (1643243245)"
```
Is this something to be concerned about?

Regardless, what might the cause be (and any effects)?

Regards,
James Cropcho

-------------------------------

```
$ avalanchego --version
avalanche/1.7.4 [database=v1.4.5, commit=ca7a521aa6c5a49c1fb52ef1e7e0ddaad6a0e760]
```

**Comment by ssakiz** [comment]
Hi,
I see the same behaivour in one of my nodes.

Please look at the last digit in timestamps field.  
The difference is always 1 betweend the failed timestamp and parent time stamp.

 timestamp (1643527941) prior to parent timestamp (1643527942)"

./avalanchego --version
avalanche/1.7.4 [database=v1.4.5, commit=ca7a521aa6c5a49c1fb52ef1e7e0ddaad6a0e760]

failed to update base fee                currentHead=71a956..ae978a err="cannot calculate base fee for timestamp (1643527941) prior to parent timestamp (1643527942)"
failed to update base fee                currentHead=5df55e..262c43 err="cannot calculate base fee for timestamp (1643527951) prior to parent timestamp (1643527952)"
failed to update base fee                currentHead=34fdd9..87c9ca err="cannot calculate base fee for timestamp (1643528011) prior to parent timestamp (1643528012)"

Do you have any suggestions ? 
Is this behaivour normal  ?

Thanks.

**Comment by ceyonur** [comment]
Hello,
Thanks for reaching out. We're aware of this issues and will be fixed with next releases. They're not critical issues.
